### ISSUE TITLE
Add wayland-session and xsession files

### ISSUE THREAD

**Issue by FSMaxB** [SirCmpwn/sway#100]
It would be nice to have a wayland-session file in `/usr/share/wayland-sessions/` and an xsession file in `/usr/share/xsessions/`, so that display managers can detect sway and display an option to start it.

Those files could look like this for example:
```desktop
[Desktop Entry]
Name=sway
Comment=SirCmpwn's Wayland window manager
Exec=sway
Type=Application
```
(note: I haven't tried out if the file above actually works)

**Comment by SirCmpwn** [comment]
I agree, but only if we see it tested.

**Comment by FSMaxB** [comment]
Nice. I'm gonna try it out with GDM.

**Comment by FSMaxB** [comment]
I've tried it with the following files:

`/usr/share/wayland-sessions/sway.desktop`
```
[Desktop Entry]
Name=Sway
Comment=SirCmpwn's Wayland window manager
Exec=sway
Type=Application
```

`/usr/share/xsessions/sway-xorg.desktop`
```
[Desktop Entry]
Name=Sway (Xorg)
Comment=SirCmpwn's Wayland window manager
Exec=sway
Type=Application
```

Works fine for me when using GDM. Note that the xsession file has to have a different name then the wayland session file.

**Comment by SirCmpwn** [comment]
Cool. Pull requests welcome.
