### ISSUE TITLE
Firefox context menus and URL bar dropdown broken under Sway 0.10

### ISSUE THREAD

**Issue by tidux** [SirCmpwn/sway#1003]
I've tested this with Firefox and Firefox Developer Edition under Sway 0.10.  It's probably not a Firefox or Wayland issue because Firefox displays an entirely different set of bugs under Enlightenment 21 as a Wayland compositor.

**Comment by FreeFull** [comment]
Is this the same issue as #571 ?

**Comment by tidux** [comment]
It does look like it.  I was unable to find 571 by searching the issues for Firefox so I assumed I was the first reporter.
