### ISSUE TITLE
Quod Libet fails to launch; segfaults immediately on Fedora 25

### ISSUE THREAD

**Issue by j39m** [SirCmpwn/sway#1009]
System information given below - just a vanilla up-to-date installation of Fedora 25. Attempting to run Quod Libet does not open the player; from a terminal, you can see that something stews a moment before printing "Segmentation fault" and dying.

    [j39m@SERN ~]$ cat /etc/redhat-release
    Fedora release 25 (Twenty Five)
    [j39m@SERN ~]$ sway --version
    sway version  (2016-11-26, branch "")
    [j39m@SERN ~]$ quodlibet --version
    Quod Libet 3.7.1
    [snip]
    [j39m@SERN ~]$ rpm -q sway xorg-x11-server-Xwayland
    sway-0.10-2.fc25.x86_64
    xorg-x11-server-Xwayland-1.19.0-2.fc25.x86_64

Please let me know if I need to provide any more information.

**Comment by j39m** [comment]
Here's a snip from the system log. Doubtful this will help, but all the same:

    Dec 23 16:08:00 flaglock3 audit[8792]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=6 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=8792 comm="quodlibet" exe="/usr/bin/python2.7" sig=11
    Dec 23 16:08:00 flaglock3 kernel: quodlibet[8792]: segfault at 21 ip 00007f82b4884575 sp 00007ffd79df0210 error 4 in libX11.so.6.3.0[7f82b47f3000+138000]
    Dec 23 16:08:01 flaglock3 abrt-hook-ccpp[8799]: Process 8792 (python2.7) of user 1000 killed by SIGSEGV - dumping core
    Dec 23 16:08:01 flaglock3 dhclient[8780]: XMT: Info-Request on wlp4s0, interval 4050ms.
    Dec 23 16:08:01 flaglock3 /usr/libexec/gdm-wayland-session[8685]: /bin/bash: line 1:  8792 Segmentation fault      (core dumped) quodlibet
    Dec 23 16:08:01 flaglock3 abrt-server[8800]: Deleting problem directory ccpp-2016-12-23-16:08:01-8792 (dup of ccpp-2016-12-23-16:07:39-8524)

**Comment by SirCmpwn** [comment]
Please provide a core dump

**Comment by j39m** [comment]
Coredump xzipped and then zipped (to appease Github).
[1009.zip](https://github.com/SirCmpwn/sway/files/671591/1009.zip)

**Comment by j39m** [comment]
Closing because it looks like a QL bug. The same crash happens in weston and can be worked around with `GDK_BACKEND=x11 quodlibet`...
