### ISSUE TITLE
Odd behavior of primary clipboard 

### ISSUE THREAD

**Issue by Hi-Angel** [SirCmpwn/sway#1010]
Selected text in `gnome-terminal` does not get pasted into `kate` and vice versa, i.e. selected content in `kate` not get pasted into `gnome-terminal`.

Interestingly, the text from `kate` could be pasted e.g. to `konsole`, and vice versa, so there's probably some subtle bug in clipboard handling.

Steps to reproduce:

1. Open `gnome-terminal` and `kate`.
2. Select a text in `gnome-terminal`.
3. Try pasting the selected with middle mouse button into `kate`.

OS: Archlinux
Sway version: 0.10-1

**Comment by SirCmpwn** [comment]
Known issue with wlc. Wayland and x clipboards are not synced.

**Comment by Hi-Angel** [comment]
@SirCmpwn could you please link the issue?

**Comment by Hi-Angel** [comment]
I've heard alike somewhere, but recently when I had to refer the problem myself, I couldn't find anything on wlc or sway github, or anywhere, as if I imagined the discussion I saw.

**Comment by SirCmpwn** [comment]
It's not really an issue that goes on anything. The solution requires an external daemon that should be a separate project.

**Comment by Hi-Angel** [comment]
@SirCmpwn well If the problem is just that, then Gnome already has the daemon *(I just checked: the problem did not reproduce in gnome-on-wayland)*, and the problem again boils down to Sway: why doesn't Sway use this daemon?

**Comment by SirCmpwn** [comment]
Because sway isn't GNOME.

**Comment by Hi-Angel** [comment]
Could you please elaborate?

**Comment by SirCmpwn** [comment]
They don't design their software to be reusable in other projects. Knowing them it probably involves dbus too.

**Comment by Hi-Angel** [comment]
So you don't know for sure… Anyway, somewhere should be the issue opened, to refer to. Because XWayland isn't going anywhere soon. E.g. I feel, it gonna take a long time for Wine to get ported.

Then, if not Sway, where should I open a bug for this? XWayland project? Anything else?

**Comment by SirCmpwn** [comment]
You should just implement it if you're that concerned about it. Opening a bug doesn't really change anything.

**Comment by jplatte** [comment]
@SirCmpwn Why would this be implemented as an external daemon instead of as part of wlc? Is clipboard handling done in sway itself, or is there some reason why wlc would only handle the clipboard for wayland applications? It seems like it has a bunch of xwayland-specific code already.

**Comment by SirCmpwn** [comment]
I suppose it could be implemented that way but a daemon could be reused for other compositors. Unlike GNOME, sway *does* strive to make reusable component ;)

**Comment by jplatte** [comment]
Hm, I think it's important enough to expect it to work out-of-the-box though. For example KeePassX uses Qt4 and AFAIK that means it will run through XWayland. And Chromium users probably also copy links or text into other applications frequently enough (Chromium still uses gtk2, not sure how far they've gotten with porting to gtk3).

We should probably also ask @Cloudef: is clipboard sharing with X programs something you would like to have in wlc?

**Comment by SirCmpwn** [comment]
You're right that it should work OOTB, but remember sway is 0.x and not done.

**Comment by SirCmpwn** [comment]
Oh, I see what you mean. Well, we can automatically run the daemon.

**Comment by jplatte** [comment]
Alright, sounds good enough. Considering gtk2 and qt4 are kind of phasing out and it's gonna be a while until it's realistic for most i3 users to switch to sway, this might not be such a big thing actually.

Just looked up if there were efforts to port keepassx to qt5, and actually it's already done and works (in arch it's as simple as installing keepassx-git from AUR) :)
