### ISSUE TITLE
resize mode changes both edges of window

### ISSUE THREAD

**Issue by cyphar** [SirCmpwn/sway#1011]
In i3, when you're in resize mode, the window's size is only changed from the left window edge or the bottom window edge. In sway, both edges are moved. While I'm not sure this is the best resizing strategy, it is the way that stock i3 works.

Should we add a config option to use sway's current resizing system, with i3's resizing system being the default?

**Comment by SirCmpwn** [comment]
:-1: I don't personally see this as a compatibility issue.
