### ISSUE TITLE
Focusing by click not working in tabbed mode.

### ISSUE THREAD

**Issue by frequem** [SirCmpwn/sway#1013]
In tabbed mode, when clicking on another window, nothing is happening. In i3 this focuses the clicked window. Focusing by using keyboard shortcuts is working.

Steps to reproduce:
1. Open atleast 2 windows
2. Switch to tabbed mode (default: mod + w)
3. Try to switch to another window by clicking with your mouse.

OS: Arch
Sway version: 0.10-1 (2016-10-25)

**Comment by SirCmpwn** [comment]
Try on the latest rc please.

**Comment by frequem** [comment]
It's working on the latest rc. Sorry for the trouble.
