### ISSUE TITLE
Color workspace when notifications arrive

### ISSUE THREAD

**Issue by Fale** [SirCmpwn/sway#1015]
ie: When a shell rings, the workspace should be colored like in i3

**Comment by SirCmpwn** [comment]
This is complicated because X and Wayland raise window notifications differently.

**Comment by Fale** [comment]
You mean that would be hard to implement at all, or that it would be hard to implement X application raising notifications in sway?

**Comment by Drakulix** [comment]
> This is complicated because X and Wayland raise window notifications differently.
If it would work at least for Wayland applications, that would be nice.

**Comment by SirCmpwn** [comment]
Does anyone know what the protocol is for doing this on Wayland? Should be fairly easy to add the X stuff to wlc. Now that I think of that, all of the above should be done in wlc. Can you move the issue?
