### ISSUE TITLE
Swaylock does not put colors over an image

### ISSUE THREAD

**Issue by Fale** [SirCmpwn/sway#1018]
Using:

```
swaylock -c 00000044 -i /usr/share/backgrounds/f25/default/normalish/f25.png -s
```

I was expecting to see the image with a "darker" tone. I do see the image in a "plain" way.  In the doc it says "If an image is in use, also enables color display.", so I guess this is a bug

**Comment by SirCmpwn** [comment]
That's not how the flag is meant to work afaik. The docs should probably be clarified.

**Comment by Fale** [comment]
Are -c and -i mutually exclusive?

**Comment by SirCmpwn** [comment]
Yes.
