### ISSUE TITLE
for_window window class criteria not compatible to i3

### ISSUE THREAD

**Issue by LeonardKoenig** [SirCmpwn/sway#1020]
Hi, you use `wlc_view_get_class()` but this does not return the criteria i3 uses:

> %class
> The X11 window class (second part of WM_CLASS)

(http://i3wm.org/docs/userguide.html)

but the first one:

```
12/28/16 13:47:38 - [handlers.c:341] handle:4 type:0 state:0 parent:0 mask:0 (x:0 y:0 w:1916 h:509) title:Mozilla Firefox class:Navigator appid:(null)
```

```
WM_CLASS(STRING) = "Navigator", "Firefox"
```

**Comment by SirCmpwn** [comment]
Sounds like a wlc issue?

**Comment by LeonardKoenig** [comment]
Well, it returns a window class but in case there are two different ones, it's not the one we want / i3 specifies.

**Comment by SirCmpwn** [comment]
Right, but wlc provides an abstraction that prevents us from having to use x-isms and if the second class is the more canonical one or something then wlc should return that. If not then it's just an incomparability we'll have to live with - I've always been okay with incomparability where x-isms are concerned.

**Comment by LeonardKoenig** [comment]
I'm not sure whether it's the more canonical one, I've never really touched X. But if so, then it's a wlc issue, yes

**Comment by SirCmpwn** [comment]
Well, find out if it is and bring it up with them please.

**Comment by LeonardKoenig** [comment]
Hm, it seems to be more of what we want if I read this correct:

> **WM_CLASS Property**
> 
> The WM_CLASS property (of type STRING without control characters) contains two consecutive null-terminated strings. These specify the Instance and Class names to be used by both the client and the window manager for looking up resources for the application or as identifying information. This property must be present when the window leaves the Withdrawn state and may be changed only while the window is in the Withdrawn state. Window managers may examine the property only when they start up and when the window leaves the Withdrawn state, but there should be no need for a client to change its state dynamically.
> 
> The two strings, respectively, are:
> 
>  * A string that names the particular instance of the application to which the client that owns this window belongs. Resources that are specified by instance name override any resources that are specified by class name. Instance names can be specified by the user in an operating-system specific manner. On POSIX-conformant systems, the following conventions are used:
> 
>    * If "-name NAME" is given on the command line, NAME is used as the instance name.
> 
>    * Otherwise, if the environment variable RESOURCE_NAME is set, its value will be used as the instance name.
> 
>    * Otherwise, the trailing part of the name used to invoke the program (argv[0] stripped of any directory names) is used as the instance name. 
> 
>  * A string that names the general class of applications to which the client that owns this window belongs. Resources that are specified by class apply to all applications that have the same class name. Class names are specified by the application writer. Examples of commonly used class names include: "Emacs", "XTerm", "XClock", "XLoad", and so on. 
> 
> Note that WM_CLASS strings are null-terminated and, thus, differ from the general conventions that STRING properties are null-separated. This inconsistency is necessary for backwards compatibility. 
> 

https://www.x.org/releases/X11R7.7/doc/xorg-docs/icccm/icccm.html#WM_CLASS_Property

I'll make an issue on wlc
