### ISSUE TITLE
swaybar locks one CPU core at 100%

### ISSUE THREAD

**Issue by rolojf** [SirCmpwn/sway#1021]
After killing the swaybar, CPU back to normal
Launched from command prompt, not within a X Session
System info: On archllinux 4.8.13-1, sway 0.11-2, Wayland 1.12.0-1, Thinkpad T450, 
on ~/.bashrc
```bash
    export XKB_DEFAULT_LAYOUT=latam
    export XKB_DEFAULT_MODEL=thinkpad
    alias sway=sway -V >> ~/sway-log-1 2>&1
```
Attached HTOP before and the relevant config part is: 
```config
bar {
        status_command custom_statusbar
        position top
        swaybar_command /usr/bin/swaybar
        pango_markup disabled
        font pango:DejaVu Sans Mono 10
        colors {
            statusline $fg
            background $bgu
            focused_workspace $bgu #222222 $fg
            active_workspace $bgu #222222 $fg
            inactive_workspace $bgu $bgu $fg
        }
}
```
Full config file in zip file:
[config.zip](https://github.com/SirCmpwn/sway/files/676313/config.zip)
.
![2016-12-28_14 49 22](https://cloud.githubusercontent.com/assets/24816104/21532250/0ee34ec8-cd14-11e6-9215-e3f62aff7e50.png)
![2016-12-28_14 50 15](https://cloud.githubusercontent.com/assets/24816104/21532251/0ee3cb32-cd14-11e6-99f5-1c7f5592c4a9.png)

**Comment by SirCmpwn** [comment]
Can we get a copy of your custom_statusbar script?

**Comment by rolojf** [comment]
The config file in ~/i3status/config has only the folowig
```
general {
        colors = true
        interval = 5
}
```

**Comment by rolojf** [comment]
and part of the same config file (attached as config.zip) has the following:
```
# Status bar uses custom script
set bg  #323232
set bgu #323232B0
set fg  #ffffff
set fgu #aaaaaa

bar {
        status_command custom_statusbar
        position top
        swaybar_command /usr/bin/swaybar
        pango_markup disabled
        font pango:DejaVu Sans Mono 10
        colors {
            statusline $fg
            background $bgu
            focused_workspace $bgu #222222 $fg
            active_workspace $bgu #222222 $fg
            inactive_workspace $bgu $bgu $fg
        }
}
```

**Comment by SirCmpwn** [comment]
But your status command is not i3status, it's `custom_statusbar`. What is custom_statusbar?

**Comment by rolojf** [comment]
I copied this form the dotfile you shared and haven't fully reviewed all of it. 

Maybe that's it. I just  yesterday removed the lines refering to sr.ht. Maybe this custom_statusbar is some script you use but I don't have it properly configured.

**Comment by SirCmpwn** [comment]
Try dropping that line from your bar config.

**Comment by rolojf** [comment]
Yes. That's was it. All ok now.
