### ISSUE TITLE
CAP_SYS_TTY_CONFIG is needed for vt activation if running without systemd/logind

### ISSUE THREAD

**Issue by gyakovlev** [SirCmpwn/sway#1022]
HI, 

Installed 0.11 on my gentoo machine and got stuck for some time without ability to launch sway.
it seems after dropping privileges sway cannot swtich to vt7.
error I traced was
```ioctl(3, VT_ACTIVATE, 0x7)              = -1 EPERM (Operation not permitted)```

I'm running without systemd, logind, or consolekit if that matters.
tried both SUID and NON-suid bits, no difference..

the following capabilities got me running again
```/usr/bin/sway = cap_sys_ptrace,cap_sys_tty_config+ep```

Is it specific to my setup or sway drops privileges too early?

It should  be fixed or documented.

I can go back and provide strace  output if you need that. let me know.

sway-0.11
wlc-0.0.7
wayland-1.12.0

**Comment by SirCmpwn** [comment]
Do you have a similar problem with orbment?

**Comment by gyakovlev** [comment]
you are quick =)
I have not tried orbment, I can try to install it and test but probably it will take a lot of time. not ready for that right now. maybe next few days.
you mean those issues, right?
https://github.com/Cloudef/orbment/issues/82
https://github.com/Cloudef/orbment/issues/102

**Comment by gyakovlev** [comment]
ok I tested orbment, it was faster than I imagined.

it opens vt7 for me  and displays black desktop and a mouse (SUID, no capabilities set) but input devices don't work, but that/s another issue I believe.

**Comment by robotanarchy** [comment]
I can confirm this on Arch Linux without systemd, and also that it works after running the following setcap command: `setcap cap_sys_tty_config=ep /usr/bin/sway`

Added this to the [wiki](https://github.com/SirCmpwn/sway/wiki/Sway-without-systemd-on-Arch-Linux).
