### ISSUE TITLE
Android Studio interface not showing up

### ISSUE THREAD

**Issue by MateusZitelli** [SirCmpwn/sway#1025]
I'm not sure if it's a issue with Sway, however, Android Studio window stays blank gray when loaded. Seems to be something small because the popups show up with the right content (even with the wrong size). That is the only thing that I'm missing to switch from i3.

I'm currently running the master branches of sway and wlc, with Android Studio 2.3.

**Comment by SirCmpwn** [comment]
Read the FAQ: https://github.com/SirCmpwn/sway/wiki#my-favorite-application-isnt-displayed-right-how-can-i-fix-this
