### ISSUE TITLE
swaylock doesn't grab mouse input unless moved

### ISSUE THREAD

**Issue by jhalmen** [SirCmpwn/sway#1026]
got this by mistake.
swaylock doesn't grab mouse clicks if the mouse wasn't moved since swaylock started.
steps to reproduce: put on a video on youtube, leave the mouse over the video, start swaylock (e.g. by keybinding), click (without moving the cursor!), the video pauses. if you click again without moving the cursor it starts again. this can be repeated until the mouse is moved, then swaylock grabs it successfully and you have to enter the correct passcode.

**Comment by SirCmpwn** [comment]
This is a wlc issue. I've mentioned this to @Cloudef before but it seems there was never a GitHub issue made. Basically when the view under the cursor changes, wlc doesn't update the cursor surface as necessary. This is also noticable when switching between workspaces. Anyway, please report this to wlc instead.

**Comment by SirCmpwn** [comment]
Hold on, just read your issue properly. It doesn't grab the keyboard focus too? So you type your password into whatever was focused before? I can't reproduce that behavior.

**Comment by jhalmen** [comment]
no you read right the first time around, keyboard input is grabbed correctly.
i will report it to wlc.
thank you for answering so promptly :)
