### ISSUE TITLE
Sway and 2 graphics card

### ISSUE THREAD

**Issue by warlock90000** [SirCmpwn/sway#1028]
**I have:**
2 graphics card and the 2 monitor.
**1.** Radeon HD6670 and monitor connected to SVGA (WLC_DRM_DEVICE = card0)
**2.** built-in Intel i5 processor and monitor connected to SVGA (WLC_DRM_DEVICE = card1)
When you run sway simultaneously, only one works.
If you do not use WLC_DRM_DEVICE, it always works **# 1**.
How to do to sway worked on both monitors

**Comment by psgarsenal** [comment]
not possible atm, see Cloudef/wlc#11

**Comment by warlock90000** [comment]
ty SirCmpwn
