### ISSUE TITLE
PulseAudio: Unable to connect: Connection refused

### ISSUE THREAD

**Issue by DerVerruckteFuchs** [SirCmpwn/sway#1031]
Normally I control my audio via `amixer` and have it assigned to keyboard shortcuts. It works fine in i3, but I seem to not have control over pulseaudio in sway.

shortcuts from my config:
```
# add shortcuts for controlling audio volume
bindsym F10 exec amixer -D pulse sset Master 10%+ unmute && killall -SIGUSR1 i3status
bindsym F9 exec amixer -D pulse sset Master 10%- unmute && killall -SIGUSR1 i3status
bindsym F8 exec amixer -D pulse sset Master toggle && killall -SIGUSR1 i3status
```
When trying to use amixer from a command line I get a `ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused` error. Trying to control audio via `pavucontrol` results in it stuck in the "Establishing connection to PulseAudio. Please wait..." stage. My assumption is that wayland and pulseaudio aren't playing nice at the moment. Using `alsamixer` doesn't help much either since I can't play with my default soundcard profile to adjust the volume. The only thing it shows is S/PDIF output for some reason, and it looks like it 'copied' the S/PDIF controls from another output sources.

Using `sway -v` I get `sway version 0.11-6-g36f896a (2017-01-04, branch "makepkg")`. I'm using Arch.

**Comment by SirCmpwn** [comment]
I'm not sure what your issue is but it has nothing to do with sway.

**Comment by DerVerruckteFuchs** [comment]
I looked more into it and pulseaudio in general isn't working for some reason, even with i3. I'm not quite sure what happened. I was going to close this myself once I figured out what it was. It's very recent whatever caused it and I didn't notice it until I just recently played with sway again.
