### ISSUE TITLE
Error when setting parameters window

### ISSUE THREAD

**Issue by Haron-Prime** [SirCmpwn/sway#1033]
**1.** Window settings are used in my config i3vm that match the criteria **window_type** and **instance**. But notice the error appears when you try to use them in the sway in the console `"window_type" criteria currently unsupported`
I would like to be able to use these criteria in settings.

**2.** The config i3vm one rule can be applied to multiple applications
```
assign [class="vivaldi-snapshot|Firefox|Tor Browser"] 1:W
for_window [instance="ncmpcpp|equalizer|htop|ranger|lxappearance"] floating enable
```
The sway is the transfer does not work, which is very sad.
I would be very grateful, if you pay attention to these issues.
*I apologize for the google-translator

**Comment by SirCmpwn** [comment]
These criteria don't work because they don't make sense on Wayland. Not all features of i3 are directly translatable to Wayland. You'll have to find different ways of matching these windows.
