### ISSUE TITLE
Permanent second mouse pointer on screen

### ISSUE THREAD

**Issue by jalbstmeijer** [SirCmpwn/sway#1037]
Hi,

Checking out the default Sway 0.10 package delivered on  Fedora 25.
It shows a second mouse pointer in the middle of the screen, not moving.

This issue stays on testing with Sway 0.11. (https://kojipkgs.fedoraproject.org//packages/sway/0.11/4.fc25/x86_64/sway-0.11-4.fc25.x86_64.rpm)

Any idea how to get rid of it?

Gr, J

**Comment by SirCmpwn** [comment]
https://github.com/SirCmpwn/sway/issues/759
