### ISSUE TITLE
new_window pixel  does not remove titlebars

### ISSUE THREAD

**Issue by bearcatsandor** [SirCmpwn/sway#1042]
adding new_window pixel <n> in configuration does not remove title bars. In fact it doesn't seem to have any effect at all.

A debug of sway wherein i start Sway in x, open a terminal and close terminal, and close sway is here:  [https://gist.github.com/bearcatsandor/08429c9bb6a276827216e58d4a2c3948)](https://gist.github.com/bearcatsandor/08429c9bb6a276827216e58d4a2c3948)

My config (largely based on SirCmpwn's dotfiles is here:  [https://gist.github.com/b4df4cd13b531c073f658b67a5aaab0a](https://gist.github.com/b4df4cd13b531c073f658b67a5aaab0a)

thanks

**Comment by SirCmpwn** [comment]
I cannot reproduce this.

**Comment by SirCmpwn** [comment]
The config you linked sets new_window twice, the second time overwriting your new_window pixel 1.

**Comment by bearcatsandor** [comment]
Thanks for helping a doofus!
