### ISSUE TITLE
Switch to last active workspace

### ISSUE THREAD

**Issue by willd** [SirCmpwn/sway#1045]
Right now, you can use "workspace prev/next" to move between your list of workspaces without using the name. I would like to see an additional option that switches to the last active workspace. 

It is a default option in dwm, which I'm used to, and one that would make my workflow in sway on par with what I'm used to.

**Comment by Airblader** [comment]
`workspace back_and_forth` ?

**Comment by SirCmpwn** [comment]
We have that command implemented, but it's undocumented and it seems to be buggy. Both of those things should be fixed.

**Comment by willd** [comment]
@Airblader Unfortunely only switches between specific workspaces, I cannot see a way to make it work across two generic workspaces :(

@SirCmpwn A good start anyway! I'll poke around and see if there's anything I can do :)

**Comment by willd** [comment]
workspace back_and_forth seems to be working alright for me. Do you want me to keep the issue open until the command has been documented, or the bugginess you mentioned have been resolved?
