### ISSUE TITLE
Workspace on wrong screen

### ISSUE THREAD

**Issue by AndreRoehrig** [SirCmpwn/sway#1046]
In my config I have:
```
workspace 1:web output e-DP1
workspace 2 output e-DP1
workspace 3 output e-DP1
workspace 4 output e-DP1
workspace 5 output e-DP1
workspace 6:dev output DP-1
workspace 7:vcs output DP-1
workspace 8 output DP-1
workspace 9 output DP-1
workspace 10:ssh output DP-1
```

But when I am on DP-1 and change to workspace 2, workspace 2 will be on DP-1 instead of e-DP1, the same applies for all similar cases, as long as there is no open window on the workspace yet.

**Comment by SirCmpwn** [comment]
Can you share the output of swaymsg -t get_outputs?

**Comment by AndreRoehrig** [comment]
I took an example, where workspace 3 is on the wrong screen.

```
[
   {
     "id": 1,
     "name": "eDP-1",
     "rect": {
       "x": 0,
       "y": 0,
       "width": 3200,
       "height": 1800
     },
     "visible": true,
     "focused": false,
     "active": true,
     "primary": false,
     "layout": "output",
     "type": "output",
     "current_workspace": "2",
     "scale": 2
   },
   {
     "id": 3,
     "name": "DP-1",
     "rect": {
       "x": 3200,
       "y": 0,
       "width": 1920,
       "height": 1080
     },
     "visible": true,
     "focused": false,
     "active": true,
     "primary": false,
     "layout": "output",
     "type": "output",
     "current_workspace": "3",
     "scale": 1
   }
 ]
```

**Comment by SirCmpwn** [comment]
How about a debug log?

**Comment by SirCmpwn** [comment]
Oh, nevermind. Your problem is you're assigning workspaces to e-DP1, when you should be using eDP-1.

**Comment by AndreRoehrig** [comment]
Yes, thank you, this fixed the problem. Could imagine this being a common error when i3-configs are copied. Is there a similarly basic reason for why I cannot move my mouse from one screen to the other?

**Comment by SirCmpwn** [comment]
You need to position them correctly with `output [name] pos [x,y]`. Read `man 5 sway` and the FAQ.
