### ISSUE TITLE
Better readability of code

### ISSUE THREAD

**Issue by galczo5** [SirCmpwn/sway#1049]
Hi,
I've tried to analyze few of your files. Sorry for saying that but readability is poor. For example: 
https://github.com/SirCmpwn/sway/blob/master/sway/commands/resize.c

Function `static bool resize_tiled(int amount, bool use_width) ` is too long, there are too many indentation levels, etc.

If you need help with cleanup I can try to find time for this.

**Comment by SirCmpwn** [comment]
Send pull requests for this sort of thing, not issues.
