### ISSUE TITLE
AltGr keys aren't working

### ISSUE THREAD

**Issue by TheNiceGuy** [SirCmpwn/sway#1063]
Hi, I use the canadian french keyboard (`setxkbmap ca`). I do most of my programming using this keyboard. The special characters `{}[]@`, etc are made with `AltGr+key` (for example `AltGr+2` gives an `@`). The problem is that it used to work just fine under X. In sway, no AltGr work at all. I'm not sure if this is a libinput, wayland or sway configuration problem. I can't figure out how to do it (if it ain't a bug). Thanks.

**Comment by hobarrera** [comment]
Are you configuring your keyboard layout first?  
eg: `XKB_DEFAULT_LAYOUT=es sway`

**Comment by TheNiceGuy** [comment]
That fixed my issue. I knew I was missing something simple. Thank you!

**Comment by riquito** [comment]
What if you need to change layout at runtime?

**Comment by cafehaine** [comment]
@riquito see https://github.com/SirCmpwn/sway/issues/532
