### ISSUE TITLE
Feature request: Please add a feature to disable window scaling

### ISSUE THREAD

**Issue by WeaponX1** [SirCmpwn/sway#1064]
Sometimes it can be very useful if I can close an application let's say terminal and everything stays intact so I can open another app in the location where the app was closed. They way I don't have to rearrange tiling all over again.

**Comment by SirCmpwn** [comment]
I'm inclined to say "no" to this. I've considered allowing users to create empty spaces, but to replace a window with an empty space when it closes would be quite complicated and niche.

**Comment by WeaponX1** [comment]
Hi Drew,


Please don't get me wrong, I'm a suckless/dynamic window manager fanatic and prefer to use keyboard most of the time however such a feature would better provide mouse support i.e. drag & drop of windows into position. It is a rather very useful functionality... not sure if inserting an empty window is the best solution IMHO. I was thinking of a command that can disable/enable dynamic scaling of windows altogether.


If you've ever used Notion Window Manager, you'd understand where I'm coming from as I'm migrating to Sway and it seems to be the only feature that I guess I will be missing.


Best regards,

Shant Kassardjian

________________________________

**Comment by SirCmpwn** [comment]
I'm not opposed to the feature. It's just complicated and I'm not sure the increase in code complexity is justified.

**Comment by WeaponX1** [comment]
Fair enough Sir.

Can't thank you enough already for your dedication to the project :)
