### ISSUE TITLE
nvc0_screen_create:785 - Base screen init failed: -19

### ISSUE THREAD

**Issue by jcf** [SirCmpwn/sway#1067]
I was hoping to checkout Sway and Wayland on Arch Linux when I ran into an issue with running `sway` after logging in to a TTY session.

```
nvc0_screen_create:785 - Base screen init failed: -19
```

I've removed proprietary Nvidia drivers and have nouveau installed. I installed Sway via Pacman with `pacman -Sy sway`.

Im guessing I need to install something or change some configuration on my machine to get things working, but I haven't been able to find the answer anywhere and I'm not sure how to proceed. Any pointers would be greatly appreciated!

If it's relevant, I have two GTX 1080s (one's reserved for use with a virtual machine), and two monitors both plugged into the one card.

**Comment by SirCmpwn** [comment]
Did you reboot after switching drivers? You might also have to specify the card with `WLC_DRM_DEVICE=card{0,1}`

**Comment by Jesin** [comment]
@jcf Just a reminder that it can be dangerous to `pacman -Sy` without `-u` (see [System maintenance#Partial upgrades are unsupported](https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported)).

**Comment by jcf** [comment]
> Did you reboot after switching drivers?

@SirCmpwn yes.

> You might also have to specify the card with WLC_DRM_DEVICE=card{0,1}

I'll give this a try this week.

**Comment by jcf** [comment]
Setting the aforementioned environment variable before running Sway didn't help.

**Comment by SirCmpwn** [comment]
Please provide a debug log.
