### ISSUE TITLE
User-specific keyboard layout with desktop manager

### ISSUE THREAD

**Issue by tmccombs** [SirCmpwn/sway#1068]
As far as I can tell the only way to set the keyboard layout is with environment variables when sway is started. This means that root must change the .desktop file in order to change the keyboard layout. As far as I can tell there isn't a way to change the keyboard layout after the session has started. (In x this could be done with setxkbmap, but that doesn't  work in wayland).

**Comment by SirCmpwn** [comment]
This has been discussed and there are not presently any plans to support this. Environment variables are the way to go for now.

**Comment by tmccombs** [comment]
But is there any way to set these environment variables for a single user?

**Comment by SirCmpwn** [comment]
Write a script?
