### ISSUE TITLE
for_window matching seems not to work

### ISSUE THREAD

**Issue by Chrysostomus** [SirCmpwn/sway#1069]
I tried to set some applications to always start fullscreen. This fails with a cryptic error message:

swaymsg for_window [class="bemenu"] fullscreen
```
[
   {
     "success": false,
     "input": "for_window",
     "error": "Unable to parse criteria: Names must be unquoted, values must be quoted"
   }
 ]

```
Same error is produced by the example command in the wiki:
```

 swaymsg for_window [id="nautilus"] border none
[
   {
     "success": false,
     "input": "for_window",
     "error": "Unable to parse criteria: Names must be unquoted, values must be quoted"
   }
 ]

```
Is this a bug or am I doing somthing wrong?

**Comment by Biohazard50** [comment]
I can reproduce the bug.

**Comment by zandrmartin** [comment]
This is probably because your shell is trying to parse the command. Try: `swaymsg 'for_window [class="bemenu"] fullscreen'`

**Comment by Biohazard50** [comment]
@zandrmartin You are right. My bad.
