### ISSUE TITLE
Implement pointer constraints

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/sway#1071]
Spec is in wayland-protocols.

**Comment by zog34** [comment]
Further information from Enlightenment's implementation (as well as a little theory):

https://blogs.s-osg.org/introduction-relative-constrained-pointers-enlightenment/

**Comment by Laaas** [comment]
Has this been implemented? I don't see any relevant commits.

**Comment by SirCmpwn** [comment]
No, but it's going to be implemented in wlroots.
