### ISSUE TITLE
Sway broken

### ISSUE THREAD

**Issue by maximiliankaul** [SirCmpwn/sway#1074]
I just updated to most recent sway (r2143.a018364-1) and wlc (0.0.7.r27.g6f3758b-1) on Arch Linux and sway is no longer usable.

I’m using a 2 monitors and got this result after starting sway:
![2017-02-13-110308_swaygrab](https://cloud.githubusercontent.com/assets/13150274/22879139/e7e3a85c-f1dc-11e6-918e-b906db8ded2b.png)

I also tried without the second monitor to rule it out as the problem:
![2017-02-13-110540_swaygrab](https://cloud.githubusercontent.com/assets/13150274/22879190/1528cfd6-f1dd-11e6-86a8-15e26f0b8f6e.png)

I first compiled `wlc-git` and then `sway-git` on an updated Arch Linux.

Please let me know if you need more information.

**Comment by hobarrera** [comment]
Same results on ArchLinux using the stable packages. It only happens when opening certain apps, can't narrow it down to what they havin in common.

**Comment by Unip0rn** [comment]
could you two drop in a config, log and list of applications suitable for reproduction?

**Comment by maximiliankaul** [comment]
Log is probably too large. Just noticed, that there are millions of lines like this:
```
02/13/17 11:05:48 - [bar.c:230] failed to dispatch wl: 32
```
(Didn’t notice at first because I only searched for `err` and `warn` - my bad).
[Here](https://github.com/SirCmpwn/sway/files/771212/sway.log.txt) is a version where I deleted all of those lines but one (to get a bit smaller than the original 150 MB).

Config is [here](https://github.com/SirCmpwn/sway/files/771217/sway.conf.txt) (all files merged in one).

**Comment by Unip0rn** [comment]
So on removed bar block in config it doesn't display the bar, but the entire BG in gray? and I'm not sure I'm getting it right, but aren't there 3(2) monitors?

**Comment by SirCmpwn** [comment]
WTF version is gaed3469? That commit does not exist. Please use stable packages if you are not a developer. I think if you remove `include /etc/sway/security` from your config and switch to stable packages the problem should go away.

**Comment by maximiliankaul** [comment]
@Unip0rn I was testing both with 1 internal + 1 external monitor (first screenshot) and 1 internal monitor (second screenshot).
@SirCmpwn well, that is embarrassing: I had an old version I used to test something in my PATH and totally forgot about. No issue with current sway (neither with `sway` nor with `sway-git`).
Should I close this issue or should I leave it open until @hobarrera’s issue is resolved as well?
Sorry for the noise!

**Comment by SirCmpwn** [comment]
@hobarrera should open a new issue and provide much more information.
