### ISSUE TITLE
Window closes if interacting with floating dialogue

### ISSUE THREAD

**Issue by BrighBrigh** [SirCmpwn/sway#1077]
If I open a program that uses a floating dialog, the whole program crashes. For this example, I am attempting to add a VPN connection NetworkManager's connection editor. Once I click the drop-down menu for the type of connection I want to add, the program crashes. Attached is the sway log file. The issue starts at 
`02/16/17` 08:32:52 - [layout.c:786] Arranging layout for 0x1a41510 Network Connections 640.000000x1059.000000+1280.000000,21.000000`
[sway.txt](https://github.com/SirCmpwn/sway/files/780624/sway.txt)

**Comment by SirCmpwn** [comment]
Can you update wlc?

**Comment by BrighBrigh** [comment]
I tried that and the issue persists. I am also noticing it with other applications such as Libreoffice Writer. When I attempt to Export a document as a PDF, a dialog pops up and the program crashes. I am not experiencing this in i3 nor in GNOME with Wayland.

**Comment by SirCmpwn** [comment]
Can you share your sway and wlc versions?

**Comment by BrighBrigh** [comment]
sway version:  (2016-12-27, branch "")

wlc: wlc-0.0.7-1

**Comment by BrighBrigh** [comment]
Also, I just wanted to say that I really appreciate what you do. Sway is an amazing WM and I look forward to seeing where the future takes it.

**Comment by SirCmpwn** [comment]
Can you update wlc to 0.0.8 please?

**Comment by BrighBrigh** [comment]
That did it! Good looking out.
