### ISSUE TITLE
Make colors for swaylock unlock indicator configurable

### ISSUE THREAD

**Issue by embik** [SirCmpwn/sway#1078]
This seems to be a rather trivial and rather petty request, but I would like to pass parameters to swaylock to change the unlock indicator's colors. My whole desktop follows a certain colorscheme and my lock script is using a blurred version of my screen as swaylock background, thus the unlock indicator looks a bit off. Would be pretty rad to change the default colors when calling swaylock.

I would implement this myself (doesn't seem too hard in principle), but I have never written a single line of C. So, if anyone has the same itch as me, that would be neat.

**Comment by Timidger** [comment]
>but I have never written a single line of C

Now's the time to learn! It's not a hard language. At worst, if you don't think it's good enough for a PR (even though it probably is) you can change it for yourself.

**Comment by SirCmpwn** [comment]
>Now's the time to learn! It's not a hard language. At worst, if you don't think it's good enough for a PR (even though it probably is) you can change it for yourself.

This. The odds of someone else doing this for you are low and the odds of you succeeding if you try are high.

**Comment by embik** [comment]
You're right, I'll take a look after my exams are over.

**Comment by 4e554c4c** [comment]
@embik With #1081 this should be possible now.

**Comment by embik** [comment]
Wow, thanks a lot @4e554c4c 👍
