### ISSUE TITLE
Proper way to launch something on startup

### ISSUE THREAD

**Issue by kenny1847** [SirCmpwn/sway#1079]
When I was using i3 there was a facility to do it placing 
```
exec "commands; more commands; even more commands"
```
and it was executed after wm starts.

Tried same in sway has no effect.
May be there any alternatives to it, may be even outside sway?
Real case one: earlier I've got `~/.xinitrc`, and many things were there. (May be exist any alternative for wayland?)
Real case two: I want to launch some applications when system starts.

I am new to wayland, so, sorry if this is stupid question.

**Comment by SirCmpwn** [comment]
Just put it on several lines:

```
exec command
exec command
exec command
```

Sway does quoting differently from i3. `exec "commands; more commands; even more commands"` will attempt to run /usr/bin/"commands; more commands; even more commands"
