### ISSUE TITLE
Feature Request: i3 Floating Container Movement

### ISSUE THREAD

**Issue by crgnclsn** [SirCmpwn/sway#1083]
I cannot see this listed on your i3 feature checklist.

The i3 implementation that allows you to move floating containers by a number of a pixels is specified here:

https://i3wm.org/docs/userguide.html#_moving_containers

I have had a brief search through the github and can't find any reference to this feature or it's potential implementation.

**Comment by SirCmpwn** [comment]
I added it to the i3 feature support issue. In the future please bring such requests up in the comments of that issue.
