### ISSUE TITLE
hidpi issues

### ISSUE THREAD

**Issue by boydkelly** [SirCmpwn/sway#1088]
Hi,
I have the following in my .config/sway/config file on my highdpi laptop
output eDP1 pos 0,0 res 3200x1800
output eDP1 scale 2

I notice that some things are displayed corectly and others not.  Oddly gnome-terminal is super small.  But mate-terminal is fine.  Emacs and Gvim display correctly. The sway status bar is super small (I'd need a magnifying glass to read the time etc.)  But when I press $MOD d then the font becomes larger and readable.  Its sort of like $Mod d is hidpi aware but the status bar isn't.  The mouse cursor also seems to not be scaled.  Anything I can do?  Thanks.

**Comment by SirCmpwn** [comment]
eDP1 isn't a valid output name. Did you mean eDP-1? Check with `swaymsg -t get_outputs`.

**Comment by boydkelly** [comment]
ok,  I fixed that, but it still does the same....  As mentioned above emacs, gvim, firefox etc actually display correctly as under gnome also with scale 2.  It is only the sway status bar that needs the magnifying glass.  When I press $MOD d the status bar becomes bigger and font readable.   When I press esc, it goes back to tiny.

**Comment by boydkelly** [comment]
Hi,  Ok I've been trying this under a kvm and on my laptop.  I have problems on both, although under the kvm the bar looks ok until y ou press $mod d as indicated.  On my laptop i have the following in my config:

output eDP-1 pos 0,0 res 3200x1800
output eDP-1 scale 2

But a swaymsg -t get_outputs will show the res a 3200x1800 as requested but the scale continues to return 1.  The setting does't seem to take.

Thanks

**Comment by mpcjanssen** [comment]
Putting it on one line works for me:

`output eDP-1 pos 0,0 res 3200x1800 scale 2`

**Comment by boydkelly** [comment]
Thank you!  That works.  Oddly if I set the resolution to 1024x768 then the Scale setting will take. (On two lines). But not with 3200x1800.
