### ISSUE TITLE
Better implemented move.

### ISSUE THREAD

**Issue by Half-Shot** [SirCmpwn/sway#109]
*(Moved this discussion from a pull request into a issue)*
Going to find a way to make move play nice with split/h and various other layouts, as currently we just shuffle up and down a list without a care for what this does to the output. It works fine for standard horizontal tiling but no good for anything else.

**Comment by Luminarys** [comment]
I think the correct way to handle this is to call the `get_swayc_in_direction` function to figure out which container needs to be grabbed, then simply swap the two in their parent's lists.

**Comment by Half-Shot** [comment]
Not going to be at my desktop til Saturday, so feel free to hack at it first.
