### ISSUE TITLE
How to get current keyboard layout?

### ISSUE THREAD

**Issue by Freyr666** [SirCmpwn/sway#1093]
Keyboard layout switching configs described in wiki work well, but I don't know the way to get current layout. Is there any? Thanx.

**Comment by SirCmpwn** [comment]
Just check the environment variable?

**Comment by Freyr666** [comment]
>Just check the environment variable?

Which one?

**Comment by SirCmpwn** [comment]
XKB_DEFAULT_LAYOUT?

**Comment by SirCmpwn** [comment]
The same one you have to set to specify the layout in the first place.

**Comment by Freyr666** [comment]
```
> echo $XKB_DEFAULT_LAYOUT
us,ru
```

No, that is not it. I need to know which one layout is set, `us` or `ru`

**Comment by SirCmpwn** [comment]
Oh. I don't know how to do that.

**Comment by Freyr666** [comment]
But you implemented kbd switching somehow, there should be some way to get the value of the current active layout? Some ipc call?

**Comment by SirCmpwn** [comment]
No, that's all done by libinput, not us.

**Comment by RichardVoid** [comment]
@Freyr666  You can use something like this: https://gist.github.com/RichardVoid/51cd296535e11a73caf102855e0df4db

**Comment by ianhattendorf** [comment]
@RichardVoid I don't think that works under Wayland. Testing on i3 works, but on Sway it's always `LED mask:  00000000`.

For example, I have `Exec=env XKB_DEFAULT_LAYOUT=us,br XKB_DEFAULT_OPTIONS=grp:alt_shift_toggle sway` in my `sway.desktop` file. I can toggle fine, however I can't query the current state. With i3, I was using the command `xkb-switch -p;xkb-switch -W` to get the initial state and then any updates in real-time.

@SirCmpwn Is this something that would have to be handled by Sway/wlroots, or is it possible to query using something like libinput? I'm not seeing anything in it's man pages or online.

**Comment by l4l** [comment]
`swaymsg -t get_inputs | jq '.[0].xkb_active_layout_name'`

That works for me, @ianhattendorf, may you also try it? It though prints full layout name, rather than 2-letters. jq util is form [here](https://stedolan.github.io/jq/download/), you may use any other json utility for that. For me keyboard is the first element in inputs array, so if it differs for you, you should replace `[0]`

**Comment by it-is-wednesday** [comment]
@l4l's solution works well, but I have a weird case where my mouse appears first in this list. The following query catches there cases:

```jq
swaymsg -t get_inputs | jq 'map(select(has("xkb_active_layout_name")))[0].xkb_active_layout_name'
```

**Comment by l4l** [comment]
Yeah, that's still doesn't work if you specify xkb toggle option only for specified identifier. So I ended up with explicit search rather than choose one by luck:

```
swaymsg -t get_inputs | jq -r '.[] | select(.identifier == "<your_keyboard_identifier>") | .xkb_active_layout_name')
```

**Comment by SNvMK** [comment]
sorry for necrobumping, but `swaymsg -t get_inputs` doesnt return json... then how do i check current layout?

**Comment by emersion** [comment]
It returns JSON if stdout isn't a tty. There's also an option to force json.

**Comment by SNvMK** [comment]
> It returns JSON if stdout isn't a tty. There's also an option to force json.

oh, didnt know, thanks
