### ISSUE TITLE
swaylock leaks partial desktop

### ISSUE THREAD

**Issue by maximiliankaul** [SirCmpwn/sway#1095]
```
$ swaylock --version                                                                          
swaylock version 0.12-rc1-13-g21ad45b (2017-02-28, branch "master")
```

When executing `swaylock -i /path/to/image.png -s stretch` on a multi monitor setup where monitor resolutions differ, parts of the desktop are not covered by the image (still shows whats beneath it).

My primary monitor is 1920 by 1080 pixels and the secondary is 1920 by 1200. The secondary leaks a strip of 60 pixels at the top and a strip of 60 pixels at the bottom.

**Comment by SirCmpwn** [comment]
We should probably clear to a solid color if -c isn't specified.

**Comment by maximiliankaul** [comment]
Clearing to a solid color would fix this. However, it used to be that the image gets stretched to fill each monitor and I think that is what users expect, when they specify `-s stretch`.

**Comment by SirCmpwn** [comment]
Ah, I see. That makes more sense.

**Comment by SirCmpwn** [comment]
Oh, durr. There's a breaking change in the swaylock command line for 0.13 (you're building from master). `-s` has been removed. Use `--scaling`.
