### ISSUE TITLE
None-alphanumeric characters don't work on workspace names

### ISSUE THREAD

**Issue by hobarrera** [SirCmpwn/sway#1099]
I've a few workspaces that have some _"weird"_ characters just to visually identify them. They seem to work fine on i3, but pressing $mod+1 does nothing on sway. Other workspaces work fine. The debug logs don't show any errors either. Relevant config:

```
bindsym $mod+1 workspace 1: 
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8: 🔊
bindsym $mod+9 workspace 9: 
bindsym $mod+0 workspace 10: 
```

**Comment by 4e554c4c** [comment]
Sway handles and displays unicode characters fine. Perhaps you have a space between the worspace number and symbol in your config?

**Comment by SirCmpwn** [comment]
Try quoting them and make sure all of the commands that reference the ws are consistent.

**Comment by hobarrera** [comment]
Yup, quoting them did the trick. Since i3wm supports these values unquoted, can this discrepancy be considered an issue, or should I just close this?

**Comment by SirCmpwn** [comment]
Yeah, we should probably join the args together when possible. Can leave this open until that's done.
