### ISSUE TITLE
Ubuntu/ Debian packaging

### ISSUE THREAD

**Issue by nicman23** [SirCmpwn/sway#1100]
I messed around with packaging sway for debian based distros (i have ubuntu) and i am writing from the compiled session :) . It is all every initial and depends are not even written (only make depends), but it works for me and I 'll make a simple ppa if i find the time.

Also the same for wlc

You are welcome to close this if you do not particularly care :)

**Comment by SirCmpwn** [comment]
Good for you, but this is a bug tracker, not a place to announce things like that.
