### ISSUE TITLE
Border none does not work on 0.12

### ISSUE THREAD

**Issue by Fale** [SirCmpwn/sway#1107]
Hi,
I have had this in my `~/.config/sway/config` since many months ago:
```
for_window [class="^urxvt"] border none
```

And it always removed the border to my urxvt256c-ml terminal windows.
Since the update to sway 0.12 this does not happen any more and now my terminal has the border.
Has the syntax changed or is the feature broken?

**Comment by SirCmpwn** [comment]
You might need instance instead of class now.

**Comment by Fale** [comment]
Thanks.

```
for_window [instance="urxvt256c-ml"] border none
```

works as expected :)
