### ISSUE TITLE
Enhancement: Book sheet tiling (automatical "smart" placement of any window at any time)

### ISSUE THREAD

**Issue by dumblob** [SirCmpwn/sway#1109]
For a thorough description, please refer to https://github.com/joewing/jwm/issues/283 . Comments welcome!

**Comment by SirCmpwn** [comment]
Can you provide a video of how this works? I don't really understand it.

**Comment by dumblob** [comment]
I don't have one currently, but I'll try to make some demonstration slideshow. In the meantime, could you please ask specific questions what exactly is not clear? I'd like to answer these and fix the description.

**Comment by SirCmpwn** [comment]
You describe enough to implement it, maybe, but not enough to understand it.

**Comment by dumblob** [comment]
I'm drowning in other work, so thanks for reminding me. I'll provide a set of screenshots describing this functionality once I'll finish some other tasks currently bothering me. Thanks for understanding.
