### ISSUE TITLE
Odd behavior when clicking on sway-bar with two windows open

### ISSUE THREAD

**Issue by that1communist** [SirCmpwn/sway#1110]
I wasn't even sure it was worth posting, but it was odd, and easily reproducible.

Open two windows, horizontal, have the one on the right in focus, click on the swaybar, now both windows have the same border as if they were both in focus.

Weird tiny reproducible thing.

**Comment by SirCmpwn** [comment]
Dupe https://github.com/SirCmpwn/sway/issues/1104
