### ISSUE TITLE
Error when starting sway: swaybg requires compositor to support desktop-shell-extension

### ISSUE THREAD

**Issue by jabranham** [SirCmpwn/sway#1111]
When trying to start sway, either from tty terminal or gdm, I get an error message: `swaybg requires the compositor to support the desktop-shell extension`. I thought sway was the compositor, so I'm a little confused on how to handle this. 

If I log into a gnome wayland session, I can start sway from a terminal just fine. 

This is on Arch linux with packages up-to-date as of today (though sway is still at 0.11 in the repos).

**Comment by ivoborisov** [comment]
I think that an update to `mesa` is causing this.

You can solve this by installing `wlc-git` and `sway-git` from AUR or wait for someone to update these packages in the official repos.

**Comment by avbobylev** [comment]
@ivoborisov using sway-git cause another error related to CAP_SYS_PTRACE in main.c:174, so sway is completely unusable after the latest mesa update even when installed from AUR

**Comment by jabranham** [comment]
Contrary to @avbobylev's experience, after installing wlc-git and sway-git from the AUR, it loads up fine for me.

**Comment by SirCmpwn** [comment]
Provide a full debug log please.

**Comment by sanpoChew** [comment]
Worked for me without installing sway-git, just wlc-git. and it probably is an update to mesa as @ivoborisov said, I had updated a few hours before resetting and seeing this.

**Comment by avbobylev** [comment]
Seems `wlc-git` aur package is messed up a little. Build both sway and wlc from git, and everything works fine.
