### ISSUE TITLE
Enpass Chrome extension

### ISSUE THREAD

**Issue by braderhart** [SirCmpwn/sway#1116]
The one blocker from me being able to use sway reliably is Enpass not working with Chrome. It shows up the first time you click on it, and then the extension won't actually visibly load in Chrome thereafter while using sway. No issues in i3wm, but I'd like to be able to use a Wayland-native WM.

**Comment by SirCmpwn** [comment]
https://github.com/SirCmpwn/sway/issues/571

**Comment by braderhart** [comment]
@SirCmpwn Thanks & sorry for missing.
