### ISSUE TITLE
Sway fails to load files on 0.12.1 in security.d when d_type == DT_UNKNOWN (eg. on XFS)

### ISSUE THREAD

**Issue by oranenj** [SirCmpwn/sway#1118]
As discussed on IRC, I had a weird problem with the configuration in /etc/sway/security.d not getting loaded unless I'd explicitly include it in the config file.

The problem is with this line, which tests whether the file is a regular one:
https://github.com/SirCmpwn/sway/blob/0.12.1/sway/config.c#L532

But on XFS, d_type is DT_UNKNOWN, so that check returns false, and the file won't be added to the list.

readdir(3) states that "All applications must properly handle a return of DT_UNKNOWN."

The issue goes  away if I mount an ext4 filesystem in security.d

EDIT: it's actually fixed on master.
https://github.com/SirCmpwn/sway/blob/ec50b92bb43af7fc17f3c6d786bcbb585f673223/sway/config.c#L540

**Comment by SirCmpwn** [comment]
Hmm. It could be a security risk if we don't know what type of node it is.

**Comment by oranenj** [comment]
I wrote a small tool to check how that thing behaves, and I'm not sure what's going on.
When I run 
```
#include <stdio.h>
#include <dirent.h>
#include <sys/stat.h>
#include <string.h>
#include <stdlib.h>
#define SYSCONFDIR "/etc"
int main() {
    DIR *dir = opendir(SYSCONFDIR "/sway/security.d");
    char *base = SYSCONFDIR "/sway/security.d/";
    struct dirent *ent = readdir(dir);
    struct stat s;
  	while (ent != NULL) {
        char *_path = malloc(strlen(ent->d_name) + strlen(base) + 1);
		strcpy(_path, base);
        strcat(_path, ent->d_name);
        printf("Checking %s... ", _path);
        lstat(_path, &s);
        if (S_ISREG(s.st_mode)) {
            printf("File is regular");
        } else if (S_ISLNK(s.st_mode)) {
            printf("File is a link");
        }
        printf("\n");
        ent = readdir(dir);
    }
    closedir(dir);
}
```
I get
```
Checking /etc/sway/security.d/.... 
Checking /etc/sway/security.d/..... 
Checking /etc/sway/security.d/00-defaults... File is regular
Checking /etc/sway/security.d/foo... File is a link
```
even with XFS.

That looks like a macro though. Maybe my system has a different definition of it than what sway was compiled with?

**Comment by oranenj** [comment]
Oh, and just to clarify, I added the symbolic link just to see if you can test for those on XFS

**Comment by oranenj** [comment]
Actually, I don't think this problem occurs with the commit I linked. What branch is that part of?

Loading works on master, because the code looks like this:
https://github.com/SirCmpwn/sway/blob/8306b886e9d24a5bbeafedf315724f97b3ae86d4/sway/config.c#L539
but fails on 0.12.1 because it doesn't use lstat
https://github.com/SirCmpwn/sway/blob/0.12.1/sway/config.c#L532

Somehow I can't find the commit that changed that code. though.

**Comment by oranenj** [comment]
Found it, the commit fixing this is 9aed9d93596cdc72e305338d82ccc0dcaf85c6e2
