### ISSUE TITLE
Way to turn screen off

### ISSUE THREAD

**Issue by airstep** [SirCmpwn/sway#1129]
Early I've used this method to make screen off:

 sleep 1 && xset dpms force off

... but now I get an issue:

X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  147 (DPMS)
  Minor opcode of failed request:  6 (DPMSForceLevel)
  Serial number of failed request:  12
  Current serial number in output stream:  14

The question is how to make it possible. For now I just need to switch to tty(n) and it works by default. Why I can't do this in wayland? And I read in some place that it is not yet possible... What you think?

And tnx for this project!

**Comment by SirCmpwn** [comment]
xset is an x tool, not a wayland tool. See #541

**Comment by Un1Gfn** [comment]
@airstep `swaymsg "output * dpms off"`

**Comment by MedievalSteel** [comment]
How to turn no screen?

**Comment by bl4ckb0ne** [comment]
`man 5 sway-output`
