### ISSUE TITLE
swaybg seems to be eating lots of ram

### ISSUE THREAD

**Issue by Fale** [SirCmpwn/sway#1131]
Doing:

    ps -eo size,pid,user,command --sort -size | awk '{ hr=$1/1024 ; printf("%13.2f Mb ",hr) } { for ( x=4 ; x<=NF ; x++ ) { printf("%s ",$x) } print "" }' | grep sway

I receive the following output:

        46.44 Mb swaybg 0 /usr/share/backgrounds/f25/default/normalish/f25.png fill 
        18.96 Mb sway -d 
         2.12 Mb swaybar -b bar-0 
         1.16 Mb sway -d 
         0.34 Mb grep --color=auto sway

If the command has no logical problem (I think it is right, but could be wrong), it seems like swaybg is eating 46.44 Mb of RAM (much more of the rest of Sway together). Why is that?

My first thought was that my image is huge, but:

    $ ls -alh /usr/share/backgrounds/f25/default/normalish/f25.png
    -rw-r--r--. 1 root root 5.8M Nov 15 16:32 /usr/share/backgrounds/f25/default/normalish/f25.png

So I wonder why to show a 5.8 Mb image 46.44 Mb of ram are used.

It seems to me that the ram usage does not change during the session, so I guess it's not a memory leak.

**Comment by SirCmpwn** [comment]
How big is the image when decoded to rgba?

**Comment by Fale** [comment]
@SirCmpwn how can I check that?

**Comment by SirCmpwn** [comment]
convert /usr/share/backgrounds/f25/default/normalish/f25.png rgba:rgba.dump
    du -h rgba.dump

**Comment by Fale** [comment]
45Mb.

Ok, so now the maths adds up, thanks a lot :)

**Comment by Fale** [comment]
Converting the image to 1:1 pixel ratio with what gets displayed and removing the parts of the image that are not showed to my screen, I arrived to:

```
$ ls -alh .dotfiles/wallpaper.png 
-rw-rw-r--. 1 fale fale 1.3M Mar 19 22:11 .dotfiles/wallpaper.png
$ convert .dotfiles/wallpaper.png rgba:rgba.dump
$ du -h rgba.dump
8.0M	rgba.dump
$ ps -eo size,pid,user,command --sort -size | awk '{ hr=$1/1024 ; printf("%13.2f Mb ",hr) } { for ( x=4 ; x<=NF ; x++ ) { printf("%s ",$x) } print "" }' | grep sway
        19.92 Mb sway -d 
         9.35 Mb swaybg 0 /home/fale/.dotfiles/wallpaper.png fill 
         2.12 Mb swaybar -b bar-0 
         1.16 Mb sway -d 
         0.34 Mb grep --color=auto sway 
```

So I guess swaybg could perform the same operations before putting the whole image in rgba on RAM to improve it's footprint

**Comment by SirCmpwn** [comment]
I'd rather not leave this open because I don't really think it's worth it. The complexity increase isn't justified for a minimal gain.

**Comment by Fale** [comment]
I see, thanks :)
