### ISSUE TITLE
ERROR: swaybg requires the compositor to support the desktop-shell extension

### ISSUE THREAD

**Issue by cactorium** [SirCmpwn/sway#1135]
Sway suddenly stopped working after an update on Arch Linux, using the sway-git AUR package (r1869.420fa20-1). Would you have any advice on troubleshooting or any info that'd be important for debugging? It fails with the error message in the title

I normally just run it off a virtual console

**Comment by 4e554c4c** [comment]
Is your WLC up to date?

**Comment by cactorium** [comment]
Whoops, yeah sorry!
