### ISSUE TITLE
how to run swaymsg in crontab

### ISSUE THREAD

**Issue by Yailm** [SirCmpwn/sway#1136]
I've got a script to update my wallpaper, and put it in my crontab.
But it throws error when it came to 

    swaymsg output 'eDP-1' bg pictures fill

showing "unable to connect to socket"

Should I set any environment variables？

**Comment by SirCmpwn** [comment]
The SWAYSOCK variable.

**Comment by Kuba314** [comment]
https://wiki.archlinux.org/title/sway#Troubleshooting mentions how to create the env value dynamically:
```
SWAYSOCK=/run/user/$(id -u)/sway-ipc.$(id -u).$(pgrep -x sway).sock
```
Works like a charm.

**Comment by emersion** [comment]
Note, this scheme is _not_ guaranteed to be stable. We might change it in the future.

**Comment by CarsonSlovoka** [comment]
crontab -e
```
# # m h  dom mon dow   command
* * * * * XDG_RUNTIME_DIR=/run/user/$(id -u) /usr/bin/bash ~/random_bg.sh   👈 if you want to use notify-send
* * * * * /usr/bin/bash ~/sh/sway/random_bg.sh
```

~/random_bg.sh
```sh
IMG_DIR="/data/desktop-theme/"

SWAYSOCK=$(find /run/user/1000/sway*sock)

random_bg=$(find $IMG_DIR -type f | shuf -n 1)
# echo $random_bg

# swaymsg            output "*" bg "$random_bg" fill # ❌ 
swaymsg -s $SWAYSOCK output "*" bg "$random_bg" fill

# 👇 for debug 
# notify-send "backgroud image update" "$random_bg\n$IMG_DIR"
```
