### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by DmitryHetman** [SirCmpwn/sway#1138]
undefined reference to symbol: udev_monitor_recieve_device@@LIBUDEV_183

**Comment by DmitryHetman** [comment]
[sway.txt](https://github.com/SirCmpwn/sway/files/869321/sway.txt)

**Comment by Hummer12007** [comment]
Do you have virtual/libudev?

**Comment by Hummer12007** [comment]
@SirCmpwn, mark it as fixed, for the time being.
