### ISSUE TITLE
Cannot move mouse and keyboard when starting sway without X11

### ISSUE THREAD

**Issue by pickfire** [SirCmpwn/sway#1139]
Hi, when I start sway without X11, I can't move the mouse and keyboard.

But when I had started sway in X11, I can do so. I then did `sway-input -t get_inputs` and it showed:
```
[
 ]
```

I am using `Linux alpine 4.9.17-0-grsec #1-Alpine SMP Thu Mar 23 09:59:13 GMT 2017 x86_64 GNU/Linux` and `sway version  (2017-03-15, branch "")` and `wlc-0.0.8-r1` (based on my package manager version).

[Debug logs](https://github.com/SirCmpwn/sway/files/872171/sway.txt)

**Comment by SirCmpwn** [comment]
Is the sway binary setuid? Do you have the correct caps enabled for it? Are you in the input group?

**Comment by pickfire** [comment]
> Is the sway binary setuid?

Probably yes, the output of ls:

    -rwsr-xr-x 1 root root 303672 Mar 15 23:27 /usr/bin/sway*

> Do you have the correct caps enabled for it?

What do you mean by that? Do I need to enable stuff for grsec compatibility?

> Are you in the input group?

Yes, I am in the input group.

**Comment by SirCmpwn** [comment]
I'm not sure what's necessary for grsec compatability. Run `getcap /usr/bin/sway` to check your caps, and see instructions in the README for setting them correctly.

**Comment by pickfire** [comment]
I get nothing for `getcap /usr/bin/sway`

**Comment by SirCmpwn** [comment]
Alright. See the README for instructions on setting them up.

**Comment by pickfire** [comment]
@SirCmpwn Now I can't even start sway in a tty.

[sway.txt](https://github.com/SirCmpwn/sway/files/872237/sway.txt)

**Comment by SirCmpwn** [comment]
Sorry, the readme doesn't mention another cap you need: cap_sys_tty_config

**Comment by pickfire** [comment]
Just notice that you had add that to the README, I had followed it and I get:

![2017-03-27-190654_1366x768_scrot](https://cloud.githubusercontent.com/assets/4687791/24353528/90427906-1320-11e7-8f07-1af2d8aade72.png)

**Comment by pickfire** [comment]
Now it works but still doesn't solve the main issue where the mouse and keyboard still doesn't work.

**Comment by Hummer12007** [comment]
You do not need to enable any caps for SUID sway. (pages @SirCmpwn)

**Comment by SirCmpwn** [comment]
https://forums.gentoo.org/viewtopic-t-1005392-start-0.html

?

**Comment by SirCmpwn** [comment]
@Hummer12007 do you remember the fix for this issue that gentoo users had to use?

**Comment by Hummer12007** [comment]
Mark the exe with paxctl? (if you're talking about hardened users)

**Comment by pickfire** [comment]
IIRC alpine doesn't come with alpine by default.
