### ISSUE TITLE
Can't move windows between scaled monitors

### ISSUE THREAD

**Issue by sandler31** [SirCmpwn/sway#1144]
Steps to reproduce:
===
1. Install sway on a laptop/pc with 1 High-DPI and 1 regular monitor
2. Configure scaling on the High-DPI monitor using the following configuration:
```output <name> scale <factor>```
3. Open a window on one of the monitors & try to move it to another monitor

Expected result:
===
The window should be moved to the other monitor?
I'm not really sure if it's a bug/regression or a missing functionality, as I'm not familiar with the code of the project.

System details:
===
System: DELL XPS 15 9560
OS: Arch Linux 4.10.6-1-ARCH
Sway version: 	0.12.1-1 (Installed from the community repo)

If any more details are needed, I'll happily provide them, as I'd really like to use this WM as my daily, due to the pretty good support for High-DPI scaling with mixed monitors.

**Comment by SirCmpwn** [comment]
By "try to move it" do you mean with the move command or by dragging it there?

**Comment by sandler31** [comment]
Move command

**Comment by SirCmpwn** [comment]
Double check that your monitors are correctly aligned in the config (with the `output pos` command). You may have to include the scale factor, I'm not sure off the top of my head.

**Comment by sandler31** [comment]
Ok, I'll try that and update, it'll be in some days, I'm not with that laptop currently.
Thanks for the prompt reply!
