### ISSUE TITLE
Access violation list operations

### ISSUE THREAD

**Issue by SirJls** [SirCmpwn/sway#1148]
I was just going through the code base base of this project to improve my understanding of C and potentionally even contribute if my understanding is on a level I'm confident about not screwing up the code base or getting rejected pull requests... Oh yes I do also use the WM, it's a great product thank you!
Back to the topic of going through the code base, my eye fell upon these two [functions](https://github.com/SirCmpwn/sway/blob/master/common/list.c#L46-L56) in the code and wondered if these shouldn't be checked for access violation as the passed index value could potentionally be greater than the current size of the list and result in undesirable/dangerous behaviour? 

As mentionded the reason why I didn't provide a PR, but did report the obervation this way was because of my lacking knowledge of C... If you would rather see small PR's which you can just flat out reject, I would be happy to oblige, as I catch myself digging into the code base more and more.

**Comment by SirCmpwn** [comment]
Seems reasonable to add a sway_assert there.
