### ISSUE TITLE
swaymsg waiting && sway 100% cpu usage

### ISSUE THREAD

**Issue by sohorx** [SirCmpwn/sway#1152]
Hi, first of all thank for your cool work.

I'm using archlinux and using sway 0.12.1-1 from community,
so here the issue:
while I was trying to put the focused window title inside conky using swaymsg -t get_tree with an interval of 0.5sec it appear that after 4 to 5 min swaymsg does not respond anymore while sway get a 100% cpu usage.

this being the half working script used by conky
```sh
swaymsg -t get_tree | sed '/focused": true/,$!d' | grep "title" | head -1 | cut -d '"' -f4
```

I don't know if using swaymsg this way is what I should do but since I can't use Xlib to get wayland window title and wayland does not allow me to see the focused window title, this is the only way I found.

**Comment by SirCmpwn** [comment]
Been running your command in a loop for a while, CPU usage seems nominal. Something else is probably the cause.

**Comment by ascent12** [comment]
I managed to reproduce the same issue after running it in a loop for about 10 minutes or so, also from the archlinux community version.

Using
```bash
#!/bin/bash

i=0

while true; do
	echo "$i"
	swaymsg -t get_tree > /dev/null
	((i++))
done
```
it freezes at 989, but does not cause any spike in CPU usage for me.
After trying to run it again:
```
Unable to accept IPC client connection: Too many open files
```
is spammed in sway's output.

I tried with the master branch as well, and the same thing happens.

**Comment by SirCmpwn** [comment]
Interesting, maybe the fds aren't closed properly.

**Comment by SirCmpwn** [comment]
Does https://github.com/SirCmpwn/sway/pull/1153 fix the problem for you?

**Comment by ascent12** [comment]
That fixes it, but I think the real issue is that client->fd is being set to -1 before the call to ipc_client_disconnect, so the cleanup functions in there aren't being called properly.

**Comment by SirCmpwn** [comment]
Ah, good point.
