### ISSUE TITLE
Sway does not register small mouse movements

### ISSUE THREAD

**Issue by ascent12** [SirCmpwn/sway#1156]
Moving the mouse cursor very slowly either right or down will not cause the cursor to move.
However, it does work properly if you move the mouse slowly up or left.

I've tried it in X11 (using xf86-input-libinput) and in weston, and it works fine, so it's not a problem with my mouse or libinput.

**Comment by SirCmpwn** [comment]
https://github.com/Cloudef/wlc/issues/181
