### ISSUE TITLE
Mouse pointer can go past edge of screen on scaled outputs

### ISSUE THREAD

**Issue by ascent12** [SirCmpwn/sway#1157]
On a scaled output, you're able to move the cursor past the left and top edges of the screen. How far it goes depends on the scale. Also, if you go near the bottom or right side of the screen, it cursor will stop short before it reaches it, and disappears.
It seems that the mouse bounds and the output bounds don't line up properly.

Also, it doesn't seem to be sending the mouse events to the correct clients. If you click on swaybar near the bottom, it will click the window open below it instead. That also seems to suggest that the mouse and the output aren't lined up properly.

**Comment by SirCmpwn** [comment]
Report to wlc
