### ISSUE TITLE
swaybar: 'mode hide' no effect (silently ignored)

### ISSUE THREAD

**Issue by tjavdar** [SirCmpwn/sway#1158]
First congrats and thanks^2 for great work from a fresh convert from i3 to sway on Wayland!

I use to hide status bar (consider it robbing too much of screen estate), so I display it just when needed
(press $mod  in i3).

The problem: i3status displays properly, but is not hidden.

Here's my corresponding lines in config:

bar {
  position         bottom
  mode             hide 
  status_command   i3status -c ~/My/skel/sway/i3status.conf  
  }

Vesrsion info:
sway 0.12.1-1 / Linux i5 4.10.8-1-ARCH

**Comment by SirCmpwn** [comment]
See #2

**Comment by minus7** [comment]
See #343 for i3bar feature support: it's not implemented yet. Feel free to implement it and send a patch.

**Comment by oblitum** [comment]
I've [hacked this](https://github.com/swaywm/sway/issues/1521#issuecomment-352237402) for manual bar hide:

```
bindsym $mod+a exec ( ( ps axo comm= | grep -w "swaybar" > /dev/null ) && pkill swaybar ) || swaybar -b bar-0 
```

**Comment by gun1x** [comment]
Is there any progress on this?

**Comment by RedSoxFan** [comment]
`mode hide` is supported on sway 1.0 and newer.

_This issue is from the 0.x era. sway (and swaybar) have been completely rewritten since._

**Comment by colesnicov** [comment]
Hello friends. 
I wrote this in the `~/.config/sway/config`:

```
bar {
  mode hide
  swaybar_command waybar
}
```

, but the swaybar is still active. It is shown just below the waybar :/ 

Any advice? :)
