### ISSUE TITLE
Compillation error

### ISSUE THREAD

**Issue by DmitryHetman** [SirCmpwn/sway#1163]
[sway.log.txt](https://github.com/SirCmpwn/sway/files/911327/sway.log.txt)

**Comment by SirCmpwn** [comment]
cc @Hummer12007 seems like libinput headers are missing

**Comment by DmitryHetman** [comment]
They are. After updating libinput got another error.
[sway.log.txt](https://github.com/SirCmpwn/sway/files/911342/sway.log.txt)

**Comment by Hummer12007** [comment]
Do you have dev-libs/libinput installed?

**Comment by Hummer12007** [comment]
And virtual/libudev

**Comment by Hummer12007** [comment]
If you have, then try re-emerging wlc and then sway.

**Comment by DmitryHetman** [comment]
Yes I have libinput and virtual libudev

**Comment by Hummer12007** [comment]
> If you have, then try re-emerging wlc and then sway.

**Comment by DmitryHetman** [comment]
wlc re-emerged, this does'nt help same error.

**Comment by Hummer12007** [comment]
Does wlc build show any errors?

**Comment by DmitryHetman** [comment]
@@LIBUDEV_183 
Is it version of virtual/libudev?

**Comment by Hummer12007** [comment]
Something like that.

**Comment by DmitryHetman** [comment]
On gentoo virtual/libudev 232 version

**Comment by Hummer12007** [comment]
It's ok, I have the same.

**Comment by DmitryHetman** [comment]
wlc only shows some warnings, not errors

**Comment by Hummer12007** [comment]
It might be caused by -Wl,--as-needed

**Comment by DmitryHetman** [comment]
[wlc.log.txt](https://github.com/SirCmpwn/sway/files/911486/wlc.log.txt)

**Comment by Hummer12007** [comment]
Try removing it from your CFLAGS

**Comment by DmitryHetman** [comment]
How remove it?

**Comment by Hummer12007** [comment]
edit your /usr/portage/make.conf

**Comment by Hummer12007** [comment]
Or from LDFLAGS...

**Comment by Hummer12007** [comment]
Ah, it's introduced by sway...

**Comment by Hummer12007** [comment]
It tries to build with the static wlc lib, which requires explicitely specifying -ludev. Try installing dev-libs/wlc without the static-libs USE flag.

**Comment by DmitryHetman** [comment]
Ok!

**Comment by DmitryHetman** [comment]
Fine, it works, but why even add static option if it doesn't work?

**Comment by Hummer12007** [comment]
I wasn't the original author. Besides, it might've worked back then

**Comment by DmitryHetman** [comment]
Don't close the issue then

**Comment by SirCmpwn** [comment]
Distro problems are not sway problems.

**Comment by DmitryHetman** [comment]
It's sway problem, it have option to build static lib, but it doesn't work.

**Comment by SirCmpwn** [comment]
Sway has no such option.

**Comment by Hummer12007** [comment]
@DmitryHetman Looked into it some time ago. Didn't notice an obvious way it to fix it. Building static wlc just marks symbols from shared libs as missing, so, for sway to link, these libraries have to be specified explicitely in the LDLIBS. It is plausible that the current build works on some configurations (when all packages have static libs installed), so I won't add a blocker either.
