### ISSUE TITLE
"scale" rounds down to nearest integer

### ISSUE THREAD

**Issue by hobarrera** [SirCmpwn/sway#1165]
I've been try to fiddle around with scaling, and it looks like it's rounded to the lowest (*not nearest*) integer.

I've been using basically a scaling of +60% on Xorg, so for sway I wanted to use a scale of 1.6 (which would result in the exact same output), but this gets rounded down to 1, which is far too smal.

With: `output eDP-1 scale 1.6`

```
$ swaymsg -t get_outputs
[
   {
     "id": 1,
     "name": "eDP-1",
     "rect": {
       "x": 0,
       "y": 0,
       "width": 2880,
       "height": 1800
     },
     "visible": true,
     "focused": false,
     "active": true,
     "primary": false,
     "layout": "output",
     "type": "output",
     "current_workspace": "1: ",
     "scale": 1
   }
 ]
```

With: `output eDP-1 scale 2.0`

```
$ swaymsg -t get_outputs
[
   {
     "id": 1,
     "name": "eDP-1",
     "rect": {
       "x": 0,
       "y": 0,
       "width": 2880,
       "height": 1800
     },
     "visible": true,
     "focused": false,
     "active": true,
     "primary": false,
     "layout": "output",
     "type": "output",
     "current_workspace": "1: ",
     "scale": 2
   }
 ]

**Comment by SirCmpwn** [comment]
This is by design, only integral scale factors are supported.

**Comment by hobarrera** [comment]
Any change that this is reconsidered? Anything I can do to help? TBH, the difference between 1.0 and 2.0 is huge, and 1.6 fit just perfect.

Rounding down 60% or up 80% is just too much difference, regrettably.

**Comment by SirCmpwn** [comment]
You can get something similar by setting your resolution to an arbitrary value. Note that due to limitations with wlc the resolution configuration is currently unrelated to modesetting, you can set it to whatever you want and the output will be scaled to it.

**Comment by hobarrera** [comment]
I tried setting the resolution so as to have a 1.6x scaling (eg: 2880x1800/1.6: `output eDP-1 res 1800x1125`) which should have given the desired results, however, I found two, quite unrelated bugs:

1. `swaygrab` grabs cropped screenshots: the resulting file is the upper-left region of the entire screen. The file is 1800x1125px, but it's as if a 1800x1125 region had been cropped out of the upscaled 2800x1800 image.
2. Everything is very blurry; this sort of scaling is very evident and unpleasant. It's slightly harder to focus and doesn't look sharp at all, so it's not really an alternative to actually being able to scale at 1.6x. :(

Would you like for me to open a separate issue for (1)?

**Comment by SirCmpwn** [comment]
To be honest, no. Configuring it this way is a hacky workaround and you shouldn't expect it to work forever.

**Comment by hobarrera** [comment]
What's the long-term plan for scaling, since the only thing currently supported is integer-only?

**Comment by SirCmpwn** [comment]
The long term plan is currently integer-only. Non-integral scaling is a non-starter, it's not a concept that really makes sense to implement or use.

**Comment by hobarrera** [comment]
Back to my actual real issue: on X I just configured it to use 160dpi to achieve a desired widget/UI/text size.

What can I do to achieve a similar result in sway?

**Comment by SirCmpwn** [comment]
Probably something specific to each GUI toolkit you use. Maybe something with fontconfig. Not sure.
