### ISSUE TITLE
Weird behavior when switching to/from VT when using scaled output

### ISSUE THREAD

**Issue by DonOregano** [SirCmpwn/sway#1167]
Using Arch on a T470s with 2560x1440 display with scaling set to 2.

If I launch a Terminator terminal it is scaled correctly and the fonts look nice and crisp. If I switch to a VT and then back again the fonts look blurred.

If I launch an urxvt terminal before switching, it looks correct, with small fonts that have been scaled up. If I then switch to and from VT it still looks the same, but if I launch a new one it will use fonts that are double in size.

It appears to me that somehow the scaling is applied twice.

(I am using gdm to launch sway, don't know if that makes a difference. I can try this without gdm tonight to see if it makes a difference).

**Comment by SirCmpwn** [comment]
Anything related to VT switching is an issue with wlc, please report your issue there.

**Comment by DonOregano** [comment]
For reference, I this is the wlc issue: https://github.com/Cloudef/wlc/issues/251
