### ISSUE TITLE
bindsym $mod+m i3-input -F 'mark %s' -l 1 -P 'Mark: ' does not work

### ISSUE THREAD

**Issue by TapioT** [SirCmpwn/sway#1170]
I have this in my i3 configuration; I use it to mark windows with a single letter. These are known as "vim type marks" in i3. The command to read a single letter in a script in a configuration file in i3 is i3-input. This command does not seem to work in sway, so I would like to know what is the correct way of implementing vim-type marks in sway config.

**Comment by SirCmpwn** [comment]
Sway does not currently have an equivalent to i3-input. Try a dmenu-based solution instead. Marks are also not available in 0.12.*, they will be shipping in the upcoming sway 0.13.

**Comment by TapioT** [comment]
Thanks for the hint! I got this to work from the command line:

echo | dmenu -p "Mark_" | xargs swaymsg '[class="Chromium"] mark '

to mark the chromium browser with a text of my choosing, and

echo | dmenu -p "Mark" | xargs swaymsg mark 

marks the current window.

**Comment by TapioT** [comment]
And this seems to work in the config file:

set $get_mark echo | dmenu -p Mark: | xargs swaymsg mark
bindsym $mod+m exec $get_mark

Should this be part of the default config file?

**Comment by SirCmpwn** [comment]
Nope.

**Comment by tmccombs** [comment]
unfortunately, dmenu doesn't have an equivalent of the `-l` option for i3-input :(

**Comment by progandy** [comment]
I just wrote a bit of code with the bemenu library to create a length limited input that closes automatically. Feel free to expand it into a proper project.

https://gist.github.com/progandy/2c05fc5f0b4e76d92002263776549bd1
