### ISSUE TITLE
IPC security `permit` silently fails for symlinks

### ISSUE THREAD

**Issue by JerziKaminsky** [SirCmpwn/sway#1172]
I hit this when I made `/usr/bin/swaybar` into a symlink into my build directory and things got very weird.
Is there a security concern behind this or is it an oversight? @SirCmpwn I can send a PR if describe desired behavior, I think it should either work or log an error (maybe even abort).

**Comment by SirCmpwn** [comment]
This is the intended behavior. Making `/usr/bin/swaybar` a symlink into your build directory is a very silly thing to do.

**Comment by JerziKaminsky** [comment]
`/usr/bin` on my system has it's fare share of symlinks, there's nothing silly about that. The intended behavior is to treat symlinks as if they were missing files and give the user absolutely no indication of the fact except mysterious errors and bizarre UI effects? :man_shrugging:

**Comment by SirCmpwn** [comment]
symlinks are fine, but symlinks into your development directory, which is presumably under /home and readable only by you, is weird and not something you should do.

We read /proc/[pid]/exe to find the location of the executable asking for special permissions, and match that with the rules in your config. The kernel follows symlinks before loading executables into memory and populating /proc/[pid]/exe. Nothing we can do about that.

**Comment by JerziKaminsky** [comment]
> symlinks into your development directory, which is presumably under /home and readable only by you, is weird

There are no other users on my home machine, what's the difference for dev purposes? But nevermind.

> Nothing we can do about that.

not even just checking if the permit target is a symlink and resolving them them to the target bin?

**Comment by SirCmpwn** [comment]
>not even just checking if the permit target is a symlink when parsing the file and resolving them them to the target bin?

We could do that but I don't really care tbh. Send a PR if you want this. However, this brings up a good point: we should check that the file being given permissions is owned by root.
