### ISSUE TITLE
Shortcuts with brackets don't work

### ISSUE THREAD

**Issue by DerVerruckteFuchs** [SirCmpwn/sway#1177]
In my sway config I have `bindsym $mod+Shift+greater` to match my i3 config. However, it does not work. Changing it to `bindsym $mod+Shift+Q` allows it to work. I also tried `>` and `Greater` instead of `greater`, which also did not work.

**Comment by zandrmartin** [comment]
Try `$mod+Shift+Period`

**Comment by DerVerruckteFuchs** [comment]
That seems to work just fine. It's not quite matching what i3 does with shortcuts, so that seems to need worked on I think. If I remember correctly, one of the goals for sway was to be able to use an i3 config file, which is what I used initially. Other than that though, it works.

**Comment by SirCmpwn** [comment]
We just do key parsing with xkbcommon. I don't intend to change that.
