### ISSUE TITLE
swaygrab

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/sway#119]
We should implement a tool called "swaygrab" or similar that allows you to dump pixels from the screen, for the sake of taking screenshots and recording video.

**Comment by Luminarys** [comment]
Weston seems to utilize its own tool for doing this, which we may want to look through to get an idea about how to do this. That being said I have the feeling that this will have to be done through wlc in some way.

On a separate note, we should probably create a list of sub-programs that we want to develop for sway so people interested can easily assist in their creation. A wiki page would probably suffice.

**Comment by SirCmpwn** [comment]
https://github.com/Cloudef/wlc/blob/master/include/wlc/wlc.h#L294-L295

**Comment by Luminarys** [comment]
Cool. How high of a priority is this?

**Comment by SirCmpwn** [comment]
Not sure. We can probably build this into i3-msg

**Comment by SirCmpwn** [comment]
If anyone plans on picking this up, let me know and I'll give you some details on how I'd like this to look

**Comment by Cloudef** [comment]
https://github.com/Cloudef/orbment/blob/master/plugins/core-screenshot/core-screenshot.c Example usage here.

**Comment by oatberry** [comment]
I'm a fan of the screenshot tool idea. On the X11 side of things, I really like @naelstrof's [`maim`](https://github.com/naelstrof/maim)] tool.

**Comment by SirCmpwn** [comment]
This exists now. It's pretty simple: https://github.com/SirCmpwn/sway/blob/master/swaygrab/main.c

**Comment by Tormen** [comment]
FYI: The swaygrab was discuontinued. The wiki now states:

```
Taking screenshots

X11 tools like scrot are not supported. Try grim.
```
