### ISSUE TITLE
PPA for Debian and Ubuntu

### ISSUE THREAD

**Issue by snoack** [SirCmpwn/sway#1197]
I packaged sway for Debian and Ubuntu, and published the package to [my PPA](https://launchpad.net/~s.noack/+archive/ubuntu/ppa). There is already another PPA linked on the [wiki page](https://github.com/SirCmpwn/sway/wiki/Unsupported-packages), which I suggest to replace. Some differences from the package I'm providing:

* Based on the latest release version of sway, and I plan to keep up with new upstream releases.
* Compatible with Debian (stable and testing) and every Ubuntu release since the last Ubuntu LTS.
* File capabilities are set automatically.
* WLC is statically linked (as opposed to be packaged separately).
* The files used to generate the package are [published on GitHub](https://github.com/snoack/sway/tree/debian/debian) (in the `debian` branch of my clone).

@SirCmpwn, what do you think?

**Comment by SirCmpwn** [comment]
Can some Debian/Ubuntu users try this guy's PPA out and let me know how well it works?

**Comment by captnfab** [comment]
I tried the package. It installs correctly on debian stretch.
I ran the programme inside an Xorg server, and it worked. Can't tell more.

I also checked the debian package sources, it looks clean and reasonable :)

**Comment by SirCmpwn** [comment]
I don't really care if it runs under X. That's a debugging feature. What matters is if it runs with the DRM backend.

**Comment by captnfab** [comment]
I ran it into a tty. It works well. I have keyboard handling problems, but I assume it has nothing to do with the Debian package.

**Comment by SirCmpwn** [comment]
It might. Can you elaborate?

**Comment by captnfab** [comment]
Ok. But first, I must say it's the first time I try sway and about the first time I try a wayland compositor.
My X keyboard setting is fr, variant bepo. It failed to recognize that. I changed it with the setxkbmap command, which I was a bit surprised to see working out of x. Some keys weren't functionnal, like & which was mixed up with up_arrow or something alike.

Another problem, probably unrelated to keyboard, I encountered after further testing was that firefox's menus were unstable or not shown at all. I was unable to enable scripts on a webpag using the "noscript" icon in the toolbar, no menu appeared.

Sorry if some of my remarks are irrelevant, I'm quite new to this project and just decided to give it a try since I'm an i3 user and found .deb package for sway today...

**Comment by SirCmpwn** [comment]
You're right, none of that is relevant to the PPA. @snoack feel free to put your PPA on the wiki

**Comment by snoack** [comment]
@captnfab: Thanks for testing!
@SirCmpwn: Done.

**Comment by snoack** [comment]
@captnfab: The Debian package from my PPA should now use the keyboard settings from `/etc/default/keyboard` as of version `0.13.0-2`. This might fix your keyboard problems. At least it makes sure that the correct keyboard layout/model/variant options are in effect.

**Comment by cawilliamson** [comment]
@snoack Hey there - any estimate on when 0.15 will be added to your apt repo? 👍

**Comment by snoack** [comment]
I just updated the PPA to sway 0.15. Thanks, for the heads up!

**Comment by sainoba** [comment]
@snoack Hey there - any estimate on when 0.15.1 will be added to your apt repo? :+1:

**Comment by JakeBrawer** [comment]
@snoack Hey there - any estimate on when 0.15.2 will be added to your apt repo? +1

**Comment by snoack** [comment]
Sorry for the delay. I plan to update the PPA soon.

**Comment by JakeBrawer** [comment]
@snoack Any updates?

**Comment by SirCmpwn** [comment]
Perhaps it would be wise to let multiple people have push access to your PPA, @snoack?

**Comment by betkuriamtikslui** [comment]
@snoack any plans for 1.0-beta.1?

**Comment by Sunderland93** [comment]
I also create experimental PPA with latest versions of wlroots and Sway. For now only for Ubuntu 19.04 https://launchpad.net/~samoilov-lex/+archive/ubuntu/sway

**Comment by emersion** [comment]
Excellent. Can you add it to the wiki?

**Comment by Sunderland93** [comment]
Done

**Comment by thuandt** [comment]
@Sunderland93 Do you have plan to also build for bionic?

**Comment by Sunderland93** [comment]
@thuandt Bionic has very old libraries, needed for building Sway. It's possible, but I dont have a time for it now. I'll take a look of it closer on weekend.

**Comment by techtonik** [comment]
@Sunderland93 any plans to update PPA to 1.1.1?

**Comment by Sunderland93** [comment]
@techtonik Yes, soon

**Comment by RJDan** [comment]
I have just upgrade using the ppa. Everything seems to work super smoothly. Thank you for all the hard work!!
