### ISSUE TITLE
Focus up/down does not work with arrow keys

### ISSUE THREAD

**Issue by aouelete** [SirCmpwn/sway#120]
The left/right arrow keys work, but up/down for some reason does not.

**Comment by Luminarys** [comment]
I've had some weird issues too with my up/down arrow keys not properly working. What is the exact keybind you're using for focus up/down?

**Comment by SirCmpwn** [comment]
Key bindings in general is pretty broken at the moment. I'll be giving it a serious overhaul soon.

**Comment by Luminarys** [comment]
Fixed.
