### ISSUE TITLE
Unable To Start Sway As Non-Root User

### ISSUE THREAD

**Issue by Dudemanguy911** [SirCmpwn/sway#1200]
I think I'm having some odd permission issue that I can't figure out. Sway starts up just fine if I run it as root, but as a non-root user it always exits with an error. I'm running Arch without systemd and logind so I'm sure that makes things more complicated, but the usual chmod +s works just fine on orbment and I can run that without root. I'm not sure why Sway would be any different.

Log: https://pastebin.com/d4Uw81if

**Comment by SirCmpwn** [comment]
https://github.com/SirCmpwn/sway/wiki/Sway-without-systemd-on-Arch-Linux

**Comment by Dudemanguy911** [comment]
Yes, I've done both of those.

**Comment by SirCmpwn** [comment]
Beats me, then.

**Comment by Dudemanguy911** [comment]
After some more time tinkering around, Sway does start up fine using elogind (as it should). Since my only concern was playing with Wayland without systemd, I'm pretty satisfied with that although I'm not convinced that Sway will work without logind.

**Comment by SirCmpwn** [comment]
I have a few systems that run sway without logind.
