### ISSUE TITLE
Middle-Button Scrolling on Thinkpad not working

### ISSUE THREAD

**Issue by hesseltuinhof** [SirCmpwn/sway#1205]
I am unable to get middle-button scrolling to work on a Thinkpad. Following `swaymsg -t get_inputs` I identified my trackpoint as **2:5:ImPS/2_Generic_Wheel_Mouse**. However, enabling **middle_emulation** has no effect.

To safeguard that my device name is correct I enabled *left_handed* and this option did the expected job.

Maybe someone here having middle button scrolling enabled on a Thinkpad machine and could help me out?

Edit: Config, Version and debug log can be found [here](https://gist.github.com/hesseltuinhof/b3f8a110406d5d31e8281ea78b9cdb9b)

**Comment by SirCmpwn** [comment]
I have a Thinkpad X200 and middle button scroll works fine.

**Comment by SirCmpwn** [comment]
https://github.com/SirCmpwn/sway/wiki#how-do-i-report-issues

**Comment by hesseltuinhof** [comment]
That's interesting. Is it working out of the box or did you have to configure it via `input device {}`?

**Comment by SirCmpwn** [comment]
Hmm, interestingly, no "Found input device ..." is shown in your logs.

**Comment by hesseltuinhof** [comment]
Can I provide any more information for you to figure out the problem maybe?

**Comment by hesseltuinhof** [comment]
Since running 0.14.0 middle-button scrolling is working fine...
