### ISSUE TITLE
Input device name wildcard

### ISSUE THREAD

**Issue by NicholasAsimov** [SirCmpwn/sway#1207]
Is it possible to specify a wildcard for an input device just like for output? For example I would like to have a generic config in which I disable pointer acceleration for every input device.
```
input * {
  pointer_accel -1
}
```

**Comment by SirCmpwn** [comment]
RTFM

**Comment by cafehaine** [comment]
https://github.com/swaywm/sway/blob/bc808680b173d5a3c4732265b33e2e8bd81e4d9b/sway/sway.5.scd#L543

So man 5 sway

**Comment by lhanson** [comment]
Gotcha, thanks.
