### ISSUE TITLE
Swaylock, after suspending PC, does not recognize password

### ISSUE THREAD

**Issue by WolfangAukang** [SirCmpwn/sway#1214]
Hello guys, I started testing Sway on Arch Linux and everything is awesome. I only have the following (weird) problem:

What I want to do is invoke swaylock after turning on the computer from a suspension (laptop is suspended, I press power button and swaylock appears on the screen). I'm basing it on two scripts I found, which work flawlessly on X11 using i3lock (the systemd setting https://gist.github.com/victorhaggqvist/603125bbc0f61a787d89 and the script to execute swaylock  https://gist.github.com/embik/eef65b532c88c101af3c8b058084e5bc).

The problem is, when I execute that systemd script as the user, and suspend the laptop, when I turn on, swaylock appears, but it seems not to recognize the password, even though I'm typing it right. I can say this is the only case where swaylock acts weird, because I had also configured swaylock to start when I press the lock key, and it works fine. It seems related to the systemd process that executes the script.

I don't know if there is a way to reproduce logs from that on swaylock because I didn't found any debug mode like on sway but I can give you more information. Thanks.

**Comment by WolfangAukang** [comment]
Just in case, I tested the script alone and it works without problems. So it seems it is related to the systemd process that executes the script.

**Comment by WolfangAukang** [comment]
Just in case, I found a way to start swaylocks using systemd. The gist is here https://gist.github.com/WolfangAukang/ffc3f481696c239c5583b5b3a0499e06

So the question is more related to why swaylock isn't recognizing the password

**Comment by hobarrera** [comment]
Are you running this as a system unit or a user one? I think you should
run it as the latter.

On Tue, May 9, 2017, at 23:09, Pedro Rodríguez de Oliveira wrote:
> Just in case, I found a way to start swaylocks using systemd. The gist
> is here
> https://gist.github.com/WolfangAukang/ffc3f481696c239c5583b5b3a0499e06> So the question is more related to why swaylock isn't recognizing the
> password> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 

--
Hugo Osvaldo Barrera

Links:

  1. https://github.com/SirCmpwn/sway/issues/1214#issuecomment-300353592

**Comment by WolfangAukang** [comment]
Right now, as a user one (and it's working). Before I made this issue, I executed it as a system unit

**Comment by likyng** [comment]
Hey @WolfangAukang could you maybe tell me in more detail how you made it work?
I think i tried the same, but I get the following error: 

    Nov 08 17:57:49 arch-tp systemd[1]: Starting Lock current sway session at device sleep...
    Nov 08 17:57:49 arch-tp swaylock[13260]: error: XDG_RUNTIME_DIR not set in the environment.
    Nov 08 17:57:49 arch-tp swaylock[13260]: E: 11/08/17 17:57:49 - [registry.c:256] Error opening display
    Nov 08 17:57:56 arch-tp swaylock[13260]: sway socket not detected.
    Nov 08 17:57:56 arch-tp swaylock[13260]: E: 11/08/17 17:57:56 - [main.c:550] Unable to connect to wayland compositor
    Nov 08 17:57:56 arch-tp systemd[1]: lock-screen.service: Control process exited, code=exited status=1
    Nov 08 17:57:56 arch-tp systemd[1]: lock-screen.service: Failed with result 'exit-code'.
    Nov 08 17:57:56 arch-tp systemd[1]: Failed to start Lock current sway session at device sleep.

my lock-screen.service file is located in `/etc/systemd/system/lock-screen.service` and I enabled it. It looks like this: 

    [Unit]
    Description=Lock current sway session at device sleep

    [Service]
    User=MYUSERNAME
    Type=forking
    Environment=DISPLAY=:0
    ExecStart=/usr/bin/swaylock -i /home/MYUSERNAME/pics/MYPIC.jpg --scaling=fill

    [Install]
    WantedBy=suspend.target

Adding `After=suspend.target` or `Before=suspend.target` to the unit file does not change anything..

**Comment by WolfangAukang** [comment]
Try to run it as a [user unit](https://wiki.archlinux.org/index.php/Systemd/User) instead of system. [This is the service file I created] (https://gist.github.com/WolfangAukang/ffc3f481696c239c5583b5b3a0499e06)

**Comment by tardypad** [comment]
I've been struggling to set this up too..., but now I have it "working"

I have a question though @WolfangAukang, I wonder how you made this work as a "user unit".
From what I see it should not be possible (and I couldn't make it work myself indeed)
From that Arch link you sent just before: `systemd --user runs as a separate process from the systemd --system process. User units can not reference or depend on system units.`
Which AFAICS means that user unit should not be triggered by the system suspending

Could you please post again the unit file you're using, along with its location on the filesystem?
I'm curious as well about that `lock-screen.sh` script you have (is it still the same as sent before?)
For me depending on the way `swaylock` is launched, I needed to remove `Type=forking` from the unit

Last question :) : when you come back from suspend, do you as well have that problem that first the screen with its applications is shown briefly (like 1sec) before the lock appears?
I tried to change orders with `Before:` but it doesn't seem to have any effect on that behavior...

Thanks for any pointers
I'm trying to have this run a bit smoother than it is now

**Comment by WolfangAukang** [comment]
Hey @tardypad, it has been a long time I haven't been using Sway with the Arch setup, but as I can recall, if I used it as a system service, I needed to use the root password to unlock the computer. Using it as a user unit fixed that issue for me (although, if running as system worked for you, that's great). I can't give you a good technical explanation of why it worked that way, though.

The lock-screen script is based on this one here (https://gist.github.com/embik/eef65b532c88c101af3c8b058084e5bc), and the service file is the one above your comment. It specifies the user, environment as it is managed differently on Wayland and the forking path is just what I've dragged from another script, without making proper tests of what it does.

I wish I could help you more, but it has been a long time without using my personal laptop with Arch :(

**Comment by tardypad** [comment]
Thanks for the extra info anyway :)

For now I removed this "feature" :/
There were too many minor issues that I didn't feel like spending time on at the moment:
- problem when screen is already locked manually before the suspend
- screen displayed before the lock on resume
- fragile looking scripting
