### ISSUE TITLE
Cannot successfully execute status_command (no JSON)

### ISSUE THREAD

**Issue by flynnham** [SirCmpwn/sway#1219]
Hey there, I've been trying to configure Sway to use a custom string in place of the default status bar, but I keep getting this error thrown at me:

```
05/10/17 16:22:15 - [config.c:706] Error on line 209 'status_command ~/scripts/statusbar.sh': Unknown/invalid command (/home/flynn/.config/sway/config)
05/10/17 16:22:15 - [config.c:486] Error(s) loading config!
05/10/17 16:22:15 - [main.c:69] Using output 0 of 1
```

I've made sure that the file is executable, and the script is able to run via `sh -c` (which is supposedly command swaybar uses to execute the command).

Here is the markup of my dumb little script file `~/scripts/statusbar.sh`:
```bash
#!/usr/bin/env bash
while (( 1 )); do
    time=$(date +"%a %Y-%m-%d %l:%M %p")
    freq=$(($(cpufreqctl info -n) / 1000 ))

    printf  "${freq} MHz  ${time}"

    printf "\n"
    sleep 1
done

# output: 3488 MHz  Wed 2017-05-10  4:26 PM
```

And the swaybar config in `~/.config/sway/config`:
```
# configs

bar {
    position top
    colors {
	status_command ~/scripts/statusbar.sh
	background #00000000
        statusline #ffffff
        inactive_workspace #32323200 #32323200 #5c5c5c
    }
}
# EOF
```

Can anyone point me to a reasonable fix?

**Comment by SirCmpwn** [comment]
You put the status_command into your color config. Move it to the bar config.

**Comment by flynnham** [comment]
Man, the things we end up missing being half-awake. Thanks for pointing that out!
