### ISSUE TITLE
Capslock as control

### ISSUE THREAD

**Issue by aidanharris** [SirCmpwn/sway#1220]
In X11 window managers I can use `setxkbmap -option ctrl:nocaps` to make the capslock key function as a control key. How can I accomplish the same with Sway?

**Comment by SirCmpwn** [comment]
Please read the [FAQ](https://github.com/SirCmpwn/sway/wiki).

**Comment by aidanharris** [comment]
@SirCmpwn Thanks. I fixed it as soon as I posted the issue (funny how that seems to happen sometimes). For future reference in case anyone stumbles upon this I solved my issue as follows:

## Copy default config
```bash
sudo cp /usr/share/wayland-sessions/sway.desktop /usr/share/wayland-sessions/sway-custom.desktop
```
## Change 'Exec' line to 'sway-custom'

```bash
[Desktop Entry]
Name=Sway (custom)
Comment=SirCmpwn's Wayland window manager
Exec=sway-custom
Type=Application
```

## Create '/bin/sway-custom'

```bash
#!/bin/bash
export XKB_DEFAULT_OPTIONS=ctrl:nocaps,
sway
```

```bash
chmod +x /bin/sway-custom
```

**Comment by mathewcohle** [comment]
For future reference, I think the right way to do it is mentioned in docs now: https://github.com/swaywm/sway/wiki#keyboard-layout

**Comment by Hirschiii** [comment]
Just in your Sway config:

`input type:keyboard {
  # Capslock key should work as escape key
  # See /usr/share/X11/xkb/rules/xorg.lst for options
  xkb_options caps:escape
}`

**Comment by rdrg109** [comment]
I just tried @Hirschiii method and it worked. I didn't have to log-in again, I just needed to execute `reload` (bound to `$mod+Shift+c` in the default configuration).
