### ISSUE TITLE
is there an equvalent for i3-msg exit?

### ISSUE THREAD

**Issue by Michael-Jing** [SirCmpwn/sway#1223]
I don't know how to exit sway, is there an equvalent for i3-msg exit? 
I tried swaymsg exit but get "Error: Permission denied for exit via IPC"

**Comment by 4e554c4c** [comment]
Yes, exit works but is denied by default to swaymsg. The default binding for this command is `$mod+Shift+e`.

**Comment by SirCmpwn** [comment]
Read `/etc/sway/security.d/00-defaults`. Write a commands block similar to the one in this file to `/etc/sway/security.d/01-exit-cmd` and change the exit permissions to `binding ipc`. This will allow it to be used from either a binding or from IPC, which is what swaymsg uses. If you do this, however, any program with IPC access or the ability to run swaymsg will be able to exit your sway session without your consent.

**Comment by hobarrera** [comment]
> any program with IPC access or the ability to run swaymsg will be able to exit your sway session without your consent

Can't any such program run kill or send a SIGKILL anyway, in most common cases?

**Comment by SirCmpwn** [comment]
It depends on how you configure your system. You could run software as other users that has limited IPC access, or can't run sway-msg.

**Comment by derekdreery** [comment]
Note that the default in i3 on some distros is (after a confirm dialog) to run `exec i3-msg exit`, but the equivalent on sway (`exec swaymsg exit`) will not work. You must use `exit` directy (without the confirm).
