### ISSUE TITLE
i3 compatibility: config option silently ignored 

### ISSUE THREAD

**Issue by tjavdar** [SirCmpwn/sway#1226]
Adding the handy i3-keybinding

     bindsym $mod+semicolon focus right

at the end of config is silently ignored.

sway 0.13.0-1, invoked with

XKB_DEFAULT_LAYOUT=se

on Linux i7 4.10.13-1-ARCH #1 SMP PREEMPT Thu Apr 27 12:15:09 CEST 2017 x86_64 GNU/Linux

**Comment by SirCmpwn** [comment]
https://github.com/SirCmpwn/sway/wiki#how-do-i-report-issues
