### ISSUE TITLE
Sway on Manjaro/OpenRC Fails to Launch

### ISSUE THREAD

**Issue by noobpurple** [SirCmpwn/sway#1227]
I'm currently running Manjaro with OpenRC instead of SystemD. I added the hook described on the wiki, which got me through one of the problems. Then I had to export XDG_RUNTIME_DIR, which cleared another problem with launching it. However, now I'm stuck. Trying to launch Sway ends up with "Failed To Drop Extra Capabilities", and the debug info isn't helping me much here. If there's any info you need, let me know and I'll provide. Is there a log file somewhere I can paste?

**Comment by SirCmpwn** [comment]
How did you install sway?

**Comment by noobpurple** [comment]
I installed the "sway" package from the official repo. Should be the same as Arch Linux.

**Comment by SirCmpwn** [comment]
You'll need to remove the caps and setuid it. Majaro is stupid, lots of Arch packages just won't work on it. You need to compile it youself or better yet, get a distro that isn't dogshit.

**Comment by noobpurple** [comment]
I told you I added the hook that already handled the setuid. I removed the caps, but the problem persists.

**Comment by SirCmpwn** [comment]
You need to remove the caps as well. Pay attention.

**Comment by SirCmpwn** [comment]
I don't really care to help a Manjaro user troubleshoot. That distro is a dumpster fire and I don't have time to help you diagnose it. You got yourself into this mess, get yourself out of it. Manjaro is even worse than Gentoo at stability, and with a worse community to boot.
