### ISSUE TITLE
dropdown menus go offscreen

### ISSUE THREAD

**Issue by bbgun7** [SirCmpwn/sway#1228]
I'm not sure how to take a screenshot in sway, scrot isn't working, but I was trying out wayland compatible browsers so that everything wouldn't be blurry on my hidpi display. I noticed in Midori the dropdown menu to get to settings goes off the screen on the right. when I put a window to the right of it, to split the desktop, then I was able to read what options there were in the menu, since it dropped down to the middle of the screen. Any way to tell dropdown menus when they go offscreen to make them switch sides?

**Comment by SirCmpwn** [comment]
Duplicate https://github.com/SirCmpwn/sway/issues/1142
