### ISSUE TITLE
Allow audio capture in swaygrab -c

### ISSUE THREAD

**Issue by clarcharr** [SirCmpwn/sway#1233]
Would be nice if there were an easy option for this. This would mostly just add `-f alsa -i pulse` or something similar to `ffmpeg`.

Although obviously a more seasoned user could just pass options to `ffmpeg` directly, it'd be nice for usability to just add this option to `swaygrab` itself.

**Comment by SirCmpwn** [comment]
I think I would rather add an environment variable or a flag like `SWAYGRAB_FFMPEG_OPTS` or `--ffmpeg-opts`

**Comment by clarcharr** [comment]
I agree that it makes sense to allow arbitrary ffmpeg opts, but it would also be nice to have a simple default that includes audio so that someone can include audio in the captured video with minimal effort.

**Comment by SirCmpwn** [comment]
I disagree. Depending on your setup there could be multiple ways of capturing audio, each different, plus there'd have to be driver-specific ways of picking the appropriate device and things like mixing in desktop audio with microphone audio... it's not going to happen.
