### ISSUE TITLE
Terminal titlebar not updating correctly from PS1

### ISSUE THREAD

**Issue by wulvyrn** [SirCmpwn/sway#1239]
```
PS1='\[\e]2;\u@\h: \w\a\]$
```
This does not update the title bar after 
```
cd
```

It does update after
``` 
cd /
cd
```

This prompt is duplicate and does work, however ugly...
```
PS1='\[\e]2;\u@\h: \W\w\a\]$
```

**Comment by SirCmpwn** [comment]
Does this work on X11? This is almost certainly not sway's problem.

**Comment by wulvyrn** [comment]
It works on i3wm

**Comment by wulvyrn** [comment]
small typo: notice the extra space after \w
```
$ PS1='\[\e]2;\u@\h: \w \a\]$ '
```
