### ISSUE TITLE
cannt open sway

### ISSUE THREAD

**Issue by narutowindy** [SirCmpwn/sway#1240]
[ipc-client.c:37] Unable to connect to /run/user/1000/sway-ipc.1000.936.sock

it was working fine, suddenly after the  rebooting it shows this error!

**Comment by SirCmpwn** [comment]
https://github.com/SirCmpwn/sway/wiki#how-do-i-report-issues

**Comment by narutowindy** [comment]
swaymsg -t get_version >

sway socket not detected.
06/17/17 10:29:05 - [ipc-client.c:37] Unable to connect to

**Comment by narutowindy** [comment]
log file
[sway.txt](https://github.com/SirCmpwn/sway/files/1082338/sway.txt)

**Comment by SirCmpwn** [comment]
Can you run other Wayland compositors like Weston?

**Comment by narutowindy** [comment]
Yes i can,

**Comment by SirCmpwn** [comment]
Is there anything unusual about your setup? Not using systemd? How did you install sway?

**Comment by narutowindy** [comment]
nope using systemd, installed direclty from AUR, sometime before arch packge.

**Comment by SirCmpwn** [comment]
Instead use sway and wlc from the official repos. Don't use -git.

**Comment by narutowindy** [comment]
yes, after the issue, i installed fromofficial repo, removed aur git variant

**Comment by SirCmpwn** [comment]
wlc as well?

**Comment by narutowindy** [comment]
yup, still has the problem

**Comment by SirCmpwn** [comment]
Beats me, then. Try rolling back any recent changes you've made one at a time to narrow down what could have caused the issue.

**Comment by narutowindy** [comment]
okay, i will undo the changes and i'll let you know !!

**Comment by narutowindy** [comment]
but there is some error 
06/17/17 10:50:52 - [main.c:65] swaybg requires the compositor to support the desktop-shell extension.
06/17/17 10:50:52 - [ipc-client.c:37] Unable to connect to /run/user/1000/sway-ipc.1000.3360.sock

**Comment by abdelq** [comment]
@narutowindy What's the output of `echo $XDG_RUNTIME_DIR`?
