### ISSUE TITLE
add the ability to change keyboard layout while sway is running

### ISSUE THREAD

**Issue by vikstrous** [SirCmpwn/sway#1242]
As far as I can tell, right now the only way to change the keyboard layout is to restart sway. It would be nice if there was a way to change it through swaymsg.

**Comment by Timidger** [comment]
This has been discussed before, and currently is not possible. It might become an option once sway migrates to wlroot.

**Comment by SirCmpwn** [comment]
Use something to this effect.

```
export XKB_DEFAULT_LAYOUT=de,us
export XKB_DEFAULT_OPTIONS=grp:alt_shift_toggle
sway
```

Read the XKB manual.

**Comment by tjaartvdwalt** [comment]
I use a very customized keyboard layout, and being able to change the keyboard layout at run time would be very handy in a couple of situations:

- A colleague wants to type on my laptop
- I want to plug in an external keyboard that has a different layout

Are there plans to support this with wlroots? Is there a way I can contribute?

**Comment by SirCmpwn** [comment]
The plan is to support this in wlroots. The best place to help out wouldn't be keyboard related, but on wlroots as a whole (because sway won't switch until every feature is done, so it won't benefit from the features you want until then).

To help, pick something to do from here: https://github.com/SirCmpwn/wlroots/issues/9

We collaborate over IRC in #sway on freenode, be there.

**Comment by toger5** [comment]
This is now also pissible with the sway configuration. It took me some time to figure it out thats why I am posting it here:

```
xkb-Layout us,de
xkb_switch_layout 
```
(it is documented in the sway input man page: https://jlk.fjfi.cvut.cz/arch/manpages/man/sway-input.5)

**Comment by aviau** [comment]
Is it now possible to change keyboard layouts with swaymsg? I am not happy with the proposed toggles here and I'd like to use bindsym instead.

**Comment by deifactor** [comment]
> Is it now possible to change keyboard layouts with swaymsg? I am not happy with the proposed toggles here and I'd like to use bindsym instead.

Yes, you can do this. It's a bit wonky, I noticed I had to explicitly set `xkb_layout us` before `xkb_variant colemak` would take any effect. but it does work.

**Comment by chesedo** [comment]
> I noticed I had to explicitly set `xkb_layout us` before `xkb_variant colemak` would take any effect. but it does work.

With the latest update `/etc/sway/definitions` and `/etc/sway/inputs/*` went missing for me. This broke my colemak variant, but setting `xkb_layout us` fixed it too

**Comment by emersion** [comment]
We never shipped these files. Maybe they were shipped by your distribution.

**Comment by chesedo** [comment]
Okay, I just filled a bug with my distribution at Manjaro-Sway/manjaro-sway#112

Is the `xkb_variant` not working unless `xkb_layout` is also set a bug though? (Which I can create a separate issue for)
