### ISSUE TITLE
environment variables that need to be set for Qt

### ISSUE THREAD

**Issue by tidux** [SirCmpwn/sway#1243]
I have both of the following environment variables set in Qt, which allows full clipboard integration across everything except a pair of misbehaving applications (Qutebrowser and Termite) across Gtk, Qt, and WINE:
`export QT_QPA_PLATFORM=wayland`
`export QT_WAYLAND_DISABLE_WINDOWDECORATION=1`

Setting these in code from Sway would solve a lot of interop issues.

**Comment by SirCmpwn** [comment]
No. Set them before you start sway if you want.

**Comment by tidux** [comment]
I can understand leaving the disable windowdecoration up to user prefs, but not setting QT_QPA_PLATFORM=wayland does nothing but cause bugs and misbehavior.  There's no reason not to set it in the compositor.

**Comment by SirCmpwn** [comment]
Report your bugs to Qt. I'm not going to add Qt-specific code to Sway.

**Comment by clarcharr** [comment]
@tidux on the other hand, adding it also breaks a lot of Qt applications for me. it's better to have Qt default to wayland than require the variables.

**Comment by Moelf** [comment]
> No. Set them before you start sway if you want.

what if, say, I want to change `GDK_DPI_SCALE` after connecting to different display?

**Comment by emersion** [comment]
This is not a good idea.

**Comment by ddevault** [comment]
We have a different mechanism (the Wayland protocol) for expressing scale to GTK.
