### ISSUE TITLE
swaygrab appears to interpret spaces in filename

### ISSUE THREAD

**Issue by louisch** [SirCmpwn/sway#1245]
When running swaygrab with a filename that contains filenames, it appears to pass the argument unquoted to ImageMagick, as it produces the following kinds of errors (I quote the filename here, so this error is internal to swaygrab):

```
 swaygrab 'test image.png'
convert: unable to open image `test': No such file or directory @ error/blob.c/OpenBlob/2701.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/504.
```

I end up having to escape the space myself inside the string:

```
 swaygrab 'test\ image.png'
```

**Comment by clarcharr** [comment]
Sway really shouldn't be piping out to shell for this; if no one takes it later this week I'll work on a better fix.

**Comment by SirCmpwn** [comment]
swaygrab is a weekend hack. Please do.
