### ISSUE TITLE
GUI frontend to swaygrab

### ISSUE THREAD

**Issue by clarcharr** [SirCmpwn/sway#1246]
I've been using xfce4-screenshooter for a long time now and I really like how it does things. Particularly I like how:

1. When it's opened, it shows a UI for whether you want to take the whole screen, just the focused container, or click and crop a selection of the screen to take a picture.
2. It also offers a timer before going off.
3. It lets you use the file picker to choose where to save the image.

And I think it'd be really cool to offer something like this as a frontend to swaygrab, or at least adding functionality to swaygrab in a way that'd make implementing a frontend very easy.

Because for the moment I have PrintScreen mapped to just run `swaygrab` and I would like a better solution.

**Comment by SirCmpwn** [comment]
I think that would be an interesting project, but a third party one. I don't want to do that upstream.

**Comment by clarcharr** [comment]
Sounds fair! I think that potentially offering the functionality to do the click-and-crop in the command-line version would be useful though.

**Comment by SirCmpwn** [comment]
No, that's already on the roadmap and won't be possible until [wlroots](https://github.com/SirCmpwn/wlroots) is ready.

**Comment by clarcharr** [comment]
Sounds good!

**Comment by janza** [comment]
Until wlroots is ready you can use [slop](https://github.com/naelstrof/slop) and imagemagick to get a screenshot of selection:
    
    swaygrab /tmp/sshot.png
    convert /tmp/sshot.png -crop "$(slop)" /tmp/sshot.png
