### ISSUE TITLE
No output from iGPU

### ISSUE THREAD

**Issue by aidanharris** [SirCmpwn/sway#1248]
I have a bit of an unusual setup where two monitors are connected to my Nvidia card (GTX 960 using the nouveau driver) and a third monitor is connected to the iGPU via display port.

When I start sway the two monitors connected to the Nvidia card work as expected but the third monitor "hangs", appearing to do nothing. When I exit sway the monitor springs back to life displaying my shells login session on tty1.

I'm running sway in debug mode now and will post logs after I've looked through them. For now I'm wondering if anyone has tried to use Sway in a similar setup and had the same issues?

The third monitor does not show up in xrandr or via smaymsg:

```sh
❯ xrandr
Screen 0: minimum 320 x 200, current 2560 x 1080, maximum 8192 x 8192
XWAYLAND0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 500mm x 280mm
   1920x1080     59.96*+
XWAYLAND1 connected 2560x1080+0+0 (normal left inverted right x axis y axis) 670mm x 280mm
   2560x1080     59.98*+
```

```sh
❯ swaymsg -t get_outputs
Output DVI-I-1
  Geometry: 1920x1080 @ 0,0
  Scale factor: 1x
  Workspace: 1:一

Output HDMI-A-1
  Geometry: 2560x1080 @ 1920,0
  Scale factor: 1x
  Workspace: 2:二

```

**Comment by SirCmpwn** [comment]
Multi-GPU support is planned for [wlroots](https://github.com/SirCmpwn/wlroots), if possible, but will not be attempted earlier than that.
