### ISSUE TITLE
0.14-rc2: status bar is blank, although workspaces numbers are shown fine

### ISSUE THREAD

**Issue by fusion809** [SirCmpwn/sway#1253]
0.14-rc2 is having difficulty with my config it seems which is [here](https://github.com/fusion809/sway-config/blob/master/config). My config uses [i3pystatus](https://github.com/enkore/i3pystatus/) to generate the status bar info. This worked fine with 0.13.0 but oddly with 0.14-rc2 it does not. No error is given by sway at the command-line, here is the output:

```bash
06/30/17 01:32:20 - [main.c:69] Using output 0 of 1
```

which to my knowledge is to be expected. Here is a screenshot showing you exactly what I see:

![screenshot_20170630_013559](https://user-images.githubusercontent.com/4717341/27696265-8e21b87c-5d34-11e7-94e5-91277bcaa146.png)

as opposed to what I saw with 0.13.0:

![screenshot_20170627_132631](https://user-images.githubusercontent.com/4717341/27696293-9f0b7d58-5d34-11e7-92b5-d7cf633f6c51.png)

Distribution is Arch Linux. Here is my PKGBUILD if relevant https://gist.github.com/990b67f7d3f2ee828e4ffc612d021445. My install file is https://gist.github.com/29cf166ecaa5a768edb23f348ed0ca51.

Oh one last issue I've noticed reloading the config with <kbd>$mod</kbd>+<kbd>Shift</kbd>+<kbd>c</kbd> (per my config) causes my system to freeze. Not just Sway the whole system freezes as when I press <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>F2</kbd> to change to a TTY terminal nothing happens. This has occurred only with 0.14-rc2 and not with 0.13.0

**Comment by SirCmpwn** [comment]
Your config link 404s for me.

**Comment by SirCmpwn** [comment]
Also, reload is known to cause this sometimes, has not be thoroughly investigated.

**Comment by fusion809** [comment]
Oops the link is fixed now.

**Comment by fusion809** [comment]
Oh the reload thing only occurs with 0.14-rc2 btw, 0.13.0 for me works fine with reload.

**Comment by SirCmpwn** [comment]
Give me more files. This isn't enough to reproduce your setup with.

**Comment by fusion809** [comment]
Which files? Really am surprised more are required as to my knowledge there's only one config file to Sway `~/.config/sway/config`.

**Comment by SirCmpwn** [comment]
How about `~/.i3/i3pystatus` or any config it might have or... give me a break man, include as much detail as you can.

**Comment by fusion809** [comment]
Oopsie the config I'm using ATM is https://github.com/fusion809/sway-config/blob/archlinux/config. Sorry for wasting ya time with the wrong config. `~/.i3/i3status.py` is https://github.com/fusion809/i3-configs/blob/master/.i3/i3status.py. Sorry I wasn't trying to make it difficult for ya I really just didn't realize what you were looking for, should have known that was the file.

**Comment by Biohazard50** [comment]
I had a similar issue. How are you launching sway? Can you reproduce the issue by launching sway from a terminal?

**Comment by fusion809** [comment]
Sure can, I usually start it with SDDM might be unsupported but it works. But if I start from a terminal I get the same behaviour.

**Comment by Biohazard50** [comment]
Then I don't know. For reference, I solved my issue by replacing `dbus-launch --exit-with-session sway` by simply `sway` (I can't remember why I had the dbus-launch stuff before) in my session script.

**Comment by SirCmpwn** [comment]
I can reproduce this. The issue is unrelated to yours, @Biohazard50. Looking into it now.

**Comment by SirCmpwn** [comment]
This is pretty weird. When I run i3status.py alone, it prints the expected output to the terminal. But when I run `i3status.py | tee ~/test` with swaybar as my status_command, only `{"version": 1, "click_events": true}` is written to `~/test`.

**Comment by fusion809** [comment]
Well if upstream ever needs to be contacted it is [enkore/i3pystatus](https://github.com/enkore/i3pystatus) (suspect yas know but just in case).

**Comment by SirCmpwn** [comment]
387eca1b29cbc6f497e2cb26a0bff0b06b50b6a1
