### ISSUE TITLE
Sway crash at login in Ubuntu 17.04

### ISSUE THREAD

**Issue by tragiclifestories** [SirCmpwn/sway#1257]
OS: Ubuntu Zesty 17.04
wlc: 0.7
sway: 0.13.0
lightdm: 1.22.0

Sway boots fine from inside another WM (if I boot into i3 and run sway from the terminal I get a sway workspace appearing just fine), but trying too boot into it from the login manager just dies with the following output in .xsession-errors:

```
xrdb: Can't open display ''
dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
xhost:  unable to open display ""
xhost:  unable to open display ""
dbus-update-activation-environment: setting GTK_MODULES=gail:atk-bridge
Error: unable to open display 
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
dbus-update-activation-environment: setting QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
dbus-update-activation-environment: setting LANG=en_GB.UTF-8
dbus-update-activation-environment: setting GDM_LANG=en_GB
dbus-update-activation-environment: setting GTK2_MODULES=overlay-scrollbar
dbus-update-activation-environment: setting PAM_KWALLET5_LOGIN=/run/user/1000/kwallet5.socket
dbus-update-activation-environment: setting MANDATORY_PATH=/usr/share/gconf/sway.mandatory.path
dbus-update-activation-environment: setting XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/james
dbus-update-activation-environment: setting USER=james
dbus-update-activation-environment: setting DESKTOP_SESSION=sway
dbus-update-activation-environment: setting DEFAULTS_PATH=/usr/share/gconf/sway.default.path
dbus-update-activation-environment: setting QT_QPA_PLATFORMTHEME=appmenu-qt5
dbus-update-activation-environment: setting PWD=/home/james
dbus-update-activation-environment: setting HOME=/home/james
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
dbus-update-activation-environment: setting LIBVIRT_DEFAULT_URI=qemu:///system
dbus-update-activation-environment: setting XDG_SESSION_TYPE=wayland
dbus-update-activation-environment: setting XDG_DATA_DIRS=/usr/share/sway:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
dbus-update-activation-environment: setting XDG_SESSION_DESKTOP=sway
dbus-update-activation-environment: setting GTK_MODULES=gail:atk-bridge
dbus-update-activation-environment: setting SHELL=/usr/bin/zsh
dbus-update-activation-environment: setting XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
dbus-update-activation-environment: setting IM_CONFIG_PHASE=1
dbus-update-activation-environment: setting QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
dbus-update-activation-environment: setting SHLVL=1
dbus-update-activation-environment: setting LANGUAGE=en_GB:en
dbus-update-activation-environment: setting GDMSESSION=sway
dbus-update-activation-environment: setting LOGNAME=james
dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
dbus-update-activation-environment: setting XDG_RUNTIME_DIR=/run/user/1000
dbus-update-activation-environment: setting XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session3
dbus-update-activation-environment: setting XDG_CONFIG_DIRS=/etc/xdg/xdg-sway:/etc/xdg:/usr/share/kubuntu-default-settings/kf5-settings
dbus-update-activation-environment: setting PATH=/home/james/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
dbus-update-activation-environment: setting _=/usr/bin/dbus-update-activation-environment
07/03/17 09:06:51 - [main.c:47] [wlc] Not running from X11 and no access to /dev/input/event0 or logind unavailable
```

Identical problems were reported in [#262](https://github.com/SirCmpwn/sway/issues/262) but none of the fixes or diagnostic tools there yield any joy. I am unable to run strace, or at least I have no idea to do that from lightdm.

Any help greatly appreciated, and I will of course provide any information requested, I just have very little knowledge about how a lot of this stuff fits together...

**Comment by wdbw** [comment]
The problem with lightdm was reported in #1159.

**Comment by SirCmpwn** [comment]
Please provide more details about how you are starting sway, as well as a debug log.

**Comment by SirCmpwn** [comment]
Nevermind, LightDM doesn't support Wayland. Use something else, or better yet just run sway from your login tty.

**Comment by tragiclifestories** [comment]
Thanks guys, but to be clear, lightDM *does* support wayland. It is advertised as doing so on [freedesktop.org](https://www.freedesktop.org/wiki/Software/LightDM/), and I can find no references to the contrary being true except in closed sway issues. Indeed, in my own case, I can happily boot into Gnome with Wayland from LightDM.

Clearly, however, using display managers is not the supported happy path for sway, which is fine and up to you guys.

**Comment by glebzlat** [comment]
It is like "we use N this way and you either do the same or go find something else" attitude. Not exactly user-friendly, I'd say. The last comment on this topic was 8 years ago, and Sway still doesn't work with LightDM.

**Comment by emersion** [comment]
This project is run by volunteers. You make it sound like maintainers owe you something. Yes, at times we take decisions that some users don't like. But "you're free to use something else if you don't like it" is a perfectly reasonable and valid answer.

Back to the topic at hand, I don't think it's especially useful to post on 8 years old issues. Please ask on IRC, and if you've found a bug open a new issue.
