### ISSUE TITLE
Mouse is fixed in the window in full-screen games

### ISSUE THREAD

**Issue by kaberc** [SirCmpwn/sway#1268]
When I'm playing games with wine and xwayland, cursor is fixed in the window area, so it makes very hard to play 3d-games. Also there is a cursor arrow ontop of the full-screen windows. Is there a way to grab mouse in wine games?

**Comment by SirCmpwn** [comment]
Mouse capture remains to be implemented.

**Comment by sbwtw** [comment]
Is there any plan to solve this problem? @SirCmpwn

**Comment by 4e554c4c** [comment]
Please don't bump long dead issues @sbwtw. It will be implemented with wlroots: https://github.com/swaywm/sway/issues/1071#issuecomment-331705286
