### ISSUE TITLE
[Question] multiple random wallpaper set as desktop background??

### ISSUE THREAD

**Issue by narutowindy** [SirCmpwn/sway#1269]
~/.config/sway/config
 output "*" background /home/onny/pictures/fredwang_norway.jpg fill

i can set only one wallpaper ?? is there any option?

**Comment by SirCmpwn** [comment]
I use [a script](https://git.sr.ht/~sircmpwn/dotfiles/tree/bin/wallpaper) and an output line like this:

    output * bg `wallpaper` fill

**Comment by nerdDan** [comment]
> I use [a script](https://git.sr.ht/~sircmpwn/dotfiles/tree/bin/wallpaper) and an output line like this:
> 
> ```
> output * bg `wallpaper` fill
> ```
broken link

**Comment by emersion** [comment]
New link: https://git.sr.ht/%7Esircmpwn/dotfiles/tree/master/bin/wallpaper

**Comment by xyproto** [comment]
I am trying to write a small utility that can change the desktop wallpaper, regardless of which windowmanager is running. The plan is to change the wallpaper according to the time of day.

Is there a command that can be used for changing the wallpaper after Sway has started?

For Gnome 3 it is something along the lines of:

    gsettings set org.gnome.desktop.background picture-uri file:///$PATH_TO_FILE

What would an equivalent command be for Sway?

**Comment by xyproto** [comment]
Found it!

    swaymsg 'output "*" background $HOME/some/image.png fill'

Never mind then. :)

**Comment by roipoussiere** [comment]
Here is a one-liner:

```
set $wallpapers_path $HOME/Images/wallpapers
output * bg `find $wallpapers_path -type f -regex '\(.*.jpg\|.*.png\)' | shuf -n 1` fill
```

**Comment by stefanhusmann** [comment]
I think the OP wants to know if one can set several different wallpapers on different desktops on the same monitor. At least that would be my question. In other words, does the "output" subcommand aplly on Monitors only or also on desktops?

**Comment by kennylevinsen** [comment]
The `output` commands apply, as the name suggests, to outputs. They do not apply to *workspaces*. Sway has no concept of "desktops".

The background is drawn by swaybg, a standalone program. Feel free to replace it with one carrying whatever logic you wish. Alternatives exist, such as oguri, and they're fairly easy to code.
