### ISSUE TITLE
Sway doesn't compile under Debian Stretch due to C14

### ISSUE THREAD

**Issue by n3rdopolis** [SirCmpwn/sway#127]
I filed something similar with WLC, apparently chck is incompatible with C14, which GCC 5 appears to default to, which is default in Debian Stretch

They ended up requiring CMake 3.1, and using a Cmake function to force it to C99

**Comment by SirCmpwn** [comment]
I compile sway under GCC 5 every day without issue. Can you provide the actual errors given?

**Comment by n3rdopolis** [comment]
Ah yes. Sorry.

sway: [ 33%] Building C object CMakeFiles/sway.dir/sway/list.c.o
sway: /srcbuild/sway/sway/stringop.c: In function ‘join_list’:
sway: /srcbuild/sway/sway/stringop.c:217:2: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
sway:   for (int i = 0; i < list->length; i++) {
sway:   ^
sway: /srcbuild/sway/sway/stringop.c:217:2: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
sway: /srcbuild/sway/sway/stringop.c:226:11: error: redefinition of ‘i’
sway:   for (int i = 1; i < list->length; i++) {
sway:            ^
sway: /srcbuild/sway/sway/stringop.c:217:11: note: previous definition of ‘i’ was here
sway:   for (int i = 0; i < list->length; i++) {
sway:            ^
sway: /srcbuild/sway/sway/stringop.c:226:2: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
sway:   for (int i = 1; i < list->length; i++) {
sway:   ^
sway: CMakeFiles/sway.dir/build.make:62: recipe for target 'CMakeFiles/sway.dir/sway/stringop.c.o' failed
sway: make[2]: *** [CMakeFiles/sway.dir/sway/stringop.c.o] Error 1
sway: make[2]: *** Waiting for unfinished jobs....
sway: /srcbuild/sway/sway/handlers.c: In function ‘handle_view_created’:
sway: /srcbuild/sway/sway/handlers.c:164:3: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘wlc_handle’ [-Wformat=]
sway:    wlc_view_get_class(handle), wlc_view_get_app_id(handle));
sway:    ^
sway: /srcbuild/sway/sway/handlers.c:164:3: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 6 has type ‘wlc_handle’ [-Wformat=]
sway: /srcbuild/sway/sway/handlers.c: In function ‘handle_view_destroyed’:
sway: /srcbuild/sway/sway/handlers.c:208:2: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘wlc_handle’ [-Wformat=]
sway:   sway_log(L_DEBUG, "Destroying window %lu", handle);
sway:   ^
sway: /srcbuild/sway/sway/handlers.c: In function ‘handle_view_state_request’:
sway: /srcbuild/sway/sway/handlers.c:265:4: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘wlc_handle’ [-Wformat=]
sway:     sway_log(L_DEBUG, "setting view %ld %s, fullscreen %d", view, c->name, toggle);
sway:     ^
sway: /srcbuild/sway/sway/handlers.c: In function ‘handle_key’:
sway: /srcbuild/sway/sway/handlers.c:324:7: warning: ‘match’ may be used uninitialized in this function [-Wmaybe-uninitialized]
sway:     if (match) {
sway:        ^
sway: CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/sway.dir/all' failed
sway: make[1]: *** [CMakeFiles/sway.dir/all] Error 2
sway: Makefile:127: recipe for target 'all' failed
sway: make: *** [all] Error 2
sway: PackageInstallSource finished in 0 seconds
sway:  PackagePostInstall finished in 0 seconds

**Comment by Luminarys** [comment]
Code tags please.

**Comment by SirCmpwn** [comment]
Interesting. Sounds reasonable to me to explicitly declare sway as C99.

**Comment by TuxCoder** [comment]
Add `set (CMAKE_C_STANDARD 99)` to the CMakeLists.txt fixes the problem for me.

ref: http://stackoverflow.com/questions/24840030/forcing-c99-in-cmake-to-use-for-loop-initial-declaration

My os is debian sid.
