### ISSUE TITLE
swaygrab feature: capture rectangular selection

### ISSUE THREAD

**Issue by vikstrous** [SirCmpwn/sway#1273]
It would be really awesome to be able to capture a rectangular selection on the screen using swaygrab. This requires an interactive selection picker. It doesn't have to be fancy, but it would significantly improve the usability of swaygrab.

Alternatively, this won't be as necessary if X based screenshot taking tools worked.

**Comment by choppa70** [comment]
#1246

**Comment by SirCmpwn** [comment]
Thanks @choppa70
