### ISSUE TITLE
swaybar crashes with wicd-gtk

### ISSUE THREAD

**Issue by lyovushka** [SirCmpwn/sway#1274]
Steps to reproduce: compile swaybar with tray support and run wicd-gtk
Result: swaybar crashes.

The log of swaybar -d is attached.

[swaybar_crash.txt](https://github.com/SirCmpwn/sway/files/1143968/swaybar_crash.txt)

**Comment by 4e554c4c** [comment]
`/org/ayatana/NotificationItem/wicd` isn't a valid message bus name, it's an object path. wicd-gtk isn't following the SNI spec and swaybar crashed accordingly.

**Comment by lyovushka** [comment]
I guess it is correct. Still, misbehaving applicants shouldn't crash swaybar.

**Comment by SirCmpwn** [comment]
Yeah, wicd-gtk is broken here, but swaybar definitely should not crash.

**Comment by 4e554c4c** [comment]
@lyovushka Does #1276 fix crashing for you?

**Comment by lyovushka** [comment]
@4e554c4c I am afraid it does not. Swaybar still crashes. I think the problematic call is dbus_bus_has_name_owner from the function register_item in sni_watcher.c.

**Comment by 4e554c4c** [comment]
Good catch! I forgot that we did name validation there. Does #1279 do the trick then? I appologise for not being able to test myself, I can't seem to get wicd to display tray items.

**Comment by lyovushka** [comment]
This one works. Swaybar does not show any icons, but also does not crush. Thanks!

**Comment by 4e554c4c** [comment]
Yep! I'll look into how KDE registers items by object path later, but for now I think this'll work.
