### ISSUE TITLE
Disabling Touchpad

### ISSUE THREAD

**Issue by onlyTrueAki** [SirCmpwn/sway#1277]
There are several methods for en-/disabling the touchpad on the fly under X11, however all I found concerning the same thing under wayland is that it is up to the compositor.
Currently the only way to disable the touchpad is to just do it in the BIOS, however that means a reboot anytime I want to change the touchpad status.
If anyone has the time and knowhow to implement this I'd greatly appreciate it.

**Comment by SirCmpwn** [comment]
`man sway-input`

**Comment by gerrard00** [comment]
For future web searchers:

```
swaymsg -t get_inputs
```
Will let you determine the identifier to use and:

```
swaymsg input <identifier> events disabled
```
will disable the device. This is deatils in the man page discussed earlier.

**Comment by Michael-AUG** [comment]
> For future web searchers:
> 
> ```
> swaymsg -t get_inputs
> ```
> 
> Will let you determine the identifier to use and:
> 
> ```
> swaymsg input <identifier> events disabled
> ```
> 
> will disable the device. This is deatils in the man page discussed earlier.

That's great. Thanks. Will this persist after reboot, or does it need to be set each time?
