### ISSUE TITLE
Can't start sway on arch linux with openrc

### ISSUE THREAD

**Issue by DesiCode96** [SirCmpwn/sway#1292]
Hi, I'm running arch linux without systemd (openrc) with sway 0.14.0. I've follow this guide 
https://github.com/SirCmpwn/sway/wiki/Sway-without-systemd-on-Arch-Linux

but i've this error:
`07/30/17 13:19:23 - [main.c:221] sway executable has both the s(g)uid bit AND file caps set.
07/30/17 13:19:23 - [main.c:223] This is strongly discouraged (and completely broken).
07/30/17 13:19:23 - [main.c:225] Please clear one of them (either the suid bit, or the file caps).
07/30/17 13:19:23 - [main.c:227] If unsure, strip the file caps.`

**Comment by SirCmpwn** [comment]
The error message tells you what to do -_-

**Comment by DesiCode96** [comment]
` Please clear one of them (either the suid bit, or the file caps)`
if i clear the suid i've this error
`[main.c:48] [wlc] Could not open /dev/tty0 to find free vt`
i've no idea how to clean the file caps
