### ISSUE TITLE
font swaybar-icons ?

### ISSUE THREAD

**Issue by bearcatsandor** [SirCmpwn/sway#1296]
In the comment https://github.com/SirCmpwn/sway/issues/343#issuecomment-237541951  sullome's config and accompanying  screenshot displays swaybar icons.

Apparently swaybar-icons is a font but i can't locate it on my Gentoo system even though all flags are selected, and i can't find it in this repository.

Is it obsolete? Where can i get it?

Thanks

**Comment by SirCmpwn** [comment]
They're probably doing something weird. I've never heard of such a font.

**Comment by embik** [comment]
Looks like [media-fonts/fontawesome](https://packages.gentoo.org/packages/media-fonts/fontawesome) to me.

**Comment by bearcatsandor** [comment]
Thank you @embik. I'll check that out.
