### ISSUE TITLE
XKB de neo does not work properly

### ISSUE THREAD

**Issue by DerJesko** [SirCmpwn/sway#1297]
So before starting sway I set following environment variables
```
export XKB_DEFAULT_LAYOUT=de
export XKB_DEFAULT_VARIANT=neo
```
After entering sway it seems to use the normal `de` a.k.a. German layout
If I then go into a terminal emulator and change the keyboard layout via
`
setxkbmap de neo
` I then can't use for example `SHIFT+m` to get a `M`.  
In neo I'm also supposed to access other keyboard layers with `CAPS_LOCK` for example `CAPS_LOCK + m` should result in a `%` instead in sway it just behaves like a normal `CAPS_LOCK`.

This is definitely not a Wayland problem. It works fine in weston with the config
```
[keyboard]
keymap_layout=de
keymap_variant=neo
```
It by the way also works in i3 and GNOME  
I'm running Arch the following versions:
```
linux 4.12.3-1
wayland 1.13.0-1
sway 0.14.0-1
```

**Comment by SirCmpwn** [comment]
You cannot use setxkbmap to change the layout in Sway, gotta configure it at runtime. Provide log please.

**Comment by DerJesko** [comment]
https://gist.github.com/DerJesko/e2bfd742ad29689326164fb424e27c34
Here is a log. I am currently using the default config. Should I for conveinience of debugging disable that config file and rerun?

**Comment by SirCmpwn** [comment]
No. According to your log, XKB_DEFAULT_VARIANT is unset.

**Comment by DerJesko** [comment]
Now I feel stupid. Misspelled it XKB_DEFAULT_VARIANT != XKB_DEFAULT_VARINANT

**Comment by leezu** [comment]
@DerJesko does the neo layout work for you with sway now?
I find that `XKB_DEFAULT_LAYOUT=de XKB_DEFAULT_VARIANT=neo sway` indeed activates the neo layout, but that the shift key fails to capitalize letters. I.e. `shift+a` produces `a` instead of `A`. Did you experience the same issue?
