### ISSUE TITLE
for_window matching seems not working

### ISSUE THREAD

**Issue by SilverBut** [SirCmpwn/sway#1306]
Version: 0.14.0

After send command:
```
swaymsg -r for_window [class="keepassx2"] kill
```

Returned:
```
[
   {
     "success": true
   }
 ]
```

But nothing happened. Use command `swaymsg -r for_window [name="KeePassX"] kill` also returned same result but nothing happened.

Still have no time to confirm if it happens on other programs, but I think so.

Find the window using `xwininfo`:
```
...
xwininfo: Window id: 0x600003 "Password.kdbx - KeePassX"
...
```

And then use `xprops -id 0x600003`:
```
...
_NET_WM_NAME(UTF8_STRING) = "Password.kdbx - KeePassX"
...
WM_CLASS(STRING) = "keepassx2", "Keepassx2"
...
WM_COMMAND(STRING) = { "keepassx2" }
```

**Comment by SirCmpwn** [comment]
What do you see in `swaymsg -t get_tree`? Also provide a debug log.

**Comment by SilverBut** [comment]
@SirCmpwn Thanks for providing `get_tree`. My fault. Seems class names detected by sway is only `Keepassx2`. Now fixed using `class=Keepassx2`.
