### ISSUE TITLE
No swaybar on startup - appears on reload

### ISSUE THREAD

**Issue by code8buster** [SirCmpwn/sway#1307]
It was working before I updated from Void Linux's musl repository, but now when I start sway I get no bar. I can make it appear when I issue Mod4+Shift+C to reload the config. It's an annoying workaround.

config file:
https://gist.github.com/code8buster/e8cfb0a6e955337174f3e257a98d6708

debug log:
https://gist.github.com/code8buster/15034014b691b8350fc7dca5c2ab297c

info from void's xbps-query:architecture: x86_64-musl
build-date: 2017-07-28 09:48 GMT
conf_files:
        /etc/sway/config
        /etc/pam.d/swaylock
filename-sha256: 2d43aa0f8cbaa34e7551ac9d672caadf39d8cbfe3df2c8338e39e9a4aa077008
filename-size: 4888KB
homepage: http://swaywm.org
install-date: 2017-08-02 00:17 EDT
installed_size: 5546KB
license: MIT
maintainer: Juan RP <xtraeme@voidlinux.eu>
metafile-sha256: 05e4369722f4ec8408d11f4a78e6b6a0f61623c26a47dc98d2c870190c3d4dfe
pkgver: sway-0.14.0_1
shlib-requires:
        libwayland-client.so.0
        libwayland-cursor.so.0
        libcairo.so.2
        libpangocairo-1.0.so.0
        libgobject-2.0.so.0
        libgdk_pixbuf-2.0.so.0
        libxkbcommon.so.0
        libc.so
        libwlc.so.0
        libpcre.so.1
        libjson-c.so.2
        libwayland-server.so.0
        libinput.so.10
        libpango-1.0.so.0
        libcap.so.2
        libpam.so.0
        libdbus-1.so.3
short_desc: i3 compatible window manager for Wayland
source-revisions: sway:8481209780
state: installed

**Comment by narutowindy** [comment]
working nicely in my machine!

**Comment by SirCmpwn** [comment]
Another issue that's probably musl related: https://github.com/SirCmpwn/sway/issues/1305

We need a volunteer to maintain musl support.

**Comment by helaan** [comment]
I have the same symptoms, upgraded from v0.13.0 to v0.14.0 and my bar only shows after a reload. I'm running Gentoo on a default/linux/amd64/13.0/desktop profile, which uses glibc.

**Comment by code8buster** [comment]
I can try getting more info with gdb. I'm just not sure how I should go about that since I don't develop software. I'll learn everything required to get you the data you will need.

**Comment by helaan** [comment]
I performed a git-bisect using wlc 0.0.10 from the repos, system-sway removed and -Wall removed from the CFLAGS to "fix" compilation.

https://github.com/SirCmpwn/sway/commit/843ad38b3c427adb0bf319e9613d9813c8d9246c was found guilty. Unfortunately it is quite a large commit and reverting it is not a feasible solution.

**Comment by helaan** [comment]
DING! Found out why this issue occurs and why this commit is significant. The code in this commit expects dbus to be running when starting sway. On our devices, this is not the case, as indicated by the "Connection is null, cannot initiate StatusNotifierWatcher" error message. Users of logind/systemd already have dbus running, but because Void and Gentoo use runit and openrc respectively, this was not the case here. A fix can be found [https://github.com/SirCmpwn/sway/wiki#im-not-using-logind-but-still-want-dbuspolkitpower-management-to-work](on the Sway Wiki) and I can confirm it works for me.

**Comment by 4e554c4c** [comment]
@helaan thanks for looking through this. I'm working on a fix.

**Comment by 4e554c4c** [comment]
Please see if #1316 fixes the problem, if not I can make more changes.

**Comment by helaan** [comment]
Patch seems to work, at least for me. Can @code8buster also confirm?

**Comment by j1e8WTb1A1nReiUc** [comment]
I have this problem on 1/3 of my screens.  After reloading my config (Mod4+Shift+C) things work as expected.

Sway is version 1.0-beta.1
Gentoo - default/linux/amd64/17.0/ profile. 
dbus is installed with support X. 
I launch sway as mentioned on the [Sway Wiki](https://github.com/swaywm/sway/wiki) without the ck-launch-session part.

Here is my sway config, gentoo system information, and sway debug log [my debug files](https://gist.github.com/j1e8WTb1A1nReiUc/57b34630761b25c08c7ee59a1934b46e)
