### ISSUE TITLE
Inconsitent Num Lock behavior when using xwayland

### ISSUE THREAD

**Issue by teiesti** [SirCmpwn/sway#1308]
I have the following issue with Num Lock:

1. Num Lock is disabled.
2. I am running Chromium (or Atom or Spotify) which has the focus.
3. I am pressing the Num Lock key, the led on the keyboard goes on.
4. In Chromium, the numpad doesn't work as expected: I cannot enter numbers; everything works as if Num Lock would be disabled.
5. I am switching the focus to e.g. Termite: Everything works as expected. I can enter numbers.
6. I am switching back to Chromium which then works fine. I can enter numbers.

To my surprise, the issue does not occur when I try to disable Num Lock when using Chromium. The issue does also not occur, when I am using e.g. Termite.

My educated guess is, that this is an issue with applications using xwayland since Chromium, Atom (which is based on Chromium) and Spotify all require an X-compatible API. Native wayland applications like Termite are not affected.

This issue might be quite similar to #1266.

**Comment by SirCmpwn** [comment]
Can you reproduce this on any other Wayland compositors?

**Comment by teiesti** [comment]
I've just tried Weston: No issue! Everything works fine!

Maybe, I should also share that I am using Arch Linux in the latest version and a German keyboard. My `.bash_profile` includes this passage to start Sway:

```bash
# Start Sway, if possible
if [ -z "$DISPLAY" ] && [ "$(fgconsole)" -eq 1 ] && [ -n "$(type -P sway)" ]; then
    export XKB_DEFAULT_LAYOUT=de
    export XKB_DEFAULT_MODEL=pc105
    exec sway
fi
```

**Comment by Timidger** [comment]
I've also noticed this issue on Way Cooler. so either Sway and I are both doing something very wrong, or it's most likely a wlc issue.

**Comment by SirCmpwn** [comment]
If you can repro on Way Cooler, then it's unlikely to be a Sway bug.
