### ISSUE TITLE
Under certain circumstances, input devices get frozen 

### ISSUE THREAD

**Issue by helaan** [SirCmpwn/sway#1332]
Under certain circumstances, the user becames unable to use input devices. The rest of the system remains usable, tray clocks and other processes keep running.

I've enquired on IRC regarding others with these issues and have confirmed that another user on Gentoo is suffering from the same bug. I'm however not sure if this is a Gentoo-exclusive issue. Reproduction by others will be very helpful.

Steps to reproduce:

"Control-C sway in a terminal"
1. Open a Virtual Terminal (VT)
2. Start sway using `sway -d 2> logfile`
3. After sway starts, switch back to the VT you started sway from.
4. Press Control and C to interrupt the running sway process.
5. Observe that you are now unable to type or switch VT's and Sway does not exit. To preserve your log, you can SSH in using a different device/phone if you have sshd running.

I've found other ways to trigger the same symptoms, which involves switching from an Openbox session running on a Nvidia card to Sway running on an intel card, but since that route is hard to reliably reproduce, is considered frivolous by SirCmpwn and might as well be caused by a different bug, I consider this something to be looked into at a different date.

My config, log and further details: https://gist.github.com/helaan/9dd930cd06d878c8864b31d6bb70b8d5

Could other test this as well and tell if they do or do not suffer from this issue, including their init system, udev provider and libinput version?

**Comment by SirCmpwn** [comment]
Try building with the tray disabled.

**Comment by helaan** [comment]
I've tried building with the tray disabled, as well as building the current version from git. Both have the freezing issue.

**Comment by ascent12** [comment]
This looks like a WLC issue. Can you reproduce this with other WLC compositors? (orbment, way-cooler, etc.)

**Comment by helaan** [comment]
I was able to succesfully reproduce this using Orbment: https://gist.github.com/helaan/9ca559d5870534170d4676eea15e1541

**Comment by SirCmpwn** [comment]
Report it there, but don't get your hopes up.
