### ISSUE TITLE
Trying to start sway on Gentoo (without systemd) and nvidia driver.

### ISSUE THREAD

**Issue by hnaparst** [SirCmpwn/sway#1335]
Here is the gist: https://gist.github.com/hnaparst/0fe97aa8be58b8d9158bf936adf728a0

Sway starts correctly if I am in i3 and type sway in an xterm, but not if X is stopped.  Then I get the stuff in the gist.  I must be doing something stupid, like not setting an environment variable... Thanks in advance.

**Comment by SirCmpwn** [comment]
The nvidia proprietary driver is unsupported. Good luck.

**Comment by hnaparst** [comment]
OK, I will try it on nouveau.  I thought the proprietary driver sort of, kind of,  almost worked...guess not. Thanks.

**Comment by SirCmpwn** [comment]
It works for some people, but if you can't get it to work yourself then no help for you is to be found here.

**Comment by hnaparst** [comment]
Fair enough.  That is what I get for using a proprietary, closed source driver.

**Comment by hnaparst** [comment]
Works fine on nouveau, by the way.  Thanks.

**Comment by SirCmpwn** [comment]
No problem, glad you got it working.
