### ISSUE TITLE
Internal display disabled after plugging external display

### ISSUE THREAD

**Issue by Ppjet6** [SirCmpwn/sway#1338]
I am probably going to miss lots of details, please ask me what you need to help resolve this. Also this might be better split into multiple issues, but I am not sure what/where to split.

I have a setup with two external monitors, one plugged via a dock using DP, a second one via miniDP directly onto the laptop. I have no output declared in my configuration file.

I usually lock my screen (swaylock) between these steps (moving from/to home/work).

EDIT: Using Archlinux (4.12.8), and aur/sway-git (r2388.7553103-1)

### Steps to reproduce

- Start sway
- Lock it (optional)
- Put it on the dock (with monitor plugged on that dock)

### What happens

Internal display gets "disabled", turns off(?), I see a black screen and no lock animation if locked.
External monitor turns on, with an empty desktop if locked, with whatever content there was opened on the internal screen otherwise.

If locked, laptop stays in locked state, and doesn't come back if I type my passwd. (I see nothing happening)

### What I expect

Internal display stays on. External display turns on, black if locked. Laptop in lock state, but reacts if I type something.

I should probably remove locking the screen out of the equation, but it's the most common case I encounter.

EDIT: I end up having to kill sway to get my login shell back, when I plan ahead and the machine is networked and I can ssh into it.

**Comment by ascent12** [comment]
A debug log from when this happens would be helpful.

Some laptop GPUs are pretty limited in the number of monitors they can use at a given time (sometimes it's as low as 2), so this may be the issue. Plugging in a 3rd monitor means you've run out of GPU resources, and WLC disables another monitor so it can get the new one to work.

It might also be related to the dock itself. Most newer laptop docks use DisplayPort MST (multi-stream transport) for the connections to the monitor. It requires a couple of things in software to handle it properly (although I don't exactly know what; I don't have any MST capable hardware), and I'm pretty sure WLC doesn't do those things.

I'm just speculating based on your description, though. More information would be helpful.

**Comment by Ppjet6** [comment]
My setup is Thinkpad x250, `Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz` (Broadwell), Thinkpad Pro Dock. My internal screen handles 1080p, and the two external monitor 1440p, (same models from Dell).

I forgot to specify I can run sway fine if I have all monitors plugged before I start it, and it does run also on X (I usually use wmii).

Thanks for the comment, I'll try to reproduce and get debug logs.

**Comment by Drakulix** [comment]
I do expirience the same on my thinkpad (t450s), if I use my DP socket (not on VGA). This might be related to how wlc scans for connectors, as DP and my monitor supports daisy-chaining, which modifies the amount connectors and might shuffle their ids around, which might result in changing the id of my internal monitor to the external.

This is only an idea, I did not debug anything related to this error.

**Comment by SirCmpwn** [comment]
Please test with wlroots as well: https://github.com/SirCmpwn/wlroots

Run the examples and see if you can reproduce this there.

**Comment by ascent12** [comment]
Yeah, seeing if it breaks on wlroots would be really helpful. It would show if it's just a WLC issue.
I've also spend a lot of effort trying to get hotplugging as good as I can, so I would really like to see tests for more exotic use-cases.

DP MST is expected to be broken, though.

**Comment by SirCmpwn** [comment]
Can you file a wlroots ticket with what you know about DP MST support?

**Comment by ascent12** [comment]
> Can you file a wlroots ticket with what you know about DP MST support?

https://github.com/SirCmpwn/wlroots/issues/130

**Comment by Ppjet6** [comment]
[sway.log.txt](https://github.com/SirCmpwn/sway/files/1266893/sway.log.txt)

What I did was, from my login shell:
- Dock the laptop, where one monitor is plugged
- Plug another external monitor via miniDP directly onto the laptop
- Start sway, `sway --debug &> /tmp/sway.log`
*sway started, 3 screens active*
- Open a terminal
- Remove miniDP monitor
*internal screen and one external monitor alive*
- Undock
*internal screen alive*
- Dock again.
*both internal and external monitor black*

**Comment by Ppjet6** [comment]
I have "cleaner" logs here, without dock, and also dmesg with drm debug.

[sway2.log.txt](https://github.com/SirCmpwn/sway/files/1267223/sway2.log.txt)
[sway2.dmesg.txt](https://github.com/SirCmpwn/sway/files/1267224/sway2.dmesg.txt)

From a login shell, no external monitor plugged:
- `sway --debug &> /tmp/sway.log`
*internal screen comes alive*
- Plug external monitor via miniDP on the laptop.
*internal screen goes away, external monitor comes alive*
- Quit sway.

**Comment by ascent12** [comment]
```
08/31/17 12:20:49 - [main.c:50] [wlc] Failed to page flip: No space left on device
```

It'll definitely be related to that. I'm not really what it means when a page flip returns this error, though.

**Comment by Ppjet6** [comment]
From what I have been able to grasp from a colleague working on weston, the buffer wlc is giving to drm is not big enough. My internal screen is 1080p and the external one is 1440p.

**Comment by martinetd** [comment]
FWIW this is https://github.com/Cloudef/wlc/issues/87 (already referenced in the bounty page, probably best not too have too many duplicates)
