### ISSUE TITLE
Impossible to switch desktop when tooltip or menu are opened in firefox

### ISSUE THREAD

**Issue by Ppjet6** [SirCmpwn/sway#1339]
### Steps to reproduce

- Open about:blank in Firefox (xwayland)
- Right click somewhere on the page, to open a menu.
  (Also happens when a tooltip gets displayed)
- Try to change virtual desktop (Mod4 + <n> here)

### What happens

Nothing.

### What I expect

Being able to change desktop.

Running Archlinux 4.12.8, sway r2388.7553103-1, Firefox Nightly

**Comment by hobarrera** [comment]
FWIW, this also happens on i3. I'd argue this might be more of a firefox issue.

**Comment by 4e554c4c** [comment]
This is expected behavior.

**Comment by SirCmpwn** [comment]
https://github.com/SirCmpwn/sway/issues/646

Please search for existing issues before submitting new ones.
