### ISSUE TITLE
Vertical monitor. Output rotation

### ISSUE THREAD

**Issue by Diadlo** [SirCmpwn/sway#1341]
Hi. I'm new sway uses and maybe miss something, but is there support for vertical monitors? I.e. can I setup rotation for the output?

**Comment by Diadlo** [comment]
Seems, upstream issue https://github.com/Cloudef/wlc/issues/86

**Comment by ascent12** [comment]
This is supported in wlroots, so when sway eventually gets ported over to that, rotation will be supported.
