### ISSUE TITLE
j4-dmenu-desktop raise cpu 100% every child windows

### ISSUE THREAD

**Issue by enricoT** [SirCmpwn/sway#1345]
sway version 0.14-rc1-102-g713ffee (2017-09-02, branch "master"
sorry it was a mirage, htop double the line with same PID one line with java, and another with j4-dmenu-desktop, top is more simple and does not, so the problem is not a real problem.

**Comment by SirCmpwn** [comment]
https://github.com/SirCmpwn/sway/wiki#how-do-i-report-issues

Your ticket is vague and confusing.

**Comment by DarkReef** [comment]
So, if this a false issue we can close it?
