### ISSUE TITLE
Sway does not have CAP_SYS_PTRACE but the cap is correctly set

### ISSUE THREAD

**Issue by avivace** [SirCmpwn/sway#1346]
`sway version 0.14-rc1-110-g5e8f83f (2017-09-08, branch "master")`

I'm getting `[main.c:245] !! DANGER !! Sway does not have CAP_SYS_PTRACE and cannot enforce security rules for processes running as other users.`.

I have run 
```
sudo setcap cap_sys_ptrace=eip /usr/local/bin/sway
sudo setcap cap_sys_tty_config=eip /usr/local/bin/sway
```

And getcap shows:

```
$ getcap /usr/local/bin/sway
/usr/local/bin/sway = cap_sys_tty_config+eip
```

Solution:

```
sudo setcap cap_sys_ptrace=eip /usr/local/bin/sway
```
Fixed the issue

**Comment by SirCmpwn** [comment]
wat

**Comment by WonderWoofy** [comment]
I think this is a legitimate issue with the README.*.md files actually.  

Setcap overwrites existing capabilities each time you call it, so setting CAP_SYS_TTY_CONFIG=eip after a separate setcap to give CAP_SYS_PTRACE=eip, you'll only end up with CAP_SYS_TTY_CONFIG=eip on the binary.

    # setcap cap_sys_ptrace=eip /usr/bin/sway
     
    $ getcap /usr/bin/sway
    /usr/bin/sway = cap_sys_ptrace+eip
     
    # setcap cap_sys_tty_config=eip /usr/bin/sway
     
    $ getcap /usr/bin/sway
    /usr/bin/sway = cap_sys_tty_config+eip
     
    # setcap cap_sys_ptrace=eip /usr/bin/sway
     
    $ getcap /usr/bin/sway
    /usr/bin/sway = cap_sys_ptrace+eip

As you can see it unsets any cap previously set.  So after a bit of searching through the man pages, I managed to find a reference to how to set two at the same time.

    # setcap "cap_sys_ptrace,cap_sys_tty_config=eip" /usr/bin/sway
     
    $ getcap /usr/bin/sway
    /usr/bin/sway = cap_sys_ptrace,cap_sys_tty_config+eip

Unfortunately, I cannot seem to find any possible way to set _Enforced_, _Inhereted_, and _Permitted_ in different combinations for two different capability sets.  Here is an example...

    # setcap "cap_sys_ptrace=ep,cap_sys_tty_config=ei" /usr/bin/sway
    usage: setcap [-q] [-v] (-r|-|<caps>) <filename> [ ... (-r|-|<capsN>) <filenameN> ]
     
    Note <filename> must be a regular (non-symlink) file.

That is really of no consequence when the instructions are to give both capability sets the same _eip_.  But I just wanted to point that out in case anyone finds this post as a reference to a related but different issue.

If this makes sense to you, please update the README pages with this information.  Thanks!

**Comment by avivace** [comment]
Exactly what my issue was about, thank you for the detailed explanation. I concur in updating accordingly the README.
