### ISSUE TITLE
Sway doesn't render colors properly with 10bit depth

### ISSUE THREAD

**Issue by Ppjet6** [SirCmpwn/sway#1348]
I am testing a new patch series for mesa[0]. I can see in the logs wlc telling me it choose RGB101010, but sway doesn't render colors correctly.

Testing with Sway 7553103 and Archlinux 4.12.10.

[0]: https://patchwork.freedesktop.org/series/29802/

**Comment by 4e554c4c** [comment]
What do you mean "Doesn't render colors correctly"? Are all colors off, sway config colors or something else?

**Comment by ascent12** [comment]
This is a WLC issue, and WLC doesn't support 10 bit colours.
