### ISSUE TITLE
swaymsg keybinding.

### ISSUE THREAD

**Issue by PeaceAlways** [SirCmpwn/sway#1349]
I searched but didn't find.
I know that I am doing this wrong. Tell me how to do this
exec --no-startup-id swaymsg 'workspace 1:General;exec /$term;workspace 1:General'

Here,
$term is my terminal variable.
Also work spaces are set as variable but I have to mention it's full name to access in swaymsg command.

**Comment by SirCmpwn** [comment]
I don't understand your question.

**Comment by PeaceAlways** [comment]
Suppose,
set $term termite
set $workspace1 "1:General"
Now, if I have to open vim inside termite in specific work space i.e., $workspace1. Then what should I do.

I tried:-
exec --no-startup-id swaymsg 'workspace $workspace1; exec $term -e vim'

but this is not working. I don't know why but due to variables are not working under quotation or something. I just want real way of doing this.

**Comment by SirCmpwn** [comment]
If you just do this at your terminal, what happens:

```
swaymsg 'workspace test; exec termite'
```

**Comment by PeaceAlways** [comment]
It goes to workspace test and opens termite.

**Comment by SirCmpwn** [comment]
How about `swaymsg 'workspace "1:General"; exec urxvt -e vim'` from the terminal?

**Comment by PeaceAlways** [comment]
Sorry for silly questions. I am running Arch Linux under wayland. And I don't know how to load .Xresources under wayland.

Can you please provide some link.
