### ISSUE TITLE
nm-applet in swaybar.

### ISSUE THREAD

**Issue by PeaceAlways** [SirCmpwn/sway#1357]
Is it possible to add nm-applet in swaybar if yes how?. If no, is it going to be implemented.
Thank You.

**Comment by SirCmpwn** [comment]
Currently only icons using StatusNotifierItem are supported. Support for legacy Xembed icons will come later.

**Comment by PeaceAlways** [comment]
Can you please suggest some replacement that can be placed over swaybar. For networks and bluetooth.

**Comment by SirCmpwn** [comment]
Beats me. I would just use nmtui from a terminal.

**Comment by walterhuangio** [comment]
Re-visiting this, I've installed nm-applet using AUR network-manager-applet-indicator package and start it with `nm-applet --indicator`, the icon shows! However, clicking it doesn't do anything. Notification works as well.

**Comment by ianyfan** [comment]
@walterhuangio See https://github.com/swaywm/sway/pull/3249

**Comment by grahamc** [comment]
For future seekers, nm-applet's connection editor does work under sway just fine if you directly execute `nm-connection-editor`.

**Comment by koponomarenko** [comment]
nm-connection-editor - a graphical user interface,
    network-manager-applet - a system tray applet (nm-applet).
It is possible to use `nm-connection-editor` only (without `network-manager-applet`).

**Comment by mb720** [comment]
> Beats me. I would just use nmtui from a terminal.

nm-applet's advantage is that it makes discovering *and* connecting to WPA2 Enterprise networks quite easy. nmtui does not allow discovering networks as far as I know.

**Comment by KristerV** [comment]
currently under Arch just `nm-applet` doesn't do anything and `nm-applet --indicator` crashes:

```
(process:4139): nm-applet-ERROR **: 10:48:19.442: Error: --indicator requested but indicator support not available
[1]    4139 trace trap (core dumped)  nm-applet --indicator
```
nmtui it is I guess..

> nm-applet's connection editor does work under sway just fine if you directly execute nm-connection-editor

I couldn't figure this UI out for the life of me.

> nmtui does not allow discovering networks

It does. Under the "Activate a connection" menu it show's new connections. Asks for password and everything. But I must say it doesn't show all connections all the time. Also It doesn't seem to always ask for a password (though obviously it will then not connect). Ahh.. I miss nm-applet.

**Comment by M4a1x** [comment]
Just found this issue via Google and wanted to leave my 2ct:

@KristerV Are you using Arch? If so, you need to use [network-manager-applet-indicator](https://aur.archlinux.org/packages/network-manager-applet-indicator/), also [see Wiki](https://wiki.archlinux.org/index.php/NetworkManager#Appindicator) from the AUR as AppIndicator support is not compiled into the main package.

An alternative I currently favor is using [`networkmanager_dmenu`](https://github.com/firecat53/networkmanager-dmenu) which can also be found in the [AUR](https://aur.archlinux.org/packages/networkmanager-dmenu-git/) with `bemenu` as backend. To do this, just place this config in `~/.config/networkmanager-dmenu/config.ini`:

```
[dmenu]
dmenu_command = /usr/bin/bemenu
```
for more options see the example config in `/usr/share/doc/networkmanager-dmenu-git/config.ini.example`

It supports the most important stuff like discovering and connecting to new networks, opening the connection manager, connecting to vpns, setting up new connections, etc

**Comment by pavlix** [comment]
I wonder why `nm-applet --indicator` just exists without any icon or error message for me. I worked on nm-applet appindicator improvements in the past, long ago when I was using Enlightenment for a short period of time. It used to work well. No need for `Xembed` cruft any more. I tried the one in openSUSE Tumbleweed and it is apparently built with appindicator support.

**Comment by pavlix** [comment]
For everyone who bumps into the same issue, `nm-applet` quits quietly when it's already running. The solution was:

```
killall nm-applet
nm-applet --indicator
```

However, it doesn't open the menu for some reason. Now the icon is there. I'm happy using `nm-cli` for all connectivity most of the time but it would be nice to have a complete support. Does `swaybar` implement the appindicator menu or not?

**Comment by progandy** [comment]
@pavlix The menu isn't implemented yet: #5161

**Comment by andrewnicolalde** [comment]
> Just found this issue via Google and wanted to leave my 2ct:
> 
> @KristerV Are you using Arch? If so, you need to use [network-manager-applet-indicator](https://aur.archlinux.org/packages/network-manager-applet-indicator/), also [see Wiki](https://wiki.archlinux.org/index.php/NetworkManager#Appindicator) from the AUR as AppIndicator support is not compiled into the main package. (As @walterhdev pointed out)
> 
> An alternative I currently favor is using [`networkmanager_dmenu`](https://github.com/firecat53/networkmanager-dmenu) which can also be found in the [AUR](https://aur.archlinux.org/packages/networkmanager-dmenu-git/) with `bemenu` as backend. To do this, just place this config in `~/.config/networkmanager-dmenu/config.ini`:
> 
> ```
> [dmenu]
> dmenu_command = /usr/bin/bemenu
> ```
> 
> for more options see the example config in `/usr/share/doc/networkmanager-dmenu-git/config.ini.example`
> 
> It supports the most important stuff like discovering and connecting to new networks, opening the connection manager, connecting to vpns, setting up new connections, etc

Curiously this package appears to have been removed from the AUR.

**Comment by andrewnicolalde** [comment]
Ah, looks like the default nm-applet package on Arch linux now supports appindicators.

Source: https://lists.archlinux.org/pipermail/aur-requests/2020-June/041394.html

**Comment by alienjedi** [comment]
> Ah, looks like the default network-manager-applet package on Arch linux now supports appindicators.
> 
> Source: https://lists.archlinux.org/pipermail/aur-requests/2020-June/041394.html

Does that mean it will work with sway? And if yes, how do I implement it. Because currently I only use  `nm-applet --indicator` to show network status on swaybar.

**Comment by xkonni** [comment]
any news on this? i can still use `nm-applet --indicator`, but not without indicator.

**Comment by rumpelsepp** [comment]
https://github.com/swaywm/sway/pull/5161

**Comment by maxnoe** [comment]
`exec nm-applet --indicator` in `sway/config` works fine now  for me on arch using sway and waybar

**Comment by mb720** [comment]
It shows the current WiFi signal strength, which is nice.

Thanks for the implementing this.

Is it supposed to show a menu with available connections when clicking on it? Because it doesn't react to clicks on my system.

**Comment by maxnoe** [comment]
I get the menu when clicking:


![nmapplet](https://user-images.githubusercontent.com/5488440/128563898-293512cd-2f6b-404f-ad5e-bfb2e39e4c5f.png)

**Comment by fkohrt** [comment]
In case anybody has issues with adding `exec nm-applet --indicator` to `~/.config/sway/config`, try `exec_always` instead:

```
exec_always nm-applet --indicator
```

**Comment by bo-tato** [comment]
it looks like waybar not swaybar in @maxnoe screenshot. swaybar doesn't support this yet, pending a PR https://github.com/swaywm/sway/pull/8920, waybar does
