### ISSUE TITLE
Failed to open device, void linux, Vega 56

### ISSUE THREAD

**Issue by treeman** [SirCmpwn/sway#1358]
I'm trying out sway in void linux and I'm getting:

```
09/12/17 00:52:14 - [main.c:50] [wlc] Failed to open X11 display
09/12/17 00:52:14 - [main.c:50] [wlc] Failed to open device: /dev/dri/card0
09/12/17 00:52:14 - [main.c:50] [wlc] Could not initialize any backend
09/12/17 00:52:14 - [main.c:48] [wlc] Failed to init compositor
```

Output of `sway -V`: https://gist.github.com/treeman/8cfdce39465e1bb66d244c0f9dcddf2a

```
sway --version
sway version  (2017-07-28, branch "")`
```

I'm using Vega 56 with the libGL package

```
lspci | grep VGA
44:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Vega [Radeon RX Vega] (rev c3)
```

```
ls -la /usr/bin/sway
-rwsr-xr-x 1 root root 320656 Jul 28 09:34 /usr/bin/sway*
```

Is there any other info you want?

**Comment by SirCmpwn** [comment]
Are you in the video group? (or whatever group is appropriate for reading /dev/dri/card0 on your machine)

**Comment by treeman** [comment]
Yes I believe so

```
> groups tree
tree : tree wheel floppy disk lp dialout audio video cdrom optical mail storage scanner network kvm input users xbuilder
```

**Comment by SirCmpwn** [comment]
And /dev/dri/card0 is in that group and g+rw?

Full debug log please.

**Comment by treeman** [comment]
Huh. I don't have the card. Does that mean I have the wrong drivers? I did get X up and running in a basic manner.

I assume `sway -Vd` is what you want?  
https://gist.github.com/treeman/05542f677f25e7c0ad56df89b794f6c6

**Comment by SirCmpwn** [comment]
You're using open source drivers, right? Do you have anything in /dev/dri? Do you have /dev/drm?

**Comment by treeman** [comment]
Yes that's the open source drivers. No /dev/dri or /dev/drm.

**Comment by SirCmpwn** [comment]
`zgrep CONFIG_DRM= /proc/config.gz`

**Comment by treeman** [comment]
```
zgrep CONFIG_DRM= /proc/config.gz
CONFIG_DRM=m
```

**Comment by SirCmpwn** [comment]
Well, beats me. It's not a Sway problem. Ask your distro support why you don't have /dev/drm. Maybe check dmesg for drm related errors?

**Comment by treeman** [comment]
Alright, will do. Thanks.
