### ISSUE TITLE
Ability to lock screen after period of idleness.

### ISSUE THREAD

**Issue by tmccombs** [SirCmpwn/sway#1359]
The actual screen locking probably doesn't belong in sway, but sway should somehow report activity/idleness, so a dameon can watch for idleness and take some action (such as locking the screen, or suspending) after a period of idleness.

**Comment by Timidger** [comment]
While I admit to not knowing the sway / i3 api off the top of my head, wouldn't it be better for this to be doable using a user script? Check for user input / event input and if it hadn't happened in n seconds lock the screen.

**Comment by ascent12** [comment]
This is related to #541, which has a bounty on it.

**Comment by tmccombs** [comment]
> Check for user input / event input and if it hadn't happened in n seconds

I'm not super familiar with wayland, but from what I can tell there isn't a way to do that. What I'm really asking for is a way to ask sway  when the last user input happened, so that a script like that is possible.

One option could be to have sway tell logind when the session is active or idle, and have systemd handle actually locking, suspending, etc. Of course, that doesn't work on systems without logind.

**Comment by SirCmpwn** [comment]
#541
