### ISSUE TITLE
Java Swing/Gtk3 windows do not take keyboard input

### ISSUE THREAD

**Issue by tidux** [SirCmpwn/sway#1362]
This makes things like ScreenConnect useless under Sway.

**Comment by SirCmpwn** [comment]
Better reproduction steps, please.

**Comment by tidux** [comment]
Steps to reproduce:

1. Install and launch MuCommander, or any other JDK9/Gtk3 application under Sway, from terminal or directly from dmenu.  

2. Notice that floating windows are improperly sized.

3. Notice that the window is proportioned oddly, with sub-widgets not displaying at all or not taking input.

I'm testing again with the non-reparenting WM Java environment variable set, and will report back.

**Comment by tidux** [comment]
Java works with the following environment variable set:

`_JAVA_AWT_WM_NONREPARENTING=1`

It may be useful to have Sway itself set this variable as it's a fairly obscure setting.

**Comment by SirCmpwn** [comment]
It's in the FAQ. I'm not adding workarounds for specific shitty UI toolkits.
