### ISSUE TITLE
Get duplicate workspaces

### ISSUE THREAD

**Issue by elverskog** [SirCmpwn/sway#1365]
I'm seeing the workspace "2" appear twice in my right monitor in i3 manage bar (screen below) . I assume there are actually two "2" workspaces and this is not an issue with the bar.

I couldn't find an existing issue like this. I think this happened after I moved a workspace from one monitor to the other.

I cannot access the second "2" in any logical way. Somehow I wind up on one versus the other but I can't see a pattern. I can move the first "2" workspace around but there are always 2 of them.

Please let me know if you want conf lines etc.

btw - swaygrab requires imageMagick (got a "convert not found error") but sway/swaygrab installs without it. I guess most people have it already?

ADDED OUTPUT OF swaymsg -rt get_workspaces

![2017-09-22-114222_swaygrab](https://user-images.githubusercontent.com/7500216/30753439-49936598-9f8d-11e7-9ff8-a3c682cb292e.png)

[wokspace-dump.txt](https://github.com/SirCmpwn/sway/files/1325091/wokspace-dump.txt)

**Comment by elverskog** [comment]
References closed issue #1364

**Comment by elverskog** [comment]
It looks like it allows for non-unique names. Is there any setting to force unique names?

**Comment by SirCmpwn** [comment]
Why did you open a new issue? Go back to the other one.
