### ISSUE TITLE
Mouse gets stuck in second screen

### ISSUE THREAD

**Issue by elverskog** [SirCmpwn/sway#1366]
Seems to have to do with move workspaces from on screen to another. Has happened a few times.

My mouse gets trapped in right hand (2nd) screen. 

Mouse can go slightly off to the right of 2nd screen but it doesn't track far (as might happen if there were a missing 3rd screen on the right). When I drag back left it is as if the mouse was just waiting 10px off the right of the screen.

**Comment by benjiprod** [comment]
If you have a popup on your currently screen, you can't switch workspaces. I don't know if there is a case about that bug.

**Comment by cafehaine** [comment]
see #646
