### ISSUE TITLE
Latest Sway version that worked with xembedsniproxy?

### ISSUE THREAD

**Issue by gnidorah** [SirCmpwn/sway#1370]
I know proper xembed support will appear in the future and I see that xembedsniproxy launching was removed from 0.14.
Just out of curiosity I want to look at Sway which worked with xembedsniproxy.
I've tried 0.13 on Arch and NixOS and few programs with xembed tray icon, however Sway doesn't launch xembedsniproxy and if I launch it manually, then program icon appears in a new window instead of showing on a bar and a small black square appears in the top left corner.

**Comment by SirCmpwn** [comment]
If xembedproxy was supported we wouldn't have said it wasn't -_-

**Comment by gnidorah** [comment]
Sorry :-)
