### ISSUE TITLE
Segmentation Fault error only with amd discrete card

### ISSUE THREAD

**Issue by ellipticaldoor** [SirCmpwn/sway#1374]
I have two graphic cards, an Intel Iris Pro as integrated and an AMD Radeon R9 M370X as discrete.

With the Intel sway starts fine but whit the amd I get **Segmentation Fault** error.

If I do **sudo sway** the error changes to this:
![image](https://user-images.githubusercontent.com/3449006/30887995-f665fa3e-a315-11e7-915b-dd7a70864bf6.png)

This is sudo with debugging:
![image](https://user-images.githubusercontent.com/3449006/30888055-52fbf96a-a316-11e7-9f68-1a5c7fda6b87.png)

And this is how it looks in verbose mode
![image](https://user-images.githubusercontent.com/3449006/30888761-21eee7ac-a31a-11e7-819a-7807ab58ab97.png)

**Comment by ellipticaldoor** [comment]
If I startx and inside the X I call sway it works

**Comment by SirCmpwn** [comment]
That's not important. That is an unsupported means of running Sway.

**Comment by SirCmpwn** [comment]
No. I will reiterate: **running Sway inside of X is not supported**.

**Comment by SirCmpwn** [comment]
Use Intel and we'll figure out your Radeon problem. Are you using the open source drivers? How are you specifying the discrete card?

**Comment by ellipticaldoor** [comment]
okay!

I have a MacBookPro11,5 with an Intel Iris Pro and a AMD Radeon R9 M370X

I use this script to change the graphics card https://github.com/0xbb/gpu-switch

**Comment by SirCmpwn** [comment]
Uh... huh. That's weird.

When using the Intel card, what are the contents of /dev/dri?

**Comment by ellipticaldoor** [comment]
looks like this

![image](https://user-images.githubusercontent.com/3449006/30912871-0de24eb8-a386-11e7-82ba-5746c5d9f504.png)

**Comment by SirCmpwn** [comment]
Try running sway as:

```
WLC_DRM_DEVICE=card1 sway
```

**Comment by ellipticaldoor** [comment]
Yes! With that command it works

**Comment by ellipticaldoor** [comment]
Can you explain why this happens? I'm really interested in this project. Awesome work :)

**Comment by SirCmpwn** [comment]
Well, I don't know what your weird EFI thing does. But the kernel exposes both of your GPUs in /dev/dri so we just instructed Sway to use the other one.
