### ISSUE TITLE
Screen flicker / i3blocks gaps

### ISSUE THREAD

**Issue by hexive** [SirCmpwn/sway#1376]
I'm trying to investigate a screen flicker issue (background images shows briefly through other open windows). The problem is intermittent and it seems to be  unrelated to any actions I'm taking. I suspect it's related to swaybar/i3blocks gaps and signal intervals. I don't have enough information to post a proper bug report, but I'm hoping you can help me with steps I could take for good troubleshooting. Besides dumping sway.log is there anything else I should be looking at? Thanks in advance.

**Comment by SirCmpwn** [comment]
Dupe https://github.com/SirCmpwn/sway/issues/1344
