### ISSUE TITLE
wl_registry@2: error 0: invalid version for global wl_data_device_manager (4): have 2, wanted 3

### ISSUE THREAD

**Issue by Laaas** [SirCmpwn/sway#1378]
BTW, I can see that the repo is moving today, but it hasn't moved yet.

I don't exactly know how these versions work and all that (not much info on the web), but it seems to be related to wlc/src/compositor/seat/data.c line 174 and line 235.

If someone could give some hints as to how I could implement it myself, I'd be glad too.

**Comment by SirCmpwn** [comment]
Needs more context. What were you doing when you encountered this problem?

**Comment by Laaas** [comment]
This is BTW on with wlc 0.0.10, sway 0.14, and it happens when running an SDL program using the wayland videodriver.

**Comment by Laaas** [comment]
I've only tested it with Natural Selection 2 (a game). Will be hard for you to reproduce, which is why I think it would be best if I implemented it myself.

**Comment by SirCmpwn** [comment]
Alright, fair enough. This ticket belongs on wlc, can you open a new one there?

**Comment by Laaas** [comment]
sure
