### ISSUE TITLE
All clicks are being consumed by sway

### ISSUE THREAD

**Issue by Luminarys** [SirCmpwn/sway#140]
I haven't looked too far into this, but somehow `pointer_mode_set` is failing to correctly set the pointer mode resulting in EVENT_HANDLED being sent for all clicks. My first assumption would be that the logic for checking if the floating_modifier is being held is somehow giving incorrect results, but I'm not too sure.

**Comment by taiyu-len** [comment]
caused by default value of floating_mod being 0.
`((modifier & floating_mod) == floating_mod) -> modifier & 0 == 0`

**Comment by Luminarys** [comment]
Fixed.
