### ISSUE TITLE
Running rofi messes up layout

### ISSUE THREAD

**Issue by aouelete** [SirCmpwn/sway#154]
Here is a [screenshot](https://i.imgur.com/wilITA2.png) after opening a second terminal. It seems like sway is completely ignoring the original terminal window on the left and there is no way to focus it. Here is the [log](http://pastebin.com/8nvNvB5W).

**Comment by Luminarys** [comment]
The issues seems to be that the rofi window isn't properly destroyed once it launches something and becomes an invisible tile. I'll look into why this seems to be happening.

**Comment by Luminarys** [comment]
The issues seems to be that when rofi is being destroyed, its wlc view type isn't properly acknowledged as WLC_BIT_POPUP, so it isn't properly removed from sway as a result, which leaves that lingering invisible window.

**Comment by taiyu-len** [comment]
hmm, its type changes, so we handled its destruction incorrectly.
easy to fix though.

**Comment by Luminarys** [comment]
Fixed.
