### ISSUE TITLE
i686 build...

### ISSUE THREAD

**Issue by AndrieVorster** [SirCmpwn/sway#163]
Will you please put a i686 build in the AUR.

Thanks,
Andrie Vorster.

**Comment by SirCmpwn** [comment]
Does the i386 build not work for you?

**Comment by AndrieVorster** [comment]
Sorry now I see there is a PKGBUILD error...

**Comment by AndrieVorster** [comment]
-arch=("i386" "x86_64")
+arch=("i686" "x86_64")

**Comment by SirCmpwn** [comment]
Nevermind, it was my fault. Fixed.

**Comment by AndrieVorster** [comment]
Thanks!
