### ISSUE TITLE
temporary wallpaper

### ISSUE THREAD

**Issue by ke7ofi** [SirCmpwn/sway#166]
I know it’ll be changed and it doesn’t matter very much, but doesn’t an animation eat more cycles than a still? It seems like it goes against the “spirit” of i3, though I certainly understand if you’ve gotten to the point where you don’t mind some divergence.

**Comment by Luminarys** [comment]
This actually is a wlc issue, not sway. We're working on getting this fixed though.

**Comment by SirCmpwn** [comment]
Wallpaper support will be in place after wlc implements protocol extensions.

**Comment by ke7ofi** [comment]
So wlc provides the animation?

**Comment by SirCmpwn** [comment]
Yes.

**Comment by ke7ofi** [comment]
Thanks for the clarification, and sorry for harrassing you guys.
