### ISSUE TITLE
commit e1d18e4 breaks window tiling when run from tty

### ISSUE THREAD

**Issue by Limvot** [SirCmpwn/sway#180]
On my laptop, a 64 bit fully updated Arch system running the intel drivers, running a sway version after commit e1d18e4 causes windows to show up on top of each other at odd, small sizes. Note that it still seemed to work properly when run from inside of X. The previous commit works from both tty and X. I hope this is enough info, just let me know of anything else you need!

**Comment by SirCmpwn** [comment]
Paging @taiyu-len to look into this

**Comment by xanecs** [comment]
I just installed it from git and I can confirm this strange behaviour.
also arch x86_64, Intel graphics, running from TTY

**Comment by taiyu-len** [comment]
whoops, i made a dumb and simple mistake.
