### ISSUE TITLE
Window fullscreens behind other window

### ISSUE THREAD

**Issue by Limvot** [SirCmpwn/sway#184]
If I have 2 terminal (sakura) windows open side by side and fullscreen the left one, it fullscreens behind the right one so that the right one still shows up on top of the left one, blocking half of the screen. (I'm running from the tty)

Let me know if you need any more information!

**Comment by SirCmpwn** [comment]
I have seen a similar issue. We probably just need to make sure that fullscreen windows are moved to the top.
