### ISSUE TITLE
zombie processes don't seem to be cleaned up properly

### ISSUE THREAD

**Issue by zetok** [SirCmpwn/sway#187]
https://gist.github.com/zetok/a8e10a5c28f5ceb90913  - all these zombies were running under xwayland

**Comment by zetok** [comment]
Sadly, 5539fd89be99bcec6d5eeb43c6123954ce59038e doesn't fix the problem - instead it introduces regression, which renders sway useless, since no processes can be launched, keyboard is being held hostage by sway, so that switching to tty is possible only after `SysRq + r`..

There also was some error message about not handling signal correctly after I killed sway from another tty.

Reverting 5539fd89be99bcec6d5eeb43c6123954ce59038e fixes the regression.

Please reopen.

**Comment by SirCmpwn** [comment]
Weird. It looked like a solid solution to me.

**Comment by zetok** [comment]
Looks like 18f4905e62e1fb2042abd79b2a4c756187e3d506 fixed it for me.

**Comment by Hello71** [comment]
@ddevault SIGCHLD SIG_IGN is inherited through execve on Linux.

**Comment by emersion** [comment]
Which is one of the reasons why we don't set up a `SIGCHLD` handler.

**Comment by Hello71** [comment]
irrelevant. *caught* signals are always reset to the default disposition after execve.
