### ISSUE TITLE
Add in testing/CI

### ISSUE THREAD

**Issue by Luminarys** [SirCmpwn/sway#20]
It would probably be a good idea at some point in the near future to setup test cases, and possibly some CI service to make testing easier.

**Comment by SirCmpwn** [comment]
Agreed. Travis works well. I'd merge a pull request adding a `.travis.yml`.

**Comment by Luminarys** [comment]
Sure, I'll get on this.

**Comment by mikkeloscar** [comment]
I looked into this and since Travis is running ubuntu 12.04 a lot of stuff is either outdated or missing, so it is quite complicated to do this.

**Comment by SirCmpwn** [comment]
We could install arch in a chroot on travis and... nevermind

**Comment by Luminarys** [comment]
I ended up almost getting Travis working a while back, but there ended up being a weird issue with some structs from #time.h somehow not being included in wlc. Have you given any more thought to how we should do CI @SirCmpwn?

**Comment by SirCmpwn** [comment]
No, not really.

**Comment by mikkeloscar** [comment]
@SirCmpwn I know you were joking about the chroot, but I actually thought about it and made a general purpose tool for automatically setting up an Arch chroot on travis: [arch-travis](https://github.com/mikkeloscar/arch-travis).

I don't wanna push it upon you, but if you think it is useful for sway, then I'll make a PR.

Here is an example of how it could work: https://github.com/mikkeloscar/sway/blob/master/.travis.yml

And an example of a successful build of sway: https://travis-ci.org/mikkeloscar/sway/builds/78777172

**Comment by Luminarys** [comment]
Neat. I recommend building wlc along with sway, but this looks pretty good to me.

**Comment by mikkeloscar** [comment]
@Luminarys something like this: mikkeloscar@cf1176c7286657e4c56cbd5bc599ba85482317b9 ?

**Comment by SirCmpwn** [comment]
Wow, that's really cool. We should use this. I'd merge a pull request that makes this work.

**Comment by Luminarys** [comment]
I agree, the arch-chroot is pretty impressive. I think it needs to run make install for wlc, but other than that It looks good to me @mikkeloscar.
