### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by TPolzer** [SirCmpwn/sway#213]
Being able to scale (like weston) would make this usable for high resolution displays.

**Comment by SirCmpwn** [comment]
https://github.com/SirCmpwn/sway/blob/master/sway.5.txt#L109-L112

Set the resolution to half the actual resolution of the display. Actual HiDPI support is wlc's problem.

**Comment by stapelberg** [comment]
Setting the resolution to half of the actual resolution makes everything big and blurry.

https://github.com/Cloudef/wlc/issues/57 seems to be the relevant issue to track.

**Comment by xeechou** [comment]
Yep, hidpi support shouldn't be simply set resolution to half.

**Comment by SirCmpwn** [comment]
The clients need to be told the scaling factor (see Cloudef/wlc#57), but halving the resolution is a workaround.

**Comment by wzhd** [comment]
@SirCmpwn I set the resolution to half the actual resolution, but when I switch to X that runs at the actual resolution and switch back to sway, the resolution becomes the actual resolution.

**Comment by SirCmpwn** [comment]
That's a problem in wlc.

**Comment by dobegor** [comment]
@SirCmpwn Cloudef/wlc#57 is closed now without any comment given. Is there any reason or fix?

**Comment by SirCmpwn** [comment]
Experimental hidpi support has landed in master. Use the scale parameter in your output configuration line to set the scale factor. See the man page for more information.

**Comment by dobegor** [comment]
Oh thanks, gonna check it out soon.

**Comment by mcoffin** [comment]
@SirCmpwn Will this effectively be solved with the move to `wlroots` in 1.0? I'm kind-of just waiting on that release to once again attempt moving to wayland, but hidpi would be a necessity.

**Comment by SirCmpwn** [comment]
Every time someone says "I'm waiting on xyz before I move to Sway" I mentally delay shipping xyz by a week. Don't wait, contribute.

**Comment by mcoffin** [comment]
> Don't wait, contribute.

I was planning on taking a look at `wlroots`, and making sure that the things I wanted for HiDPI support were in there. That's why I was asking. I was just confirming that the move to `wlroots` was the planned way that this was going to get solved, and that I wouldnt' just be barking up the wrong tree.

@SirCmpwn

**Comment by SirCmpwn** [comment]
Yes, that's the plan.
