### ISSUE TITLE
Doxygen comments on source code?

### ISSUE THREAD

**Issue by DragonAxe** [SirCmpwn/sway#218]
I'm wanting to contribute to this project, but the lack of doxygen comments makes it a bit hard to know what's going on in the code.

It would be awesome if someone who knows a bit about the project could add them in, and it would make my life and any future contributer's life easier.

Thanks!

**Comment by SirCmpwn** [comment]
I would merge PRs that add more comments to this effect. I'll add some myself, too, but at this point a significant amount of sway was written by others.
