### ISSUE TITLE
Conky

### ISSUE THREAD

**Issue by feliwyn** [SirCmpwn/sway#222]
Hi! 

Totally no support of conky?
No conky-bar, and no conky on my desktop. :)

**Comment by SirCmpwn** [comment]
I haven't tried. I wouldn't expect much.

**Comment by kon14** [comment]
almost works with xwayland enabled, positioning is somewhat broken.

**Comment by juju2143** [comment]
Conky works quite fine for me. I even wrote a lua script to get the current workspace. Allow me to share my config I did after many trial and error: https://gist.github.com/juju2143/aece6992955462333712

Of course, starting from commit 6596582, you can set `out_to_x = false` and `out_to_console = true` in conky.conf and do a `exec "swaybar 0 conky"` instead in your sway config, but it will look less good.

**Comment by SirCmpwn** [comment]
Adding something along the lines of `exec swaybar` to your sway config is not a future proof solution, by the way. Sometime in the near future, sway will run swaybar itself (and the command line usage of swaybar is undocumented and likely to change).

**Comment by juju2143** [comment]
Yeah, I know. You gotta follow the development of swaybar and make the necessary changes in your config as soon as they come out. Right now, swaybar only serves to reserve some space at the bottom so I can draw conky on it, but that would be nice if you can do that directly in conky somehow.

**Comment by onny** [comment]
Wow juju2143, do you mind sharing a screenshot of a working example? Looking forward to trying it out!

**Comment by juju2143** [comment]
Sure.

![screenshot-201512141305](https://cloud.githubusercontent.com/assets/894481/11789286/7e71a0be-a263-11e5-84f3-d2d2b223c23a.png)

**Comment by onny** [comment]
Now I'm using sway with i3status and this configuration:
 status_command i3status
Unfortunately I don't have the colors of i3status in the swaybar :(
![2015-12-21-152519_swaygrab](https://cloud.githubusercontent.com/assets/757752/11934025/6534792a-a7f7-11e5-907a-fb462b6c0a95.png)

**Comment by mikkeloscar** [comment]
@onny The colors hasn't been implemented yet, but I'm sure it will happen soon.

**Comment by onny** [comment]
Thanks for the info, sounds awesome :)

**Comment by juju2143** [comment]
Colors would be nice. Are they supposed to be the standard ANSI escape codes?

**Comment by mikkeloscar** [comment]
@juju2143 no, swaybar is supposed to implement the i3bar protocol: http://i3wm.org/docs/i3bar-protocol.html so the colors should be provided as part of the json data.

**Comment by onny** [comment]
Looks like there's already a pull request for that https://github.com/SirCmpwn/sway/pull/394#discussion_r48265119 :)

**Comment by onny** [comment]
I changed i3status output_format to i3bar but unfortunately swaybar doesn't render it :(

**Comment by progandy** [comment]
This is how it looks for me:
![2015-12-22-200819_1366x768_scrot](https://cloud.githubusercontent.com/assets/1003865/11963612/7a927050-a8e8-11e5-8fc1-f522e9ca3224.png)

**Comment by onny** [comment]
Do you have i3status as input? And how did you configure it?

**Comment by feliwyn** [comment]
Wooow! I don't understand why are you speaking about i3bar. I can't use sway without conky. I like my conky bar :<

**Comment by progandy** [comment]
@onny: Yes, I have i3status. I configured it with output_format=i3bar, colors=true and interval=5.
@feliwyn: Works with conky, too. Currently you have to send everything on a single line with less than 1024 characters total. I guess there might be some problems with buffers.

**Comment by feliwyn** [comment]
Ow... Some prob for me. My conky conf is here : https://github.com/feliwyn/i3config

**Comment by onny** [comment]
i3status config:
```
general {
        output_format = i3bar
        colors = true
        interval = 5
}
```
sway config:
```
    bar {
        status_command i3status
        font pango:DejaVu Sans Mono 8
    }
```
i3status output:
```
{"version":1}
[
[{"name":"ipv6","color":"#00FF00","full_text":"2a02:8071:****"},{"name":"disk_info","instance":"/","full_text":"1.0 GiB"},{"name":"run_watch","instance":"/var/run/dhclient*.pid","color":"#FF0000","full_text":"DHCP: no"},{"name":"run_watch","instance":"/var/run/vpnc/pid","color":"#FF0000","full_text":"VPN: no"},{"name":"wireless","instance":"wlp2s0","color":"#00FF00","full_text":"W: (077% at ***) 192.168.1.33"},{"name":"ethernet","instance":"enp3s0","color":"#FF0000","full_text":"E: down"},{"name":"battery","instance":"/sys/class/power_supply/BAT1/uevent","full_text":"FULL 93.18%"},{"name":"load","full_text":"0.25"},{"name":"tztime","full_text":"2015-12-22 22:33:28"}]
```
But whole swaybar is somehow broken after that :(

**Comment by juju2143** [comment]
@progandy Oh, that might be why I couldn't see anything in the bar after switching to the JSON format in my Conky config.

Otherwise, fun fact, if you switch to the Lua config format, you can put somewhere in your config these lines, before config.text:
```
print([[{"version":1},
[
[],]])
```
and you can directly put `exec conky` in `status_command` in your bar config.

**Comment by juju2143** [comment]
Oh, it works as of 23df7ed now. Looks like a pretty simple fix.

**Comment by onny** [comment]
Yep nice, it works for me now! Thank you!

**Comment by progandy** [comment]
@feliwyn Can you try it with these changes #402?

**Comment by feliwyn** [comment]
@progandy Yeah! It's works!

But found another probleme. (I can open a new issue, if necessary)
Mode doesn't show their 'menu'

https://paste.feliwyn.fr/?f11f28ed7b8123f2#1yzDh9Tfar5EZPo3hKvshoLp0qnuTPF9dq4btkGd09c=

For exemple, in this paste, the text : "resize" isn't show. So, you don't really now if you are in the mode or no.
Like here : http://i.imgur.com/oAj31Fl.png

**Comment by SirCmpwn** [comment]
That's covered by this issue:

https://github.com/SirCmpwn/sway/issues/343
