### ISSUE TITLE
RWX mmap anonymous mappings

### ISSUE THREAD

**Issue by Manouchehri** [SirCmpwn/sway#228]
Looks like somewhere between c43ef2a and ab3d6f6 an anonymous mapping issue was introduced. Found it with grsecurity after I rebuilt sway, not sure which patch it originates from exactly.

```[ 1076.802509] grsec: denied RWX mmap of <anonymous mapping> by /usr/bin/sway[sway:2863] uid/euid:1000/1000 gid/egid:1000/1000, parent /usr/bin/bash[bash:2171] uid/euid:1000/1000 gid/egid:1000/1000```

As a temporary fix for grsecurity users, run `sudo setfattr -n user.pax.flags -v "m" /usr/bin/sway`. It would probably be a good idea to figure out the root cause though.

**Comment by SirCmpwn** [comment]
Can you do a bisect?

**Comment by Manouchehri** [comment]
I can check later, I was just heading out for dinner and wanted to submit
the issue before I left.

**Comment by SirCmpwn** [comment]
No worries, thanks!

**Comment by SirCmpwn** [comment]
Is this still an issue? It may have been fixed.

**Comment by Manouchehri** [comment]
As of g86372d0 it's still the same.
```
~ > sway --verson
PROT_EXEC|PROT_WRITE failed.
~ > sudo dmesg | tail -1
[ 7870.915655] grsec: denied RWX mmap of <anonymous mapping> by /usr/bin/sway[sway:6673] uid/euid:1000/1000 gid/egid:1000/1000, parent /usr/bin/bash[bash:6648] uid/euid:1000/1000 gid/egid:1000/1000
~ > sudo setfattr -n user.pax.flags -v "m" /usr/bin/sway
~ > sway --version
sway version g86372d0 (2015-11-18, branch "makepkg")
```

**Comment by SirCmpwn** [comment]
What does this error mean? I'm not familiar with grsec.

**Comment by Manouchehri** [comment]
There's a mapping created that has read-write-execute on it. Should be read-execute or read-write.

I can only find [`void *data = mmap(NULL, size, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);`](https://github.com/SirCmpwn/sway/blob/fb0bfa13ce8b5f71e4ba1570dd6d39f98a2f5fdf/wayland/buffers.c#L64) though. I don't see where PROC_EXEC is coming from.

Related: https://bitbucket.org/cffi/cffi/issues/177/foo-segfaults-with-grsec-denied-rwx-mmap

**Comment by SirCmpwn** [comment]
That code isn't invoked for sway, either, just for swaybg. I don't know what's up here.

**Comment by Manouchehri** [comment]
It might be a malloc, apparently Linux sets the default to PROT_EXEC in some cases?

https://stackoverflow.com/questions/6315296/whats-the-protection-flags-of-memory-allocated-by-malloc

**Comment by SirCmpwn** [comment]
I have no clue.

**Comment by mikkeloscar** [comment]
@Manouchehri Can you still produce this error? I have no clue about grsec, but I just tried to run the grsec kernel in Arch, and I don't get any errors when running sway. Do you use some custom config?

**Comment by Manouchehri** [comment]
I haven't been using sway recently. I also had a slight accident with my hard drive, so my system is down right now.

**Comment by thestinger** [comment]
@mikkeloscar You need to install paxd, or the userspace PaX features will be disabled.

**Comment by mikkeloscar** [comment]
@thestinger thanks for the info. I have now tried to run sway on the grsec kernel with paxd installed and don't see any of the errors mentioned here. So I'm inclined to close this, unless someone objects.
