### ISSUE TITLE
Heads up about the debian install script link I added to the wiki

### ISSUE THREAD

**Issue by nathanross** [SirCmpwn/sway#231]
Hey there, 

I created an install script for Sway on the current Debian stable as there are quite a few steps required to get it up and running.

I figured you might want a link to it on the [wiki](https://github.com/SirCmpwn/sway/wiki), so I added it, but you also might not, so this is just me notifying you for in the event that's the case.

**Comment by SirCmpwn** [comment]
Nice script! I established a new page for your script and others like it instead of using the FAQ:

https://github.com/SirCmpwn/sway/wiki/Install-on-other-distros
