### ISSUE TITLE
Poll - usage of layout saving in i3

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/sway#234]
How many sway users actually save their layout with i3? Is this feature valuable for you to have in sway? I feel like it's a messy feature and would be complicated to implement, and I would like to defer it to a low priority or simply avoid supporting it altogether.

**Comment by hidariryoushin** [comment]
TL;DR: Defer to low priority.

For me personally, it's a nice to have feature, but i'm not currently using it. However, I can imagine myself making great use of this for development enviroments that involve non-tmuxable software.

**Comment by Luminarys** [comment]
I personally don't use it, and do agree that it would be likely be rather complicated to implement. Down the line it might be something to consider implementing though.

**Comment by sce** [comment]
I've never tried it, I actually didn't know that feature even existed until I stumbled upon it in the documentation when hacking on sway.

I guess some variant of "predefined layout" would be nice. E.g. being able to specify invisible "placeholder containers" for specific workspaces in the config file that are filled/replaced when views appear there. But yeah, low priority.

**Comment by Drakulix** [comment]
Following sway for quite a while and this feature is absolutely unimportant for me. 
The only things missing for me are swaybar, swaylock, borders+color and for_window.

**Comment by aouelete** [comment]
I've never used this feature in i3. Sometimes I think that it might be useful, but so far I have never found an actual use for it. So, I don't really care if it is implemented in sway.

**Comment by KenMacD** [comment]
never use it here

**Comment by getsmp** [comment]
Never used that feature. Instead, I do use assignments to automatically place windows to specific workspaces, but there's almost never more than one window per workspace. So, IMHO, to implement assign keyword support is far more important.
Thanks you for sway! As soon as swaybar and assign feature are implemented I'm going to completely leave i3 for this awesome peace of software.

**Comment by saraiva132** [comment]
Also never used this feature. As getsmp said, i am looking forward to move to sway as soon as you get swaybar up and running. Keep up the good work!

**Comment by SirCmpwn** [comment]
Thanks for all the feedback. Will definitely prioritize other features. Swaybar is coming soon, by the way.

**Comment by StephenBrown2** [comment]
A bit late here, but I am just getting started with i3 and sway and find this feature to be quite useful for my work desktop, where I always have the same applications on the same monitors in the same layout, but I'm pretty sure this can be replicated with swaymsg commands without terrible difficulty, though it would be more complicated, so while I wouldn't vote for not supporting it, it can most certainly be lower priority.

**Comment by cwmke** [comment]
I fully agree with @StephenBrown2.  I don't think it needs to be a priority but it is a very useful feature for those of us that currently rely on it.  I have three layouts ready to fire off when I need them including two that I auto-start each login.

**Comment by cwmke** [comment]
I fully agree with @StephenBrown2.  I don't think it needs to be a priority but it is a very useful feature for those of us that currently rely on it.  I have three layouts ready to fire off when I need them including two that I auto-start each login.

**Comment by cwmke** [comment]
I fully agree with @StephenBrown2.  I don't think it needs to be a priority but it is a very useful feature for those of us that currently rely on it.  I have three layouts ready to fire off when I need them including two that I auto-start each login.

**Comment by cwmke** [comment]
I fully agree with @StephenBrown2.  I don't think it needs to be a priority but it is a very useful feature for those of us that currently rely on it.  I have three layouts ready to fire off when I need them including two that I auto-start each login.

**Comment by jodigiordano** [comment]
I'm late to the party but for me the lack of layout saving/loading is a deal breaker: I need some way to quickly set layouts as I often shutdown/restart my laptop and I have a very specific dev environment. That said, I would not mind migrating my layouts using `swaymsg` commands if it does the same job in the end. I'll need to dig in the documentation to make sure it is feasible before doing the switch.

**Comment by jplatte** [comment]
I'm using layout loading as well. Not sure exactly sure if this issue is only about saving and loading layouts to / from files specifically; in that I don't really need it. The only thing I need is an automated way of setting window layout. It doesn't need to by via window placeholders as in i3, it could also just be `swaymsg` commands that I send right after starting the program (is that already a thing?).

**Comment by sajattack** [comment]
:+1:
