### ISSUE TITLE
Output should be able to be rotated.

### ISSUE THREAD

**Issue by TMaYaD** [SirCmpwn/sway#235]
Also better documentation with the resolution and position format could help with an example possibly

**Comment by SirCmpwn** [comment]
Report to [wlc](/Cloudef/wlc).

**Comment by TMaYaD** [comment]
I'm talking about the output config option and man 5 sway documentation.

**Comment by SirCmpwn** [comment]
Right, we can't rotate displays because wlc does not support it. Send a PR improving the docs if you like, though.

**Comment by TMaYaD** [comment]
I would love to; if and when I manage to figure it out.

**Comment by SirCmpwn** [comment]
output HDMI-A-1 pos 0,0 res 1920x1080

**Comment by SirCmpwn** [comment]
You can get output names by running `i3-msg -t get_outputs`.

**Comment by TMaYaD** [comment]
Awesome. I'll try that.

Also, raised an issue with wlc: https://github.com/Cloudef/wlc/issues/86

**Comment by SirCmpwn** [comment]
Thanks.

**Comment by thearthur** [comment]
is ewlc or wlc the place to work on this? I'm interested in hacking on it and digging into the history on this.

**Comment by SirCmpwn** [comment]
wlc.
