### ISSUE TITLE
Implementing --release option. Problems detecting WLC_KEY_STATE_RELEASED

### ISSUE THREAD

**Issue by saraiva132** [SirCmpwn/sway#236]
Hi from reddit, i am implementing (as promised) the --release option. First, i noticed there was no support for flags in the bindsym command (would like to add, if possible support for multiple flags ,not only --release).

Secondly, i am noticing that there is no call to handle_key with state == WLC_KEY_STATE_RELEASED. I am running sway on top of X server but i do not think that would be the issue. i added the sufficient logic to detect the --release flag but i can't get to catch the released state.

Can you confirm this?

**Comment by SirCmpwn** [comment]
https://github.com/SirCmpwn/sway/blob/master/sway/handlers.c#L266

This definitely gets called so far as I can tell.

**Comment by SirCmpwn** [comment]
Sway has an internal state machine for keeping track of the keyboard. If wlc isn't sending key release events, then shit would be pretty borken.

**Comment by saraiva132** [comment]
I will look into it.  I also thought it to be extremely weird. Thank you for the feedback,

**Comment by SirCmpwn** [comment]
Any news?

**Comment by mikkeloscar** [comment]
I guess this was implemented in #439
