### ISSUE TITLE
Artwork needed - default wallpaper for sway

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/sway#238]
Unlike i3, sway is going to include support for managing your wallpaper (due to constraints with Wayland). I'd like to ship a nice default one. Anyone want to put something together?

**Comment by DragonAxe** [comment]
Does Sway have a logo, mascot, or idea associated with it that would be good for a background?

**Comment by SirCmpwn** [comment]
Nope, none of the above, though I'm open to changing that.

**Comment by robotanarchy** [comment]
Let's start with a logo concept. It's a mix of the wayland and i3 logos. What do you guys think?

Feel free to use the idea, or modify the image or put it on a wallpaper.

![sway-logo-concept3](https://cloud.githubusercontent.com/assets/7833187/11312599/6a3d9308-8fd7-11e5-9cb9-9716bcd3ad13.png)

**[svg](https://robotanarchy.space/sway-logo-concept.svg)**

*Sway looks really promising, can't wait until it has a status bar :>*

**Comment by SirCmpwn** [comment]
That looks nice given the goals you set, but I'm not sure that it's right for sway. I'd rather do something original instead of ripping off the i3 logo. I'm also not a huge fan of the Wayland logo in general.

**Comment by DragonAxe** [comment]
For some reason I keep returning to the idea of a tree as being a good logo for Sway. It kind of goes along with the phrase "Sway with the wind".
I do like the wayland+i3 logo that you put together robotanarchy.

**Comment by FSMaxB** [comment]
A tree would also represent the data structure in which the windows are in. Nice idea in my opinion.

**Comment by SirCmpwn** [comment]
Tree sounds like a good idea. Or perhaps just detail of a branch? Maybe even with a single leaf on it.

**Comment by Manouchehri** [comment]
@robotanarchy That also looks quite similar to the Jack Ü logo.

![Jack Ü logo](http://jackuofficial.com/wp-content/themes/jacku/images/social.jpg)

**Comment by kon14** [comment]
@robotanarchy I loved the logo myself, though it's indeed crossing the borders with i3.

The tree concept is nice, how about a rope swing swaying in the wind under the tree? Would defnitely be too much for a logo but could make a nice and elegant wallpaper. blue background and the tree/swing burned in with a darker shade?

**Comment by saraiva132** [comment]
@kon14 
That idea looks sweet and elegant :) I would love to have something like that as a wallpaper,

**Comment by coxley** [comment]
:+1:, I like the tree direction.

**Comment by SirCmpwn** [comment]
How about fields of tall grass? That comes to mind more so when I hear the word "sway". Sort of like this:

![](https://sr.ht/HZ9D.jpg)

**Comment by kon14** [comment]
I was thinking about something along those lines, yet I'm awful at gimp and can't actually reproduce the image I had in mind. Maybe add the logo beneath the grass on the left and a thick SWAY on the right, but that would ruin the minimal factor. 

Drawing is from google but I might be more successful in drawing the thing rather than editing it in gimp.

![sway_tree](https://cloud.githubusercontent.com/assets/1786609/11324668/86fe6dd2-9130-11e5-8092-1724c831d1dc.png)

**Comment by SirCmpwn** [comment]
I don't think we need to include the word "sway". Something more simple and subtle would be better.

**Comment by MaxLeiter** [comment]
Perhaps something like this?

![Tree](https://s-media-cache-ak0.pinimg.com/236x/da/72/fe/da72fe7018d4fa78f0f3fb4d51f616f9.jpg)

Sorry for low-quality, all I could find.

**Comment by SirCmpwn** [comment]
What if the logo isn't involved at all? The wallpaper could just be something nice that conveys the idea we're going for, without having to plug the logo.

**Comment by SirCmpwn** [comment]
Also reduces the problem to "find a wallpaper" rather than "find a wallpaper, make a logo, and incorporate the logo into the wallpaper".

**Comment by FreeFull** [comment]
I'm thinking the wallpaper could be something nice and abstract, with "sway" written on it in a very stylised way.

**Comment by coxley** [comment]
http://digitaljames.deviantart.com/art/life-is-minimal-669228

Something like this is simple and neat.

**Comment by SirCmpwn** [comment]
I have permission to use this image, what do you guys think?

![](https://sr.ht/y6RX.jpg)

**Comment by Drakulix** [comment]
I like simple less distracting backgrounds more. this just seems noisy to me. but hey, its just the default wallpaper and its your decision, what shall represent sway.

**Comment by saraiva132** [comment]
Have to agree with @Drakulix. Users tipically enjoy a simple, clean wallpaper. @coxley example is a fairly good example.

**Comment by SirCmpwn** [comment]
I agree that his example works well, but we need something that's CC-BY-SA or similar.

**Comment by DragonAxe** [comment]
I like the colors and overall feel of the tree leaves picture, but the motion in the foreground is a bit too much.
Here's a picture that I took, but I think evergreens are a little more spiky than the name 'sway' might bring to mind:
![sway-background](https://cloud.githubusercontent.com/assets/12703200/11387260/2a0bb410-92e6-11e5-8329-c00e8ad47af4.jpg)

**Comment by StephenBrown2** [comment]
Perhaps something more abstract?
https://github.com/berock212/Maze-background
or
https://github.com/tmathmeyer/maze
offer interesting options. Why have a static image when you could generate one!
Sources: https://redd.it/3sxw7g and https://redd.it/3tdv6i

**Comment by StephenBrown2** [comment]
And of course I mean once per login, or once forever, not like wlc's default moving background...

**Comment by SirCmpwn** [comment]
Generated backgrounds - no

**Comment by progandy** [comment]
Maybe an image of a high wire obstacle course?
I don't have one with a good license, though.

**Comment by stephen304** [comment]
I think it should be less nature photograph and more abstract / color gradient, which would be less distracting but still pleasing. Look at xfce's default background, which is just a blue radial gradient.

**Comment by gpyh** [comment]
Why can't we have both?

![abstract forest](http://topwalls.net/wp-content/uploads/2012/05/abstract-forest-728x415.jpg)

http://topwalls.net/abstract-forest/

If you really wish to, you can easily incrustate the word 'sway' in the bottom left corner, on the cyan paint stroke.

(Getting back to work after a fulfilling involvement in bikeshedding :dancers: )

**Comment by SirCmpwn** [comment]
That'd be perfect, but waht license is it distributed under?

**Comment by StephenBrown2** [comment]
The bottom of the page linked has the text '© 2012 HD Wallpapers /', but no licensing details are available on the site.

**Comment by SirCmpwn** [comment]
We can't use it under those conditions, I'm afraid.

**Comment by coxley** [comment]
How about [this](http://jjuuhhaa.deviantart.com/art/Sway-Wallpaper-104965631)?

Some people in the thread reported using it in articles, I wonder if it could be as easy as asking for permission to distribute with a package.

**Comment by SirCmpwn** [comment]
I like that. Could work.

**Comment by juju2143** [comment]
I could definitely try to come up with a logo, that would be nice. I agree the default wallpaper could be a fancy, but simple gradient with the logo somewhere in there (when we come up with one) like many other WMs out there. It just works. Also you can definitely put several wallpapers to choose from in /usr/share/sway or something, if we have more than one default wallpaper.

**Comment by SirCmpwn** [comment]
I doubt we're going to be able to come up with several wallpapers. It'll be hard enough to get one wallpaper in several aspect ratios.

**Comment by the-duck** [comment]
![Wallpaper](https://cloud.githubusercontent.com/assets/4602269/11815549/778954d8-a34c-11e5-9349-4f4496194ab3.jpg)
Hi, it's my own image so there'll be no licensing problems with this wallpaper, if you like it of course :)

**Comment by DragonAxe** [comment]
I like coxley's and the-duck's pictures. (We might want to have a poll to see what picture everyone likes best.)

Why would there be a problem with aspect ratios? I might be missing something, but wouldn't having a large enough image would do the trick with a zoom to fit option in swaybg. After all, just take a look at the [wikipedia page on screen resolutions](https://en.wikipedia.org/wiki/Display_resolution) and all the different aspect ratios that we would need to converte our background to! But again, I might be missing something.

**Comment by SirCmpwn** [comment]
The issue with aspect ratios is that not all pictures look as good in portrait than in landscape.

**Comment by juju2143** [comment]
A good picture is one that would look good even cropped with the zoom to fit option.

**Comment by stephen304** [comment]
A gradient or solid color looks good in all aspect ratios ;)

I'm still for something like xfce's background.

**Comment by SirCmpwn** [comment]
Alright, new strategy. Everyone post your suggestions for wallpapers. They must be available under creative commons. After a few weeks, I will pick one.

**Comment by coxley** [comment]
These are my suggestions, but I am in favor of numbers 2 and 3:

[[1]](http://netzlemming.deviantart.com/art/Field-of-Barley-05240017-307176737?q=gallery%3ACreative-Commons%2F26171828&qo=26)
[[2]](http://pomprint.deviantart.com/art/Summer-in-Scotland-322104304?q=gallery%3ACreative-Commons%2F26171828&qo=52)
[[3]](http://pomprint.deviantart.com/art/A-Tree-for-Ms-C-318989576?q=gallery%3ACreative-Commons%2F26171828&qo=55)

Their resolutions are large enough to look great when filled/scaled on most landscape orientations. Could distribute either in their normal size or write something with imagemagick to target many resolutions exactly instead of using the scale function.

**Comment by StianTheDark** [comment]
I'll make one, but I'll need a couple of days. Just discovered this thread. Not an artist, but I love making minimalistic backgrounds.

**Comment by juju2143** [comment]
Well, that works.

**Comment by SirCmpwn** [comment]
I've reached out to a design I've worked with on other projects (notably [TrueCraft](https://github.com/SirCmpwn/TrueCraft)) to make a logo and default wallpaper for Sway. I expect the final version tomorrow and will be switching to it.

**Comment by mikkeloscar** [comment]
Awesome!

**Comment by coxley** [comment]
Very cool
