### ISSUE TITLE
Can set primary output/display?

### ISSUE THREAD

**Issue by StephenBrown2** [SirCmpwn/sway#242]
Is there an option to set the primary display, like I could with xrandr?
```
xrandr --output HDMI1 --mode 1680x1050 --pos 0x0 --rotate normal --output HDMI2 --primary --mode 1680x1050 --pos 1680x0 --rotate normal --output HDMI3 --mode 1680x1050 --pos 3360x0 --rotate normal
```
I see there's a 'primary' description here: https://github.com/SirCmpwn/sway/blob/f64b7e7/sway/ipc.c#L444
but there isn't any documentation saying I can, for example, write:
```
output HDMI1 resolution 1680x1050 position 0,0
output HDMI2 primary resolution 1680x1050 position 1680,0
output HDMI3 resolution 1680x1050 position 3360,0
```
in sway config?

**Comment by SirCmpwn** [comment]
There's no such thing as a primary display on Wayland.

**Comment by StephenBrown2** [comment]
Ah, derp. Well then, I wonder how swaybar will decide what output to be on... Probably an explicit setting, I'll bet.

**Comment by SirCmpwn** [comment]
Correct.

**Comment by StephenBrown2** [comment]
Excellent. This will serve for posterity, anyone else wanting to know some more differences between wayland and X output handling.

Thank you for your work!
