### ISSUE TITLE
Cannot turn off output

### ISSUE THREAD

**Issue by Manouchehri** [SirCmpwn/sway#246]
Disabling real displays doesn't work, and I get `{ "success": true }` for attempting to disable any output (regardless if it exists or not).

```
~ > i3-msg output fake-output disable
{ "success": true }
~ > i3-msg -t get_outputs
[ { "name": "LVDS-1", "active": true, "primary": false, "rect": { "x": 4652, "y": 0, "width": 1366, "height": 768 }, "current_workspace": "10" }, { "name": "HDMI-A-1", "active": true, "primary": false, "rect": { "x": 1366, "y": 0, "width": 1920, "height": 1080 }, "current_workspace": "2" } ]
~ > i3-msg output LVDS-1 disable
{ "success": true }
~ > i3-msg -t get_outputs
[ { "name": "LVDS-1", "active": true, "primary": false, "rect": { "x": 6018, "y": 0, "width": 1366, "height": 768 }, "current_workspace": "10" }, { "name": "HDMI-A-1", "active": true, "primary": false, "rect": { "x": 1366, "y": 0, "width": 1920, "height": 1080 }, "current_workspace": "2" } ]
```

**Comment by SirCmpwn** [comment]
Are you able to disable outputs from the config file rather than on the fly?

**Comment by Manouchehri** [comment]
What's the correct way of doing that? (I can't tell what parts of the man page are implemented or not.)

**Comment by SirCmpwn** [comment]
Everything in the man pages is implemented. Add this line to your config:

    output LVDS-1 disable

**Comment by Manouchehri** [comment]
sway-msg in mentioned in the man pages and doesn't exist. 

One second while I restart to try that.

**Comment by SirCmpwn** [comment]
Ah, well, everything on sway(5) is implemented.

**Comment by Manouchehri** [comment]
Putting it in the config file works (sort of). The screen is still physically on, but it's not being used (as intended).

**Comment by SirCmpwn** [comment]
I see. Well, will leave this issue open until it's sorted.

**Comment by Manouchehri** [comment]
Is `output LVDS-1 1366x768` the correct way to turn it back on?

LVDS-1 is gone from `get_outputs` when it's disabled via the config file (don't know if that's intended or not).

```
~ > i3-msg -t get_outputs
[ { "name": "HDMI-A-1", "active": true, "primary": false, "rect": { "x": 0, "y": 0, "width": 1920, "height": 1080 }, "current_workspace": "1" } ]
```

**Comment by SirCmpwn** [comment]
You can't enable/disable outputs on the fly. It has to be done through the config file. The way to turn it back on is to not turn it off in the first place.

**Comment by Manouchehri** [comment]
That would explain why I wasn't able to do it.

**Comment by Manouchehri** [comment]
So by extension, isn't hot-plugging also not supported?

**Comment by SirCmpwn** [comment]
Hotplugging works fine. The features are unrelated.

**Comment by Manouchehri** [comment]
I don't understand how they're unrelated; how does physically plugging in a screen differ from turning it back on via software?

**Comment by SirCmpwn** [comment]
Because sway is not a complete piece of software. The code to disable/enable on the fly through commands hasn't been written. It's not that it's impossible, it's that no one's done it yet.

**Comment by a0n** [comment]
> You can't enable/disable outputs on the fly. It has to be done through the config file. The way to turn it back on is to not turn it off in the first place.

This seems to be no issue now in the 1.0 beta.

I can disable and enable outputs via swaymsg without a problem.
