### ISSUE TITLE
Sway fails with zero log

### ISSUE THREAD

**Issue by fenque** [SirCmpwn/sway#262]
![1448542323](https://cloud.githubusercontent.com/assets/5204968/11423467/57086a36-944d-11e5-9e5a-e36aa1c9a234.png)
Gentoo 64bit

**Comment by SirCmpwn** [comment]
More details about your setup?

**Comment by fenque** [comment]
Latest versions of wlc and sway, under weston sway successfully launches wlc-x11 with no errors.
emerge --info log https://gist.github.com/fenque/b9738d15d4c055dcf2d1

**Comment by SirCmpwn** [comment]
Can you try compiling it manually? Without emerge?

**Comment by fenque** [comment]
Manually compiled version identical to the version that was installed with emerge.

**Comment by SirCmpwn** [comment]
Just to be clear, this is a seperate issue from the raspberry pi issue?

**Comment by fenque** [comment]
Yes, my problem does not appear in the egl problems.

**Comment by SirCmpwn** [comment]
Did you install wlc from source as well?

**Comment by fenque** [comment]
@SirCmpwn yes, same zero log as with version from package manager.

**Comment by SirCmpwn** [comment]
And sway -v produces no output, either? That's really the thing that gets me.

**Comment by fenque** [comment]
@SirCmpwn build from source gave progress, sway now successfully runs under X11 with the log no errors, but tty still return nothing

**Comment by SirCmpwn** [comment]
Even with -d from the tty?

**Comment by fenque** [comment]
@SirCmpwn Yes, any parameter that I pass sway returns nothing. After reboot sway again now works in x11.

**Comment by SirCmpwn** [comment]
That's quite strange. I don't know where to go from here if there are no logs that hint at what could be wrong. You may have to debug this one yourself. I guess the other thing that it could be - are you using the nvidia proprietary driver?

**Comment by fenque** [comment]
@SirCmpwn i use latest nouveau.

**Comment by SirCmpwn** [comment]
Then I'm out of ideas, @fenque. Good luck, you're on your own here.

**Comment by fenque** [comment]
Hmm, if i run file directly (like ./sway -v), it prints version, progress...

**Comment by mikkeloscar** [comment]
Have you tried to run `strace sway` that might give you some information?

**Comment by fenque** [comment]
@mikkeloscar with this https://gist.github.com/fenque/47a53f945efba701666b script from weston build instruction, sway successful starts from x11, in gentoo variable XDG_RUNTIME_DIR not set, so sway fails. And log from tty strace https://gist.github.com/fenque/3a1ef60422d0926b6131

**Comment by sce** [comment]
I'm pretty sure it fails here: https://github.com/Cloudef/wlc/blob/3b836aad5e6a281f78fb78c36d83be4857822334/src/wlc.c#L308-L309

That message is supposed to be logged by sway (the log handler is already set), so I'm not sure why it doesn't show up, maybe it needs to be flushed first (so that wlc doesn't quit before sway gets a chance to write the die-message to the log).

**Comment by mikkeloscar** [comment]
@fenque if you are running sway from a tty you might wanna do something like `sway -d 2> ~/sway.log` to capture the sway log output.

**Comment by fenque** [comment]
@mikkeloscar i tried it many times, no log at all.

**Comment by sce** [comment]
Ah, while the wlc log handler is set I now realize that of course the log for sway hasn't been initialized yet: https://github.com/SirCmpwn/sway/blob/master/sway/main.c#L127 (it happens after `wlc_init` which is the one that fails). That's why there's no log.

**Comment by SirCmpwn** [comment]
suid the sway executable to root.

**Comment by fenque** [comment]
It already root.

**Comment by SirCmpwn** [comment]
sudo chmod a+s /usr/bin/sway

**Comment by fenque** [comment]
Still failing.

**Comment by SirCmpwn** [comment]
New strace and logs, please, with a+s set.

**Comment by SirCmpwn** [comment]
Also, just merged a PR that improves logging in this scenario, so please rebuild sway.

**Comment by fenque** [comment]
@SirCmpwn https://gist.github.com/fenque/f5f28f6bece659c56917 stray log
sway log:
```
[wlc] Not running from X11 and no access to /dev/input/event0 or logind available

```

**Comment by SirCmpwn** [comment]
Hmm. `/dev/input/event0` exists, right? Paging @Cloudef

**Comment by fenque** [comment]
@SirCmpwn i'll try adding myself to input group.
![1448807019](https://cloud.githubusercontent.com/assets/5204968/11457592/98745b14-96b5-11e5-84b7-c9de4c52ca50.png)

**Comment by SirCmpwn** [comment]
Well, suid should let you read it. The sway binary is owned by root, too?

**Comment by fenque** [comment]
Finally works, but need script to create XDG_RUNTIME_DIR and do ```sudo chmod a+s /usr/bin/sway``` after every build, thanks all. Maybe we should mention this in the faq?

**Comment by SirCmpwn** [comment]
afaik you shouldn't have to create XDG_RUNTIME_DIR so long as the binary is a+s. We can probably add this as a build step somehow, detect if logind is present and chmod after install.
