### ISSUE TITLE
Hardcoded /etc path

### ISSUE THREAD

**Issue by gpyh** [SirCmpwn/sway#280]
I am currently packaging sway for the NixOS distribution.
It manages configurations in a special way, preventing the user from writing in /etc in order to preserve a clean system.
In order to build sway on this distro, I had to patch CMakeLists to add a "DETCDIR" flag.
Therefore, a new /etc destination can be given at compile time (in my case, I give the one the distro wants in order to build sanely).

I would like to propose this change to be made upstream. Although it is quite rare to break the /etc convention, it is common for CMakeLists to expose such a parameter.

**Comment by SirCmpwn** [comment]
I would merge a PR that makes the path customizable.

**Comment by gpyh** [comment]
Be right back then.
