### ISSUE TITLE
Support for more image formats for wallpapers

### ISSUE THREAD

**Issue by aouelete** [SirCmpwn/sway#282]
Currently only .png's are supported because of [this](https://github.com/SirCmpwn/sway/blob/master/swaybg/main.c#L59). It would be nice to be able to use .jpg's for wallpapers, but I don't know enough about this code to implement it.

**Comment by SirCmpwn** [comment]
Probably involves using MagickWand or something. Or we could just straight up add support for more kinds of images.

**Comment by algmyr** [comment]
Cairo has support to create surfaces from pixel data, see cairo_image_surface_create_for_data(): http://cairographics.org/manual/cairo-Image-Surfaces.html

So adding other formats shouldn't be harder than to use some library to convert images to byte data. ImageMagick libs would probably be a great candidate considering the wide array of formats it supports.

**Comment by progandy** [comment]
The most common solution is to use librsvg for svg images. With that you already pull gdk-pixbuf2, so use that to load other formats. My installation supports ani, bmp, gif, icns, ico, jasper (jpeg-2000), jpeg, pnm, qtif, tga, tiff, xbm, and xpm

**Comment by SirCmpwn** [comment]
#296 has been merged.
