### ISSUE TITLE
Can't set a .jpg background

### ISSUE THREAD

**Issue by zetok** [SirCmpwn/sway#299]
sway 266393a705ce2b6db982a4bd048bb536ec556a85

I've tried with different sized jpg and png images, png ones always worked, while jpg ones never worked.

**Comment by aouelete** [comment]
I just tested this and was able to use both jpg's and png's for the wallpaper.
One thing that I have noticed is that I am unable to change the background on the fly, once I set it in the config file, I can't change it.

**Comment by SirCmpwn** [comment]
> One thing that I have noticed is that I am unable to change the background on the fly, once I set it in the config file, I can't change it.

Unrelated, known problem.

**Comment by zetok** [comment]
Actually, not a sway bug. Since gdk-pixbuf is used for images, it needed to be recompiled with `+jpeg` USE flag.
