### ISSUE TITLE
Unable to access menus, flickering while trying to open

### ISSUE THREAD

**Issue by soredake** [SirCmpwn/sway#301]
https://u.pomf.io/vnmsmb.mp4
https://u.pomf.io/ngchfe.mp4
https://u.pomf.io/mutdqv.mp4
https://u.pomf.io/hmkkyd.mp4

**Comment by SirCmpwn** [comment]
Are you up to date on everything? In particular, make sure you're up to date on both wlc and sway.

**Comment by fenque** [comment]
Yes, all system is up to date.

**Comment by SirCmpwn** [comment]
Could you humour me by recompiling wlc? This was a known bug that was fixed in https://github.com/Cloudef/wlc/commit/359cfe776a17a0fae5f8179e8a89e9b47256f602

**Comment by fenque** [comment]
I recorded this videos after recompiling, so...

**Comment by SirCmpwn** [comment]
Recompiling sway or wlc? What distro are you on?

**Comment by fenque** [comment]
Yes, i recompile sway, wlc, and packages on which they depend after seeing a bug. Gentoo unstable.

**Comment by SirCmpwn** [comment]
Which version of xwayland?

**Comment by fenque** [comment]
1.17.4

**Comment by SirCmpwn** [comment]
Can you try 1.18.0?

**Comment by fenque** [comment]
Still flickering with 1.18.0.

**Comment by SirCmpwn** [comment]
Strange. I can't reproduce. You're on your own here.

**Comment by joecool1029** [comment]
I've had this issue for some weeks.  Chromium generates it easy enough, just hover over any tabs and you'll get flickering when it fails to display the tooltip (hover-over text).

**Comment by fgaz** [comment]
Same here on every qt5 program. The menu either flickers or opens as a new window until I move the cursor.
I just recompiled wlc and sway.

**Comment by SirCmpwn** [comment]
Unmanaged windows are pretty buggy in sway. I think they're the source of this and other problems.

**Comment by fgaz** [comment]
I just installed orbment and the same thing happens. It's probably wlc.

**Comment by SirCmpwn** [comment]
My current understanding of the issue is that the fault is shared between all three.
