### ISSUE TITLE
Handle changes in output resolution from clients

### ISSUE THREAD

**Issue by fluxchief** [SirCmpwn/sway#306]
Running sway in x11, initial resolution is the sum of my two monitors but is resized to only one:

    [main.c:35] [wlc] Activating tty
    [main.c:35] [wlc] WLC-1 Chose mode (0) 3360x1050
    [handlers.c:118] Output 1 resolution changed to 3360 x 1050
    ...
    [main.c:35] [wlc] Added output (1)
    [main.c:35] [wlc] become active
    [handlers.c:118] Output 1 resolution changed to 1676 x 1011
    ...

However, swaybar gets different values (modifications in swaybar main.c):

    ...
    struct output_state *output = registry->outputs->items[desired_output];
    sway_log(L_INFO, "Detected output size: %dx%d", output->width, output->height);

Output:

    [main.c:245] Using output 0 of 1
    [main.c:248] Detected output size: 3360x1050
    [main.c:155] Running on output WLC-1

Expected output: 'Detected output size: 1676x1011'

**Comment by fluxchief** [comment]
I tried to figure out where the problem lies and added logging to the wayland registry display callbacks.
The output is

[registry.c:29] display_handle_geometry x=0 y=0 phy_w=0 phy_h=0 spx=0 make=Xorg model=X11 Window t:0
    [registry.c:17] display_handle_mode flags=3 w=3360 h=1050 r=60000

The display_handle_geometry won't be called even if the resolution changes.
A quick look at the wlc sources showed that they also suscribe to x11 events, I guess we're not receiving any callbacks for this type of event.

**Comment by mikkeloscar** [comment]
I believe this was fixed as part of Cloudef/wlc@2cf560cf.
