### ISSUE TITLE
Wayland cursor theme?

### ISSUE THREAD

**Issue by qubidt** [SirCmpwn/sway#330]
Should sway/wayland be respecting the cursor theme from ~/.icons/default/index.theme? It doesn't seem to be using the default Adwaita cursor. The solid black block arrow it's using must be a default.

Am I missing something?

**Comment by SirCmpwn** [comment]
Wayland uses client-side cursors, meaning that the wayland clients define the appearance of the cursor. Yes, it's stupid. No, there's nothing sway can do about it.

**Comment by SirCmpwn** [comment]
That being said, the cursor over xwayland windows being wrong is a bug in wlc. https://github.com/Cloudef/wlc/issues/21

**Comment by qubidt** [comment]
Gotcha. Thanks a lot. Still getting used to how wayland works.

**Comment by mikkeloscar** [comment]
What about the cursor you get when you don't have any windows open? It seems like weston uses [`wl_cursor`](http://cgit.freedesktop.org/wayland/weston/tree/clients/window.c?id=ac3e5f2feb99ac0fad18461975a0b105cb8dab2d#n647) to load a cursor theme and use that for non-client interaction. It even supports the location mentioned by OP.

Is there any reason why this wouldn't work in sway (excepts it's not currently implemented in wlc)?

This would give us a mostly consistent cursor theme assuming the toolkits like QT and GTK use the same method for loading a theme (which I think they do).

**Comment by SirCmpwn** [comment]
The cursor is actually set like that for swaybg, but the way that swaybg is rendered by sway means that the cursor doesn't show up. It's in the back of my mind to deal with that sometime.

**Comment by mikkeloscar** [comment]
It would be cool if (at some point) it would be possible to draw the cursor on top of windows, for instance when dragging and resizing, such that the cursor shape could match the action. :). Wouldn't really work through swaybg though.
