### ISSUE TITLE
[Feature Suggestion] Implement easier scriptability?

### ISSUE THREAD

**Issue by steelcowboy** [SirCmpwn/sway#342]
I honestly 100% am not asking for this, as it may be a little counter to the goal of sway. However, the last wm I used before i3 was bspwm, which had the excellent advantage of everything being configured by bash scripts. Just a thought, but what if there were a way to implement a bit of scripting into sway's configuration, so you could have a bit of logic in the config file? (Like choose different colors for things such as i3bar based on the time of day). Get the power of i3 with the flexibility of bspwm, and have backwards compatibility with i3's config.

**Comment by SirCmpwn** [comment]
You can configure sway from a bash script using `swaymsg`. This doesn't let you configure everything, but I'll merge pull requests that add more things for you to configure with it.
