### ISSUE TITLE
swaybar high cpu

### ISSUE THREAD

**Issue by crondog** [SirCmpwn/sway#345]
Running the default swaybar command results in high cpu usage. Also exiting sway doesnt kill the bar...

**Comment by SirCmpwn** [comment]
Split the second problem into #346

**Comment by SirCmpwn** [comment]
CPU usage is still a bit high, paging @Cloudef for advice.

**Comment by SirCmpwn** [comment]
Our pre-render is here: https://github.com/SirCmpwn/sway/blob/master/sway/handlers.c#L74-L115

**Comment by Cloudef** [comment]
Is the high cpu usage in sway or the swaybar? Using tool like `perf` can find time consuming function easily. Using tool like `perf` can find time consuming function easily.

**Comment by SirCmpwn** [comment]
@Cloudef it's sway that's sitting at high CPU. I'll run it through perf later today, looping you in because I suspect wlc's the culprit.

**Comment by Cloudef** [comment]
It probably is, if that's the case. WLC_DEBUG=render,render-loop,commit is useful here. If swaybar is not constantly requesting new content to be rendered the issue is in wlc.

**Comment by SirCmpwn** [comment]
swaybar was constantly requesting a rerender, but I fixed it so it only does so if it needs to change its appearance. Now it's requesting a rerender about once a second with the default config.

**Comment by mikkeloscar** [comment]
I'm pretty sure the problem is that the `dirty` variable is never set to false, so it will render non stop. I will try to handle this tomorrow if no one beats me to it.
