### ISSUE TITLE
swaybar doesn't handle new configuration at runtime.

### ISSUE THREAD

**Issue by mikkeloscar** [SirCmpwn/sway#347]
If you edit the config and reload it while sway is running the bar doesn't update with the new bar configuration.

**Comment by SirCmpwn** [comment]
Related - you can't change your wallpaper at runtime. We need to kill and restart the sway subprocesses.

**Comment by mikkeloscar** [comment]
If we store the pids of swaybar and swaybg somewhere then it would be easy to kill and restart them on reload. My idea would be to store them in an output container since each swaybg/swaybar process *"belong"* to a single output as far as I can tell. What do you think of this approach?

**Comment by SirCmpwn** [comment]
I like that approach.

**Comment by mikkeloscar** [comment]
Ok, cool, I will try to work on that tomorrow then.

**Comment by mikkeloscar** [comment]
Fixed in #358
