### ISSUE TITLE
ipc_event_workspace not triggered in all cases.

### ISSUE THREAD

**Issue by mikkeloscar** [SirCmpwn/sway#382]
`ipc_event_workspace` is not triggered in the following situation resulting in the bar not being updated.

* open sway
* spawn 2 (or more) windows on workspace one
* move one of the windows to workspace two (e.g. `$mod+Shift+2`)

The window is moved but the `ipc_event_workspace` is not triggered and the bar only shows one workspace button.

**Comment by crondog** [comment]
I have a solution to this but I don't think it is correct. Adding ipc_event_workspace(container, destination); at the end of move_container_to() gets the update happening.

**Comment by SirCmpwn** [comment]
That solution is the correct one.

**Comment by mikkeloscar** [comment]
Except the event might be triggered twice for some operations, since it is triggered in `set_focused_container()` in most cases.

**Comment by SirCmpwn** [comment]
It's okay to trigger it twice IMO.
