### ISSUE TITLE
swaybar font name

### ISSUE THREAD

**Issue by crondog** [SirCmpwn/sway#385]
If you just have `bar{}` in your config, swaybar crashes since there is code which checks for "pango:", yet the default font is "monospace 10"

Should we change the default font to "pango:monospace 10" or change swaybar to not check for "pango:". I think pango can deal with fonts starting with "pango:" so that check might not be needed...

**Comment by SirCmpwn** [comment]
Fixed by fc71c6303ca10b59c8f64e752307b0dd26832b52.
