### ISSUE TITLE
swaygrab: -- makes getopt stop parsing arguments

### ISSUE THREAD

**Issue by juju2143** [SirCmpwn/sway#397]
Once `getopt()` encounters `--` on the command line it stops parsing arguments and sends the rest in the filename variable. In `swaygrab`, it have the side effect that all remaining arguments are passed to `convert` or `ffmpeg`, so you can do stuff like, for instance, streaming directly to Twitch.tv or something like that (although right now you have to enclose everything after `--` in quotes). If you don't want that, it would probably a good idea to use libmagick and/or libffmpeg instead of directly calling the binaries, otherwise, that would be a nice thing to put in the man page (the quotes thing would probably be a bug, though).

**Comment by SirCmpwn** [comment]
If you want to change how imagemagick/ffmpeg are invoked, use raw mode (presently unimplemented).
