### ISSUE TITLE
Unexpected input events crash sway

### ISSUE THREAD

**Issue by vikstrous** [SirCmpwn/sway#411]
I have a touchscreen monitor. I ran sway from a TTY. i3lock activated after a while. By tapping the screen I crashed sway and it left me at a logged in shell. This is a security issue. Unexpected input should never crash sway. There are a lot of switch statements without default cases in `sway/input_state.c`, so I suspect that that's the issue. All of those should fail gracefully.

**Comment by robotanarchy** [comment]
about the logged in shell, consider locking it with vlock after starting sway.

**Comment by SirCmpwn** [comment]
#203
