### ISSUE TITLE
If i3lock activates while a different TTY is selected, it doesn't hide the screen

### ISSUE THREAD

**Issue by vikstrous** [SirCmpwn/sway#412]
If i3lock activates while a different TTY is selected, it doesn't get drawn on top of everything. It does steal input, so anything you type goes to i3lock, but the current window is drawn and if you mouse over other windows, they are drawn too.

**Comment by SirCmpwn** [comment]
i3lock or swaylock?

**Comment by vikstrous** [comment]
This is i3lock. I have xautolock set up to activate i3lock after 5 minutes of inactivity.

I tried swaylock and it didn't even work when run from within a sway session on the command line. It crashed with:

```
(process:3574): GdkPixbuf-CRITICAL **: gdk_pixbuf_new_from_file: assertion 'filename != NULL' failed
ERROR: Failed to load background image.
```

**Comment by SirCmpwn** [comment]
i3lock isn't supported on sway and swaylock doesn't work yet.
