### ISSUE TITLE
swaylock: proxy already has listener

### ISSUE THREAD

**Issue by ghost** [SirCmpwn/sway#413]
The exact error is this:

`proxy 0x1a1e050 already has listener`
`Error: Signal 11. Printing backtrace`
`Backtrace: swaylock(error_handler+0x2f) [0x40448f]`
`Backtrace: /usr/lib/libc.so.6(+0x33680) [0x7f958d119680]`
`Backtrace: swaylock(main+0x140) [0x4036b0]`
`Backtrace: /usr/lib/libc.so.6(__libc_start_main+0xf0) [0x7f958d106610]`
`Backtrace: swaylock(_start+0x29) [0x403c19]`

when running `swaylock wallpaper.jpg` from a terminal. The proxy changes every time, but the rest seems not to change.

**Comment by SirCmpwn** [comment]
Still an issue? Run swaylock -i wallpaper.jpg.

**Comment by mikkeloscar** [comment]
@SirCmpwn I'm positive you fixed this in baa958ea, so I'm gonna close this issue.
