### ISSUE TITLE
When I `killall sway` swaybar is left running and eating 100% CPU

### ISSUE THREAD

**Issue by vikstrous** [SirCmpwn/sway#416]
Steps to reproduce:

1. start sway in a new tty
2. open a terminal and run `killall sway`
3. run top, htop or whatever. swaybar is still alive and using 100% CPU

I was using i3bar with sway, so that may be related. I haven't tried it with an empty config.

**Comment by SirCmpwn** [comment]
How recently did you update sway? How were you using i3bar?

**Comment by vikstrous** [comment]
Sorry, I meant i3status.

sway --version
sway version 33a74bf (2015-12-27, branch "master")

**Comment by SirCmpwn** [comment]
Thanks. Will look into it when possible.

**Comment by mikkeloscar** [comment]
This is because `sway` currently doesn't handle a `SIGTERM` signal and gracefully shuts down.
