### ISSUE TITLE
Sway fails to build on Arch Linux

### ISSUE THREAD

**Issue by archfan** [SirCmpwn/sway#420]
As of right now Sway does not compile on Arch with the PKGBUILD provided on AUR.

https://aur.archlinux.org/packages/sway-git/

More details here:
http://pastebin.com/qyuPLHcD

**Comment by SirCmpwn** [comment]
Update wlc-git.

**Comment by Kaligule** [comment]
While I don't know @archfan s setup, I can confirm sway from AUR does compile and run on arch linux (tested right now).

**Comment by archfan** [comment]
Yup, compiling works fine now after updating the wlc libraries.

**Comment by Kaligule** [comment]
:)
