### ISSUE TITLE
Output * resolution doesn't set the monitor resolution

### ISSUE THREAD

**Issue by chetanpm** [SirCmpwn/sway#423]
swaymsg -t get_outputs : lists the device as VGA-1, active and set to 1024x768

Edit in the config file to- "output VGA-1 resolution 1280x1024 position 1280,0" seem to not change the display resolution. 

I also found that- if the output *bg line is commented out and then edit the output line to- "output VGA-1 resolution 1280x1024 position 1280,0 bg ~/Ferrari.jpg fill", the background image stops showing after reload.

Also: "output * res 1280x1024 pos 1280,0" don't work for me.

**Comment by SirCmpwn** [comment]
`output *` not setting the resolution or position is intentional because it doesn't make sense.

As for the rest, what's the output of `swaymsg -t get_outputs`? You have to restart sway for output settings to take effect, by the way.

**Comment by chetanpm** [comment]
[ { "name": "VGA-1", "active": true, "primary": false, "rect": { "x": 0, "y":0, "width":1024, "height":768 }, "current_workspace": "1" } ]

**Comment by SirCmpwn** [comment]
Thanks. And you tried editing your config, stopping, and restarting sway? If so, please provide a [sway log](https://github.com/SirCmpwn/sway/wiki#enable-logging).

**Comment by chetanpm** [comment]
Here's the log: https://clbin.com/nz7FR
The bg image error, it is showing for other pictures as well.(should there be any specific package to process images to make them suitable for wallpaper?

still WLC chose mode (0)

**Comment by SirCmpwn** [comment]
`ls -l ~/Cars/Ferrari_458\Italia.jpg`

If there's any error in the output line, the whole thing will not be applied.

**Comment by chetanpm** [comment]
Taking the background off, Can you make an inference from this log: https://clbin.com/TSlto

The text on screen are smaller-like they should be.
Bullet 2 monitor resolution still stuck on 1024x768, 85hz. 
Bullet 2 swayer is only up to 3/4th the width of display. The remaining area allows mouse pointer but unclickable(checked with chrome)

Can't we list all the modes supported by the monitor first and then choose one from there. Because my monitor has 1024x768 85hz, 1156x956 75hz, 1280x1024 60hz,.... and so on.

**Comment by SirCmpwn** [comment]
The output you get here is WLC-1. You're running sway under xorg, not directly.

    New output 1:WLC-1

Of course your VGA-1 settings won't work here.

**Comment by chetanpm** [comment]
I am running it directly from tty. I don't even have xorg package installed.
Fresh install wayland and its dependencies only.

**Comment by SirCmpwn** [comment]
The log you gave me is sway running under x.

**Comment by chetanpm** [comment]
Is there any suggestion of where to look, because I rechecked- I got no xorg installed, no display managers. I boot into tty and run sway from there. Can't understand why does it invoke New output 1..

**Comment by SirCmpwn** [comment]
Running sway within sway will run it with xwayland and cause this.

**Comment by chetanpm** [comment]
which I am definitely not doing.
The log says something about a lock file and another compositor running thing in the first line. should I delete that file??: https://clbin.com/TSlto

**Comment by SirCmpwn** [comment]
I have no idea what you're doing, but you aren't telling the whole story. Give me more details about what you're doing. Exhaustive detail.

**Comment by chetanpm** [comment]
Alright:
# I was hoping to build a usable DE on the modern standards. The resolution is defaulting to low output,
# I am more fixated now on knowing how is the issue fixed.

I have a fresh arch installation, with just base packages.
I then got wayland, sway-git and it dependencies and (dmenu, and chromium).
I always boot to tty and then start sway. Now to rice it the way I want, starts configuring.

My desktop monitor is a CRT. Unlike LCDs it has default resolution 1024x768 85hz, but capable of 1280x1024 60hz. The first thing I do after an os installation is to increase resolution, so that everything look not gigantic.
I am following each step, and as the culture of work in progress, am just curious about how to fix this. Maybe framework is too modern to support the vintage 2006 CRT, am curious.

**Comment by SirCmpwn** [comment]
>Unlike LCDs it has default resolution 1024x768 85hz, but capable of 1280x1024 60hz.

Here's the issue. WLC (which sway uses for low level things) does not support modesetting. You can only use the default mode, and then scale the interface *up* to meet it (useful for HiDPI, for example). Anyway, this is a wlc issue, roping in @Cloudef and closing this issue.

**Comment by FreeFull** [comment]
You might be able to change the screen resolution before you launch sway, using fbset

**Comment by chetanpm** [comment]
@FreeFull: It looks like the feature needs to be added and enabled through DRM protocol- http://goo.gl/uLyXTK
