### ISSUE TITLE
Double escape character in config

### ISSUE THREAD

**Issue by dotlambda** [SirCmpwn/sway#426]
I'd like to do something like
```sh
set $bg #101b2a
set $fg #dcdccc
set $dmenu dmenu -fn ProFont-11 -nb \\$bg -nf \\$fg -sb \\$fg -sf \\$bg
set $menu j4-dmenu-desktop --dmenu="$dmenu" --term="$term"
```
But sway won't let me double escape a variable.

**Comment by mikkeloscar** [comment]
What is this supposed to achieve?

**Comment by dotlambda** [comment]
I want to run `j4-desktop-menu` calling `dmenu` (corrected from dmenu_run) with the specified colors that I also use in other places in the config.
I think I made it work:
```sh
set $dmenu 'dmenu -fn ProFont-11 -nb "$bg" -nf "$fg" -sb "$fg" -sf "$bg"'
set $menu j4-dmenu-desktop --dmenu=$dmenu --term=urxvt
```
But having a possibility to write a single backslash in front of a variable would still be nice:
```sh
set $color #ffffff
set $menu dmenu -nf \\$bar
```
should result in $menu containing `dmenu -nf \#ffffff` (without the backslash the `#` indicates a comment I guess)
