### ISSUE TITLE
opening window when another window is in fullscreen

### ISSUE THREAD

**Issue by Kaligule** [SirCmpwn/sway#431]
When there is a window in fullscreen and another one is created (for example bz pressing mod+enter), there is nothing to see (No problem here until here).
When exiting the fullscreen window (mod+f), suddenly the other window is in fullscreen. When leaving this fullscreen (mod+f again), the first window goes up in fullscreen, again.

So it is not really possible to directly leave fullscreenmode, only by moving a window to another workspace or quiting it.
This is reproducible on sway version f69d765 (2016-01-02, branch "master") on Arch linux.

**Comment by crondog** [comment]
Ok I can reproduce your issue. When you have term1 opened in fullscreen mode, then open term2 it gets put behind term1, however term2 has focus. This means that when you press mod+f it is fullscreening term2.

Not sure what the best way to handle this situation is. I tested this in i3 and found that if i have a fullscreen term, I am unable to spawn a new term. I don't really agree with that.

Two alternatives that I can see are: If in fullscreen mode, make the new view have fullscreen or if in fullscreen return focus to the original fullscreen view.

**Comment by SirCmpwn** [comment]
>return focus to the original fullscreen view

this

**Comment by StephenBrown2** [comment]
Should this also make the spawned window "urgent" (or would it do that naturally), so that one knows a new window hasn't been lost when in fullscreen mode?

**Comment by SirCmpwn** [comment]
Wayland has no concept of urgency so I want to hold off on all related features for now.

**Comment by Kaligule** [comment]
> I tested this in i3 and found that if i have a fullscreen term, I am unable to spawn a new term.

Thats doesn't hold for my setup (Arch Linux, i3 version 4.11). When I'm in fullscreen and I open a new term, it is opened in the background and the fullscreen window persists.

The commit #433 solved that issue for me by implementing the exact same bahaviour. Thanks a lot.
