### ISSUE TITLE
A brief list of things that bother me about using sway.

### ISSUE THREAD

**Issue by that1communist** [SirCmpwn/sway#447]
1. No way to swap keys... I had super and capslock swapped, so when i push the traditional capslock, it would do super, nad when i do the traditional super, it'd enable capslock.

2. No borders (obviously being fixed)

3. In resize mode, it acts as though there is no keyboard repeat.

4. Chromium & mousepad (probably applies to other X.org things) stops working after a bit, sometimes vanishes after you use it for a bit, and vanishes if you switch workspaces occasionally.

5. No system tray icons.

6. No way to edit the repeat rate.

When these things are fixed i'm switching fulltime, I looked around and didn't see anything about any of these. Although I should probably make seperate issues for them.

**Comment by SirCmpwn** [comment]
>No way to swap keys... I had super and capslock swapped, so when i push the traditional capslock, it would do super, nad when i do the traditional super, it'd enable capslock.

Not true, look into configuring your xkb settings properly.

>No borders (obviously being fixed)

Yep.

>In resize mode, it acts as though there is no keyboard repeat.

https://github.com/Cloudef/wlc/pull/107

>Chromium & mousepad (probably applies to other X.org things) stops working after a bit, sometimes vanishes after you use it for a bit, and vanishes if you switch workspaces occasionally.

Report as a separate bug.

>No system tray icons.

Will be fixed, have patience.

>No way to edit the repeat rate.

Bring it up with wlc.

**Comment by mikkeloscar** [comment]
> No way to edit the repeat rate.

I haven't tried myself, but wlc has `WLC_REPEAT_RATE` see [readme](https://github.com/mikkeloscar/wlc#env-variables).
