### ISSUE TITLE
Compositor Effects

### ISSUE THREAD

**Issue by VadikLeshy** [SirCmpwn/sway#453]
What about some smart effects like blur and fading? On Wayland it is compositors work isn't it?

**Comment by SirCmpwn** [comment]
Yeah, that's the compositor's responsibility. It's about the same priority for sway as adding Windows support.

**Comment by WillPower3309** [comment]
[swayfx](https://www.github.com/willpower3309/swayfx) currently has rounded corners and shadows, as well as dimming. Although, blur is currently in a draft PR, so it will be merged soon. Fade animations will be next!
