### ISSUE TITLE
SWAYSOCK not set inside xwayland

### ISSUE THREAD

**Issue by crondog** [SirCmpwn/sway#460]
This means that `sway --get-socketpath` returns "sway socket not detected" 

It is not too much of an issue but more of an inconvenience.

**Comment by SirCmpwn** [comment]
Can you elaborate? It's set so far as I can tell.

**Comment by crondog** [comment]
So inside sway if I open termite (native wayland) and run swaymsg i get `{ success : true}`. If i use st (xwayland) and run swaymsg I get `sway no socket detected`

**Comment by SirCmpwn** [comment]
Interesting. I cannot reproduce.

**Comment by crondog** [comment]
I thought it might have been because I have xorg in tty1 but I tried just with sway and no xorg running at all and it still happens.

**Comment by crondog** [comment]
Ok I know how to reproduce.

Open sway spawn a terminal with tmux: st -e tmux
Exit sway without closing st. Just mod+shift+e
Check the processes. You should see tmux still running.
Run sway again.
Open terminal
Run swaymsg and it wont work

**Comment by SirCmpwn** [comment]
Okay if you reattach to a tmux that was created with an older SWAYSOCK then of course it's not going to work.

**Comment by crondog** [comment]
Hmm I would have thought that tmux would have been killed when I exit sway.

**Comment by SirCmpwn** [comment]
The entire purpose of tmux is to do the opposite.

**Comment by FreeFull** [comment]
You can set which variables tmux grabs from its environment when it's attached in a terminal using the `update-environment` option. By default it's set to copy over some environment variables relating to Xorg.
