### ISSUE TITLE
bind apps to the specific workspace

### ISSUE THREAD

**Issue by i7otep9wka** [SirCmpwn/sway#462]
Hello! 
I tried to use : "workspace 1; exec /usr/bin/app_to_start" as in the i3, but no result. If there is no mistake above, please add the function of binding specific apps to  workspaces. Thx.

**Comment by SirCmpwn** [comment]
Blocked by the lack of a means to get the pid of the client given a wlc_handle. cc @Cloudef

**Comment by Cloudef** [comment]
I'll add wlc_view_get_client to wlc-wayland.h, you can then use wl_client* functions from "wayland-server-core.h" which includes wl_client_get_credentials.

**Comment by SirCmpwn** [comment]
Sounds good to me, @Cloudef.

**Comment by SirCmpwn** [comment]
wlc has support for this, so now we should be able to track pids of windows that we open and assign them to the workspace that was visible when they were invoked.
