### ISSUE TITLE
Strip backslashes in get_inputs

### ISSUE THREAD

**Issue by mikkeloscar** [SirCmpwn/sway#468]
They don't seem to be needed so they will only confuse users: https://github.com/SirCmpwn/sway/issues/365#issuecomment-174241434

**Comment by colemickens** [comment]
The slashes are added because the output format is JSON. swaymsg could decode the json rather than just printing it out.

**Comment by mikkeloscar** [comment]
Ok, one has to wonder why the hell slashes can be escaped in JSON.

**Comment by algmyr** [comment]
json-c added a flag to disable escaping of slashes a while back: 316da8581819726597592be6d8ac787120c979bf

It could prove helpful here.

**Comment by mikkeloscar** [comment]
Yeah I saw that as well, but we will have to wait for a new json-c release before we can use it.
A quick hack would be to just remove the slash escaping from the json string printed by swaymsg.

**Comment by SirCmpwn** [comment]
See https://github.com/SirCmpwn/sway/pull/472 for details on why this was closed.
