### ISSUE TITLE
sway crashes when trying to display scratchpad while it is being displayed on other workspace

### ISSUE THREAD

**Issue by TehMillhouse** [SirCmpwn/sway#469]
I'm running an up-to-date x86_64 Arch Linux with sway version 2597321 (2016-01-16, branch "master").

The following steps reproduce the crash reliably on my machine:
* move a window into the scratchpad
* show the scratchpad
* switch to a different workspace
* show the scratchpad

**Comment by SirCmpwn** [comment]
I can reproduce this.
