### ISSUE TITLE
Focus issues with unmanaged views and xwayland views

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/sway#47]
Some weirdness is going on. One is easy to reproduce:

1. Open firefox
2. Type in a URL

It will behave quite strangely. I think this is because of unmanaged views getting focus automatically, but  we probably shouldn't do that. Let's see if dmenu freaks out without it.

**Comment by taiyu-len** [comment]
getting rid of handler.c line 100 seems to work.
`wlc_view_focus(handle);`

**Comment by SirCmpwn** [comment]
I figured as much, but I wanted to see if dmenu would still work with that removed.

**Comment by taiyu-len** [comment]
im guna try to move the wlc stuff from new_view into the handler,
and then try to handle it by its type.
i think i got it figured out.

**Comment by SirCmpwn** [comment]
Alright.
