### ISSUE TITLE
Smart_hide mode for swaybar

### ISSUE THREAD

**Issue by DerpyCrabs** [SirCmpwn/sway#470]
Can you add smart_hide mode when swaybar is visible only if there is any window on a current workspace? 
It is useful if your conky have all information from i3status and you use empty workspace like lockscreen just to hide windows from others.

**Comment by SirCmpwn** [comment]
Haha, just use swaylock when it's done to lock your screen. That's not a bad idea for a feature, though.

**Comment by DerpyCrabs** [comment]
I use empty workspace as lockscreen in order to always see information from conky (like time, current track, battery level). I used my python script to hide i3bar on i3. I will be happy if i don't need this hack.

**Comment by ke7ofi** [comment]
Would it be practical to have swaylock just literally lock the screen in its current state (`--transparent`?), requiring a password before accepting more input? This would allow the use of conky, a webpage in a browser, a video, whatever, as a “lock screen”.

**Comment by SirCmpwn** [comment]
I think it's entirely fair for swaylock to support transparency in the --color argument, so you could specify a completely transparent color to achieve that effect. Could also use semitransparent images as the background image.

**Comment by ke7ofi** [comment]
:+1: for the general idea, but maybe make that the default sub-arg to --color? I'm not sure how to make it comply with the standard RGB notation.

**Comment by SirCmpwn** [comment]
`swaylock --color #00000000` - transparent black

`swaylock --color #000000` - solid black

`swaylock --color #FF000000` - solid black

**Comment by crondog** [comment]
Solid black should be `swaylock --color #000000FF` so it will play nice with cairo_set_source_u32

**Comment by SirCmpwn** [comment]
>Solid black should be swaylock --color #000000FF so it will play nice with cairo_set_source_u32

Yeah, my mistake.

**Comment by DerpyCrabs** [comment]
I like the idea with transparency. Waiting for this feature.

**Comment by ke7ofi** [comment]
I feel like breaking from 6-digit hex and retaining the general scheme is ugly. A discrete `-t` is starting to sound better and better.

**Comment by DerpyCrabs** [comment]
Transparency of swaylock has fixed this issue. Thank you.
