### ISSUE TITLE
swaybar don't show external scripts anymore

### ISSUE THREAD

**Issue by podhorsky-ksj** [SirCmpwn/sway#473]
Hi,

I have an issue with showing output of external script.
when I use only i3status it work good.
>bar {
>        status_command i3status
>        #status_command ~/.config/i3/i3status.bash
>        tray_output primary
>}

but when I use external script, which is written just like mentioned here:
>http://i3wm.org/i3status/manpage.html#_external_scripts_programs_with_i3status

Whole swaybar shows only unprintable chars.  In previous versions of sway it worked, now it doesn't work. 

Do you know, how to fix it or do you have some recommendation for using another printer with similar settings as i3status?

Thanks

**Comment by mikkeloscar** [comment]
Would it be possible to post the script you are using (or a minimal example that shows the problem) then it would be easier to test.

**Comment by podhorsky-ksj** [comment]
It's not in the script. When I try the minimal script, it behaves the same way:

>$ cat .config/i3/i3status.bash 
>\#!/usr/bin/bash
>\# shell script to prepend i3status with more stuff

>i3status | while :
>do
>  read line
>  echo "$line" || exit 1
>done

I think it's something about output_format.
When I run this script in terminal, it prints correctly the rows
It also prints before it:
>i3status: trying to auto-detect output_format setting
>i3status: falling back to "none"

**Comment by mikkeloscar** [comment]
The output format in i3status should be "none" when running it this way. Should auto detect if you don't set the value.

I can't replicate the issue, it looks fine when I run the minimal script you posted. What happens if you run i3status as status_command, but set output_format = "none" in the config, does that work?

**Comment by SirCmpwn** [comment]
Let's start by checking that you're running the latest version of sway, @podhorsky-ksj.

**Comment by podhorsky-ksj** [comment]
I just pull out the latest version of wlc and sway and build. Still the same behaviour.

But when I add to block general {} in i3status/config the
>output_format = "none"

i3status (without the external script):
>status_command i3status

shows the same unprintable chars.

So, somehow the bar can't  show the output formated with:
>output_format = "none".

**Comment by SirCmpwn** [comment]
Can you share your sway log? See the FAQ

**Comment by podhorsky-ksj** [comment]
Ok here is the file:
[sway.txt](https://github.com/SirCmpwn/sway/files/103217/sway.txt)
Here is also script  how I run sway. 
Maybe some features are obsolete, I created it when I used orbment.
[sway-run.txt](https://github.com/SirCmpwn/sway/files/103225/sway-run.txt)
And yes, I rebooted before it.

Also, when I exited sway, to get log from i3status, some segfault was occured and then process sway-msg put CPU into heavy load.
I have always enabled logging, so there is log from it. I'm not sure if it is connected with sway.
[sway-segfault.txt](https://github.com/SirCmpwn/sway/files/103236/sway-segfault.txt)

**Comment by mikkeloscar** [comment]
Could you also post the i3status config you use? I suspect it has something in it that messes up the bar, since I can't replicate the issue with my own config.

**Comment by podhorsky-ksj** [comment]
Ok, here it is:

[i3status.txt](https://github.com/SirCmpwn/sway/files/103261/i3status.txt)

**Comment by mikkeloscar** [comment]
@podhorsky-ksj thanks for reporting it, I don't know why I couldn't trigger the issue without your config, but it's fixed now.

**Comment by podhorsky-ksj** [comment]
@mikkeloscar fix is ok, thanks.
A what about the segfault. Is it connected with sway?

**Comment by mikkeloscar** [comment]
We need you to run `addr2line` on the backtrace and post it, so we can get an idea of what's going on.

You can use this helper script: https://gist.github.com/mikkeloscar/badebca2b9766a067397

```
cat swaylog | python addr2line_sway.py /path/to/sway-binary
```

And please create a new issue for this.

**Comment by podhorsky-ksj** [comment]
Ok thanks. I recompiled the binary, but if the issue will occur again, this script will help.
