### ISSUE TITLE
Window borders

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/sway#477]
Discussion on how best to implement window borders. Two main choices:

* Draw them with GL in wlc's pre-render hook
* Create rgba surfaces for each window that sit behind each window and draw the border around it

I'm really not convinced either way is the obvious solution. Discuss.

**Comment by crondog** [comment]
Just a few thoughts. Which is the easiest to implement right now and what
would be the performance of each? We might not know that yet though
On 26 Jan 2016 8:19 am, "Drew DeVault" <notifications@github.com> wrote:
>
> Discussion on how best to implement window borders. Two main choices:
>
> Draw them with GL in wlc's pre-render hook
> Create rgba surfaces for each window that sit behind each window and draw
the border around it

**Comment by SethBarberee** [comment]
With rgba surfaces, wouldn't that mean that the user could specify the colors too and hence a colored border? I think that would be good choice in terms of customization...

**Comment by crondog** [comment]
You can specify color in gl too :)

**Comment by SirCmpwn** [comment]
Probably easier to implement with GL. Unsure about the performance.

**Comment by SirCmpwn** [comment]
Text rendering in GL (for window titles) is a pain in the ass, fwiw

**Comment by crondog** [comment]
We can use Cairo for that can't we

**Comment by SirCmpwn** [comment]
Probably, but the GL backend for cairo is experimental. Not sure what that implies.

**Comment by crondog** [comment]
Hmm most wayland client code/tutorials that I have seen all use egl and cairo and they all run ok

**Comment by SirCmpwn** [comment]
Well, if it works, it works.

**Comment by crondog** [comment]
Would the surface method be something like 

* Create a surface and attach to a view
* When rendering the view also render the surface

**Comment by SirCmpwn** [comment]
The surface method would be to create a new surface every time a view is created that needs window borders and somehow associate it with that window, then move it during the layout arrangement.

**Comment by crondog** [comment]
I am leaning towards the pre hook method as we only need to calculate and draw the border instead of dealing with creating/linking/moving/drawing another object

**Comment by ViktorNova** [comment]
I'm just chiming in with my 2 cents, but I really hope Sway is planning to support window buttons at some point in the future, and that whatever decision is made will allow for that feature down the road!! 

I know i3 does not do this and has no plans to do so, but it would be great if Sway did

**Comment by SirCmpwn** [comment]
I have no intention of implementing window buttons.

**Comment by ViktorNova** [comment]
Aww sad.

**Comment by gpyh** [comment]
How will this interfere with client-side window decoration?

**Comment by mikkeloscar** [comment]
@gpyh they will just be inside the borders drawn by sway.

**Comment by ke7ofi** [comment]
@ViktorNova if you're sad and have the skills, fork it. For something keyboard-operated like Sway, there's no reason to have them.

**Comment by ke7ofi** [comment]
I'm not very familiar with the current situation, but isn't it basically just using the wallpaper? With i3, there's no “justification” for having wallpaper, as it's never shown while windows (except the floating kind) are up, but here, the wallpaper could *be* the borders, providing a practical reason to have one.

Basically, I'm suggesting not implementing custom borders at all, but I don't know if that would entail a loss of functionality.

**Comment by SirCmpwn** [comment]
I don't really understand what you're suggesting.

**Comment by mikkeloscar** [comment]
@ke7ofi borders are very helpful to see what window has focus, in i3 the focused window has a blue border while the others have a grey border (by default).

Also the title of the window is nice to have.

**Comment by SirCmpwn** [comment]
Borders are also very useful in the tiled and stacking layouts.

**Comment by ke7ofi** [comment]
@mikkeloscar I rarely use the titles except when they're forced (in tabbing mode), but I definitely see why that's important. Focus is also important, so I suppose my suggestion didn't make sense, sorry.

**Comment by ledti** [comment]
Also worth noting is the ```hide_edge_borders``` feature, since its potential implementation might affect the consideration of how to implement window borders.

---

As for the discussion, I see titlebars and borders as two separate features:

Titlebars are definitely needed for stacking/tabbed layouts.

Borders are only necessary as an indicator of focus, but otherwise they're just a cosmetic feature.

**Comment by SirCmpwn** [comment]
>As for the discussion, I see titlebars and borders as two separate features:

They aren't, really.

**Comment by ke7ofi** [comment]
I'm not sure how separate you're thinking of, but I think i3's semi-optional titlebars are a reasonable implementation. (I guess reasonable design is a large part of why I like i3 so much, actually.)

**Comment by ViktorNova** [comment]
The reason this makes me sad is because right now there is no such thing as a tiling window manager that is touchscreen-friendly. However, i3 accidentally turned out to be damn near perfect for a touchscreen, but because of the main developers ideals, they 'will never add window decoration buttons'. 

I was hoping with Sway's broader goals and a different crew that I might be able to persuade you to at least consider this feature that, if implemented, could possible make Sway a major contender in the rapidly growing touchscreen market that is currently only served by window managers that are floating and/or fullscreen only.

Sadly I am not a coder, or I would absolutely fork it myself!

**Comment by SirCmpwn** [comment]
We're going to be adding multitouch bindings in the future, so you could bind a gesture to do whatever the buttons could do.

**Comment by mikkeloscar** [comment]
@ViktorNova what about CSD? Most clients has it enabled by default in wayland so the buttons are already there.

**Comment by ViktorNova** [comment]
@SirCmpwn - That is EXCELLENT to hear, I will definitely keep my eye on the project! =)

@mikkeloscar - This is unfortunately true only for GTK3 apps, which only accounts for a portion of Linux desktop software
