### ISSUE TITLE
Un-fullscreen windows when switching workspaces on the same output

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/sway#48]
But put them back if you return. I think this might be easiest to support if we use our own fullscreen mechanism instead of having wlc do it. Paging @Cloudef for an opinion.

**Comment by Cloudef** [comment]
Yeah, the wm is supposed to handle this case. Wlc tries to not change window states behind the scenes.
wlc_view_set_state can be set the FULLSCREEN bit.

**Comment by SirCmpwn** [comment]
Not really relevant now.
