### ISSUE TITLE
Lockscreen and views arranging

### ISSUE THREAD

**Issue by crondog** [SirCmpwn/sway#481]
Having a transparent swaylock allows us to see the views on the workspace being arranged   which includes an area for swaylock even though swaylock is fullscreen and shouldn't be included.

**Comment by ke7ofi** [comment]
I don't understand; what do you mean?

**Comment by crondog** [comment]
Steps to reproduce:

* Make sure you have commit https://github.com/SirCmpwn/sway/commit/73ec01d8541a6a05ff253e2b1934d53932e26508
* Open a terminal
* Run `swaylock -c ff00ff11`
* You now have a semi transparent purple lockscreen over the whole screen, but the terminal is not a single full view now. It has been moved to the left and half the size

**Comment by aouelete** [comment]
It seems like I am still experiencing this issue with the latest version.
Here's a screenshot:
![screen](https://cloud.githubusercontent.com/assets/12178067/13381198/d7d2270e-de23-11e5-9f0e-c51be276767d.png)

**Comment by progandy** [comment]
I think sway has to call arrange_windows after the window has been moved in the tree, so this pull request adresses that.
