### ISSUE TITLE
swaylock causes WM CPU usage to substantially increase

### ISSUE THREAD

**Issue by nuew** [SirCmpwn/sway#485]
When running `swaylock`, the cpu usage of `sway` goes from about 0.7 to 60.

From what I can tell, it's caused by [arrange_windows_r](https://github.com/SirCmpwn/sway/blob/master/sway/layout.c#L432) running much more often when `swaylock` is open than otherwise.

Here's some output from the logfile, which is pretty much infinitely repeated, though, as said above, much faster when `swaylock` is open: 
```
Arranging layout for 0x627200 (ROOT '(null)')
Arranging layout for 0x627200 (null) 0.000000x0.000000+0.000000,0.000000
Arranging output 'DVI-I-1' at 0.000000,0.000000
Arranging layout for 0x237adc0 (OUTPUT 'DVI-I-1')
Arranging layout for 0x237adc0 DVI-I-1 1920.000000x1080.000000+0.000000,0.000000
Arranging layout for 0x23847e0 (WORKSPACE '1')
Arranging layout for 0x23847e0 1 1920.000000x1059.000000+0.000000,0.000000
-> Found panel for this workspace: 1920x21, position: 1
Arranging workspace '1' at 0.000000, 0.000000
Arranging 0x23847e0 horizontally
Calculating arrangement for 0x2550970:4 (will scale 1920.000000 by 1.000000)
Arranging layout for 0x2550970 [An X Application] 960.000000x1059.000000+0.000000,0.000000
Set view to 960 x 1059 @ 0, 0
Calculating arrangement for 0x25569e0:4 (will scale 1920.000000 by 1.000000)
Arranging layout for 0x25569e0 (null) 960.000000x1059.000000+960.000000,0.000000
Set view to 960 x 1059 @ 960, 0
Arranging output 'DVI-D-1' at 1920.000000,56.000000
Arranging layout for 0x2508990 (OUTPUT 'DVI-D-1')
Arranging layout for 0x2508990 DVI-D-1 1280.000000x1024.000000+1920.000000,56.000000
Arranging layout for 0x25292d0 (WORKSPACE '2')
Arranging layout for 0x25292d0 2 1280.000000x1003.000000+0.000000,0.000000
-> Found panel for this workspace: 1280x21, position: 1
Arranging workspace '2' at 0.000000, 0.000000
Arranging 0x25292d0 horizontally
Calculating arrangement for 0x2555590:4 (will scale 1280.000000 by 1.000000)
Arranging layout for 0x2555590 (null) 1280.000000x1003.000000+0.000000,0.000000
Set view to 1280 x 1003 @ 0, 0
focus:R      |(0x627200)(p:(nil)   )(f:0x2508990)(h:-1)Type:root|layout:-    |w:   0|h:   0|x:   0|y:   0|g:  0|vis:t|children: 2|name:(null)
|focus:X     |(0x237adc0)(p:0x627200)(f:0x23847e0)(h: 1)Type:op  |layout:-    |w:1920|h:1080|x:   0|y:   0|g: -1|vis:t|children: 1|name:DVI-I-1
|-focus:X    |(0x23847e0)(p:0x237adc0)(f:0x25569e0)(h:-1)Type:ws  |layout:Horiz|w:1920|h:1059|x:   0|y:   0|g: -1|vis:t|children: 2|name:1
|--focus:X   |(0x2550970)(p:0x23847e0)(f:(nil)   )(h: 3)Type:view|layout:-    |w: 960|h:1059|x:   0|y:   0|g: -1|vis:t|children: 0|name:[An X Application]
|--focus:X   |(0x25569e0)(p:0x23847e0)(f:(nil)   )(h: 4)Type:view|layout:-    |w: 960|h:1059|x: 960|y:   0|g: -1|vis:t|children: 0|name:(null)
|focus:X     |(0x2508990)(p:0x627200)(f:0x25292d0)(h: 2)Type:op  |layout:-    |w:1280|h:1024|x:1920|y:  56|g: -1|vis:t|children: 1|name:DVI-D-1
|-focus:W    |(0x25292d0)(p:0x2508990)(f:0x2555590)(h:-1)Type:ws  |layout:Horiz|w:1280|h:1003|x:   0|y:   0|g: -1|vis:t|children: 1|name:2
|--focus:K   |(0x2555590)(p:0x25292d0)(f:(nil)   )(h: 6)Type:view|layout:-    |w:1280|h:1003|x:   0|y:   0|g: -1|vis:t|children: 0|name:(null)
```

Here's the output section of my `.config/sway/config`, in case it's relevant:
```
output DVI-I-1 res 1920x1080 pos 0,0 bg ~/Pictures/wallpapers/wallpaper1.jpg center
output DVI-D-1 res 1280x1024 pos 1920,56 bg ~/Pictures/wallpapers/wallpaper2.jpg center
```

Sway's version: `sway version 6793648 (2016-01-30, branch "makepkg")`
wlc was compiled from commit `67d1bf2acd8774e9daac84d5be43641743ef4fbb`
Wayland is at version 1.9.0-1.
I'm using Arch Linux's xf86-video-ati (radeon) driver at version 1:7.6.1-1.

**Comment by crondog** [comment]
Just a couple of things. What is the swaylock command you are running? Does this happen with 1 output? Does this happen when running sway inside X? I don't have a dual setup so I can't reproduce

**Comment by nuew** [comment]
Just `swaylock`, no, and no.

**Comment by crondog** [comment]
Forgot to ask before but could you also post a full log from the time of launch to after you unlock?

**Comment by nuew** [comment]
Here you go (pssway is cpu usage, logged once per second).

Also, github doesn't allow .log files. Huh.

[sway.txt](https://github.com/SirCmpwn/sway/files/111429/sway.txt)
[pssway.txt](https://github.com/SirCmpwn/sway/files/111428/pssway.txt)

**Comment by mikkeloscar** [comment]
I can't reproduce on my setup with two monitors.

I have seen something like what you describe long ago, and I suspect it's not related to swaylock but rather that swaylock is in fullscreen. Could you try to reproduce it with fullscreened windows on both your monitors instead of swaylock?

**Comment by nuew** [comment]
No, not nearly as much CPU increase with two fullscreen windows on both monitors.
Could it be that the monitors are different sizes?

I know that j4-dmenu-desktop is the width of my bigger screen, even on the smaller one.

**Comment by nuew** [comment]
With one of todays commits (perhaps 89bb6a4 ?), I'm no longer experiencing this issue.
