### ISSUE TITLE
Moving the mouse around slowly moves the mouse up

### ISSUE THREAD

**Issue by Timidger** [SirCmpwn/sway#491]
When you move the mouse around, the cursor eventually will reach the top of the screen. It's easier to see with touchpads, but can be seen with all mice. Move the mouse back and forth in a solid equal distance motion in any direction. Notice how eventually it will tend toward the top of the screen, even if you did not lift your finger up (when it should just stay in place in the small part where you're moving the mouse back and forth).

I have noticed that in the example for WLC as well, so it might actually be a WLC bug. Wondered if you had any input on this though.

**Comment by FreeFull** [comment]
I can reproduce this with both sway and orbment, so it's presumably a bug in WLC or libinput, and not in sway.

**Comment by SirCmpwn** [comment]
Report to WLC.

**Comment by progandy** [comment]
I don't think this is a bug. I can do the same with xorg in all directions with my touchpad. I think this should be related to mouse pointer acceleration. In one direction you move your finger a bit faster and that results in a faster pointer movement.

**Comment by Timidger** [comment]
@progandy I found that if you simple push down on the touchpad without moving at all, it will still slowly move upward, so I don't think that mouse acceleration being the issue (because I'm not moving in any direction faster, since I'm keeping still)
