### ISSUE TITLE
Keybindings are messed up after screen is locked/unlocked

### ISSUE THREAD

**Issue by aouelete** [SirCmpwn/sway#498]
Recently I noticed a very strange issue with swaylock. If I lock the screen and then unlock it, some of my keybindings get messed up. 
For example, I use mod+Ctrl+l to run swaylock, but after I unlock the screen, swaylock runs when I only press mod+Ctrl. Also mod+Enter is no longer recognized.

I'm not sure how I would debug this issue, would a log help?

**Comment by SirCmpwn** [comment]
I can get why this might be happening. Once the screen is locked, the code to deal with key events is short circuited to avoid executing keybindings and passing keys along to programs. Should rework it to keep the internal keyboard state machine accurate even when locked.
