### ISSUE TITLE
More complex border designs

### ISSUE THREAD

**Issue by addisonamiri** [SirCmpwn/sway#506]
I'm trying to start a project which requires a tiling display of multiple windows. The project's goal is to create something like [DexUI](http://nnkd.org/dexui/) but usable for everyday use. I'd want a tiling WM that allows for dynamic graphical window borders. DexUI relies on a background image for the fancy window borders but for my project I'd need them to change based off the state of the active workspace (window titles/layout/etc).

From what I know, in X this requires compositing unless window borders are a solid line, but I am unfamiliar with the way wayland compositors do this. How are window borders usually implemented in wayland compositors (if there even is a usual in anything wayland at this point)? Considering Sway is a tiling window manager in wayland I was curious if anyone here would know how to implement a sort of theming engine on top of sway. I'd take it upon myself to write it if feasible. Basically all I'm thinking is raster or vector based window borders and maybe a little logic to decide where to draw certain things (if a window is too far north, draw the title on the bottom type stuff).

If this is possible, I'd develop a patch but leave it up to you guys as to whether it'd be useful to merge. As it seems now, most of the Sway community runs a fairly lightweight, minimal setup so fancy graphics might be unwanted. I'm just asking about the feasibility and perhaps a few pointers so I don't write yet another window manager to achieve this.

I've also never seen a "fancy" tiling window manager and think Sway would be a good starting point. As of now, there are only tiling plugins for other desktop environments (which don't work too well in my experience). I think Sway is awesome and I'd love to create something new out of it.

Thanks for your help!

**Comment by SirCmpwn** [comment]
Check out the window-borders branch.

**Comment by addisonamiri** [comment]
Thanks. I didn't realize normal borders weren't implemented yet. I'll take
a look at this.
