### ISSUE TITLE
[Feature request] Support for powerline in swaybar

### ISSUE THREAD

**Issue by her001** [SirCmpwn/sway#511]
[Powerline](https://github.com/powerline/powerline) is a status line plugin with [support](https://powerline.readthedocs.org/en/latest/usage/wm-widgets.html#i3-bar) for a [modded i3bar](https://github.com/s-ol/i3bgbar), among other things. It does **not** support mainline i3bar. The main requirement, as far as I know, is to have support for background colors and fallback fonts (the latter of which might be in swaybar already).

![Powerline in i3](https://camo.githubusercontent.com/501295d61b8e57c512897e858e45dab1b4296b49/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313733313237392f313730393537302f35333236303236382d363132312d313165332d383339372d3262333466623737313931632e706e67)

Edit: Fallback fonts are not even required, as Powerline can use [themes](https://powerline.readthedocs.org/en/latest/configuration/reference.html#themes) that do not use their special characters

**Comment by SethBarberee** [comment]
Fallback fonts are supported in swaybar but I don't know about background colors. Powerline is kinda what I'm doing with my status bar in sway but mine has only has the arrow tips in it

**Comment by mikkeloscar** [comment]
Swaybar has support for background colors through the i3bar protocol.

To do the arrows like that, swaybar would need to support per block separators with different fg/bg color by extending the i3bar protocol.

An alternative would be to add support for another protocol which is not aware of blocks like the protocol used in [LemonBoy/bar](https://github.com/LemonBoy/bar#formatting) (Which is the preferred way to do a powerline status bar in i3, it seems).

**Comment by ke7ofi** [comment]
This is slightly irrelevant, but does swaybar support arbitrary input like i3blocks?

**Comment by mikkeloscar** [comment]
@ke7ofi you can pass it an arbitrary line of text if that is what you mean? You won't get colors that way though.

**Comment by SirCmpwn** [comment]
Feel free to keep having a discussion, but I'm not sure there's something actionable here so I'm going to close the issue.

**Comment by her001** [comment]
@SirCmpwn If someone were to submit a pull request that implemented support for powerline, do you think it would be appropriate to add that feature to swaybar?

**Comment by SirCmpwn** [comment]
It depends on what's necessary to support it. What would have to change?

**Comment by her001** [comment]
I am not 100% sure as I have not gone through the code ([here](
https://github.com/s-ol/i3bgbar) is the old fork of i3bar that supports it).

This [issue](
https://github.com/powerline/powerline/issues/145#issuecomment-30094902) on
the Powerline github has some details on how it was implemented. Looks like
it was mostly adding a key to the json input for background-color and
making sure it actually changed the background color for that text.

On Thu, Mar 17, 2016 at 10:24 PM, Drew DeVault <notifications@github.com>
wrote:

> It depends on what's necessary to support it. What would have to change?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/SirCmpwn/sway/issues/511#issuecomment-198184575>
>



-- 
Andrew Conrad
<aconrad103@gmail.com>

**Comment by SirCmpwn** [comment]
That sounds like it's supported by i3-gaps and falls under the scope of https://github.com/SirCmpwn/sway/issues/307

**Comment by her001** [comment]
Oh, wow... I never saw that issue. It does look like it should work, if
Powerline was modified. Thank you for pointing me in the right direction.

On Thu, Mar 17, 2016 at 10:35 PM, Drew DeVault <notifications@github.com>
wrote:

> That sounds like it's supported by i3-gaps and falls under the scope of
> #307 <https://github.com/SirCmpwn/sway/issues/307>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/SirCmpwn/sway/issues/511#issuecomment-198186074>
>



-- 
Andrew Conrad
<aconrad103@gmail.com>
