### ISSUE TITLE
some bindsym exec commands do not work as expected

### ISSUE THREAD

**Issue by harrisonrodgers** [SirCmpwn/sway#518]
Hello.

I was trying to specify colors for dmenu in bindsym and:

`bindsym $mod+a exec dmenu_run -b -i -nb "#FDF6E3" -nf "#657B83" -sb "#EEE8D5" -sf "#CB4B16"` 
* does not work in sway
* works in i3

`bindsym $mod+d exec dmenu_run -b -i -nb '#FDF6E3' -nf '#657B83' -sb '#EEE8D5' -sf '#CB4B16'`
* does not work in sway
* works in i3

`bindsym $mod+g exec dmenu_run -b -i -nb "'#FDF6E3'" -nf "'#657B83'" -sb "'#EEE8D5'" -sf "'#CB4B16'"`
* works in sway
* does not work in i3

Note the following work from a terminal:
* `dmenu_run -b -i -nb #FDF6E3 -nf #657B83 -sb #EEE8D5 -sf #CB4B16`
* `dmenu_run -b -i -nb '#FDF6E3' -nf '#657B83' -sb '#EEE8D5' -sf '#CB4B16'`
* `dmenu_run -b -i -nb "#FDF6E3" -nf "#657B83" -sb "#EEE8D5" -sf "#CB4B16"`

`sway -d -V` output [http://pastebin.com/raw/5F1hruns](http://pastebin.com/raw/5F1hruns)

Thanks.

**Comment by ilpianista** [comment]
Commit 99f26c6 breaks the following config:
```
bindsym $mod+x exec "dmenu_run -i -nb '#181818' -nf '#d8d8d8' -sb '#181818' -sf '#a1b56c'"
```
This works in i3, but doesn't in sway.

I'm missing why strip_quotes strips **all** quotes and not just starting and trailing quotes?

**Comment by mikkeloscar** [comment]
This has been discussed a bit here: https://github.com/SirCmpwn/sway/issues/521

Basically in any sane implementation anything wrapped in `""` means a single argument, if you start to make special cases like i3 does, it gets complicated and confusing. We like to avoid that if possible.

**Comment by SirCmpwn** [comment]
To clarify: this is a place where I am willing to break backwards compatability in exchange for saner behaviour. The correct command is:

    bindsym $mod+x exec dmenu_run -i -nb '#181818' -nf '#d8d8d8' -sb '#181818' -sf '#a1b56c'
