### ISSUE TITLE
Segregation of commands into config and runtime

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/sway#531]
We should not do this. According to sway(5), we currently have bar, bindsym, and set commands that can't be used at runtime. I agree with the bar command, but I see no reason why we shouldn't be able to (re)define variables and (re)define keybindings at runtime.

**Comment by SirCmpwn** [comment]
Note: i3 does this differently, I see this as a chance for us to improve on i3's design without breaking backwards compatability.

**Comment by mikkeloscar** [comment]
`sway(5)` is also a bit wrong about what must be called at runtime. e.g. `floating_modifier` can be used directly in the config, but that's not what the man page says.
