### ISSUE TITLE
Keyboard switching 

### ISSUE THREAD

**Issue by VasilPupkin** [SirCmpwn/sway#532]
![language](https://cloud.githubusercontent.com/assets/18009816/13956535/361b70e8-f05a-11e5-8a73-7c31053bb2fe.png)
I run all this commands in console, but i can switch keyboard language yet. 
In i3 I use setxkbmap like this  `setxkbmap -model logitechdinovoedge -layout us,ru -option grp:alt_shift_toggle`
What I doing wrong? Which is difference with setxkbmap and  XKB.Please  help me. I have been registered in Github for this.

**Comment by progandy** [comment]
You have to set the xbk definitions before starting sway. The following settings work for me.
```
export XKB_DEFAULT_LAYOUT=de,us
export XKB_DEFAULT_OPTIONS=grp:alt_shift_toggle
sway
```

**Comment by VasilPupkin** [comment]
Thank you.

**Comment by ke7ofi** [comment]
@VasilPupkin Sorry that this is off-topic, but are Rennaissance waifus a thing?

**Comment by VasilPupkin** [comment]
Sorry, I dont check my git acc yet. I dont understand what mean "Rennaissance", because  im from Russia and I learn english now in school. I just choose arch-tan picture for wallpaper. If you want to know my favorite anime girl is Azusa from K-ON, lol.

**Comment by riquito** [comment]
@cafehaine thanks for redirecting me here but it doesn't seem to help with my problem.
I cannot understand how to change the keyboard layout *from inside a running sway* (I usually change keyboard layouts to write in different languages to different people. Killing and restarting sway is not exactly the solution I was hoping for). If it isn't supported I'll open a feature request

**Comment by cafehaine** [comment]
export XKB_DEFAULT_LAYOUT=de,us
export XKB_DEFAULT_OPTIONS=grp:alt_shift_toggle
sway

then press alt and shift to switch layouts

There is now way to do it programmatically

**Comment by riquito** [comment]
My brain started working again, it's indeed a solution and I don't really need to do it programmatically. Thank you very much

**Comment by knezi** [comment]
Hi to all,
this option for switching layouts is not applicable to my use case. I use the following two layouts:

`setxkbmap cz-prog,cz-moje -variant ,ucw -option grp:caps_switch`

`setxkbmap us,cz-moje -variant ,ucw -option grp:caps_switch`

between which I toggle with a small bash script. I can't use Alt+Shift to toggle between them, because it uses capslock as a switch between the variants. The question is if there is any way to switch between these two without the need of restarting sway?

**Comment by SirCmpwn** [comment]
No, that's not presently possible.

**Comment by knezi** [comment]
Should I fill feature request?

**Comment by SirCmpwn** [comment]
No. It should be possible when wlroots is complete.
