### ISSUE TITLE
NVIDIA 364.12 beta driver still not working

### ISSUE THREAD

**Issue by 602k4** [SirCmpwn/sway#533]
I'm trying to run Sway on my desktop using the new NVIDIA 364.12 beta driver, but I can't due to following errors:

[main.c:39] [wlc] Failed to activate vt2 for restoration
[main.c:39] [wlc] Failed to switch back to vt2

The changelog for the driver is showing Wayland compatibility: http://www.nvidia.com/download/driverResults.aspx/100577/en-us

I can test any workaround you provide me and help with debug process, but I can't write a fix for myself.

Thanks.

**Comment by SirCmpwn** [comment]
Can you run orbment with the nvidia driver?

**Comment by 602k4** [comment]
I can't run orbment, the error is also related to "vt2 restoration screen".

**Comment by SirCmpwn** [comment]
Redirect your issue to [wlc](https://github.com/Cloudef/wlc)

**Comment by progandy** [comment]
Upstream bug:
Cloudef/wlc#138

The weston folks don't like the implementation either, so don't expect it in the near future.
ML discussion for weston [here](https://lists.freedesktop.org/archives/wayland-devel/2016-March/027547.html) (and responses to patches, specifically [4/7](https://lists.freedesktop.org/archives/wayland-devel/2016-March/027551.html))
