### ISSUE TITLE
In latest commit swaybar does not appear

### ISSUE THREAD

**Issue by nicman23** [SirCmpwn/sway#567]
Distro: arch linux both a 32 and a 64 machine have the same issue (intel gfx on latest software)

Yesterday it worked now does not and i am really confused. ~~Interestingly, this happened after upgrading the kernel. Will try an older version and edit in a few seconds.~~ Compiled and tried both sway and sway-git aur packages to no effect.

sway -V complains about wlc not being able to open x11 display and being unable to terminate swaybar (when i kill sway)

Will try to downgrade wlc

**Comment by progandy** [comment]
It works for me on an up-to-date Arch Linux x64 (testing) with
wlc-git r910.5deece7-1 (== v0.0.1-9-g5deece7)
sway-git r1441.0d4c31e-1 (== 0.3-13-g0d4c31e)

Do you have some autostart exec commands in your sway config?

**Comment by SirCmpwn** [comment]
Works for me, too. Post sway debug log.

**Comment by SirCmpwn** [comment]
And config file

**Comment by nicman23** [comment]
well sway does not write anything when i issue `sway -V -d > txt` :/ . Here is my config file

[config.txt](https://github.com/SirCmpwn/sway/files/199889/config.txt)

**Comment by SirCmpwn** [comment]
The log is printed to stderr. See the FAQ for how to save logs correctly.

**Comment by nicman23** [comment]
will do and sorry, missed that part of the faq

**Comment by nicman23** [comment]
logs:
[sway.txt](https://github.com/SirCmpwn/sway/files/199900/sway.txt)

**Comment by SirCmpwn** [comment]
[config.c:720] Invoking swaybar for bar id 'bar-0'
    [layout.c:58] Adding 0x22aeba0 (1, 1024.000000x600.000000) to 0x634440 (0, 0.000000x0.000000)
    (snip)
    [main.c:43] [wlc] Added output (1)
    [main.c:43] [wlc] become active
    [main.c:49] Using output 0 of 1
    ERROR: Unable to connect to 
    (snip)
    [handlers.c:727] Compositor is ready, executing cmds in queue

I'm guessing the ERROR there is swaybar output. Maybe this would be fixed if we didn't invoke swaybar until after the compositor is ready?

**Comment by SirCmpwn** [comment]
Do you get a wallpaper, @nicman23?

**Comment by nicman23** [comment]
yes

**Comment by nicman23** [comment]
huh there is no SWAYSOCK in my env and `find /run/user/1000/ -name 'sway*'` has no results

**Comment by nicman23** [comment]
also i3bar -- crashes with invalid pointer.

**Comment by nicman23** [comment]
sorry misclick

**Comment by nicman23** [comment]
sigh made a temporary user and it worked. Then with the original user i run bash (was using zsh) and sway and it worked and of course works with zsh (having changed nothing) .... 

Testing now on a second pc with the same problem (what even - i cant)

**Comment by nicman23** [comment]
Well this was a massive waste of time for everyone.... Turns out i had an line in my zshrc that read
`export SWAYSOCK=/run/user/1000/ -name 'sway*'`
which of course did not do anything if sway was not up
the line was for controlling sway from other ttys / ssh. It appears that sway did not like it.

I was running with this line for some days now without any problems, as to why it appeared now, i do not know.
