### ISSUE TITLE
libinput: support accel profile selection

### ISSUE THREAD

**Issue by colemickens** [SirCmpwn/sway#576]
Sway could/should support setting the acceleration profile via libinput.

Relevant:
 * Initial libinput changes. This change should follow the same pattern as the initial options: https://github.com/SirCmpwn/sway/commit/28081b76891ddbbb825dee6c202037d78aa8f164
 * libinput patch: https://lists.x.org/archives/xorg-devel/2015-September/047300.html
 * libinput docs: https://wayland.freedesktop.org/libinput/doc/latest/group__config.html (particularly: libinput_device_config_accel_set_profile)

**Comment by colemickens** [comment]
cc: @Flandoo

**Comment by tajjada** [comment]
I forked sway to work on this. Will update with progress.

**Comment by tajjada** [comment]
Done. Tested it on my system; seems to work. Enjoy.

**Comment by AStrangeEnigma** [comment]
I know this is delayed, but thanks very much @tajjada and @colemickens - really awesome work! I am super eager to come back to sway now that this is implemented.

@SirCmpwn thanks for the great project in general :)

(I'm @flandoo)
