### ISSUE TITLE
Pointer wanders when finger resting on trackpad

### ISSUE THREAD

**Issue by that1communist** [SirCmpwn/sway#577]
Whenever I leave my finger sitting on the mousepad, the pointer will wander up and to the left for seemingly no reason, this does not happen on regular i3, so i've determined it isn't a hardware issue.

`input 2:7:SynPS/2_Synaptics_TouchPad {
    tap enabled
    natural_scroll disabled
    dwt enabled
}
`

I think that's relevant but i'm not sure.

**Comment by mikkeloscar** [comment]
It's a bug in libinput: https://github.com/Cloudef/wlc/issues/126
