### ISSUE TITLE
Floated QT5 windows are not visible

### ISSUE THREAD

**Issue by vially** [SirCmpwn/sway#578]
Floating any QT 5 window makes it invisible. Toggling it back (Mod+Shift+space) into tiling mode makes it reappear.

You can reproduce this using qtcreator (or any other QT 5 app):

1. Start `qtcreator` (make sure you have set the `QT_QPA_PLATFORM=wayland-egl` environment variable before doing so).
2. Toggle the window to floating mode (Mod+Shift+space). The window will disappear.
3. Toggle the window back to tiling mode. The window will reappear.

I'm testing this on archlinux using `sway-git` from AUR.

**Comment by sd-hd** [comment]
same problem here, with qt5 and wayland 1.1.1 

$ swaymsg --version
swaymsg version 1.1.1
