### ISSUE TITLE
cppcheck

### ISSUE THREAD

**Issue by Oppen** [SirCmpwn/sway#58]
Sorry for the premature posting, I accidentally hitted enter.
I made a cppcheck run and found the following issues:

[sway/commands.c:180]: (style) The scope of the variable 'i' can be reduced.
[sway/commands.c:512]: (error) Common realloc mistake: 'parts' nulled but not freed upon failure
[sway/commands.c:527]: (error) Common realloc mistake: 'parts' nulled but not freed upon failure
[sway/handlers.c:36] -> [sway/handlers.c:41]: (warning) Possible null pointer dereference: focused - otherwise it is redundant to check it against null.
[sway/handlers.c:200] -> [sway/handlers.c:201]: (warning) Possible null pointer dereference: c - otherwise it is redundant to check it against null.
[sway/handlers.c:158]: (style) The scope of the variable 'parent' can be reduced.
[sway/log.c:22]: (style) The scope of the variable 'flag' can be reduced.
[sway/readline.c:20]: (error) Common realloc mistake: 'string' nulled but not freed upon failure
[sway/readline.c:29]: (error) Common realloc mistake: 'string' nulled but not freed upon failure
[sway/stringop.c:89]: (style) The function 'code_strchr' is never used.
[sway/stringop.c:84]: (style) The function 'code_strstr' is never used.
[sway/list.c:46]: (style) The function 'list_cat' is never used.
[sway/log.c:36]: (style) The function 'sway_abort' is never used.
[sway/stringop.c:107]: (style) The function 'unescape_string' is never used.
[sway/workspace.c:144]: (style) The function 'workspace_prev' is never used.

Aside from the cosmetic fixes, there are some concerns that I got after inspecting the signaled lines. First, the total disregard for OOM situations. Is that intentional? I know it's common to just let it crash if that's the case, but I though I'd better rise the issue in case it wasn't something decided upon but an accident.
Other than that, there is a particularly suspicious piece of code. In the lines 36 to 41 in handlers.c, you first get the focused container to a focused pointer. It's alright up until that point. Later, my guess after a shallow inspection is that whoever wrote the code considered the focused windows could change, but never reassigned this possible change to focused. Then checks as if it was checked. That, or the first if, in line 37 can crash, since it dereferences focused to access the handle contained by it.
Other than that, if you want it, I can make a pull request for the trivial fixes at some point this week.

**Comment by Luminarys** [comment]
I quickly ran cppcheck through, and it didn't yield anything particularly useful. For the time being, static code analysis isn't a massive priority; we're doing code reviews on all the PRs, and cleaning up along the way. Thanks for pointing this out though.

**Comment by Luminarys** [comment]
You make a good point about the code in `focus_pointer`, the code there needs to be rearranged there so that focused is checked for validity initially.

**Comment by SirCmpwn** [comment]
Low hanging fruit for pull requests, if anyone is interested.

**Comment by SirCmpwn** [comment]
Seems like this is taken care of now.
