### ISSUE TITLE
Testing sway on virtualbox

### ISSUE THREAD

**Issue by michallepicki** [SirCmpwn/sway#581]
I have installed `sway-git` and copied the config file over to `./config/sway/config`

`sway -d` output:
```
[main.c:43] [wlc] logind: session control granted
[main.c:43] [wlc] Running on vt 1 (fd 0)
[main.c:41] [wlc] Failed to open X11 display
[main.c:41] [wlc] Failed to open device: /dev/dri/card0
[main.c:43] [wlc] Closed drm
[main.c:41] [wlc] Could not initialize any backend
[main.c:39] [wlc] Failed to init compositor
[main.c:43] [wlc] Parent exit(479)
[main.c:43] [wlc] Restoring vt 1 (0x4) (fd 0)
```

As I understand virtualbox has a crippled graphics stack. Is there a way I can use sway with FBDEV?

**Comment by SirCmpwn** [comment]
Nope. VirtualBox doesn't support KMS and therefore sway won't work on it.

**Comment by SirCmpwn** [comment]
Suggestion: qemu

**Comment by michallepicki** [comment]
Thank you for the quick response. Installed it on a real system and works pretty well, apart from multi-monitor setup (but that may be a hardware/config thing, will look into that).

**Comment by StephenBrown2** [comment]
Note that Wayland names outputs slightly differently than Xorg.
Run `swaymsg -t get_outputs` to find out what yours are named, and if it sees them at all.

**Comment by concatime** [comment]
I met this issue today. Sad that VirtualBox doesn't support it.

**Comment by majewsky** [comment]
FYI: There is a KMS driver in the works for VirtualBox [1]. As of kernel 4.13, it lives in the kernel's staging area [2]. Since there seems to be some active development going on over there, there is a certain chance that, in the near future, we can finally have Sway (or any other Wayland compositor, for that matter) on VirtualBox guests. (Disclaimer: I only follow kernel development via news outlets, so I don't have any insider information about the progress or technical details.)

[1] https://www.phoronix.com/scan.php?page=news_item&px=VirtualBox-vboxvideo-Plans
[2] https://github.com/torvalds/linux/tree/master/drivers/staging/vboxvideo

**Comment by SirCmpwn** [comment]
That's nice, but you really should be using qemu. VirtualBox is pretty bad.

**Comment by cecton** [comment]
Is it the same problem for Hyper-V? I also get "Failed to init compositor"

**Comment by SirCmpwn** [comment]
Probably. Use qemu.

**Comment by purefffire** [comment]
Is it possible to use sway on  qemu with haxm acceleration https://www.qemu.org/2017/11/22/haxm-usage-windows/ ?

**Comment by tgharib** [comment]
![image](https://user-images.githubusercontent.com/6457015/166863159-4c132720-d9b8-4ebe-94d1-91fc27262514.png)

I tried to use qemu on windows to boot my physical linux partition but it didn't seem to work. I obtained OVMF.fd from [here](https://github.com/clearlinux/common/blob/master/OVMF.fd). I am running with `.\qemu-system-x86_64.exe -drive file=\\.\PHYSICALDRIVE0 -bios "C:\Users\Owner\Downloads\OVMF.fd" -accel whpx -m 4096`

**Comment by codethief** [comment]
@tgharib Your comment just brought an end to an hour-long debugging session! I had tried running QEMU with `-vga none -device virtio-gpu-pci` before but I was still seeing tons of artifacts and glitching in Sway (similarly to [this screenshot here](https://www.reddit.com/r/swaywm/comments/cswafc/weird_graphical_glitches_on_new_install/exigoic)). Finally, `WLR_RENDERER=pixman` did the trick! Thank you _so_ much!
