### ISSUE TITLE
Output blurry at wrong TTY resolution

### ISSUE THREAD

**Issue by janhieber** [SirCmpwn/sway#583]
My output is blurry and distorted.
I have a notebook with 1920x1080 and a dock with:
left: 1920x1200
right: 1920x1080

My config:
> output eDP-1 disable
> output DP-3 pos 0 0 res 1920x1200
> output DP-4 pos 1920 0 res 1920x1080

Config from sway:
> $ swaymsg -t get_outputs | python -m json.tool
> [
>     {
>         "name": "DP-3",
>         "active": true,
>         "primary": false,
>         "rect": {
>             "x": 0,
>             "y": 0,
>             "width": 1920,
>             "height": 1200
>         },
>         "current_workspace": "1"
>     },
>     {
>         "name": "DP-4",
>         "active": true,
>         "primary": false,
>         "rect": {
>             "x": 1920,
>             "y": 0,
>             "width": 1920,
>             "height": 1080
>         },
>         "current_workspace": "2"
>     }
> ]

Result:
DP-3 (left): aspect ratio / res is OK, but everything is blurry
DP-4 (right): screen is squeezed in height

"Screenshot": [http://l02i.imgup.net/IMG_201604b0c0.jpg](http://l02i.imgup.net/IMG_201604b0c0.jpg)

I think the TTY resolution is the same on every output (1920x1080) and thats the problem.
But how to change it? And if I change it to 1200 height, will I have problems with the 1080 screens?

**Comment by mikkeloscar** [comment]
Yeah, it sounds like wlc is setting the wrong resolution (from the tty). However a bit strange that both screens would have a wrong resolution. Can you post the log you get from running `sway -d 2> ~/sway.log` just to see what resolution wlc chooses at startup?

**Comment by janhieber** [comment]
OK, after a reboot and not changing anything the right screen (1080) looks OK. The left one is still blurry, I think its 1200 height scaled to 1080 an then send to display and there scaled to 1200 or smth like this.

sway log: [http://pastebin.com/RV9b3bq9](http://pastebin.com/RV9b3bq9)

fbset output:
> mode "1920x1080"
>     geometry 1920 1080 1920 1080 32
>     timings 0 0 0 0 0 0 0
>     accel true
>     rgba 8/16,8/8,8/0,0/0
> endmode

**Comment by SirCmpwn** [comment]
This is a [WLC](https://github.com/Cloudef/wlc) problem. Please report it there.
