### ISSUE TITLE
Can't switch workspace

### ISSUE THREAD

**Issue by Celes-Eternal** [SirCmpwn/sway#584]
Hello,

I just installed sway today. It looks really promising so thanks for your work!
Bu i have a litlle problem (in fact i had the same problem on bspwm), i can't switch workspace.
Everything else seems too work (with some bugs, but that's not a problem right now), but i was never able to switch on another workspace.

I use the last git version i think (gentoo overlay).
This is the log generate with sway -d 2> sway_log.txt
[sway_log.txt](https://github.com/SirCmpwn/sway/files/217707/sway_log.txt)

Have a nice day

**Comment by SirCmpwn** [comment]
I don't see you making any attempts to switch workspaces here. Try running this and see if it changes the workspace for you:

    swaymsg workspace test

**Comment by Celes-Eternal** [comment]
I wasn't able to focus on the new sway context, but i was hoping some clues in the log.
But you're rigth i can switch...
So i don't know why it's not working with bindsym

**Comment by SirCmpwn** [comment]
Can you share your config file? What kind of keyboard are you using?

**Comment by Celes-Eternal** [comment]
I use the default config for now with just 2/3 line in more, (but i tried to switch with other bindsym like $mod+a)
[config.txt](https://github.com/SirCmpwn/sway/files/217761/config.txt)

and i launch sway with this :
```
#!/bin/zsh
XKB_DEFAULT_LAYOUT=fr XKB_DEFAULT_MODEL=pc104 sway
```

**Comment by SirCmpwn** [comment]
Run `xev` and let us know what key name is reported when you press 1 on your keyboard.

**Comment by Celes-Eternal** [comment]
When i press the same touch as i3 : 
```
KeyPress event, serial 32, synthetic NO, window 0x1000001,
    root 0x260, subw 0x0, time 5601835, (-22,460), root:(635,508),
    state 0x10, keycode 10 (keysym 0x26, ampersand), same_screen YES,
    XLookupString gives 1 bytes: (26) "&"
    XmbLookupString gives 1 bytes: (26) "&"
    XFilterEvent returns: False

KeyRelease event, serial 32, synthetic NO, window 0x1000001,
    root 0x260, subw 0x0, time 5601930, (-22,460), root:(635,508),
    state 0x10, keycode 10 (keysym 0x26, ampersand), same_screen YES,
    XLookupString gives 1 bytes: (26) "&"
    XFilterEvent returns: False
```
```
With the numeric pad:
KeyPress event, serial 32, synthetic NO, window 0x1000001,
    root 0x260, subw 0x0, time 5660720, (-22,729), root:(635,777),
    state 0x10, keycode 87 (keysym 0xffb1, KP_1), same_screen YES,
    XLookupString gives 1 bytes: (31) "1"
    XmbLookupString gives 1 bytes: (31) "1"
    XFilterEvent returns: False

KeyRelease event, serial 32, synthetic NO, window 0x1000001,
    root 0x260, subw 0x0, time 5660787, (-22,729), root:(635,777),
    state 0x10, keycode 87 (keysym 0xffb1, KP_1), same_screen YES,
    XLookupString gives 1 bytes: (31) "1"
    XFilterEvent returns: False

```

**Comment by SirCmpwn** [comment]
Try binding to "mod+ampersand", or using bindcode 10 instead of bindsym.

**Comment by Celes-Eternal** [comment]
Sorry, i just realized that all other bindsym i have tried was already use...
And yes ampersand is working :)
I think i have just wast your time...
I'll work on sway this summer as excuses ^^
