### ISSUE TITLE
Debian Installation Guide, dependency missing.

### ISSUE THREAD

**Issue by alexfornuto** [SirCmpwn/sway#585]
The [Debian Installation Guide](https://github.com/SirCmpwn/sway/wiki/Debian-installation-guide) includes `lib-xcb-emwh-dev` as required to build wlc. It's correct that it will not built, but lib-xcb-emwh-dev is not in Debian's repositories, as far [as I can find](https://packages.debian.org/search?keywords=lib-xcb-emwh-dev&searchon=names&suite=all&section=all).

**Comment by alexfornuto** [comment]
Resolved by changing to libxcb-emwh-dev (no idea why searching Debian's repos for just `emwh` didn't find that), but another dependancy listed, `libinput5`, is missing. Assuming that `libinput10` will work for the moment.

**Comment by SirCmpwn** [comment]
Thanks for updating the wiki page.

>Assuming that libinput10 will work for the moment.

Wouldn't hold your breath.
