### ISSUE TITLE
State of Sway - April 2016

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/sway#591]
Writing this GitHub issue so that the 128 people watching this repository aren't out of the loop.

https://drewdevault.com/2016/04/20/State-of-sway.html

**Comment by ke7ofi** [comment]
Wouldn't anyone watching get notifications for #2 unless they've unsubscribed?

**Comment by SirCmpwn** [comment]
Sure, but this is a recap of all development, including stuff not directly related to #2. I also don't bump the thread on #2 for changes, I usually just tick the checkbox.

**Comment by ke7ofi** [comment]
Sorry, I had #2 open already, and since I have a Firefox extension that changes the placement of new tabs (but not the fact that ctrl+tab goes right one), I didn't realise it was a blog post.
