### ISSUE TITLE
Can't splith after splitv

### ISSUE THREAD

**Issue by diegoviola** [SirCmpwn/sway#593]
Problem: After I do `$mod+v` I can't longer do `$mod+s` to split horizontally.

My system is Arch Linux (x86_64)
sway 0.5-2

**Comment by SirCmpwn** [comment]
Config file?

**Comment by diegoviola** [comment]
The default one from /etc/sway/config copied to ~/.config/sway/config

**Comment by diegoviola** [comment]
Can you reproduce it?

**Comment by 4e554c4c** [comment]
Using the Arch Linux package sway I can confirm for the default config that I am no longer able to split horizontally once I split vertically.

**Comment by mikkeloscar** [comment]
The problem is that the default config file has `$mod+s` defined twice, so we need to find another default for either `layout stacking` or `splith`. i3 uses `$mod+h` for `splith` but that is used for `focus left` in sway, so I'm not sure what the best default would be?

**Comment by progandy** [comment]
i3 moves the hjkl movement one key to the right, to "jklö" with a german layout. I hated that, so I set it back to the well-known hjkl and moved splith to $mod-b, since b was unset and is next to $mod-v for the vertical split

**Comment by mikkeloscar** [comment]
@progandy I like the idea of using `$mod+b` for `splith` and keep the `hjkl` movement default in sway. What do you think about that approach @SirCmpwn?

**Comment by SirCmpwn** [comment]
That's agreeable to me.

**Comment by diegoviola** [comment]
Thanks.
