### ISSUE TITLE
Some GTK apps maintain its default window header

### ISSUE THREAD

**Issue by jarias** [SirCmpwn/sway#594]
OS: `Linux lucy 4.5.1-1-ARCH #1 SMP PREEMPT Thu Apr 14 19:19:32 CEST 2016 x86_64 GNU/Linux`

Sway Package version `0.5-2`
WLC Package version `0.0.2-1`

![2016-04-21-225359_swaygrab](https://cloud.githubusercontent.com/assets/119519/14756596/d51f9c4a-08a7-11e6-8dce-f6937a04d6bb.png)

Don't know if related but also some modal windows don't show as floating windows.

![2016-04-21-230935_swaygrab](https://cloud.githubusercontent.com/assets/119519/14756648/5cd29a16-08a8-11e6-8e74-a10e477f13bd.png)

Can share my config file if needed

**Comment by SirCmpwn** [comment]
[FAQ](https://github.com/SirCmpwn/sway/wiki#disabling-client-side-gtk3-decorations)

**Comment by jarias** [comment]
@SirCmpwn thanks for pointing to the FAQ page I guess I miss that one, just one question how come i3 doesn't have this issue, is it a X11 trick? Patching every app that have this issue doesn't seem like a manageable solution, also having a patch version GTK could also be a pain in the long run.

**Comment by SirCmpwn** [comment]
Yes, this is a wayland specific problem.
