### ISSUE TITLE
Sway treats comments as arguments

### ISSUE THREAD

**Issue by FSMaxB** [SirCmpwn/sway#60]
When running sway, I get (amongst others) the following error message:

    Handling command 'set $mod Mod4       # Logo key. Use Mod1 for Alt.'
    Invalid set command.(expected 2 arguments, got 9
   Command failed: set

It looks like it interprets the comment at the end of the line as arguments to the set command.

(commit 786bb87, using AUR package sway-git)

**Comment by SirCmpwn** [comment]
Thanks for letting us know!
