### ISSUE TITLE
Error setting gaps in config file

### ISSUE THREAD

**Issue by sklv** [SirCmpwn/sway#600]
I have the following lines in my config:

```
#gaps
smart_gaps on
gaps outer all set 0
gaps inner all set 5
```

Which results in the following log output when loading the config file:
```
find_handler(smart_gaps) 0
handling config command 'gaps outer all set 0'
find_handler(gaps) 0
Error on line 8 'gaps outer all set 0': Expected 'gaps edge_gaps <on|off|toggle>' or 'gaps <inner|outer> <current
|all|workspace> <set|plus|minus n>' (/home/sklv/.config/sway/config)
handling config command 'gaps inner all set 5'
find_handler(gaps) 0
Error on line 9 'gaps inner all set 5': Expected 'gaps edge_gaps <on|off|toggle>' or 'gaps <inner|outer> <current
|all|workspace> <set|plus|minus n>' (/home/sklv/.config/sway/config)
```

sway version is 0.5-12-gd848241 (2016-04-24, branch "branch-master")
wlc version is 0.0.2

**Comment by mikkeloscar** [comment]
As I understand from the man page (and the source) this is a runtime only command, to change gaps at runtime.

If you wanna set the default gaps, just use: `gaps outer 0` and `gaps inner 5`

**Comment by mikkeloscar** [comment]
The error message could be better though.
