### ISSUE TITLE
Weird dialog windows

### ISSUE THREAD

**Issue by jarias** [SirCmpwn/sway#604]
Some dialog windows don't show as floating windows others appear too small to be used or resize.

Arch Linux
`Sway 0.5-2`
`wlc 0.0.2-1`
`xwayland 1.18.3-1`

![2016-04-26-090555_swaygrab](https://cloud.githubusercontent.com/assets/119519/14823724/c78c4e98-0b90-11e6-913a-78de94778d85.png)

In this example the small black square is the dialog window it appears floating but the size is useless, can't even resize it.

![2016-04-26-092032_swaygrab](https://cloud.githubusercontent.com/assets/119519/14823774/f5d49f6c-0b90-11e6-88fa-2bef3e68b418.png)

**Comment by johnp** [comment]
Workaround for the probably Java-related case (happens to me in Jetbrains IDEs, JDownloader, Cisco ASDM): Selecting floating fragment and change to fullscreen. Won't be able to switch back though. Would be interesting if setting some minimum size for floating windows in case their dimensions can't be inferred helps.

**Comment by SirCmpwn** [comment]
Does #691 fix this for you?

**Comment by jarias** [comment]
@SirCmpwn would test that out as soon as I can.

**Comment by jarias** [comment]
@SirCmpwn It work for the minimum size now at least its usable not great cause manual resize is till needed but at least I can resize it now, but for the libreoffice example still works the same way the dialog is not floated and not clickable either

**Comment by SirCmpwn** [comment]
Yeah I figured LO wouldn't be helped but I'm glad to hear the other one is better.
