### ISSUE TITLE
layout misinterpretation

### ISSUE THREAD

**Issue by lordtoniok** [SirCmpwn/sway#608]
When using "exotic" layout (french bépo) sway doesn't interpret well every shortcuts 

you can't mod+1, mod+2, mod+3 or altmod+1, altmod+2, altmod+3 … to change workspace or move windows to workspace. sway doesn't grab it.

Sway doesn't interpret well non ascii characters 

> Error on line 86 'bindsym $mod+é exec …': Unknown key 'é'

**Comment by SirCmpwn** [comment]
How about binding with bindcode instead of bindsym?

**Comment by mikkeloscar** [comment]
Does `$mod+é` work in i3? It's not recognized in sway because the keyname of `é` is `eacute` in xkb.

**Comment by lordtoniok** [comment]
I tried bindcode $mod+10 workspace 1 but it failed too. Keys are still sent to the focused terminal.

yes $mod+é works in i3.

If i start sway on qwerty layout it works well.
Numbers aren't on direct access on the bépo layout but need to be shifted.

**Comment by SirCmpwn** [comment]
Should be fixed by #611, please confirm

**Comment by lordtoniok** [comment]
I confirm it works with bindcode now.

**Comment by mikkeloscar** [comment]
Regarding `$mod+é`. i3 can't parse it either:
```
2016-04-29 10:18:03 - ERROR: Could not translate string to key symbol: "é"
```
So I don't understand how it could work for you. The right thing is to use `$mod+eacute`.

**Comment by concatime** [comment]
Hey. While setting my `$right` to `'`, I came across this issue. Using `bindcode` solved this issue. I think it would be wise If we add to the wiki.

**Comment by SirCmpwn** [comment]
Wikis are publically editable.
