### ISSUE TITLE
Clicks are passed through to native wayland clients after switching the workspace

### ISSUE THREAD

**Issue by Hummer12007** [SirCmpwn/sway#626]
Steps to reproduce:
1) Hover over something clickable in a native wayland client.
2) Switch to another workspace.
3) Click.

**Comment by SirCmpwn** [comment]
Focus does move, but the mouse focus doesn't seem to come along. Paging @Cloudef cause it's probably a wlc issue.

**Comment by Cloudef** [comment]
Yeah, wlc doesn't update focused view in this case.

**Comment by SirCmpwn** [comment]
Closing cause WLC issue.
