### ISSUE TITLE
Support of custom modelines

### ISSUE THREAD

**Issue by hashashini** [SirCmpwn/sway#631]
Are there any means to use a modeline not exported by edid?
(like e.g. in weston, cf. https://wiki.archlinux.org/index.php/wayland#Configuration (second [output]-section from bottom in ~/.config/weston.ini))

**Comment by SirCmpwn** [comment]
Modesetting of any kind isn't supported by WLC yet.

**Comment by nirbheek** [comment]
Am I correct that wlroots supports this now since https://github.com/swaywm/sway/issues/631, is it possible to implement this feature in sway-output now?

**Comment by emersion** [comment]
Sway supports this, see the man page (grep for `--custom`).

**Comment by nirbheek** [comment]
That only lets me specify the `WIDTHxHEIGHT@RATE` that's not in the EDID, not the [full modeline](https://en.wikipedia.org/wiki/XFree86_Modeline#Syntax) which is often necessary for displays that do not specify an EDID at all.

In retrospect, that's not what the original issue was asking for, so I'm posting this in the wrong issue. Should I open a new one?

**Comment by emersion** [comment]
Can you explain why you need the full modeline? wlroots will automatically generate it.

**Comment by nirbheek** [comment]
wlroots can't automatically generate modes if there's no EDID information from the display. In that case you need to either specify the EDID blob yourself using the `edid_firmware` drm/kms-helper module param or if you don't have the EDID, you need to specify the full modeline. Weston has an option for this for precisely this reason, see `man 7 weston-drm`, search for `mode=dotclock [...]`.

**Comment by emersion** [comment]
[wlroots can](https://github.com/swaywm/wlroots/blob/master/backend/drm/cvt.c)

**Comment by nirbheek** [comment]
That's auto-detection/guessing, isn't it? How do we ensure that it's correct?

**Comment by tdaede** [comment]
I would like support for custom (non-cvt) modelines, for switchres (a program that generates special arcade monitor modes). Would you accept a wlroots patch from me?

**Comment by emersion** [comment]
wlroots already supports this.

Why isn't the custom mode support enough?

**Comment by tdaede** [comment]
The only public API seems to be wlr_output_set_mode() and wlr_output_set_custom_mode(), the latter of which at least only generates a CVT timing modeline. Arcade timings are generally non-CVT timings, generally closer to CEA timing. The main differences are active area and sync polarity, though there are also interlaced modes (gross I know).

I could also write directly to the drm device, but I don't think there is a good way to synchronize wlroots' state with it.

**Comment by emersion** [comment]
`wlr_drm_connector_add_mode`

**Comment by tdaede** [comment]
Ah, I totally missed that was in a public header. That's exactly what I want, thanks!

**Comment by tdaede** [comment]
Ah, I totally missed that was in a public header. That's exactly what I want, thanks!
