### ISSUE TITLE
XDG_CONFIG_HOME not used / potential overflow

### ISSUE THREAD

**Issue by steven-jackson** [SirCmpwn/sway#64]
I have a patch for this but as I'm in work I can't build and test it - https://gist.github.com/steven-jackson/b388215f239af9f9bfe0

sway/config.c Lines 43 and 96

As you can see the home variable is copied to temp, but xdg_config_home contains the path that should be copied. If home is larger than xdg_config_home then an overflow can occur.

**Comment by SirCmpwn** [comment]
Thanks! I fixed that bug, but I didn't feel that it was necessary to merge your entire patch for several reasons.

**Comment by steven-jackson** [comment]
Okay...

**Comment by SirCmpwn** [comment]
Well, to elaborate:

* Several style errors in your code
* Not convinced it's necessary to add a whole join function
* This code is slated to be rewritten later anyway

So, not worth the effort.

**Comment by steven-jackson** [comment]
1. It matches the style perfectly - there is already inconsistent attachment of pointers to types / identifiers and inconsistent use of space before an opening bracket.
2. You can check for a NULL return from malloc in a single place instead of fixing it in each place, which is what I should have done.
3. Irrelevant

Apparently it wasn't worth my effort either.
