### ISSUE TITLE
Disabling outputs does not move Desktops

### ISSUE THREAD

**Issue by somebears** [SirCmpwn/sway#641]
I use sway on my Laptop. At home, I use it in conjunction with a docking station and a second monitor.

When I use the dual screen setup and then remove the Notebook from the docking station, all outputs + desktops remain active. 

If I remove the secondary output with
`swaymsg output <output> disable`
it gets removed and I can't move my mouse there anymore. However my desktop still resides there.

I can move all desktops to my primary screen, but I end up with one not being visible anymore (as in probably still sending the output so my disabled second monitor)

The proper behaviour would probably be to move all desktops back to the primary output

**Comment by SirCmpwn** [comment]
Is this still reproducable?

**Comment by somebears** [comment]
I don't know, I unfortunately had to switch to proprietary drivers and away from wayland/sway.

**Comment by SirCmpwn** [comment]
Closing this until you get a chance to verify. It was likely fixed in ce98569.
