### ISSUE TITLE
swap caps and escape?

### ISSUE THREAD

**Issue by mpolitzer** [SirCmpwn/sway#651]
tried: setxkbmap -option 'caps:swapescape'
however works partially, not sure if a sway problem (or even its responsability)

What happened:

1. open a terminal
2. run: setxkbmap -option 'caps:swapescape'
3. escape toggles to and from capital letters
4. open a new terminal
5. small letters on new terminal, capital on previous.

(The caps key still toggles the led even thou now it is escape)

Could be related to the terminals running in XWayland

Great job on sway btw!

**Comment by SirCmpwn** [comment]
Read the FAQ https://github.com/SirCmpwn/sway/wiki#why-is-my-keyboard-layout-wrong
