### ISSUE TITLE
Sway cannot handle spaces in file path to desktop background.

### ISSUE THREAD

**Issue by tajjada** [SirCmpwn/sway#654]
I have a background switching script (chooses a random image file from a directory, and uses swaymsg to change my background), which runs:

`swaymsg "output DP-2 bg \"${PATH}\" fill"`

It works fine, as long as there are no spaces in the filename. If there is a space in the filename, it fails. Here are the relevant messages from the sway log:

```
Handling command 'output DP-2 bg "/home/tajjada/Pictures/Wallpapers/wide/02 - Antelope Canyon Sunrise.jpg" fill'

IPC Client -1 disconnected{ "success": false, "input": "output", "error": "Background file unreadable (\/home\/tajjada\/Pictures\/Wallpapers\/wide\/02)" }

```

As you can see, it chokes on the first space in the path. I even tried wrapping the whole path in quotes (as you can see). Without the quotes, it (obviously) didn't work either.

It would be nice if sway could handle spaces in paths correctly.

**Comment by beanaroo** [comment]
Spaces are generally input field separators. I don't think this is a sway problem. The script generating the image ${PATH} variable (which is a system variable name, by the way) is not escaping spaces correctly. It should be expanded to:

    Handling command 'output DP-2 bg "/home/tajjada/Pictures/Wallpapers/wide/02\ -\ Antelope\ Canyon\ Sunrise.jpg" fill'

**Comment by tajjada** [comment]
I just assumed that if the path is inside quotes, spaces do not need to be escaped.

I guess quotes have no effect in the sway config, then.

**Comment by mikkeloscar** [comment]
sway should handle things in quotes as a single argument, so a path with spaces should work if it's in quotes. It's indeed a bug that it doesn't work.

**Comment by FlyingWombat** [comment]
It seems this has popped back up again.
Well, at least in sway-wlroots it has; not sure about sway-wlc.
Sway Version:
sway-wlroots-git 1.0.alpha.5.r334.gdbaafdfa-1  (commit# = dbaafdf)
wlroots-git r3065.769a8e99-1 (commit# = 769a8e9)

I have two image files to set as background: `asdf.jpg` and  `as df.jpg`
setting background for `asdf.jpg` works as expected 
Using `swaymsg output eDP-1 bg "~/asdf.jpg" fill` with or without quotes.

Setting 'as df.jpg' does not work using either
`swaymsg output eDP-1 bg "~/as df.jpg" fill`
`swaymsg output eDP-1 bg ~/as\ df.jpg fill`

**Comment by SirCmpwn** [comment]
Does `swaymsg output eDP-1 bg ~/"as df.jpg" fill` work?

**Comment by FlyingWombat** [comment]
No, that doesn't work either.

**Comment by emersion** [comment]
Does `swaymsg output eDP-1 bg \"~/as\ df.jpg\" fill` work?

**Comment by FlyingWombat** [comment]
No, that also does not work.
Is this working for you?

**Comment by FlyingWombat** [comment]
Thanks to @RedSoxFan  for the fix
I found one more issue, though.
That is ` swaymsg output eDP-1 bg "~/asdf(1).jpg" fill ` doesn't work.
I get `Error: Invalid syntax (~/asdf(1).jpg)`

**Comment by Nomeji** [comment]
The bug seems to be fixed for swaybg but not for swaylock.

I have an image called "foo bar.jpg" in ~

```
[nomeji@Yuu ~]$ swaylock -i foo bar.jpg
2018-12-10 22:32:21 - [sway/swaylock/main.c:889] Parsing CLI Args
2018-12-10 22:32:21 - [sway/common/background-image.c:32] Failed to load background image (Failed to open file “foo”: No such file or directory).
2018-12-10 22:32:21 - [sway/swaylock/main.c:248] output name is LVDS-1
[nomeji@Yuu ~]$ swaylock -i "foo bar.jpg"
2018-12-10 22:32:27 - [sway/swaylock/main.c:889] Parsing CLI Args
2018-12-10 22:32:27 - [sway/common/background-image.c:32] Failed to load background image (Failed to open file “foo”: No such file or directory).
2018-12-10 22:32:27 - [sway/swaylock/main.c:248] output name is LVDS-1
[nomeji@Yuu ~]$ swaylock -i foo\ bar.jpg
2018-12-10 22:33:16 - [sway/swaylock/main.c:889] Parsing CLI Args
2018-12-10 22:33:16 - [sway/common/background-image.c:32] Failed to load background image (Failed to open file “foo”: No such file or directory).
2018-12-10 22:33:16 - [sway/swaylock/main.c:248] output name is LVDS-1
[nomeji@Yuu ~]$ ls -l "foo bar.jpg" 
-rw-rw-rw- 1 nomeji users 81765 Jan 11  2013 'foo bar.jpg'
```
