### ISSUE TITLE
Capslock keyboard layout switch isn't work as expected

### ISSUE THREAD

**Issue by Svadkos** [SirCmpwn/sway#657]
While other methods, like alt+space, works well, capslock seems buggy. 
On start in every text field(urxvt, dmenu etc), language not changing, and need to press capslock 3 times, to change it.

Variables
export XKB_DEFAULT_OPTIONS=grp:caps_toggle,grp_led:scroll,compose:ralt

**Comment by roosemberth** [comment]
workaround: create a layout file and export it before launching sway:
```
XKB_DEFAULT_LAYOUT=MyLayout GDK_BACKEND=wayland sway -d &>/var/log/sway/logfile
```
with file available at `/usr/share/X11/xkb/symbols/MyLayout` and containing and xkb symbols definition

the following is an example for swapping caps lock with escape and left control with left shift:
```
xkb_symbols "MyCustomLayout" {
    // Base keyboard layout: /usr/share/X11/xkb/symbols/ch section fr
    include "ch(fr)"
    // Swap caps with escape
    key <CAPS> { [ Escape ] };
    key <ESC>  { [ Caps_Lock ] };
    // Swap left shift with control
    key <LFSH> { [ Control_L ] };
    key <LCTL> { [ Shift_L ] };
};
```

**Comment by SirCmpwn** [comment]
Please report to wlc.

**Comment by sofutru** [comment]
@ddevault I've set keyboard layout switch to Caps, and no keyboard shortcut works for me, do i report it to wlroots?
