### ISSUE TITLE
Cursor "flows" away on synaptics touchpad

### ISSUE THREAD

**Issue by mersinvald** [SirCmpwn/sway#660]
Just trying out wayland and sway, so I'm not sure if compositor has something to do with this issue.

Problem: When touchpad is touched continuously in any manor, cursor slightly goes top-right, making pointing unusable.
Screencast: https://www.youtube.com/watch?v=M5Mmcl8YVSs&feature=youtu.be

**Comment by SirCmpwn** [comment]
https://github.com/Cloudef/wlc/issues/126
