### ISSUE TITLE
Switching to tabbed layout, when windows have no border, results in tabs not being rendered.

### ISSUE THREAD

**Issue by tajjada** [SirCmpwn/sway#661]
How to reproduce:

1) Open a couple of windows with 'border none', to have no borders.
2) Switch to tabbed layout with 'layout tabbed'.
3) Notice that there is an empty area where the tabs should be.
4) Change one of the windows to 'border normal', and the tab appears.

Tabs should always be rendered, even if the windows were set to 'border none', like in i3.

**Comment by andya9** [comment]
IMHO if border is set to none the window should be enlarged to fill the screen; I don’t like i3 behaviour here.

**Comment by tajjada** [comment]
@andya9 
That is another way to handle the situation, yes. I actually agree with you that it might be a better way to do it. However, sway aims to be an exact i3 replacement, intending to behave exactly like i3, so it should probably be done the same way as i3 does it.

Either way, currently, the situation is not handled properly, as neither of the two is being done, and there is just an empty space. Screen space wasted (unlike your proposal), and tabs not drawn (unlike i3 behaviour).
