### ISSUE TITLE
Switching from a workspace with a full screen app to an empty one does not redraw the screen

### ISSUE THREAD

**Issue by Hummer12007** [SirCmpwn/sway#665]
(At least when the pointer is not moved after switching to the workspace with the full-screen app and until the pointer is moved).
I had this in mpv with the opengl-hq/x11 backend (only when the video is paused).
Steps to reproduce:
~~1) Open fullscreen mpv in a workspace
2) Stop moving your pointer
2) Switch from another non-empty (?) workspace (don't move your pointer yet) to the mpv workspace
4) Switch to an empty workspace
..nothing happens..
5) Move your pointer
6) The screen is updated!~~
1) Pause fullscreen mpv
2) Switch to another empty workspace
...Nothing happens
3) Move your pointer
4) The screen is updated

**Comment by SirCmpwn** [comment]
Unable to reproduce.

**Comment by FreeFull** [comment]
I'm not able to reproduce this either.

**Comment by Hummer12007** [comment]
Unable to reproduce in recent head neither.
