### ISSUE TITLE
Disconnecting an external screen wronlgy reorders workspaces

### ISSUE THREAD

**Issue by psgarsenal** [SirCmpwn/sway#669]
Let's say display 1 has the following workspaces: [1][10]
And display 2 has the following: [4][5]

When unplugging display 2, on display 1 the workspaces won't be [1][4][5][10] but [1][10][4][5]

**Comment by progandy** [comment]
delete_output doesn't do the same as new_workspace and has to be fixed.

delete_output: https://github.com/SirCmpwn/sway/blob/master/5b0af661b0b369a4edba71eb3c5d0a9ad81428ce/container.c#L354
new_workspace: https://github.com/SirCmpwn/sway/blob/5b0af661b0b369a4edba71eb3c5d0a9ad81428ce/sway/container.c#L183
