### ISSUE TITLE
Regressions with workspaces and focus

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/sway#67]
There were several problems with multiple outputs introduced by the focus changes in #65 that I missed.

* Last workspace on an output is destroyed, leaving output inaccessible (Fixed by a64b10df83f84e7ee8933ac139f10c59bfd76466)
* Setting focus for outputs is broken (Fixed by a64b10df83f84e7ee8933ac139f10c59bfd76466)
* When leaving a workspace for one on another output, when the destination output has no views, the window on the previous output remains activated
* Switching outputs with `focus` commands no longer works if the destination output has no views

cc @taiyu-len

**Comment by taiyu-len** [comment]
yep, working on fixing it up.
