### ISSUE TITLE
Running without xwayland?

### ISSUE THREAD

**Issue by Chrysostomus** [SirCmpwn/sway#676]
Is it possible to run sway without xwayland with only wayland native apps? If so, what are the steps to do this?

Sway seems to perform exceptionally well, but the ram usage is high compared with other tiling window managers. This completely fine, since as a wayland compositor it also performs most of the functions that are usually done by xorg. However, this makes running xwayland feel excessive. On my system xorg takes about 16-40mb depending on what I'm doing. Xwayland always starts at 41mb.

Anyway, I really like this project! I'll probably build a distrolette around within few years.

**Comment by SirCmpwn** [comment]
>Is it possible to run sway without xwayland with only wayland native apps? If so, what are the steps to do this?

Just don't install Xwayland, or run sway with WLC_XWAYLAND set to 0.

>Sway seems to perform exceptionally well, but the ram usage is high compared with other tiling window managers.

This is mostly because of the memory leaks that are all over sway. They'll be cleaned up prior to 1.0. You're right, though, it's not fair to compare Sway's memory usage to X window managers. Better to compare it to X window managers usage plus Xorg memory usage.

**Comment by Chrysostomus** [comment]
Many thanks! I currently use bspwm, but I'll probably transition to to sway when wayland ecosystem matures. I'm very excited about this project!

**Comment by emersion** [comment]
You can't start Xwayland manually.

Note that you can now disable Xwayland in the config file.

**Comment by damianatorrpm** [comment]
@emersion Thanks!

**Comment by martin-braun** [comment]
In a proxmox KVM, if I attempt to start `sway` with Virtio-GPU I get "server.c:282 Failed to start Xwayland binary /usr/bin/Xwayland DRI: failed to create screen" despite not having `xwayland` installed and `WLC_XWAYLAND` set to `0`.

Why is that?
