### ISSUE TITLE
Bar invisible on restart until 2nd window opened

### ISSUE THREAD

**Issue by tuncer** [SirCmpwn/sway#678]
If you restart while only one window exists, the bar will stay invisible until you open a 2nd window.

**Comment by SirCmpwn** [comment]
I suspect WLC issues here.

**Comment by SirCmpwn** [comment]
Possibly related: swaylock issues on multiple outputs.

**Comment by tilpner** [comment]
On `reload`, the bar only shows if there are windows with `border normal` for me. Maybe this is related?
