### ISSUE TITLE
xterm text corruption

### ISSUE THREAD

**Issue by tuncer** [SirCmpwn/sway#679]
Text in xterm is randomly corrupt such that some characters are only drawn partially. No such issue when running the same xterm under Weston.

**Comment by SirCmpwn** [comment]
Can you reproduce this problem with orbment?

**Comment by tuncer** [comment]
I'll try to build and run orbment for comparison.

**Comment by tuncer** [comment]
Same corruption with xterm under orbment.

**Comment by SirCmpwn** [comment]
Report to wlc.

**Comment by tuncer** [comment]
Okay, done: Cloudef/wlc#170.
