### ISSUE TITLE
Config segfaults

### ISSUE THREAD

**Issue by tuncer** [SirCmpwn/sway#681]
I've run into segfaults with two config modifications:

1. uncomment the suggested `hostname` include as found in the sample config file
2. `set wallpaper ~/some_path/some_pic.jpg` and then try to reference `$wallpaper` in the wallpaper directive

Both crash immediately on startup and are very easy to reproduce.

**Comment by SirCmpwn** [comment]
@tuncer is this fixed with #673 and #703 merged?

**Comment by tuncer** [comment]
Thanks, b63b011 doesn't crash anymore, closing.
