### ISSUE TITLE
Firefox (gtk2) Clear Recent History dialog dimensions

### ISSUE THREAD

**Issue by tuncer** [SirCmpwn/sway#682]
Firefox's Clear Recent History dialog's dimensions are not respected and you get a squished dialog which I oddly enough wasn't able to resize with the mouse.

**Comment by ids1024** [comment]
I have seen this behaior too (though not in firefox, which I don't use). Using mod4+shift+space to switch the window out of floating mode seems to resize it to something usable.

**Comment by SirCmpwn** [comment]
Does #691 fix this for you?

**Comment by tuncer** [comment]
Unfortunately, it doesn't. The window dimensions looks similar to the vertically large, horizontally small floating mpv (aka like a column), just not as high as the mpv window. Tested with `sway version 0.6-107-g09670fc (2016-06-02, branch "master")`.

**Comment by tasn** [comment]
I get this in many places in Firefox. The easiest to reproduce is the window that pops when you click on the toolbar icon of the extension "uMatrix". I've also seen it many times already in other places too, just can't remember where.

**Comment by tuncer** [comment]
As of today's build that's using https://github.com/Cloudef/wlc/commit/e3abf0b2f322b9d376ced452190cd4dd9f6fcb8a and https://github.com/SirCmpwn/sway/commit/ea0f1f3a7edf92537f74b70b520103bb38ff1411
the issue persists for me with Firefox, which now exclusively uses GTK+3, since GTK+2 support has been dropped.

1. Clear setting dialog dimension ignored (it's correctly floating, though)
2. About dialog is tiled but dimensions are not broken
3. Firefox update progress bar dialog is not floating but tiled and as a GTK+3 window gets stretched and zoomed in. It doesn't get tiled in a useful way like About.

Is this issue tracked in a different ticket, or should this one be re-opened?
