### ISSUE TITLE
Binding swaylock

### ISSUE THREAD

**Issue by tuncer** [SirCmpwn/sway#683]
I'm probably doing this wrong, but I tried to bind swaylock to `$mod+Shift+l`, and neither that nor `Mod4+Shift+l` worked. I could only get `Mod1+Shift+l` to execute swaylock.

**Comment by SethBarberee** [comment]
Try those commands with a plus instead and see if that works. Mine is like this:

`bindsym $mod+Print exec swaylock -i ~/wallpaper/angelswaylock.png -s fill`

**Comment by tuncer** [comment]
It's actually `+` in the config file and these are typos in the ticket only.

**Comment by SethBarberee** [comment]
Can you post your config file?

**Comment by tuncer** [comment]
This works:

```
bindsym Mod1+Shift+l exec swaylock -c 333333 -s fill -i ~/some_wallpaper.jpg
```

These don't:

```
bindsym Mod4+Shift+l exec swaylock -c 333333 -s fill -i ~/some_wallpaper.jpg
```
```
bindsym $mod+Shift+l exec swaylock -c 333333 -s fill -i ~/some_wallpaper.jpg
```

**Comment by tuncer** [comment]
I found the culprit. The default config has $mod+Shift+l bound to `move right`.

**Comment by tuncer** [comment]
Solved by removing default binding.
