### ISSUE TITLE
Cannot change focus or switch workspaces by clicking on titlebars and workspace tabs respectively 

### ISSUE THREAD

**Issue by vadixidav** [SirCmpwn/sway#688]
In i3 one can click on a titlebar in a tabbed or stacked window to change focus to that choice. You can also click on workspace tabs to switch workspaces. Since I have started using sway, I have realized that these things are not possible in sway (unless there is some option to enable this). Perhaps this feature is so little used by most that it went unnoticed? I do not need this feature, but I remember it being sometimes more convenient to click on things than always use the keyboard, and it is necessary to be feature-parity with i3.

**Comment by psgarsenal** [comment]
This is due to swaybar not handling clicks for the moment, this is on the feature list of this project's website. So, not possible for now.

**Comment by vadixidav** [comment]
@psgarsenal Does that also account for the titlebars as well? I wasn't aware they used the same system, but they do look similar now that I look. It looks like swaybar is in this repository either way, so this is the right place then.

**Comment by SirCmpwn** [comment]
This is not currently implemented.

**Comment by camoz** [comment]
Switching workspaces via mouse clicks seems to work now, but switching tabbed/stacked windows by clicking on their title bar still doesn't work yet.
