### ISSUE TITLE
When clicks are handled by sway, do not send them to clients

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/sway#69]
cc @Luminarys

**Comment by Luminarys** [comment]
We currently only block the clicks from going through if `(pointer && pointer != focused)` where pointer is the container under the pointer, does this need to be expanded?

**Comment by SirCmpwn** [comment]
Yes. When you do movement or resizing, we shouldn't send those clicks through.

**Comment by Luminarys** [comment]
Ok, so just check if the pointer is over a floating window, and if so, deny the request?

**Comment by Luminarys** [comment]
What I said above will end up denying all clicks to floating windows which is bad. The only way around this is to check for the floating_modifier key being held as the click happens, but this is not what i3 does. I think we should just allow clicks to happen, honestly.

**Comment by SirCmpwn** [comment]
>What I said above will end up denying all clicks to floating windows which is bad. The only way around this is to check for the floating_modifier key being held as the click happens, but this is not what i3 does. I think we should just allow clicks to happen, honestly.

This is what i3 does.

**Comment by Luminarys** [comment]
Yea you're right, my bad. I was somehow checking in i3 incorrectly, so I mispoke.

**Comment by taiyu-len** [comment]
fixed all that in #79, checks if floating_modifier is pressed, and sets dragging/resize state or sends key to client.
