### ISSUE TITLE
Feature Request: Support for sequences of commands in configuration files

### ISSUE THREAD

**Issue by roosemberth** [SirCmpwn/sway#700]
This feature would be similar to shell repetition expansion.
e.g.:
```
bindsym $mod+{b,v} {splith,splitv}
```
would expand to
```
bindsym $mod+b splith
bindsym $mod+v splitv
```

Similar features are found on [sxhkd](https://github.com/baskerville/sxhkd) and [zsh](http://www.zsh.org/).

I'd be willing to implement it myself if this proposal would get merged.

**Comment by SirCmpwn** [comment]
I think that this adds unnecessary complexity. If you want a more complex configuration file, then I've generally suggested invoking a bash script and using swaymsg from the script to perform further configuration.

**Comment by SirCmpwn** [comment]
Since no one has chimed in to support this idea, I'm closing the issue.
