### ISSUE TITLE
Is there a way to get the functionality of xset?

### ISSUE THREAD

**Issue by person666** [SirCmpwn/sway#712]
I have not been able to figure out how to enable my keyboard back-light. With X I used `xset led 3`. How can I achieve the same with sway? I think I am missing something obvious.

**Comment by progandy** [comment]
I think the keyboard leds are managed by libinput without any way to toggle them manually.

**Comment by Hummer12007** [comment]
@person666 you need to take a look at your /sys/class/leds and set the brightness directly via sysfs.
