### ISSUE TITLE
A regression in split {h|v} behavior

### ISSUE THREAD

**Issue by Hummer12007** [SirCmpwn/sway#714]
The commands in question are (sort of) ineffective. In the git head as of today, so as well as of the latest release.
Works for the only container on a workspace tho.
Attached an example screencast: https://u.sicp.me/nKgSj.mp4
An example log (I've tried to split v than split h): https://u.sicp.me/hxeER.txt

**Comment by Hummer12007** [comment]
`git-bisect(1)` showed that this was probably introduced by 0f1859ed.

**Comment by SirCmpwn** [comment]
I don't really understand how 0f1859e could be involved. I'm using the latest release and split h/v works as expected for me.

**Comment by aereaux** [comment]
I am experiencing the same issue on sway 0.8.  Seems to be the same as or related to #710.  Interestingly, when I open a new window from a terminal (for example calling mpv somefile), it behaves as expected.
