### ISSUE TITLE
Support for color temperature

### ISSUE THREAD

**Issue by psgarsenal** [SirCmpwn/sway#722]
Hi, I have asked here: Cloudef/wlc#174 if there was a way to have support of applications like redshift in wlc.
It appears that it is needed to add a protocol in sway to support it, like it is done in this compositor https://github.com/giucam/orbital/blob/gamma/protocol/gamma-control.xml ?
Thanks for reading !

**Comment by SirCmpwn** [comment]
I think this belongs in wlc.
