### ISSUE TITLE
swaylock behaves differently than i3lock

### ISSUE THREAD

**Issue by tasn** [SirCmpwn/sway#725]
Hey,

The swaylock process exits after it has been unlocked, i3lock exits once the lock screen is up. This makes i3lock much easier to use, because you can do things like: "i3lock && suspend" and use it as a key binding, while with swaylock it is not possible.

Reproduce:
swaylock && date
// Unlock
i3lock && date
// Unlock

See that in i3lock the date is much earlier (time of lock compared to time of unlock).

Thanks.

**Comment by sleep-walker** [comment]
It behaves the same was as slock so it fits me. You could do something like
```
swaylock & sleep 1; date
```

**Comment by SirCmpwn** [comment]
I don't know if I really appreciate this behavior of i3lock. I would merge a PR that adds -f (fork) to swaylock, though.

**Comment by tasn** [comment]
That's a hack, no the same. What if locking takes 10 seconds due to system
load? Or fails?

**Comment by sleep-walker** [comment]
It's hack, I agree. Clean solution is the one @SirCmpwn already proposed. Nice to see using sway ;)

**Comment by tasn** [comment]
I've always been meaning to give i3 and wayland a proper go, so I thought I'd kill two birds with one stone. :)

Unfortunately though, I've encountered a lot of bugs, mostly with xwayland, some with sway, and one with sway/gtk3 (gnome-calculator). I haven't gotten around to reporting them all, because still unsure what I'm supposed to report as I guess everything is still WIP.

**Comment by SirCmpwn** [comment]
Please report the bugs you find. As for gnome-calculator, does this fix it for you?

    for_window [id="gnome-calculator"] floating enable; border pixel

I've been thinking about distributing some default window rules with sway, anyone else have some thoughts?

**Comment by tasn** [comment]
@SirCmpwn, OK, will try to get around to reporting them.

As for gnome-calculator, yes, making it float fixes it. I wrote the tiling module for www.enlightenment.org so I'm all too familiar with these issues. When I wrote it, I only had X in mind, not sure about all of the Wayland equivalents, but I'm sure there are.

I'd strongly advise against touching the default window rules. That is just an annoying cat and mouse game that will always be frustrating. The more correct approach in my POV (and what I did in Enlightenment) is to automatically float certain windows. If for example a window has a minimum/maximum size that you can't cater to (because of other minimum/maximum size constraints, for example), make it float, if a window is fixed size (like gnome-calculator), make it float, if a window is a dialog (there are a few classes in X, I forgot atm), make it float. You get the drill.

These are roughly the rules I put in the Enlightenment tiling module, don't allow tiling (force floating) if:

1. min size == max size (in the relevant direction) and they are > 0. Though the more correct thing is to see if catering to both min and max size in both directions will violate constraints. This is essentially the gnome-calculator issue iirc.
2. window requested to be centred (don't know if there's a wayland equivalent there).
3. If the config option to tile dialogs is off and a window is a dialog or "transient for".
4. If the window is fullscreen/maximized/iconic (minimized)/sticky
5. If the window is ignored (like root window, bars and etc).

I hope this helps.

**Comment by SirCmpwn** [comment]
Those rules are sane, but the information you mention isn't being bubbled up to us in Wayland.

**Comment by tasn** [comment]
@SirCmpwn, I checked with a colleague that works on Wayland, and unfortunately:
Min/Max/Centred aren't standardised yet, I wonder though, should sway just support whatever people are doing already in different toolkits (if that even exists).
Windows can have parents so that solves the dialog/transient for issue I guess? Or do parents have other meanings too.

Maybe as a hack it's a good idea to have defaults now, but this feels so wrong, and once the gates open, you'll just start maintaining a massive list of such hacks for a million different scenarios. Not fun. :|

**Comment by SirCmpwn** [comment]
Well, presumably most of them would be added by users via PR when they find windows that need tweaking. In practice my list is pretty short (I have 5 window rules and some of them aren't really that important).

As for identifying parents for modals, I agree that we can detect that and handle it fine. The code needs to be updated to reflect that. Some changes just landed in wlc yesterday related to this as well.
