### ISSUE TITLE
Weird characters in titlebar with Hebrew text

### ISSUE THREAD

**Issue by tasn** [SirCmpwn/sway#730]
Hey,

Open firefox on http://www.ynet.co.il/home/0,7340,L-8,00.html
The tab title is full of garbage. It doesn't seem to be there in the source text, and it works in the tab title in firefox and under X with other WMs.

![Screen grab](https://cloud.githubusercontent.com/assets/108670/16480497/6c3f3c44-3e9e-11e6-9a2a-53c6d8dcd8cf.png)

**Comment by t0b1nux** [comment]
I think it depends of the font used: on my side it works (I'm using DejaVu Sans Mono 8).
![2016-06-30-181908_swaygrab](https://cloud.githubusercontent.com/assets/7265382/16499288/334200e2-3eef-11e6-9bd4-9202b61e89b6.png)

**Comment by SirCmpwn** [comment]
Make sure your sway and wlc are both up to date, and xwayland as well.

**Comment by t0b1nux** [comment]
It doesn't seem well supported everywhere however:
```
$ grep 'Setting focus to 0x1ce93a0' ~/.sway.log
[debug_log.c:94] Setting focus to 0x1ce93a0:3 (VIEW 'ynet - _____, ___)
[debug_log.c:94] Setting focus to 0x1ce93a0:3 (VIEW 'Commits _ SirCmpwn/sway )
```
I run sway with the shell script 
```
$ cat sw
#!/bin/sh
export XKB_DEFAULT_LAYOUT=fr
pulseaudio --start
sway -d 2> ~/.sway.log
```
But maybe it is my shell fault. I will check that.

**Comment by tasn** [comment]
Indeed fixed with latest sway and wlc from git.

It wasn't a font issue, but something was properly broken.
