### ISSUE TITLE
Significant performance regressions since 0.8

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/sway#741]
Sway idles at around 50% CPU on the latest git. This needs to be fixed before we ship 0.9.

**Comment by deklov** [comment]
For me it  idles well below 1%. If you don't mind, could you share your configuration file and I'll try to reproduce this. If you think it has nothing to do with how its configured, could you give some pointers on how to reproduce?

**Comment by SirCmpwn** [comment]
https://gogs.sr.ht/SirCmpwn/dotfiles

**Comment by deklov** [comment]
Can't reproduce. However, I found that when XXX in bar { status_command XXX } does not exist swaybar runs at 100% CPU.

**Comment by deklov** [comment]
Hey, @SirCmpwn maybe you could try what happens if you don't use your custom status command.

**Comment by N8Fear** [comment]
Yeah - I have had similar problems due to "wrong" settings in i3blocks (my status bar command uses it and sway sat at about 30% CPU utilization). Fixing my status bar helped and now it's normal again.
Maybe it would be a good idea to kind of rate limit the statusbar updates to protect users from their wrong configs...

**Comment by Hummer12007** [comment]
Sway idles at up to 50% usage in some cases for me too, although killing the bar does reduce cpu usage, it is not that significant.
@N8Fear statusbar just renders the last line (or JSON) output by a program. Sway has no control over the update rate whatsoever.

**Comment by SirCmpwn** [comment]
I solved this "problem" by not having debug logging enabled all the time. @Hummer12007 related?

**Comment by thejan2009** [comment]
This might be caused by floating windows - on my machine, idle CPU use by sway goes from 2% to 40-50%, and that's without logging.
