### ISSUE TITLE
Borders unchanged on focus parent

### ISSUE THREAD

**Issue by thejan2009** [SirCmpwn/sway#746]
Expected: Both child and parent containers' visuals change to indicate focus.

Actual: No visible change, although the right container is selected (subsequent actions operate on the right container).

To reproduce: Spawn 2 windows in split layout, focus parent.

**Comment by SirCmpwn** [comment]
Fixed?

**Comment by acrisci** [comment]
#811 will fix this.

**Comment by SirCmpwn** [comment]
Oh, okay. I misunderstood the bug and wasn't able to reproduce it.
