### ISSUE TITLE
Third level of window hierarchy crashes sway

### ISSUE THREAD

**Issue by Ferruck** [SirCmpwn/sway#751]
Sway crashes on my machine when I try to introduce a third level of window hierarchy. The steps I need to reproduce are:

1. Open a terminal with `$mod + d`
2. Open a second terminal
3. Switch to tabbed mode with `$mod + w`
4. Switch back to the first one and hit `$mod + b` to create the second level.
5. Open a third terminal
6. Again, switch back to the first terminal and hit `$mod +b` or `$mod + v` to create the third level of hierarchy
7. Sway crashes

I haven't tested all the edge cases, probably sway crashes for other applications as well (I personally can confirm Geany). Also, I have not tried all possible combinations of vertical and horizontal splitting and/or splitting on the first or second opened application, but I can confirm that the problem is reproducable with the steps outlined above. If you're interested in some specific tests, please let me know.

[`sway -d &> sway.log`](https://gist.github.com/Ferruck/9ffced70da84e90c1c9d0516e69dfca6)

**Comment by thejan2009** [comment]
I could reproduce the crash by creating a tabbed layout and then constantly refocusing the first window, creating new containers in horizontal split.

Interesting enough, when I try to get a similar crash with vertical split, sway doesn't crash, but the lower windows are squashed into 0 height. Attached is the relevant log. Notice how a few containers occupy the bottom side of the output, with a height of 0.
[sway.log](https://github.com/SirCmpwn/sway/files/365193/sway.log.txt)

On another retry of reproducing the bug with horizontal split, I again managed to set visible container's width to 0, and then crash the program.
[sway.log](https://github.com/SirCmpwn/sway/files/365206/sway.log2.txt)
