### ISSUE TITLE
NixOS information is outdated on the wiki

### ISSUE THREAD

**Issue by siddharthist** [SirCmpwn/sway#755]
sway is definitely a package in nixpkgs, and Wayland isn't fully supported yet (https://github.com/NixOS/nixpkgs/issues/5071), but it's mostly usable.

**Comment by SirCmpwn** [comment]
So send a pull request? Seems like an easy fix.

**Comment by SirCmpwn** [comment]
On the wiki, even, why by its nature is publicly editable. I don't even have to approve your changes to it :smile:

**Comment by siddharthist** [comment]
@SirCmpwn Just wanted to get some feedback before going ahead and changing it, especially considering that no review is needed for a wiki. I'll go ahead and do that now.

**Comment by SirCmpwn** [comment]
Thanks! Changes on the wiki do show up in many people's feeds as well and will surely be addressed if changes are necessary.

**Comment by siddharthist** [comment]
@SirCmpwn What do you think about adding NixOS to the README, since Sway is supported now?

**Comment by SirCmpwn** [comment]
Go for it.

**Comment by gpyh** [comment]
This omission was from my part and deliberate. Wayland is far from being supported in NixOS.

I was wary of adding the sway package to nixpkgs for this reason. Someone did anyway ; this is fine, but know that you won't be able to enjoy most of NixOS benefits -- no module for sway -- or Waylaid benefits -- most packages are compiled without Wayland support.

**Comment by SirCmpwn** [comment]
Think the change should be reverted?

**Comment by gpyh** [comment]
No, it's fine. I'm on my phone right now but latter in the day I'll submit a PR adding a note with more or less what I just said.

Users should know that they can't expect an experience in NixOS as good as one in, say, Arch.
