### ISSUE TITLE
Screensaver in Sway

### ISSUE THREAD

**Issue by lepianoman** [SirCmpwn/sway#758]
Is it currently possible to set a screensaver in sway? I know that this is looking upstream probably all the way to wayland but anyway, if this isn't possible, I'd be curious what's needed to make it possible.

I was using sway today and my monitor never turned off, even after 3-4 hours away.

**Comment by SirCmpwn** [comment]
A screensaver program could be made, but none exist. As for the latter issue see #541.

**Comment by lepianoman** [comment]
Curious, what about Weston screensaver? (I'm not very knowledgeable so that may be a n00b question)

**Comment by lepianoman** [comment]
Also, thank you

**Comment by SirCmpwn** [comment]
Is that a thing? It probably doesn't work on sway.

**Comment by lepianoman** [comment]
The limit of my knowledge can by attained by going to this link:

https://wiki.archlinux.org/index.php/wayland

And searching for the word screensaver. So yes, I think it exists. Honestly, swaylock is a perfectly fine screensaver for my purposes--I'm just not sure how to turn it on after a certain idle period. Most of that kind of documentation for i3 references x. Let me know if you have wayland knowledge or anything I could put in the config file that would meet my need? Thanks :)

**Comment by SirCmpwn** [comment]
No, there's not presently any sort of idle time monitoring mechanism.
