### ISSUE TITLE
Extra cursor hanging around after sway starts from GDM

### ISSUE THREAD

**Issue by neon64** [SirCmpwn/sway#759]
The cursor doesn't move and just sits there in the middle of the screen looking annoying.
I haven't tested other display managers, however when starting sway from the command line it works as expected.

Also is https://github.com/SirCmpwn/sway/issues/604 fixed? Because dialogs (eg: save window in gedit) look really funky to me. Perhaps there is something simple I'm missing though, as I am new to sway (and to desktop Linux as a whole)

**Comment by SirCmpwn** [comment]
Which version of sway are you using?

**Comment by neon64** [comment]
I installed the latest version from pacman, which says it is `0.8.2` but it hasn't been updated since July the 20th so it is probably quite out of date. Should I use `sway-git` from the AUR instead?

**Comment by SirCmpwn** [comment]
Probably not. This is more of a problem with gdm than with sway though, tbh.

**Comment by rubdos** [comment]
I'd press the +1 button, but qutebrowser doesn't seem to support that.

Anyhow, I have this issue too, should I report that to gdm, and how?

**Comment by SirCmpwn** [comment]
Yes, and why would I know how to report bugs on an unrelated project?

**Comment by FreeFull** [comment]
I'm guessing the issue is that gdm uses a hardware cursor, and sway uses a software cursor. I agree that it's a gdm bug, it should be clearing/disabling the hardware cursor.

**Comment by duckbrain** [comment]
I didn't see a bug report for this in GDM's issue tracker, so I submitted one here:

https://bugzilla.gnome.org/show_bug.cgi?id=771394

**Comment by Ferruck** [comment]
There's been no reaction on the bugzilla since you reported the bug. It's really annoying, I hope they dig into it soon.

**Comment by SirCmpwn** [comment]
These are voluneer efforts. I encourage you to dig into it and send them a patch.

**Comment by Ferruck** [comment]
Sorry, I didn't want to offend anybody. I know that all this is volunteer work and I really appreciate this. Unfortunately I'm really busy at the moment so I've got no sparse time left to dig into a bigger code base such as `gdm`s. That's why I _hope_ that someone who already has a profund knowledge of the code base would care about the issue.

**Comment by SirCmpwn** [comment]
There's no profound knowledge to be had. GDM isn't that complicated. You overestimate the effort involved in hunting this down.

**Comment by SirCmpwn** [comment]
https://github.com/Cloudef/wlc/commit/71f013f62bd346bf415710e1ddcfd4d0f13a84bd

Fixed
