### ISSUE TITLE
When a fullscreen window dies, focus is not returned to another

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/sway#76]

**Comment by taiyu-len** [comment]
ill fix that. just going to push it in a moment.

**Comment by Luminarys** [comment]
I just pulled the latest changes, I'm not sure that this has been fixed. Could someone else confirm this?

**Comment by SirCmpwn** [comment]
Works for me. I closed it earlier after testing it, and I just tested it again with success.

**Comment by Luminarys** [comment]
Ok, I'll close the issue and make sure that I'm up to date.

**Comment by Luminarys** [comment]
Yep, I'm good now.
