### ISSUE TITLE
Switching workspaces while a view is fullscreen results in no view being focused on the new workspace

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/sway#77]

**Comment by Luminarys** [comment]
Sending in a patch now.

**Comment by SirCmpwn** [comment]
774e594714579699a5f73fd110007ebb5a60cec6 did not fix this on my system.

**Comment by Luminarys** [comment]
I'll look into this, there may have been some regressions that resulted from recent changes.

**Comment by taiyu-len** [comment]
the problem is the `active_workspace = workspace;` part, it shouldnt be there.
that is handled in `set_focused_container` and `focus_update`

these handle all cases where the focus for a container changes.
which includes setting the active workspace.

**Comment by SirCmpwn** [comment]
Thanks @taiyu-len
