### ISSUE TITLE
Poor 3D performances

### ISSUE THREAD

**Issue by kilbith** [SirCmpwn/sway#775]
### glxgears ¹

| i3 | sway | gnome-wayland |
| --- | --- | --- |
| 6086 FPS | 3076 FPS | 6550 FPS |
# 

_EDIT - July 30, 2016_
### Xonotic Benchmarks ²

|   | xonotic-glx | xonotic-sdl ³ |
| --- | --- | --- |
| **i3** | 37.94 FPS | 37.72 FPS |
| **gnome** | 38.72 FPS | - |
| **gnome-wayland** | - | 47.02 FPS |
| **sway** | 26.57 FPS | 41.08 FPS |
#

**Comment by jonas-schievink** [comment]
Are you sure that this isn't an X11 vs. Wayland benchmark?

**Comment by kilbith** [comment]
> Are you sure that this isn't an X11 vs. Wayland benchmark?

Absolutely not, I just added a small note above.

**Comment by jonas-schievink** [comment]
> Note : Gnome on Wayland gives more FPS than on X.

Is Gnome on Wayland faster than sway too?

**Comment by kilbith** [comment]
> Is Gnome on Wayland faster than sway too?

Yep, absolutely.

**Comment by jonas-schievink** [comment]
Might be related to #741, which sway version are you using?

**Comment by kilbith** [comment]
> which sway version are you using?

sway 0.8, on Arch. I've briefly tried the git version but the CPU was overly consuming up to 40% for basic tasks...

**Comment by SirCmpwn** [comment]
Can you run this with gprof and get is some profiling data?

**Comment by kilbith** [comment]
I did some profiling with Valgrind instead...

- [Callgrind](http://mamadou3.free.fr/callgrind.out.1041)
- [Massif](http://mamadou3.free.fr/massif.out.1355)

**Comment by SirCmpwn** [comment]
No, no, profile sway, not glxgears.

**Comment by kilbith** [comment]
Note : launching has prematurely aborted for some reason...

- [Callgrind](http://mamadou3.free.fr/callgrind.out.1317)
- [Massif](http://mamadou3.free.fr/massif.out.1333)

**Comment by thejan2009** [comment]
@kilbith If I remember correctly, only the latest Valgrind from their SVN repository can successfully launch sway.

**Comment by DarkDefender** [comment]
I sadly can't help with profiling either as Valgrind does not support my Bulldozer CPU (it can't handle some AMD speficic instructions).

I just wanted to say that I notice the same problem with my AMD 290x.
In xorg I get ~6000 fps with  glxgears. In weston I get ~5600 fps and in sway I get ~4500 fps.

@kilbith do you get the same fps with weston as with gnome-wayland?

**Comment by kilbith** [comment]
More extensive benchmarks (Xonotic) added in first comment.

@DarkDefender Not tested on Weston.

**Comment by Cloudef** [comment]
Note that wlc uses GLES2 for compositing. I'm not sure what gnome uses for rendering but it may use less GPU resources. wlc also doesn't have direct scanout so fullscreen windows will be composited even though there would be no need. That said I would be interested in profiling results.

**Comment by SirCmpwn** [comment]
Profile and send patches.

**Comment by kilbith** [comment]
I'm sorry, but I'm not understanding. I have ran some rigorous benchmarks, indicated objective values as the results of several circumstances that some users can correlate.

Profiles or not it exposes a real issue, isn't that enough to keep this opened ? Or maybe it's preferable to re-open this on `wlc` ?

Also : as a simple user, I'm not required to send you patches.

Regards,
The doofus.

**Comment by SirCmpwn** [comment]
Benchmarks and profiling are not the same thing. Benchmarks tell you there are performance issues. Profiling tells you what they are.

I'm closing issues that don't have enough information to solve. Profile it and leave a comment with the results, and I'll re-open this.

>Also : as a simple user, I'm not required to send you patches.

As a developer, I'm not required to write them for you.
