### ISSUE TITLE
Built-in theme picker

### ISSUE THREAD

**Issue by acrisci** [SirCmpwn/sway#801]
Add a config directive to apply a theme to the windows. Sway will ship with default colorschemes that can be applied by the user, or serialized in json format and applied from a file.

Example:

```
colorscheme solarized
colorscheme ~/.config/sway/my-theme.json
```

A variety of themes are available from the [i3-style](https://github.com/acrisci/i3-style) project that can be used for default themes.

I know from my support of i3 in the irc chat, and the popularity of my i3-style project, that this is a highly demanded feature among users. A quick survey of i3 desktop images available on the internet indicates to me that nearly everyone does some sort of customization to their colorscheme. Many more users who do not want to expend the effort searching for tools would customize their colors if it were easy, improving the experience of sway. It makes sense to provide a way to do this that is as user friendly as possible.

**Comment by SirCmpwn** [comment]
Do you think a similar feature is going to land in i3 (not that I'm necessarily opposed to having this sort of feature in sway)?

I would also prefer to see this implemented with something like the `include` command (which is unique to sway but is [under discussion](https://github.com/i3/i3/issues/1197) for inclusion in i3), which would be able to simply include colorschemes from ~/.config/sway/conf.d or whever you like in the form of simple i3 configs.

**Comment by acrisci** [comment]
No, this feature was rejected from i3 so you don't have to worry about api conflicts.

An include would not work for bar colors because they must be configured within the bar block and including a bar block in the include makes themes unportable. It still leaves users to search for themes, which is overhead to customization.

**Comment by SirCmpwn** [comment]
Good point. Can we explore alternate ways of setting bar colors instead? For example, in #547 we talked about things like having bars configured like this:

    bar "id" {
        ...
    }

Which would expand to things like:

    bar "id" ...

How about supporting something like `bar * ...` to support configuring properties that all bars inherit by default?

**Comment by acrisci** [comment]
Sure, that would work. Then you could include a default search path to resolve a relative path for the colorscheme, so something like `colorscheme solarized` expands to /usr/path/to/solarized.config` behind the scenes.

That approach would be simple, but you gain a lot with a json format. Look at [this](https://github.com/acrisci/i3-style/blob/master/themes/solarized) colorscheme for solarized. It is very easy to read and modify. It gives you color aliases to make it even easier to modify. That could be done with variables, but the i3 config format is difficult to read because you have to look up what the positional arguments of the color directives are.

**Comment by SirCmpwn** [comment]
Since the include directive supports shell expansion, maybe we could do something like this:

    include `i3-style solarized`

Which would dynamically rejigger the JSON schemas i3-style already supports into something i3-config-like and drop it in /tmp or something. Thoughts?

**Comment by acrisci** [comment]
If you're just including what comes from stdout, that would take an argument like `i3-style solarized --colors-only` but that's not hard to do. However, it would have to be sway-specific because the top level bar config directives will not be supported by i3.

**Comment by SirCmpwn** [comment]
And then things like i3-style could install something to /etc/sway/config.d/i3-style or similar and it would just werk. Sounds like a good plan. I'm okay with programs having to write sway specific code to take advantage of sway specific features.

**Comment by acrisci** [comment]
Well if it's a separate utility, people still have to search for it and go through the install steps, which requires the technical ability of a developer, and they still have to be clever enough to put all of that together. If you're ok with that, it's fine, but I think the built-in `colorscheme` directive is still the best choice.

So if it's a separate utility, how about adding a page to the wiki explaining how to change the colorscheme?

**Comment by SirCmpwn** [comment]
A place on the wiki sounds like a great place to discuss that. As for avoiding a seperate utility and using the `colorscheme` directive to support it, well, I feel like that's out of scope if we can find an acceptable solution for it built on top of sway's existing mechanics. As a bonus I feel it'll expand the usage of installing sway config.d files with packages to extend sway's functionality for them.

**Comment by acrisci** [comment]
Actually after thinking about it, I think the way the tool is used now is superior because I don't have to have it installed for my theme to work which is one less moving part per machine (I don't have it installed now actually).

**Comment by SirCmpwn** [comment]
I don't think that's a very strong use-case, since you can also just do something like `i3-style solarized > .config/sway/config.d/colorscheme` or something similar and then remove i3-style.

**Comment by acrisci** [comment]
Yeah or you could do `i3-style solarized -s` and it will modify your config in place and then remove i3-style. Then you don't have to have two config files, which is one less moving part. Flat is better than nested.

**Comment by SirCmpwn** [comment]
Either way.
