### ISSUE TITLE
Wallpapers bloating the repository unnecessarily

### ISSUE THREAD

**Issue by kilbith** [SirCmpwn/sway#807]
Already discussed on IRC, opening an issue to know what the other users think about removing the wallpapers from the repository.

It bothers me to wait 10-15s more for downloading sway just because of wallpapers that I'm not gonna using. This is kind of very personal preference, your users love personalizing their desktop and are not likely using these bundled wallpapers either.

Wallpapers as an artwork have nothing to do alongside a WM's codebase. I suggest to split them in a separate repository and set a solid color as background for the sake of simplicity and lightweightness.

**Comment by Hummer12007** [comment]
It's not like it'd make any difference, when you clone the repo (with full history contents).

**Comment by psgarsenal** [comment]
It makes a difference when you install sway-git on arch, because it means you fully reclone the repo each time you want to update the package. For me it should be on another repo.

**Comment by mikkeloscar** [comment]
I agree, it would be nice to make it a separate repo and package. I don't notice now because I have a decent connection. But when you are on a shitty connection like I was for the past few months then 10MB really is a lot :)

@Hummer12007 is right, it will clone the whole history including the wallpapers, even if they are removed at some point. It would make sense to patch `makepkg` to not clone the entire history IMO.

I have a CI server automatically building sway-git packages so cloning the whole repo is not a problem for me though :)

**Comment by SirCmpwn** [comment]
If I chose to remove it from the repo, I can purge it from the entire history of the repo if necessary.

**Comment by rumpelsepp** [comment]
But then commit IDs will change. Might be problematic with tags and references in the bugtracker.

**Comment by progandy** [comment]
> It makes a difference when you install sway-git on arch, because it means you fully reclone the repo each time you want to update the package.
That is wrong. I keep the repos for my git packages around and don't clone them each time.

Anyways, I don't think it isn't too critical for a development tree. If you wish to provide a leightweight release, then creating a tarball without the images should be possible.

**Comment by AbstractBeliefs** [comment]
Those who really want a small copy of the repo for light development purposes can just `git clone --depth=1` to only get the current head, no need to rewrite history.

It's really substandard for any real work, though I think if images are too much a size constraint, best not try compiling anything.

**Comment by kilbith** [comment]
Issue closed in all disdain from the majority of feedbacks in favor of removing these shitty wallpapers.

**Comment by SirCmpwn** [comment]
I'm not going to break the repo's history by rebasing them out, so the bloat will always be there for clones. There's an option not to install them during the build. Kindly go fuck yourself.
