### ISSUE TITLE
Sway is unusably slow

### ISSUE THREAD

**Issue by renekliment** [SirCmpwn/sway#82]
Hey! I was excited to hear about sway so I tried it out.
Unfortunately, it is super slow for me. I think it might be because I have Intel GMA 950 graphics card (I know, but I don't play games and for other uses it's sufficient; kvm works fine). I'm not sure if sway / wayland uses any 3D, or any other advanced GPU features so I'm asking you for help / answer to my problem. Also, as you can see in the htop window, it uses 100% of my CPU core most of the time.

I'm using Arch Linux and latest sway from git.

Here is the log: https://gist.github.com/renekliment/9d79047cd29d67aca8ec
And here is the video: https://youtu.be/2CZeqII02LE

Thank you.

**Comment by SirCmpwn** [comment]
Paging @Cloudef

**Comment by SirCmpwn** [comment]
Can you try running it with WLC_BG set to "0"?

**Comment by renekliment** [comment]
Well, shit, that was fast! 
It works like a charm, thank you! So I guess the cool background uses some 3D or something?
Can I use something for a static background like I use feh for a desktop background image in i3?

**Comment by SirCmpwn** [comment]
>It works like a charm, thank you! So I guess the cool background uses some 3D or something?

Yeah, that's a wlc thing (wlc is our wayland compositor library).

>Can I use something for a static background like I use feh for a desktop background image in i3?

Eventually, yes.
