### ISSUE TITLE
Scrolling on swaybar doesn't work if pointer touches the screen border

### ISSUE THREAD

**Issue by minus7** [SirCmpwn/sway#825]
I have swaybar at the bottom of the screen. If i move the mouse to the very edge of the screen, scrolling does not change workspaces; moving it one pixel higher makes it work. I run a 3-monitor setup with 1920x1080 and 2560x1440 resolutions. I couldn't reproduce the problem when running inside X11.

**Comment by chpii** [comment]
I found that whole 1px area on the bottom and right edge of the screen is dead zone even in fullscreen in any application.

Tested with Chromium (try scrollbars or fullscreen video) and urxvt (try selecting text with mouse, selection cancels at mentioned edges).

**Comment by SirCmpwn** [comment]
Is this still a problem?
