### ISSUE TITLE
Blurry font rendering hidpi

### ISSUE THREAD

**Issue by jarias** [SirCmpwn/sway#829]
4k screen 
Scale factor 2

Sway
![screenshot-20160803-192814](https://cloud.githubusercontent.com/assets/119519/17387471/57d2af74-59b1-11e6-8b79-45d86ad6e93c.png)

i3
![screenshot-20160803-193209](https://cloud.githubusercontent.com/assets/119519/17387481/74238ed2-59b1-11e6-934a-20ec362d6f53.png)

**Comment by psgarsenal** [comment]
xwayland, swaybar and swaylock don't support native scaling at the moment. If you want a crisp font for your terminal, you can try and switch to a native wayland terminal, such as:
-weston-terminal
-germinal
-wlterm
-hawaii-terminal

Hope this helps!

**Comment by jarias** [comment]
@psgarsenal Thanks for the info, that was my guess, do you know if xwayland will have scaling support eventually that's a big show stopper for me at least since I still use a lot of apps that don't support wayland yet. This is the only ticket I found https://bugs.freedesktop.org/show_bug.cgi?id=93315.

**Comment by psgarsenal** [comment]
It's on a per-toolkit / per-application basis, gtk can be scaled via an environment var for example.
This means that there is no global solution for now, but we might see one in the future
You can see more in the arch-wiki page about HiDPI:
https://wiki.archlinux.org/index.php/HiDPI

**Comment by stapelberg** [comment]
Do I need to do anything to make `weston-terminal` support hidpi? 

With sway 0.9 and wlc 0.0.5, I added `output * scale 2` to my `~/.config/sway/config`, but all fonts are still blurry — it looks like the applications were rendered at low-dpi, then scaled up:

![screenshot](https://cloud.githubusercontent.com/assets/55506/18156870/dc523368-7019-11e6-9c96-1409a0e017b4.png)

For comparison, this is what I expect it to look like (from i3):

![2016-09-01-075952_2559x1406_scrot](https://cloud.githubusercontent.com/assets/55506/18156900/28333836-701a-11e6-8a04-0a99fb2300fe.png)


I tried creating `~/.config/weston.ini` with the following contents:
```ini
[output]
name=eDP-1
scale=2
```

…but that didn’t change anything either.

**Comment by SirCmpwn** [comment]
weston-terminal might not support HiDPI. If you're looking for a term that does, try gnome-terminal.

**Comment by SirCmpwn** [comment]
Oh, and the window decorations and bar are known limitations in sway's HiDPI support. See #797

**Comment by stapelberg** [comment]
Using gnome-terminal indeed works.

I was originally trying weston-terminal because it was recommended in https://github.com/SirCmpwn/sway/issues/829#issuecomment-237478787

**Comment by SirCmpwn** [comment]
Ah. I wouldn't suggest weston-terminal for any purpose.

**Comment by psgarsenal** [comment]
To be honest I did not test the scaling function, I just thought most native wayland applications supported scaling, which proves to be wrong

**Comment by SirCmpwn** [comment]
swaybar, swaybg, and swaylock all support hidpi as of https://github.com/SirCmpwn/sway/compare/0913eff9157a...af441541197a

**Comment by stapelberg** [comment]
I can confirm that swaybar is now hidpi-compatible. Can we get window title bars next please? :)

![2016-09-07-084513_swaygrab](https://cloud.githubusercontent.com/assets/55506/18302327/93cd92c8-74d7-11e6-9566-963c5b0abd3a.png)

**Comment by SirCmpwn** [comment]
That's what I'd like to look into next. I actually missed a spot with swaybar I need to fix, though.

**Comment by SirCmpwn** [comment]
https://github.com/SirCmpwn/sway/issues/797

**Comment by rucuriousyet** [comment]
How can I set Sway to hidpi mode? I am currently using on a 4k display and its pretty blurry.

**Comment by SirCmpwn** [comment]
RTFM

**Comment by danielcb** [comment]
@stapelberg did you get rxvt to work without blurry fonts by any chance? I've everything setup and working quite well. Gnome-terminal is as sharp as it can be (hidpi, scale 2), but I can't get rxvt-unicode to render sharp fonts (Xft.dpi 282, antialias and the like are set already).

**Comment by kaueraal** [comment]
@danielcb Yes, that's an Xwayland issue. This is somewhat tracked in #1047 .

**Comment by Inc0ns1st3nt** [comment]
Hi, is there any work around for blurry xwayland app in hidpi?
