### ISSUE TITLE
Both outputs have the same ID, only one works

### ISSUE THREAD

**Issue by RyanDwyer** [SirCmpwn/sway#847]
Hi,

I have a laptop with two external monitors; one HDMI and one VGA. The HDMI sits to the left of the VGA. I have the following in ~/.config/sway/config:

```
output HDMI-A-1 res 1920x1080 pos 0,0
output VGA-1 res 1920x1080 pos 1920,0
output LVDS-1 disable
```

I also have workspaces 1 and 2 configured to open on the left/HDMI monitor, and 3 and above to open on the right/VGA.

When I start sway, only the HDMI monitor shows anything, and it shows what the VGA monitor should be showing (workspace 3). I can move my mouse off it towards the left as if there's another output there, but I can't move my mouse off it to the right. It seems as if Sway is misidentifying my monitors and writing the VGA output to the HDMI.

I ran swaymsg -t get_outputs:

```
[ { "id": 1786901480, "name": "VGA-1", "rect": { "x": 1920, "y": 0, "width": 1920, "height": 1080 }, "visible": true, "active": true, "primary": false, "layout": "output", "type": "output", "current_workspace": "3: terms", "scale": 1 }, { "id": 1786901480, "name": "HDMI-A-1", "rect": { "x": 0, "y": 0, "width": 1920, "height": 1080 }, "visible": true, "active": true, "primary": false, "layout": "output", "type": "output", "current_workspace": "1: web", "scale": 1 } ]
```

This all looks correct according to the config, but surely they aren't meant to have the same ID? The IDs change each time I start Sway but they're always identical. Both monitors are the same make and model by the way.

I tried disabling VGA-1 and enabling LVDS-1 (laptop's built-in display) but they get the same ID too and only HDMI works.

I'm using the versions that are in Arch's repos:

```
$ sway -v
sway version  (2016-08-02, branch "")
$ pacsearch sway
community/sway 0.9-1 [installed]
$ pacsearch wlc
community/wlc 0.0.5-1 [installed]
```

**Comment by SirCmpwn** [comment]
That's weird.

**Comment by RyanDwyer** [comment]
In sway/ipc-json.c, in ipc_json_describe_container() I can see it's writing &c to the "id" object:

    json_object_object_add(object, "id", json_object_new_int((uintptr_t)&c));

Surely this is setting the "id" to the *address* of the variable that's being used to iterate the outputs? If I remove the & and recompile I get different IDs for each output.

Still doesn't explain why I can't get two outputs working though :-\

**Comment by SirCmpwn** [comment]
Can you get two outputs working on X?

**Comment by zandrmartin** [comment]
FWIW the `id` in the JSON response is not used anywhere, it's just included for compatibility with i3.

**Comment by RyanDwyer** [comment]
Yes, I can get two outputs working on X. It's an Intel HD 4000 (integrated).

**Comment by RyanDwyer** [comment]
[sway.log](https://github.com/SirCmpwn/sway/files/412164/sway.txt)
[~/.config/sway/config](https://github.com/SirCmpwn/sway/files/412166/config.txt)

**Comment by SirCmpwn** [comment]
Paging @Cloudef

**Comment by Cloudef** [comment]
What happens if all outputs are enabled?

**Comment by RyanDwyer** [comment]
As before, only the HDMI displays a picture. The VGA goes into sleep mode (it also does this when trying with two). I believe my integrated graphics can't handle all three displays at once - it's not something I've ever been able to do under X.

[sway.log](https://github.com/SirCmpwn/sway/files/413052/sway.txt)
[~/.config/sway/config](https://github.com/SirCmpwn/sway/files/413053/config.txt)

I note this in the log file - don't know if it's important:

    08/11/16 21:19:43 - [wlc] Failed to page flip: Device or resource busy

**Comment by RyanDwyer** [comment]
If I disable HDMI and enable VGA and LVDS then I get an image on VGA only.

**Comment by Cloudef** [comment]
Failing page flip means the image will not ever land to screen, so it's very important. What devices do you have in /dev/dri/ ?

**Comment by RyanDwyer** [comment]
My /dev/dri devices are:

    /dev/dri/card0
    /dev/dri/controlD64
    /dev/dri/renderD128

The page flip error isn't in the earlier log BTW. Maybe it's only there because the card can't output to three displays at once.

**Comment by RyanDwyer** [comment]
I started WLC with WLC_DEBUG=handle,render and with LVDS-1 disabled and found some more information. I think the LVDS output isn't being terminated properly. It tries to re-use the handle for LVDS-1 but doesn't call the constructor when that handle is replaced by VGA-1.

[sway.log](https://github.com/SirCmpwn/sway/files/416259/sway.txt)

Here WLC is setting up LVDS with handle 1:

    08/13/16 08:17:25 - [wlc] => Calling constructor for (output) 1
    08/13/16 08:17:25 - [wlc] => Called constructor for (output) 1
    08/13/16 08:17:25 - [wlc] New handle (output) 1
    08/13/16 08:17:25 - [wlc] LVDS-1 Chose mode (0) 1920x1080
    08/13/16 08:17:25 - Output 1 resolution changed to 1920 x 1080

Sway terminates the LVDS output:

    08/13/16 08:17:25 - [wlc] Set new bsurface to output (1)
    08/13/16 08:17:25 - New output 1:LVDS-1
    08/13/16 08:17:25 - Matched output config for LVDS-1
    08/13/16 08:17:25 - [wlc] Output (1) terminated...
    08/13/16 08:17:25 - [wlc] Released drm surface (0x157df38)
    08/13/16 08:17:25 - [wlc] Removed bsurface from output (1)
    08/13/16 08:17:25 - [wlc] Removed output (1)

VGA-1 appears without the constructor being called - handle is 1:

    08/13/16 08:17:26 - [wlc] Set new bsurface to output (1)
    08/13/16 08:17:26 - New output 1:VGA-1
    08/13/16 08:17:26 - Matched output config for VGA-1
    08/13/16 08:17:26 - Set VGA-1 size to 1920x1080 (1)
    08/13/16 08:17:26 - Set VGA-1 position to 1920, 0

WLC sets up the HDMI output with handle 2:

    08/13/16 08:17:26 - [wlc] Added output (1)
    08/13/16 08:17:26 - [wlc] => Calling constructor for (output) 2
    08/13/16 08:17:26 - [wlc] => Called constructor for (output) 2
    08/13/16 08:17:26 - [wlc] New handle (output) 2
    08/13/16 08:17:26 - [wlc] HDMI-A-1 Chose mode (0) 1920x1080
    08/13/16 08:17:26 - Output 2 resolution changed to 1920 x 1080
    ...
    08/13/16 08:17:26 - New output 2:HDMI-A-1
    08/13/16 08:17:26 - Matched output config for HDMI-A-1
    08/13/16 08:17:26 - Set HDMI-A-1 size to 1920x1080 (1)
    08/13/16 08:17:26 - Set HDMI-A-1 position to 0, 0

Maybe WLC thinks handle 1 is still terminated?

**Comment by progandy** [comment]
Did you try to run with all three monitors without disabling LVDS?

**Comment by RyanDwyer** [comment]
Yes. I believe my graphics card doesn't support three outputs at the same time (not even under X), hence the page flip error posted previously. When I tried all three only the HDMI displayed an image.

It seems like WLC always finds my LVDS output first. For me to use VGA and HDMI at the same time I must disable LVDS, but when I disable LVDS it re-uses the handle for one of the others and incorrectly thinks it's disabled.

If someone wants to try and replicate my problem, you could try:

1. Have two or more displays.
2. Start Sway normally, then examine your Sway log to determine which display is found first.
3. Disable that output in your Sway config then restart Sway.

**Comment by Cloudef** [comment]
The handle reuse should not matter. When sway terminates the output (by returning false in output.created callback) the whole output, including handle gets destroyed.

**Comment by RyanDwyer** [comment]
I don't believe this is a Sway or WLC problem any more.

If you recall, Sway works fine if I physically unplug either my HDMI or VGA and run with the other two. Well, if I try to launch X using xf86-video-modesetting (by uninstalling xf86-video-intel) then X crashes, unless I unplug one either my HDMI or VGA monitor in which case xf86-video-modesetting works fine. So it seems like the issue is something higher in the graphics chain, and xf86-video-intel happens to work around it maybe. I tried running the Arch LTS kernel (4.4) to see if that makes a different but it doesn't.

I'm happy for someone to close this issue as it's not an issue with Sway or WLC, but if you have any suggestions on where I should look it would be appreciated.

**Comment by Cloudef** [comment]
>I'm guessing that making the initial mode setting happen after the output.created handler has returned should fix my problem.

Yeah by default wlc wakes up all outputs, and it calls create callback _after_ it's confirmed to be OK, instead of doing the creation after the callback and then have the output fail. Not sure if this is driver bug really.

**Comment by RyanDwyer** [comment]
I would say it's not a driver bug. When the modesetting DDX tries to set the mode on all three, this appears in the Xorg log:

    (EE) modeset(0): failed to set mode: Invalid argument

So it seems like the driver is returning EINVAL for whatever the modesetting call is. From the driver's perspective this is correct behaviour. The DDX/compositor shouldn't be trying to activate more outputs than the hardware can support.

Could it be that WLC isn't deactivating the mode when the output is terminated? If the driver has allocated resources for it then that would cause the third one to fail in my case.

Some error checking and logging in output_push_to_resource() would be useful BTW.

**Comment by Cloudef** [comment]
The push to resource is simply wayland communication which you can see with WAYLAND_DEBUG=1, I'm not sure how to know how many outputs hardware can support, but if you can make PR to improve this that would be good.

**Comment by RyanDwyer** [comment]
That commit doesn't have any noticeable effect for me (still shows VGA's image on HDMI when I start Sway with LVDS disabled).

I'm currently learning a lot about the Linux graphics stack. I'll experiment more with WLC when I can. Given enough time, I'll send a PR eventually.

**Comment by Cloudef** [comment]
@RyanDwyer Thanks, I'll hope you manage to fix your issue.

**Comment by RyanDwyer** [comment]
I've figured out exactly what's going on. To put it shortly, it's using the same CRTC for both HDMI and VGA. That's what causes the "Device or resource busy" when page flipping. Now for the long answer...

My video card has 3 CRTCs (26, 30 and something else) and 4 encoders (LVDS, VGA, HDMI and DisplayPort). When I first boot my computer and I'm at the console, it's showing the console on LVDS and VGA. The LVDS and VGA encoders are both using CRTC 26. CRTC 30 and the other are unused.

When WLC starts, query_drm() iterates the connectors and calls find_encoder_for_connector() on each.

* For LVDS, it returns the LVDS encoder and sets out_crtc_id to 26.
* For VGA, it returns the VGA encoder and sets out_crtc_id to 26 (!).
* For HDMI, the connector is not using an encoder so it enters the for() loops further down. encoder->possible_crtcs is 7 (binary 00000111), meaning all 3 CRTCs may be used. It uses the first CRTC in the array, which is ID 26 (!).

As you can see, this has no checks to see if the CRTC is already in use. One option is to keep track of which CRTCs have been assigned and don't re-assign them. However, I think the ideal option is to configure the CRTCs after the output.created callbacks. For example, Sway might return false from the output.created callback in which case a CRTC shouldn't be configured for it. Or Sway might want to position two outputs at the same position, using the same resolution and refresh rate in which case it makes complete sense to use the same CRTC. This depends on WLC having a way for Sway to relay position information, disable and enable outputs on the fly and request mode setting.

What do you think about all of this @Cloudef?

**Comment by RyanDwyer** [comment]
I've managed to work around my issue by setting the console's outputs and resolution via kernel parameters:

    video=HDMI-A-1:1920x1080 video=VGA-1:1920x1080 video=LVDS-1:d

I see from some of your other open issues that there's still work to be done in WLC on the DRM/modesetting side of things. There's little point in me submitting a fix because it might create more issues and it'll get superseded by the new DRM/modesetting code.

**Comment by Cloudef** [comment]
>As you can see, this has no checks to see if the CRTC is already in use. One option is to keep track of which CRTCs have been assigned and don't re-assign them. However, I think the ideal option is to configure the CRTCs after the output.created callbacks. For example, Sway might return false from the output.created callback in which case a CRTC shouldn't be configured for it. Or Sway might want to position two outputs at the same position, using the same resolution and refresh rate in which case it makes complete sense to use the same CRTC. This depends on WLC having a way for Sway to relay position information, disable and enable outputs on the fly and request mode setting.

I really don't have much more to say to this. This is not something I would like to expose outside of wlc though, wlc should be able to figure out how to enable outputs and display the image. I would perhaps suggest to look at how weston does the detection.
