### ISSUE TITLE
Output - incorrect native resolution detection

### ISSUE THREAD

**Issue by ldmldmldm** [SirCmpwn/sway#848]
Hello.

```
arch:~$ swaymsg -t get_outputs
[
   {
     "id": -2075744264,
     "name": "LVDS-1",
     "rect": {
       "x": 0,
       "y": 0,
       "width": 1280,
       "height": 800
     },
     "visible": true,
     "active": true,
     "primary": false,
     "layout": "output",
     "type": "output",
     "current_workspace": "1",
     "scale": 1
   },
   {
     "id": -2075744264,
     "name": "DP-1",
     "rect": {
       "x": 1280,
       "y": 0,
       "width": 1280,
       "height": 800
     },
     "visible": true,
     "active": true,
     "primary": false,
     "layout": "output",
     "type": "output",
     "current_workspace": "2",
     "scale": 1
   }
 ]
```

```
arch:~$ man 5 sway
    ....
    output <name> <resolution|res> <WIDTHxHEIGHT>
    Configures the specified output to use the given resolution.

    Note: sway does not currently support modesetting. Your output’s native resolution will be used and
    the screen will be scaled from the resolution specified to your native resolution.
    ....
```

So the DP-1 is a 3840x2160 monitor but it seems like sway detects it as a 1280x800 monitor. Then due to how `output DP-1 resolution 3840x2160` simply _"scales from the resolution specified to your native resolution"_ means that the 4k is scaled down to 1280x800.

The man page says sway does not currently support modesetting, so is there anything I can do to get my external monitor working at native resolution?

Thanks

**Comment by thejan2009** [comment]
It's actually the driver that defaults to some strange resolution, not sway. If you want to change it, read this: https://wiki.archlinux.org/index.php/Kernel_mode_setting#Forcing_modes_and_EDID
Your kernel command line should probably look like `video=DP-1:3840x2160D`
As a side effect, your laptop display might get disabled, though.

**Comment by SirCmpwn** [comment]
This is a wlc problem.

**Comment by ldmldmldm** [comment]
thanks @thejan2009 that worked, https://github.com/Cloudef/wlc/issues/167

**Comment by danroconnor** [comment]
Thanks @thejan2009! Adding a second video parameter forces the laptop display on as well:

`video=DP-1:1920x1200D video=eDP-1:1440x900D`
