### ISSUE TITLE
Input - really slow mouse movements not detected downwards or rightwards

### ISSUE THREAD

**Issue by ldmldmldm** [SirCmpwn/sway#849]
Hi.

Moving really slowly (like 0.3cm/sec) results in the cursor not moving at all.
- **Only** occurs when moving downwards or rightwards.
- Does not occur when moving upwards or leftwards.
- Occurs for the touchpad **and** the mouse.
- Does not occur under libinput on X11

Note: on the touchpad I start from the middle to avoid any of the palm detection (which triggers if you start from top left or top right)

I confirmed I am using libinput on X using
```
arch:~$ grep -e "Using input driver " ~/.local/share/xorg/Xorg.0.log
[ 25022.988] (II) Using input driver 'libinput' for 'USB Optical Mouse'
[ 25023.031] (II) Using input driver 'libinput' for 'bcm5974'
```

My sway settings:
```
input * {
    accel_profile flat
    tap enabled
    scroll_method two_finger
    dwt enabled
    natural_scroll enabled
}
```

My X11 settings:
```
Section "InputClass"
    Identifier "libinput touchpad catchall"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    Driver "libinput"

    Option "Tapping" "true"
    Option "NaturalScrolling" "true"
    Option "DisableWhileTyping" "true"
    Option "ScrollMethod" "twofinger"

    Option "AccelProfile" "flat"
EndSection
```

Version info:
```
arch:~$ pacman -Qi wlc-git
Version         : 0.0.5-1
arch:~$pacman -Qi sway-git
Version         : r1863.49afdb4-1
arch:~$ sway -v
sway version 0.9-38-g49afdb4 (2016-08-10, branch "master")
```

Thanks.

**Comment by psgarsenal** [comment]
can you check if this solves your issue?

https://github.com/Cloudef/wlc/issues/166#issuecomment-237883598

@SirCmpwn maybe this could be added in the faq since a few people had this problem

**Comment by SirCmpwn** [comment]
Please report to wlc, and it's probably related to the issue @psgarsenal linked.
