### ISSUE TITLE
Allow * to be used for input (like it can be used for output)

### ISSUE THREAD

**Issue by ldmldmldm** [SirCmpwn/sway#852]
Hello.

The star does not seem to match all input devices:
```
input * {
    accel_profile flat
    natural_scroll enabled
}
```

However when using the actual identifiers, the configurations apply:
```
input "1133:49242:Logitech_USB_Optical" {
    accel_profile flat
}

input "1452:594:Apple_Inc._Apple_Internal_Keyboard_\/_Trac" {
    accel_profile flat
    natural_scroll enabled
}

input "1452:594:bcm" {
    accel_profile flat
    natural_scroll enabled
}
```

It is quite clear the star configuration does not work as natural scrolling does not apply.

I suggest an improvement to input to allow the use of * to match all inputs (similar to how it matches all output names).
Thanks

**Comment by progandy** [comment]
Well, maybe input and output could use ```fnmatch``` to allow pattern matching?

**Comment by nloewen** [comment]
Better would be a way to target classes of devices like you can with the libinput Xorg configs.

**Comment by harrisonrodgers** [comment]
Yes it would be nice to target all input for flat accel, but only all touchpads for natural scrolling.

**Comment by ldmldmldm** [comment]
Yes it would be nice to target all input for flat accel, but only all touchpads for natural scrolling.
