### ISSUE TITLE
How to change brightness?

### ISSUE THREAD

**Issue by sjug** [SirCmpwn/sway#854]
In i3 I used an xbacklight exec command. 

Now in sway I get the error:
xbacklight: No outputs have backlight property

I have tried light-git from the AUR, but it doesn't do anything either.
I haven't seen any keybindings for XF86MonBrightness* in any sample configs either.

What works?

**Comment by aouelete** [comment]
I have been using `light` without any problems. 

You can always use `/sys/class/backlight`, see https://wiki.archlinux.org/index.php/Backlight.

**Comment by sjug** [comment]
Thanks light did work just not the -m or -c flags, SAU does. Cheers @aouelete.

**Comment by ObiWahn** [comment]
```
» cat /usr/local/sbin/light
#!/usr/bin/env bash
set -uo pipefail

main() {
    case ${1:-reset} in
        get)
            /usr/bin/ddcutil -d 1 getvcp 10
            /usr/bin/ddcutil -d 2 getvcp 10
            /usr/bin/ddcutil -d 3 getvcp 10
        ;;
        low)
            /usr/bin/ddcutil -d 1 setvcp 10 10
            /usr/bin/ddcutil -d 2 setvcp 10 20
            /usr/bin/ddcutil -d 3 setvcp 10 10
        ;;
        reset|*)
            /usr/bin/ddcutil -d 1 setvcp 10 30
            /usr/bin/ddcutil -d 2 setvcp 10 47
            /usr/bin/ddcutil -d 3 setvcp 10 30
        ;;
    esac
}

check_module(){
    if ! /usr/sbin/lsmod | /usr/bin/grep -q i2c_dev ; then
        /usr/sbin/modprobe i2c-dev
    fi
}

check_module
main "$@"
```

**Comment by ferronyx** [comment]
Hello there! The `light` seems to have been abandoned. Are there any viable alternatives?

Best regards
Susabh

**Comment by rodhfr** [comment]
this is the first response on google then let's do it for archival
# ~/.config/sway/config/
bindsym XF86MonBrightnessUp exec brightnessctl set 10%+
bindsym XF86MonBrightnessDown exec brightnessctl set 10%-
