### ISSUE TITLE
Error messages spamming other TTYs

### ISSUE THREAD

**Issue by ldmldmldm** [SirCmpwn/sway#855]
Hi.

Starting sway in one TTY then switching to another results in the following error messages being printed on the console (i believe these are from wlc). They appear about every half a second and thus make the other TTYs unusable.

```
[ 2124.905378 ] ERROR @wl_dev_intvar_get : error (-1)
[ 2124.905379 ] ERROR @wl_cfg80211_get_tx_power : error (-1)
[ 2124.905390 ] ERROR @wl_dev_intvar_get : error (-1)
[ 2124.905391 ] ERROR @wl_cfg80211_get_tx_power : error (-1)
...
```

Maybe it's appropriate to keep these on the TTY that the wm was launched from?

--
Thanks

**Comment by SirCmpwn** [comment]
Please report this to wlc.

**Comment by ldmldmldm** [comment]
I'm so sorry I thought I did.

**Comment by FreeFull** [comment]
Those messages seem to be related to wireless networking (wl would stand for wireless)
