### ISSUE TITLE
Invisible window in workspace

### ISSUE THREAD

**Issue by acorreya** [SirCmpwn/sway#857]
Hi! There seems to be a bug with firefox window having a terminal in fullscreen. It occurs occassionaly when a terminal window is fullscreen and windows are moved around workspaces. Even the workspace remains lit without any window in it. Please let me know if any log is needed.
![swaybug](https://cloud.githubusercontent.com/assets/3225091/17666929/3f32805c-6320-11e6-8b26-14c08a11dcc6.png)

**Comment by SirCmpwn** [comment]
Yes, a log would be nice.

**Comment by acorreya** [comment]
Hello..

Got busy with life. Meanwhile, I need to know how can I collect the logs.
I'm failing to reproduce the error tho..

Adrine Antony Correya
Doctoral Researcher
International School of Photonics
Cochin University of Science and Technology
Kochi, India - 682022
+91 9746-117-110

**Comment by acorreya** [comment]
Can't reproduce this anymore. I think it's something with Firefox like windows
