### ISSUE TITLE
critical issue if workspace_layout set to tabbed

### ISSUE THREAD

**Issue by okeri** [SirCmpwn/sway#858]
Hi there. First for all, thank you for this project.
Unfortunately i've found a segfault(

steps to reproduce:
1. put the line "workspace_layout tabbed" to /etc/sway/config and start sway
2. start browser (firefox or chromium) 
3. find any link and press right button and choose "save link as". 
New popup window will be created and browser will be crushed. Sway will be crushed as soon as you press any key. 

First look to issue gives an error at handlers.c:843
**for (i = 0; i < pointer->parent->floating->length; i++) {**
while pointer->parent->floating == NULL

Actually i don't really know why this is happened here. Hope you will fix this, or tell me any kind of workaround. My goal is to have tabbed layout by default.

**Comment by VoidNoire** [comment]
This might be a dupe of #674 .

**Comment by okeri** [comment]
Ou. it's true
