### ISSUE TITLE
Improve man sway-input

### ISSUE THREAD

**Issue by goetzc** [SirCmpwn/sway#860]
From `man sway-input` it is not clear the sintaxis for the configuration and how to get the `<identifier>`.

```man
DESCRIPTION
       Sway allows for configuration of libinput devices through
       input { } blocks in your config file.

COMMANDS
       input <identifier> accel_profile <adaptive|flat>
           Sets the pointer acceleration profile for the
           specified input device.
...
```

I had to search configuration examples to find the correct way: 
`input <identifier> { options }`  

Querying the identifier with `swaymsg -t get_inputs`

Adding an example in the config file would be handy.

**Comment by SirCmpwn** [comment]
#840

**Comment by goetzc** [comment]
Oh, didn't see that PR.

What about the other two items?

**Comment by SirCmpwn** [comment]
What two items are you referring to?

**Comment by goetzc** [comment]
An 'input {}' example in the config file. 
 
And the other is that it is not so clear from the man page, that the sway-input commands must be specified *inside* the `input {}`block. The sway-bar man is clearer about that. Using those workings, one could have:

In the DESCRIPTION section, instead of:
> Sway allows for configuration of libinput devices through input { } blocks in your config file.

This:
> Sway allows for configuration of libinput devices within the sway configuration file. sway-input commands must be used inside a input {} block in the config.

**Comment by SirCmpwn** [comment]
Ah. Well, feel free to send along a patch.

**Comment by goetzc** [comment]
Sure, hope it is ok #862.
