### ISSUE TITLE
Black screen with cursor in top left corner

### ISSUE THREAD

**Issue by kiljacken** [SirCmpwn/sway#870]
Upon attempting to start sway on my laptop running intel hd graphics (HD 4000, i5-3317U) all I get is a black screen with a non-responsive cursor in the top left corner. Has anybody encountered this issue before?

Here's the output of `sway -dV` when running from a plain tty: [link](https://gist.github.com/kiljacken/518eee4a5bb8e1aef4c28a38c8b40550)

**Comment by SirCmpwn** [comment]
Paging @Cloudef

**Comment by kiljacken** [comment]
I should probably add that the issue also occurs with the default config included with sway.

**Comment by Reventl0v** [comment]
When this happen, is X running at the same time or not ?

**Comment by kiljacken** [comment]
@Reventl0v This happens in several cases, straight from a tty, X as main wm, and as a window inside a X wm.

**Comment by kiljacken** [comment]
Upon reinstalling my laptop I can no longer reproduce this issue. Must've been a quirk with my setup.
