### ISSUE TITLE
Support for input methods like ibus

### ISSUE THREAD

**Issue by jessesung** [SirCmpwn/sway#873]
Please add support for input methods.

There are quite a lot of input method framworks run on X, like ibus, fcitx, uim, ucimf, gcin,...
Currently gnome uses ibus, thus there's wayland support in ibus.

No idea if there's a general way to support various input methods, and how much it would take to make sway support ibus or let other input methods work in wayland.

**Comment by Kunagi7** [comment]
Right now sway supports basic input method switching via xkbconfig, I use this on my script to start sway:
```
# Keyboard setup:
export XKB_DEFAULT_LAYOUT=es,ru
export XKB_DEFAULT_VARIANT=deadtilde,phonetic
export XKB_DEFAULT_MODEL=pc101
export XKB_DEFAULT_OPTIONS=grp:win_space_toggle
sway
```
First line sets the layouts, the second one the layout types, third one the keyboard type and fourth the toggle key.
To obtain the keyboard layouts, variants... I used this command:
```
man xkeyboard-config
```
I've been trying to add the japanese keyboard but without ibus anthy it's quite useless...
I hope they add ibus support into sway.

**Comment by SirCmpwn** [comment]
I got ibus working with xwayland apps today on sway with this configuration:

https://gogs.sr.ht/SirCmpwn/dotfiles/commit/618910b97e3b400766a0d499372b2ad3d15fd7c2

It's not perfect but it's だいじょぶ :)

**Comment by Kunagi7** [comment]
I found an ibus-toggle script on an archlinux forum which pretty match kills or starts the ibus-daemon (I have IBus 1.5.11).
Also added the different environment variables into my sway launch script.
Executing ibus engine :
```
(process:21078): IBUS-WARNING **: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.
No engine is set.
```
Leaves me into that...
But after poking a little, if I do:
```
ibus engine anthy
```
すごいい！日本語！
So pretty much, I can't switch between methods unless I use the terminal.
Since I already have russian in xkb I could make a shortcut to switch between xkb and ibus anthy :+1: .

**Comment by nerdDan** [comment]
@SirCmpwn I can not open your script

**Comment by SirCmpwn** [comment]
See https://git.sr.ht/~sircmpwn/dotfiles/

**Comment by 1wxyz** [comment]
> I got ibus working with xwayland apps today on sway with this configuration:
> 
> https://gogs.sr.ht/SirCmpwn/dotfiles/commit/618910b97e3b400766a0d499372b2ad3d15fd7c2
> 
> It's not perfect but これは大丈夫です :)

It doesn't work for libpinyin

**Comment by kisik21** [comment]
But what about native wayland apps? If I use xwayland apps only on sway, why would I need sway? I could just use i3... oh wait, I can't because Xorg's DPMS support is utterly broken on my machine while Sway works perfectly :3

**Comment by imyxh** [comment]
> It doesn't work for libpinyin

Mhm. The pinyin selection dialog flashes in the upper left but goes away immediately for me. If I press space very quickly after typing my character, I can at least get the first match to be selected ... but given how Chinese works, that's pretty much useless—we really need to be able to scroll through the match list.

**Comment by tmccombs** [comment]
How do you get functionnality like <ctrl>+<shift>+u for unicode and <ctrl>+<shift>+e for emoji?
