### ISSUE TITLE
Can't copy from PDFs when opened with Evince

### ISSUE THREAD

**Issue by VoidNoire** [SirCmpwn/sway#880]
I tried copying text from four different PDFs (none of which are copy-protected I think) opened with Evince and wasn't able to. I am able to copy them if I open the files using pdf.js in Firefox so it might be an issue with Evince. Interestingly, when I try to copy the selected text in Evince using ^C then again using the right-click menu option, Evince crashes and the terminal outputs:

(evince:6556): Gdk-WARNING **: Error 22 (Invalid argument) dispatching to Wayland display.

If I don't try to copy using ^C beforehand, it won't crash when I try to copy using the right-click menu option. Not sure if that is related though. The problems don't occur in i3 so I suspect it is something related to sway/wlc. I think the relevant lines in [sway.log](http://pastebin.com/B2NBFSJr) are at ~514.

Maybe I should post a ticket in https://github.com/Cloudef/wlc as well?

**Comment by SirCmpwn** [comment]
wlc doesn't yet support syncronization between the x and wayland clipboards.
