### ISSUE TITLE
systemd-logind idle suspend even on user activity

### ISSUE THREAD

**Issue by acorreya** [SirCmpwn/sway#886]
Hi! I am not sure if this is the right place to be posting this. But systemd-logind suspends my laptop every n minutes as per setting even when I'm working hard on it. As per https://bugs.freedesktop.org/show_bug.cgi?id=77671 is there a way to rectify this?

**Comment by SirCmpwn** [comment]
There's no fucking way I'm hardcoding some systemd API into sway to tell it not to suspend your laptop.

**Comment by acorreya** [comment]
Thanks for all the great work, btw. Maybe I'll find a way out and let you know. Huge fan, by the way.

**Comment by SirCmpwn** [comment]
There should be some kind of setting exposed by systemd to disable this behavior. You should ask them about that.

**Comment by nloewen** [comment]
Is this something that could be handled/abstracted in WLC? They already have a chunk of logind specific code.

**Comment by progandy** [comment]
It should be possible to call something like this in after sway has started:
```
#!/bin/bash
sp=$(gdbus call -y -d org.freedesktop.login1 -o /org/freedesktop/login1 -m org.freedesktop.login1.Manager.GetSessionByPID $$ | sed -n "s/^(objectpath '\(.*\)'.*$/\1/p")

gdbus call -y -d org.freedesktop.login1 -o "$sp" -m org.freedesktop.login1.Session.SetIdleHint false
```

**Comment by prosoitos** [comment]
My apologies for using this thread for an issue unrelated to sway, but I was wondering whether you found a solution to your problem @acorreya.

I am having the exact same problem on Arch Linux with totally different setup (not using i3, not using Wayland) and at a loss to find solutions. So any clue would be very helpful. Thank you.
