### ISSUE TITLE
IPC compatibility issue (i3ipc)

### ISSUE THREAD

**Issue by johnp** [SirCmpwn/sway#890]
In [`ipc_json_describe_container_recursive`](https://github.com/SirCmpwn/sway/blob/416417a54c5875abcdc257b6ad10ff086c35eefc/sway/ipc-json.c#L357) the `floating_nodes` and `nodes` arrays are not always added which causes compatibility issues with software that relies on i3 assumingly unconditionally adding those arrays (though empty in the case where Sway doesn't add them at all).

Case in point: python-i3ipc blindly iterates down the tree trough the `nodes` attribute and fails with a `KeyError` [here](https://github.com/acrisci/i3ipc-python/blob/master/i3ipc/i3ipc.py#L439).

I'm happy to take this to the i3ipc dev, but I don't know how much other projects may rely on this weird behavior and if it's something Sway should replicate or not.

**Comment by SirCmpwn** [comment]
Should definitely be fixed in sway, not in i3ipc. Thanks for the bug report.

**Comment by zandrmartin** [comment]
FWIW those arrays do get added to views in the `ipc_json_describe_view()` function [here](https://github.com/SirCmpwn/sway/blob/master/sway/ipc-json.c#L202-L203), but I'm going to do a PR to merge those with the code in `ipc_json_describe_container_recursive()` anyway just to clean it up.

**Comment by SirCmpwn** [comment]
Is this good to go?

**Comment by johnp** [comment]
Well, the first KeyError seems to be fixed. [Here's](https://github.com/acrisci/i3ipc-python/blob/master/i3ipc/i3ipc.py#L104) the next (`BindingEvent` is missing `mods` key).  
Should I open a new issue for this or shall we just continue to collect i3ipc compat issues here?

**Comment by zandrmartin** [comment]
That's a non-standard key according to the i3 docs [here](http://i3wm.org/docs/ipc.html#_binding_event). Looks like it might be an old version of `event_state_mask` which we do include.

**Comment by johnp** [comment]
Yeah it apparently is: [i3 source code comment](https://github.com/i3/i3/blob/f0cea63fd5dd20c24f9cc8eb87d854b9575bce2a/src/ipc.c#L209)

**Comment by SirCmpwn** [comment]
New problems, new issues.
