### ISSUE TITLE
Segmentation fault in printf_core when opening a web page

### ISSUE THREAD

**Issue by kobezda** [SirCmpwn/sway#893]
Sway segfaults when opening a page in qutebrowser.

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f3af50bb1c2 in printf_core (f=f@entry=0x7ffe2776fbe0, 
    fmt=fmt@entry=0x5637d34dc9e0 "-25 % na cel\303\275 sortiment d\303\241mskej starostlivosti o ple\305\245 - qutebrowser", ap=ap@entry=0x7ffe2776fa58, 
    nl_arg=nl_arg@entry=0x7ffe2776faf0, nl_type=nl_type@entry=0x7ffe2776fa70) at src/stdio/vfprintf.c:554
```

To reproduce, run `qutebrowser --backend webkit --temp-basedir 'http://www.dm-drogeriemarkt.sk/sk_homepage/active_beauty/vyhody/aktivity/870834/joker-plet.html'`

gdb's bt full: [btfull.txt](https://github.com/SirCmpwn/sway/files/465859/btfull.txt)
core dump: [core.zip](https://github.com/SirCmpwn/sway/files/465860/core.zip)
sway log: [sway.txt](https://github.com/SirCmpwn/sway/files/465862/sway.txt)
qutebrowser log: [qute.txt](https://github.com/SirCmpwn/sway/files/465863/qute.txt)
sway config: [sway-config.txt](https://github.com/SirCmpwn/sway/files/465871/sway-config.txt)
emerge info: [emerge_info.txt](https://github.com/SirCmpwn/sway/files/465872/emerge_info.txt)

**Comment by alkino** [comment]
I reproduce it with a minimal case...

```c
#include <stdio.h>
int main(int argc, char *argv[])
{
  printf("%s\n", argv[1]);
}
 ```
The title of the page is 
> -25 % na celý sortiment dámskej starostlivosti o pleť
Compile the binary, give the title of the page as first argument make sway crash.
