### ISSUE TITLE
Support for numeric character reference for workspace names

### ISSUE THREAD

**Issue by Leinnan** [SirCmpwn/sway#897]
In i3(or at least i3-gaps version) we have support for this characters(example[with spaces, because github replace code with one char just like i3bar]: & # x0C8D;), which are great when we using icon fonts like font awesome. In sway we have just plain text. Any chance for support that?
https://en.wikipedia.org/wiki/Numeric_character_reference

**Comment by SirCmpwn** [comment]
I guess we should implement that to support i3 compatability, but ftr I disagree with the feature. Why not just output unicode characters?

**Comment by nloewen** [comment]
Unicode characters can be difficult to type. This is especially when working with icon fonts which make use of otherwise unused code points which won't show up in any physical or soft keyboards.

**Comment by SirCmpwn** [comment]
But you can use i.e. \u

**Comment by nloewen** [comment]
Ah, I was confusing this for any character substitution. Then I've got no clue.
