### ISSUE TITLE
No latam (Spanish Latin American) support ?

### ISSUE THREAD

**Issue by ignaciocaamanio** [SirCmpwn/sway#898]
Setting XKB_DEFAULT_LAYOUT=latam doesn't work, but "es" layout does. 

No support for "latam"?

**Comment by SirCmpwn** [comment]
latam is listed in xkb's keyboard layouts. This is an XKB problem, not a Sway one.

**Comment by ignaciocaamanio** [comment]
Yes, latam is listed in xkb's keyboard layouts, and works in all  WM's that I use. Some help to make it work? Thanks.

**Comment by SirCmpwn** [comment]
Does it work on orbment?

**Comment by SirCmpwn** [comment]
Or Weston?

**Comment by ignaciocaamanio** [comment]
Sorry, I was making something wrong when setting XKB_DEFAULT_LAYOUT, now it works. Thanks for yout help.
