### ISSUE TITLE
[Feature Request] change kbmap for windws individually

### ISSUE THREAD

**Issue by Unip0rn** [SirCmpwn/sway#899]
The idea is to add something in the config like 
`for_window [title="eclipse $"] kbmap us`
so you can use different kbmaps hen you like to, but are not bound to reswitch when just switching to IRC for a quick replay (just an example)

**Comment by acrisci** [comment]
It's possible to do this with the IPC.

**Comment by SirCmpwn** [comment]
Send feature request up to wlc, then we'll add a command for it if they support it.

>It's possible to do this with the IPC.

How?

**Comment by xXWebinterfaceXx** [comment]
thanks for the replies, I will request at wlc then.

**Comment by kenny1847** [comment]
another better one idea is to allow users to has different kbmap per window.
With X11 there were some tools kinda kbdd etc.

**Comment by ejiek** [comment]
Afaik **kbdd** uses Extended Window Manager Hints (EWMH) and **wlc** does have an `xcb-ewmh` as a dependancy. Are EWMH supported in Sway?
____
For now kbdd is not usable in Sway (even with X apps)

**Comment by SirCmpwn** [comment]
This is planned for wlroots.
