### ISSUE TITLE
"Failed to switch back to vt2estoration" [sic] error message on startup

### ISSUE THREAD

**Issue by l0b0** [SirCmpwn/sway#908]
I'm able to run Sway inside Awesome WM, but when running in a different VT it prints this error message and exits (It looks like there's an issue with printing `\r` instead of `\n` resulting in the error message being clobbered). Could this be an issue related to running X in a different VT or to proprietary nvidia drivers?

**Comment by SirCmpwn** [comment]
Sorry for the late response. Running sway within x is a developer feature and is unsupported. You can use it if you want, but not file bugs about it.
