### ISSUE TITLE
HIDPI bar doesn't scale correctly

### ISSUE THREAD

**Issue by jarias** [SirCmpwn/sway#910]
![screenshot-20160919-092520](https://cloud.githubusercontent.com/assets/119519/18637957/743c90a8-7e4b-11e6-937e-79080439d290.png)

Sway: master
WLC: master

Output config:

`output eDP-1 scale 2 bg ~/Images/wallpaper.png fill`

**Comment by SirCmpwn** [comment]
Thanks! I can reproduce this problem.
