### ISSUE TITLE
Non-integer scale factor

### ISSUE THREAD

**Issue by dobegor** [SirCmpwn/sway#912]
https://github.com/Cloudef/wlc/issues/57#issuecomment-145515885

Right now we can't set non-integral scale factor.

**Comment by SirCmpwn** [comment]
This isn't supported by any Wayland compositor. You could fake it by setting your resolution to the effective resolution you want.

**Comment by dobegor** [comment]
Could you please provide an example how do I calculate the needed resolution?

**Comment by SirCmpwn** [comment]
If your resolution is i.e. 300x300 and you want to use 1:3 scale you would set your res to 100x100 in your output config line.

**Comment by dobegor** [comment]
Thanks!
