### ISSUE TITLE
Switch to workspace

### ISSUE THREAD

**Issue by heret1c** [SirCmpwn/sway#922]
Hello 

When setting "XKB_DEFAULT_LAYOUT=cz", I can not switch between workspaces. Otherwise, all the keys are working. When using "XKB_DEFAULT_LAYOUT=gb" as a default, work well all the hotkeys.
I also use X11 with i3wm and all shortcuts work well.

Thank you all.

**Comment by alkino** [comment]
We need more info about this.
Does it work with swaymsg? What are you're binding to change workspace. Give us some hints with "xev" and "libinput-debug-events".

Regards

**Comment by heret1c** [comment]
Hi

Swaywm version 0.9-1
Wayland 1.12.0-1
Key remapping works great. But they appeared to me other problems.
When gaming, the system is still active cursor. DOSBox and native games for Linux. Perhaps the problem is on the side of Weston config file?

Yours sincerely

**Comment by adamjedlicka** [comment]
Same problem is happening to me. I'm to using Czech keyboard layout and default config. This is output of libinput-debug-events when trying to switch workspaces: http://pastebin.com/RCy17FKt

When I press '1' key (that one over 'Q' button, not on numpad) on Czech layout I get '+' sign. '2' is 'ě', '3' is 'š' and so on (special characters). When I try to rebind workspaces to these characters it does nothing : bindsym $mod+ě workspace 2

**Comment by benjiprod** [comment]
For Czech or other keyboard, you have to remap your keyboard with 'xmodmap' for displaying key code.

Try this for your keyboard : 
```
bindsym $mod+plus workspace 1
bindsym $mod+ecaron workspace 2
bindsym $mod+scaron workspace 3
bindsym $mod+ccaron workspace 4
bindsym $mod+rcaron workspace 5
bindsym $mod+zcaron workspace 6
bindsym $mod+yacute workspace 7
bindsym $mod+aacute workspace 8
bindsym $mod+iacute workspace 9
bindsym $mod+eacute workspace 0

bindsym $mod+Shift+plus move container to workspace 1
bindsym $mod+Shift+ecaron move container to workspace 2
bindsym $mod+Shift+scaron move container to workspace 3
bindsym $mod+Shift+ccaron move container to workspace 4
bindsym $mod+Shift+rcaron move container to workspace 5
bindsym $mod+Shift+zcaron move container to workspace 6
bindsym $mod+Shift+yacute move container to workspace 7
bindsym $mod+Shift+aacute move container to workspace 8
bindsym $mod+Shift+iacute move container to workspace 9
bindsym $mod+Shift+eacute move container to workspace 0
```

**Comment by benjiprod** [comment]
I am pretty sure you can close this issue.
