### ISSUE TITLE
sway segfaults while using scratchpad

### ISSUE THREAD

**Issue by jhalmen** [SirCmpwn/sway#927]
arch linux x_64 install, using the official community builds
reproducible: always
how-to: 
  start sway
  open terminal (mod+enter)   -- tested different terminals, happens regardless of which i'm using
  put terminal on scratchpad (mod+shift+minus)
  bring it into view (mod+minus)
  while focused, open another terminal (mod+enter), focus will move away, but no terminal will appear
  without moving the focus, move this newly created terminal into the scratchpad as well (mod+shift+minus)
  --> segfault

stacktrace follows:
```
Stack trace of thread 8068:
      #0  0x00000000004199d7 update_visibility_output (sway)
      #1  0x0000000000419a7b update_visibility_output (sway)
      #2  0x00000000004254a8 arrange_windows (sway)
      #3  0x0000000000411d04 n/a (sway)
      #4  0x000000000041247e handle_command (sway)
      #5  0x000000000041dc44 n/a (sway)
      #6  0x00007f3324c29cb4 n/a (libwlc.so.0)
      #7  0x00007f3324c2cb61 n/a (libwlc.so.0)
      #8  0x00007f3324c3ffc4 n/a (libwlc.so.0)
      #9  0x00007f33245c1d32 wl_event_loop_dispatch (libwayland-ser
      #10 0x00007f33245c01da wl_display_run (libwayland-server.so.0
      #11 0x00007f3324c413ac wlc_run (libwlc.so.0)
      #12 0x0000000000408f4c main (sway)
      #13 0x00007f332332d291 __libc_start_main (libc.so.6)
      #14 0x0000000000408fa9 _start (sway)
```

**Comment by alkino** [comment]
I can reproduce something similar.
Focus a floating window. Open a terminal when this window is focused => crash
