### ISSUE TITLE
$mod+h/l does not wrap around

### ISSUE THREAD

**Issue by wasamasa** [SirCmpwn/sway#930]
In i3wm, using focus movement repeatedly wraps around or in other words, if I move focus in a v-split from the right window to the left and repeat, I end up with focus on the right window again.  In sway focus would stay on the left window.  This is not the entire i3 behavior as it appears to apply to workspaces on adjacent screens, too, but I haven't quite figured it out yet.  Perhaps a look at the sources would be instructive to pin it down...

**Comment by Inc0n** [comment]
in i3 there is also `focus_wrapping no` now, which disable this behaviour, is this something sway supports as well.
