### ISSUE TITLE
Resize indicator looks different from i3

### ISSUE THREAD

**Issue by wasamasa** [SirCmpwn/sway#932]
[i3](http://i.imgur.com/HQwdmYK.png)
[sway](http://i.imgur.com/E94utJi.png)

Both use the same config and do otherwise look the same.

**Comment by mikkeloscar** [comment]
can you post your config?

**Comment by wasamasa** [comment]
https://github.com/wasamasa/dotfiles/blob/master/home/wasa/.config/i3/config

**Comment by thejan2009** [comment]
Here is what happens: if binding_mode colours aren't provided in config, i3 uses urgent_workspace setting as a fallback. Swaybar is also missing 3 colour settings: ```focused_background```, ```focused_statusline``` and ```focused_separator```.
