### ISSUE TITLE
High sway CPU usage playing video 

### ISSUE THREAD

**Issue by sjug** [SirCmpwn/sway#939]
**System info**
Linux 4.7.6-ARCH
wayland 1.12.0-1
sway 0.9-1
mpv 0.20.0-1
libva 1.7.2-1

**mpv.conf**

```
hwdec=vaapi
vo=opengl
volume-max=200g
```

**Steps to reproduce**
1. Play 1080p video with `mpv` that is supported by VA-API acceleration
2. Check CPU usage with `htop` or similar
3. `mpv` is using very low/no CPU due to hardware accelerated decoding, `sway` is using 18-20% CPU solid

**Comment by alkino** [comment]
Can you try with my patch?

**Comment by sjug** [comment]
@alkino Should I build off your branch?

**Comment by alkino** [comment]
Yes.

**Comment by sjug** [comment]
@alkino Tested the same video with the same conditions on both Sway v0.9 and on your branch. Unfortunately, I see no performance difference with the setup described.

**Comment by alkino** [comment]
Ok so. I will explain you how make performance measurement.

Clean all your builds.
Enable performance:
``` shell
cmake -DCMAKE_C_FLAGS=-pg -DCMAKE_EXE_LINKER_FLAGS=-pg -DCMAKE_SHARED_LINKER_FLAGS=-pg ..
make
```
Run your executable, a `gmon.out` should appear.
Now run:
```
gprof ./bin/sway gmon.out
```
and send me this report.

**Comment by sjug** [comment]
@alkino 

I've run your instructions, report gist: https://gist.github.com/sjug/84e135878f5b165a0c52218057f011d9

**Comment by alkino** [comment]
As you can see. Nothing take time in sway \o/
Do you run your movie in your sway? If yes, maybe you need to run it longer.

**Comment by sjug** [comment]
@alkino You're right sorry, that was a useless report. I've done another one that actually has some data.
Let me know if this is more helpful: https://gist.github.com/sjug/3f01b61db85370ed614ae5cc934908df

**Comment by alkino** [comment]
As you can see, the function which takes most of the time is _swayc_by_handle_helper. This function has been remove by my patch. So can you take a new measurement with my patch?

**Comment by sjug** [comment]
Very clear difference in application profile with the patch, but the performance difference I do not see.
See: (gprof report gist)[https://gist.github.com/sjug/19402a93c4b89f67fd5c2aacab541ee5]

**Comment by alkino** [comment]
Hm. My patch reduce use of CPU of sway. But it seems that the time is not lost in sway but in a sway's library. I'm doing more verbose perf test with "perf" in linux-tools, and it gives me that "__mmsse3_memcpy" consume a lot of time. Keep you in touch later.

**Comment by sjug** [comment]
I turn off borders on mpv, so shouldn't it not be calling that?

**Comment by alkino** [comment]
As you can see: render_view_border is call 639,081 times for you.

**Comment by DarkDefender** [comment]
Maybe this problem is also related to why we get lower fps with glxgears: #775

**Comment by alkino** [comment]
I got 60 FPS with glxgears.

**Comment by psgarsenal** [comment]
start glxgears like this to avoid the 60fps cap: vblank_mode=0 glxgears

**Comment by alkino** [comment]
Thanks. 710 FPS. I will start an implementation of "redraw_borders" only when needed.

**Comment by occivink** [comment]
How much do you get under X11 though? Ideally there shouldn't be any difference.

**Comment by alkino** [comment]
1000FPS vs 500FPS...

**Comment by SirCmpwn** [comment]
Profile it and send patches.

**Comment by sjug** [comment]
Not fixed but OK.

**Comment by sjug** [comment]
I have profiled it. You might be lost though, this is the issue tracker not
PR list. I'm reporting an issue.

**Comment by SirCmpwn** [comment]
If you've profiled it you need to make the results of your profiling available here, or this issue is useless. See #1004 for a better example of how to report performance issues.

**Comment by sjug** [comment]
What are you on about? How are the results of my profiling not available here, did you check this thread at all? So you're saying because I wasn't asked for a flame graph at any time and never generated one... That's somehow what should be done. Good one.

**Comment by SirCmpwn** [comment]
My mistake, I see your results now. However, it appears to be the same underlying issue as in #1004.

Remember this project is run by volunteers who owe you nothing, getting snotty with us gets you nowhere.

**Comment by sjug** [comment]
"Getting snotty"? I did everything I did to help debug the issue by these "volunteers" you speak of. Everything was fine until you rolled in here closing the issue and saying "Profile it and send patches."

Let me know how I was "snotty" prior to anything you said.
