### ISSUE TITLE
Qt window decorations remain within border

### ISSUE THREAD

**Issue by stozi** [SirCmpwn/sway#949]
In i3 Qt window decorations do not appear, but in Sway they do.

**Comment by SirCmpwn** [comment]
Read the FAQ.

**Comment by stozi** [comment]
so... I have to change my environment variables everytime I switch between window managers? This wasn't necessary in i3/X11

**Comment by SirCmpwn** [comment]
Most people write a script that sets up their environment variables the way they like and then launches sway with them.
