### ISSUE TITLE
Proper Resizing.

### ISSUE THREAD

**Issue by Luminarys** [SirCmpwn/sway#95]
Resizing is a tricky thing to do properly and needs to be handled in more than a few situations. This issue will serve to list proposed ideas and to debate them.

* Resizing windows using `resize grow/shrink height/width`:
Check to see if the parent container has the layout which is in line with our type of movement(L_HORIZ for width). If it does not, or it has 0 children which are to the left/right or top/bottom of our current container, then move up to the next parent and check again. Repeat until root container is hit, or we get a proper check. Once we do, count the number of containers that are either to the left/right or top/bottom of our focused container. If there are only containers to one side or the other, increase the edge of the current container by the specified amount, and decrease the edges of all the siblings by the specified amount/sibling number. If there are containers on both sides, increase both sides of our container by amount/2 and decrease the other containers by the amoumt/number on that side * 1/2. These containers will have the recursive resizer applied to them to ensure that they are resized properly with all children.

* Resizing windows using the mouse:
Find the edge of the currently focused view that the mouse is closest to. Check the parent of the currently focused view's edge to see if it has the same X or Y coordinate as the currently focused view's edge. If it does, move up to the parent and perform the check again. If the parent does not share the edge, then resize all views within the current container in the proper direction, and resize all views in the bordering container in the opposite direction. A recursive function will perform this resizing, but its exact functionality is tbd.

* Inserting a new view:
There's some discussion between me and @taiyu-len about the best way to do this. I favor a method in which, all sibling containers have their width/height reduced by `parent container width or height/number of siblings+1`. This width/height and X/Y reduction will be performed by the recursive resizing function using edges determined by mouse direction, and the new view is inserted into the new space which should be around where the mouse was.

* Recursive function to properly resize a container and all its children:
This function should take a container, a direction, and a pixel value. It should add the pixel value(either positive or negative) to the container's X or Y on the proper edge and also add the pixel value to either the width or height. Then it should find the number of of children which have the same orientation as the provided edge(i.e. width corresponds to the number of containers on the left/right of eachother and vice versa), and apply the function using the pixel change divided by this number of children, and the given direction.

Thoughts, alternative ideas, etc?

**Comment by nim-** [comment]
I not skilled enough to comment on the difficulty of implementing this, but in regards to mouse resizing I think it would make sense to implement simultaneous x- and y-axis mouse resizing of tiled windows as other WM's (like bspwm for example) have done it.

Example:
http://youtu.be/U17CLayt_aA?t=14s

This is an accepted i3 feature request but has not been implemented yet, probably because it is very complex (see https://github.com/i3/i3/issues/1122). Since sway is being built up from the ground it might be cleaner to implement this than in vanilla i3, but I wouldn't know.

**Comment by SirCmpwn** [comment]
That's cool as shit, we should try do to that

**Comment by Luminarys** [comment]
I don't think that it would actually be too hard. I need to think more about this, but I believe that we could allow resizes in arbitrary directions by simply considering the movement to be a vector made up of a horizontal and vertical resize, and applying the logic I described for mouse resizes in both directions.

**Comment by SirCmpwn** [comment]
Status update?

**Comment by Luminarys** [comment]
I've implemented everything described. The whole sibling insertion thing is somewhat irrelevant as arrange_windows takes care of this stuff. The only thing really left to debate are the minor details of how resizing should work, so I'm going to close the issue.
