### ISSUE TITLE
Crash when trying to move windows

### ISSUE THREAD

**Issue by AStrangeEnigma** [SirCmpwn/sway#951]
Affects latest HEAD, as far as I can tell. Wasn't have the issue before.

Steps to reproduce:
Launch sway
Open two windows
Try to move one of them down

So for me:
sway -d
mod+enter
mod+enter
mod+shift+down

...which is exactly what I ran to get the following output:

https://gist.github.com/AStrangeEnigma/fd75e6a0bf82d5cf97dc37881fb3b03c#file-gistfile1-txt-L496

thejan2009 remarked on irc:
SirCmpwn: DenialAdams: that was caused by the latest pr

Thanks!

**Comment by AStrangeEnigma** [comment]
Unfortunately I don't have the knowledge to fix it, but it looks like it it is getting stuck in the while(true) loop at layout#268.

**Comment by thejan2009** [comment]
#945 is the culprit.

**Comment by AStrangeEnigma** [comment]
Works great now! Thanks
