### ISSUE TITLE
Workspace buttons - Background color is now white

### ISSUE THREAD

**Issue by esphen** [SirCmpwn/sway#955]
Hi, just dropping by to report a possible minor regression.

I just emerged `sway-9999` again today, and now I am now seeing the background color of the workspace buttons in the title bar have a constant white background color. Previously they were gray-ish. This is only the case for inactive workspaces.

Try the following config:
```
bar {
  status_command swaybar
  tray_output primary
  colors {
    statusline #ffffff
    background #000000
    inactive_workspace #32323200 #32323200 #5c5c5c
  }
}
```

As long as the `inactive_workspace` key is present, the background color of the buttons is white, but if I take it out and reload my config, it looks like it did before updating.

Removing the two trailing zeroes seems to make it not-white again; has there been any changes affecting the alpha channel values of inactive workspace buttons?

**Comment by SirCmpwn** [comment]
The default blending mode has been changed to overwite. This behavior won't be included in sway 0.10 and will be configurable in sway 0.11.
