### ISSUE TITLE
[Feature request] Close button on the window bars

### ISSUE THREAD

**Issue by sfgasdfsafggfgg** [SirCmpwn/sway#956]

**Comment by thejan2009** [comment]
Would closing a window by middle-clicking the title bar be a legit substitute?

**Comment by mikkeloscar** [comment]
In my mind this is sort of against the philosophy of i3/sway. Wayland already gives you CSD for better or for worse, so you can just use the close button drawn by the clients if you want this feature.

**Comment by sfgasdfsafggfgg** [comment]
@thejan2009 I worry about accidently closing a window if I'm middle-clicking on web browser tabs to close them.

@mikkeloscar What is CSD?

**Comment by FreeFull** [comment]
@sfgasdfsafggfgg CSD = "Client-Side Decorations", that is, the client itself draws its own window border and title bar.
