### ISSUE TITLE
Gnome 3.22 apps and xdg_shell

### ISSUE THREAD

**Issue by gferon** [SirCmpwn/sway#957]
I've been testing Fedora 25, and since Gnome 3.22 apps have been introduced, they seem to revert to using XWayland in Sway.

Here is the message is shows when either starting nautilus or gnome-terminal for instance:
`(gnome-terminal:12612): Gdk-WARNING **: Wayland compositor does not support xdg_shell interface, not using Wayland display`

Is this a known issue? How would one even start tackling this issue, because from my understanding the xdg_shell interface looks like concepts for more conventional window managers.

**Comment by gferon** [comment]
Compiled `sway` and `wlc` from source, and the issue is gone! Keep up the good work, I'll try to find a way to contribute in the future :)

**Comment by mrgrumpyarse** [comment]
I believe the issue still partially exists but appears to be in wlc
https://github.com/Cloudef/wlc/issues/200

**Comment by SirCmpwn** [comment]
Leave this in wlc's tracker.
