### ISSUE TITLE
Monitor hotplugging

### ISSUE THREAD

**Issue by main--** [SirCmpwn/sway#960]
Sway gets very confused whenever I connect or disconnect one of my monitors.

The most common issues are:
- I expect a dead output's workspaces to be moved to any of the remaining screens (and I'm pretty sure that's how i3 handles it). Instead, the workspace usually still exists but there's no way to view it. Sometimes the whole workspace just disappears. In that case the applications may or may not die.
- When connecting my second monitor, sway starts rendering all workspaces on the wrong display: When I select a workspace from the left screen, the left bar highlights it correctly but the actual windows appear on the right screen and vice versa. It's fully inverted.
- Monitor hotplug can sometimes make the bar disappear.
- When disconnecting the last monitor, sway drops all windows and workspaces. Upon reconnecting, the windows will be _behind_ everything, just like swaybg usually is. Even mouse interaction is still possible. This is especially annoying as there is no workaround - I have to exit sway every time I switch both monitors to my Windows VM (gpu passthrough).

**Comment by SirCmpwn** [comment]
Most of these problems almost certainly originate from wlc.

**Comment by craigcabrey** [comment]
When I plug in an external monitor, my laptop display goes black and the external monitor shows a new workspace. Unplugging the display does not bring back my laptop's screen. I am forced to hard reset my machine. Is this a `wlc` issue?

**Comment by DebugReport** [comment]
Confirm, i get black screen too...
https://gist.github.com/DebugReport/2448323415a554ac971ba60925e9d9bb

**Comment by main--** [comment]
So after some more extensive testing (aka everyday use), here's what I can reproduce reliably. Note that I have two displays, one 2K monitor that's connected via HDMI and one 4K monitor via DP.

* Disconnecting the second (DP) monitor works *fine*. Only when I reconnect it, the bar always becomes inverted and the new monitor's background is black.
* Launching sway on the first (HDMI) monitor and only then connecting the other one works *fine* - no issue with the bars. However, many applications (emacs, mumble, etc) start rendering text (and only the text) in a bigger font size. Interestingly, this would be exactly what I want on my 4K monitor but it appears to be distinct from sway's actual highdpi support (I disabled that because I don't like the blurriness you get from scaling).
* Disconnecting the first monitor does not work. Sway never notices that it's gone and just keeps pretending it's still there until I reattach it. At least for my usecase (gpu passthrough) this is actually better as I don't usually *want* my window manager to move workspaces away from a display just because I temporarily switched it to Windows. Given that it still shows up as connected in `/sys/class/drm` I guess this is just the kernel being weird though.

The problem @craigcabrey and @DebugReport mention where the first monitor blacks out when I reconnect the second one did happen a few times on my system but I'm not able to reproduce it reliably. The same goes for the *disappearing* bar.

@SirCmpwn Which of these do you think are wlc issues? If it helps, [here](https://gist.github.com/main--/7a7494a8df83ade38f20e208a8dd6924) are the logs.

**Comment by main--** [comment]
The bar reliably disappears (crashes?) whenever I try to scroll through it (with mousewheel) once it's inverted.

**Comment by SirCmpwn** [comment]
Open an issue in wlc's tracker please.

**Comment by emersion** [comment]
>XWAYLAND0 and XWAYLAND1 is what I get from xrandr

Don't do that, it doesn't work.

**Comment by shengis** [comment]
@emersion yes thx, I saw that after posting... I will just "unpin" my workspaces.
