### ISSUE TITLE
Brightness Adjustment

### ISSUE THREAD

**Issue by ngrammel** [SirCmpwn/sway#964]
Adjusting screen brightness with xbacklight doesn't really work in Wayland. In i3, I'd have something like "bindsym XF86MonBrightnessUp exec xbacklight -inc 1" and similarly for decreasing the brightness. However, in wayland (and thus sway), xbacklight doesn't detect any devices ("No outputs have backlight property").

The only way I know of at the moment to adjust the brightness is directly modifying the "brightness" file of a device in /sys/class/backlight. This requires root access, making scripting a pain. It'd be nice if sway could provide some interface for modifying the brightness, so that users have a convenient utility to bind keys to.

**Comment by jplatte** [comment]
I don't think sway needs to provide an interface for this. Try https://haikarainen.github.io/light/

**Comment by ngrammel** [comment]
Thanks for the link. I wasn't aware of that one, nor would I have expected it to work in wayland (it does seem to work, though). I guess I imagined it might be nice for sway to provide this functionality itself, the way swaygrab replaced eg scrot. Perhaps at the least there should be a mention in the documentation somewhere (eg in sway(5) manpage) that refers the user to light. Since sway is meant to be a sort of drop-in replacement for i3, and surely many i3 users have keyboard shortcuts mapped to xbacklight. 
In any case, I think this is just a minor feature request at best.

**Comment by SirCmpwn** [comment]
Read the FAQ

**Comment by neon64** [comment]
If you want something with the same interface as xbacklight, check out [acpilight](https://github.com/wavexx/acpilight). It's been working quite well for me so far.
