### ISSUE TITLE
[RFE] Color temperature functionality

### ISSUE THREAD

**Issue by bagnaram** [SirCmpwn/sway#968]
Ability to set screen brightness/color temperature. This is common in X applications like F.lux or redshift. Unfortunatly, because Wayland does not expose color manipulation, this has to be implemented in the compositor. GNOME is implementing similar functionality: https://bugzilla.gnome.org/show_bug.cgi?id=741224

**Comment by SirCmpwn** [comment]
https://github.com/Cloudef/wlc/issues/174

**Comment by kamiyaa** [comment]
Hey, just wondering if there's any documentation on how to do this now that sway has migrated to wlroots?

**Comment by smlx** [comment]
https://github.com/swaywm/sway/wiki#redshift
