### ISSUE TITLE
Can't run sway from kmscon

### ISSUE THREAD

**Issue by DebugReport** [SirCmpwn/sway#969]
OS: ArchLinux
Sway: version 0.10-rc1-67-gde79fee (2016-11-15, branch "master")
WLC: Version : r992.f8bb91b-1
Kmscon: Version : 8-3
Log: https://gist.github.com/DebugReport/59967439df06c6a1565c91202ec147b8

**Comment by SirCmpwn** [comment]
This is either an issue with wlc or kmscon, not sway.
