### ISSUE TITLE
Lots of GTK programs don't work at all

### ISSUE THREAD

**Issue by Laaas** [SirCmpwn/sway#970]
LibreOffice crashes with "Application Error"

Gedit crashes with

(gedit:4908): Gtk-WARNING **: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned

(gedit:4908): Gtk-WARNING **: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned

(gedit:4908): Gtk-WARNING **: Failed to get an inhibit portal proxy: The name org.freedesktop.portal.Desktop is not owned

Then a segmentation fault (core dumped)

Gnome terminal crashes with

Warning: DESKTOP_STARTUP_ID not set and no fallback available.
Error creating terminal: Message recipient disconnected from message bus without replying

Firefox (50, tested both aurora nightly and normal) also has visual issues with pull-down menus (showing in incorrect places, not showing at all, etc.), but they still work as expected if you're blind.

I don't know if there's something special you have to do to view errors or warnings, since I don't see any with firefox.

I'm using arch linux with default linux kernel 4.8.8-1

**Comment by Laaas** [comment]
I haven't tested any other GTK programs, but I'd expect it to be the same.
BTW Discord canary works, even though it has gtk2 as a requirement.

**Comment by Laaas** [comment]
Chromium also works fine

**Comment by Lourens-Rich** [comment]
Which version of Xorg do you have?

**Comment by Laaas** [comment]
I'm using the latest version. Though this may not be a problem with sway as I tried gnome today and it didn't work either. Maybe I just fucked something up, maybe xwayland just doesn't work lately, or maybe it's gtk's fault.

**Comment by Lourens-Rich** [comment]
@Laaas Xorg 1.19 or 1.18?

**Comment by Laaas** [comment]
1.19

**Comment by Fale** [comment]
On Fedora 25, with Xorg 1.19 I don't see the described problem

**Comment by Laaas** [comment]
Honestly I think there is an incompatibility in my configuration somewhere,
because everything worked fine when I created a new user and tested on that
user. If I find the cause I'll say it here.

Den 24/11/2016 19.21 skrev "Fabio Alessandro Locati" <
notifications@github.com>:

**Comment by Laaas** [comment]
Honestly I just give up. I nuked my original user and made a new one.
Couldn't figure out exactly what was causing the programs to crash.

**Comment by Laaas** [comment]
Closing the issue

**Comment by Lourens-Rich** [comment]
@Laaas, please give for us your old configuration file.

**Comment by Lourens-Rich** [comment]
Or maybe you help me, what i must change for myself?
