### ISSUE TITLE
gtk3 applications crash when trying to open context menu

### ISSUE THREAD

**Issue by jplatte** [SirCmpwn/sway#976]
I've tried this with roxterm and a bunch of gnome programs, they crash reliably. The all print the same error message. E.g. gedit:

```
(gedit:10785): Gdk-ERROR **: Error flushing display: Broken pipe
[1]    10785 trace trap (core dumped)  LC_ALL=C gedit
```

This problem doesn't happen with Pidgin (gtk2 via XWayland) or Dolphin (Qt5).

I can reproduce this bug both with wlc 0.0.7 and sway 0.10 from the official arch repositories as well as with the latest git versions of both. Also for some bizarre reason, when using gtk3 with the typeahead patch (gtk3-typeahead in AUR), the processes all still terminate, but actually just with exit code 1, no core dump; and the error message looks different:

```sh
# LANG=en_US.utf8
Gdk-WARNING **: Error 71 (Protokollfehler) dispatching to Wayland display.

# LANG=de_DE.utf8
Gdk-WARNING **: Lost connection to Wayland compositor.
```

I'd be happy to help debug this. I guess I'd start by rebuilding gtk3 without stripping symbols, right?

EDIT: Right clicking is not the problem, in dwt where it opens a popover instead of a context menu, this issue doesn't occur.

**Comment by SirCmpwn** [comment]
Yes, that'd be a good first step. The issue is likely a problem with wlc - try to reproduce this with the orbment compositor, then move your bug to the wlc repo if you can. As a workaround, try forcing GTK to use the x11 backend with GDK_BACKEND=x11

**Comment by jplatte** [comment]
Yup, can reproduce with orbment. And thanks for providing a workaround!

*Moved to https://github.com/Cloudef/wlc/issues/210*
