### ISSUE TITLE
Poll: do any sway users rebind keys at runtime, or use the reload command via IPC?

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/sway#980]

**Comment by acrisci** [comment]
I do

**Comment by SirCmpwn** [comment]
Can you describe your use-case?

**Comment by acrisci** [comment]
The bindings need to be changed for some reason so I edit the config file to change them. Then I do `i3-msg reload` in the terminal.

**Comment by SirCmpwn** [comment]
How would you feel about binding reload to a key?

**Comment by acrisci** [comment]
It's not my workflow. I'm already in a terminal from vim so that's where my head is at. I do everything I can from the terminal. I know from my experience supporting i3 is that this community loves the terminal.

**Comment by SirCmpwn** [comment]
Sure, I love the terminal too :) thanks for the input

**Comment by SirCmpwn** [comment]
Put together a strategy that'll keep the option available, but it's likely to be turned off by default.

**Comment by acrisci** [comment]
ugh ok

**Comment by SirCmpwn** [comment]
Well, the concern is that a malicious program could rewrite security rules in your config and then trigger a reload via IPC. Open to suggestions. You can change this behavior by editing [this](https://github.com/SirCmpwn/sway/pull/981/files#diff-11ed175dd8956b9126753428fa050c44R47) in the default security rules.

**Comment by acrisci** [comment]
So they can't read the config, find the button to reload, and simulate the key event that does the reload?

**Comment by SirCmpwn** [comment]
Simulate the key event how?
