### ISSUE TITLE
Configuration errors against 0.11-rc1

### ISSUE THREAD

**Issue by pecastro** [SirCmpwn/sway#983]
12/04/16 13:52:29 - Error on line 30 'modifier enabled': Unknown/invalid command (/etc/sway/config.d/security)
12/04/16 13:52:29 - Error on line 48 'restart binding': Unknown/invalid command (/etc/sway/config.d/security)

No swaybar on top.

**Comment by SirCmpwn** [comment]
https://github.com/SirCmpwn/sway/commit/6604bb67ea1d7f7d395477607dc0395a63eea7be
