### ISSUE TITLE
XKB_XXXXX variables all defaults to "no" on FreeBSD

### ISSUE THREAD

**Issue by johalun** [SirCmpwn/sway#987]
As the title says. Haven't looked into it deeper yet.

Need to add to .cshrc for it to launch at all

setenv XKB_DEFAULT_RULES   xorg
setenv XKB_DEFAULT_LAYOUT  us
setenv XKB_DEFAULT_VARIANT mac
setenv XKB_DEFAULT_MODEL   pc105

**Comment by SirCmpwn** [comment]
This has nothing to do with sway. Whatever is setting those to "no" is at fault here.

**Comment by johalun** [comment]
Oh that's interesting.. I wonder where that is. Well, thanks for the info!
