### ISSUE TITLE
swaybar date update command can cause endless sleepless loop

### ISSUE THREAD

**Issue by johalun** [SirCmpwn/sway#988]
https://github.com/SirCmpwn/sway/blob/5778c59a2f302071fd781683db57a97b51396c87/sway/config.c#L1213

Don't remember exactly the circumstances but a problem I got a few times is that during testing/development is that `date` can start to fail. If that happens this will be a sleepless tight loop, causing heavy cpu usage. Even though this does not happen often, it might be good to exchange && for ; so that we'll always get a second sleep.

**Comment by SirCmpwn** [comment]
Seems like an easy change, send a pull request?

**Comment by johalun** [comment]
Yep will do
