### ISSUE TITLE
Swaybar memleak

### ISSUE THREAD

**Issue by motherload** [SirCmpwn/sway#989]
After a 3day uptime, swaybar was using 4gb of memory.

**Comment by SirCmpwn** [comment]
What version of sway?

**Comment by motherload** [comment]
sway version 0.10-rc1-34-g8d277bc (2016-10-10, branch "makepkg")

**Comment by SirCmpwn** [comment]
You aren't meant to use the rc once the stable release is out, FYI.

This issue is solved in 0.11. 0.11-rc2 is out if you'd like to try it.
