### ISSUE TITLE
Add version information

### ISSUE THREAD

**Issue by minus7** [SirCmpwn/sway#99]
The `--version` command line switch as well as the `get_version` IPC command (see #98) could use this information. Should probably generated at compile time.

i3 IPC version information includes:
```json
{
    "human_readable": "4.10.3-347-g586854b (2015-07-30, branch \"makepkg\")",
    "major": 4,
    "minor": 10,
    "patch": 3
}
```

**Comment by SirCmpwn** [comment]
Yeah, we need to figure out how to make cmake read the git tags (and also start tagging versions). Blocked until I decide to mark the first version of sway.

**Comment by SirCmpwn** [comment]
@Luminarys @minus7 IPC reminder

**Comment by minus7** [comment]
IPC taken care of, just needs to be patched up with better version information.

**Comment by SirCmpwn** [comment]
For the sake of everyone who isn't on IRC, sway will start being versioned once wlc starts being versioned.

**Comment by Luminarys** [comment]
I'll work on improving the tag information later tonight. Do you still want to do everything through macros defined at compile time?

**Comment by SirCmpwn** [comment]
Yep.

**Comment by Luminarys** [comment]
I'm closing this for the time being, as the output is now essentially the same as i3's with the exception of the version.
