### ISSUE TITLE
Different behavior from i3 when launching app

### ISSUE THREAD

**Issue by alkino** [SirCmpwn/sway#993]
When launching a heavy app from dmenu. And the app takes several seconds to be launched. During the launch you switch of workspace.

With i3, the app is launched in the workspace where dmenu was used.
With Sway, the app is launched in the current workspace.

Dig a little in i3 around "start_application()", but I don't understand how it does it.

**Comment by alkino** [comment]
In fact, they do it through "startup notification". When the view is created, they got the startup_id and look the workspace when it was asked and move the view in the right ws.

**Comment by SirCmpwn** [comment]
I'm not sure this is practical for us to address.

**Comment by SirCmpwn** [comment]
A workaround:

```
bindsym $mod+d exec dmenu_path | dmenu -p "Run:" -l 10 | xargs swaymsg exec
```
