### ISSUE TITLE
Libcap required

### ISSUE THREAD

**Issue by Fale** [SirCmpwn/sway#997]
Hi,

Compiling sway 0.11, the following error occured:

```
/builddir/build/BUILD/sway-0.11-rc2/sway/main.c:12:28: fatal error: sys/capability.h: No such file or directory
```

Speaking with alkino in IRC, he suggested to install the headers of libcap, and this solved the problem.
I don't see the libcap reference in the readmenor in the cmake file.
Maybe we should add something as documentation and/or check about it?

**Comment by SirCmpwn** [comment]
Added to README
